### ISSUE TITLE
Uninstalling application after logging in with Amplify Auth does not delete user data

### ISSUE THREAD

**Issue by ekmwilson** [aws-amplify/amplify-ios#1016]
**Describe the bug**
When we use `Amplify.Auth.signInWithWebUI()` to have a user log into the application, if they uninstall the application without logging out then when they reinstall the application they are still in a logged in state via the SDK.

This behaviour is inconsistent with the Android Amplify SDK.

**To Reproduce**
1. Have the user sign in by calling Amplify.Auth.signInWithWebUI(), generating tokens and putting them in a signed in state.
2. Uninstall the application
3. Re-install the application and notice that the SDK has retained the user's information and still considers the user in a signed in state.

**Expected behavior**
We would expect that all data associated with the application would be deleted when they uninstall the application. When they re-install they would need to login again.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.1
 - Dependency Manager: Cocoapods
 - Swift Version : Swift 5.2

**Device Information (please complete the following information):**
 - Device: reproducible across all devices
 - iOS Version: iOS 12

**Additional context**
There are additional issues we're running into by having this data persist. Is there any info you could provide on how we could manually clear out those values on our end?

**Comment by gevartosky** [comment]
Hi,

To complement the information, clearing Keychain doesn't seem to help either.
In fact, if you follow the process of
* Installing the app
* Logging in
* Deleting the app
* Install the app again
Then, if Keychain is cleared right after the app is installed, and you try to login, the web view goes up and down and you get logged in with the same credentials. If you don't clear Keychain after installing the app, you get prompted to login twice, the first time you are automatically logged in and you get the login popup again but this time your credentials are requested.

I also tried to clear any cookies but with no success

**Comment by palpatim** [comment]
Hi @ekmwilson,

This is expected behavior. The AWS SDK for iOS stores auth information in the local system keychain (https://developer.apple.com/documentation/security/keychain_services), which does not guarantee any particular behavior around whether data is removed when an app is uninstalled.

Deciding on when to clear this auth information is not something that the SDK can do in a generic way, so App developers should decide when to clear the data by signing out. One strategy for accomplishing this would be to use [UserDefaults](https://developer.apple.com/documentation/foundation/userdefaults) to detect whether or not the app is launching for the first time, and invoking [`Auth.signOut()`](https://docs.amplify.aws/lib/auth/signOut/q/platform/ios) if the app has not been launched before. We'll consider options for handling this on behalf of app developers in the future.

**Comment by ekmwilson** [comment]
Thanks for the suggestion @palpatim . Because we're using a web UI, calling `Auth.signOut()` to invoke the logout when the app starts for the first time in this case will show a popup to the user asking them to go to the web to sign in as per [this issue](https://github.com/aws-amplify/aws-sdk-ios/issues/3141). This flow will be confusing to the user and they will likely select cancel on that pop up if shown when starting the app, which will leave them in the logged in state. 

The best strategy that we've come up with is when the user opens the app for the first time in this case, we recognize that and wait until the first time they try signing in to first log them out so that the flow of seeing that popup makes sense to the user. After the logout, we call,` Amplify.Auth.signInWithWebUI()` so the user unfortunately will be shown two popups and webviews in this flow. However, because the [signout handler is invoked immediately instead of when the SFVC is dismissed](https://github.com/aws-amplify/amplify-ios/issues/959) our call to sign in after the log out call does not work unless we add some delay.

Having an option to handle it from the development side would be preferred.

**Comment by palpatim** [comment]
@ekmwilson Thanks for the feedback. We'll consider that as we explore options for this in the library. 

Also, please note that as of [Amplify 1.6.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0), Amplify now includes an option to prefer private sessions when signing in. If you select that option on iOS 13+, then users are not presented with a webview on sign out, which may help mitigate the UX confusion you describe.

**Comment by palpatim** [comment]
Added uninstall behavior explanation in docs on https://github.com/aws-amplify/docs/pull/2941. Closing this, but as noted, we'll consider ways to handle this in future versions of the library.
