### ISSUE TITLE
Amplify.API.subscribe onCreate(senderName: String) with filter condition 

### ISSUE THREAD

**Issue by tranminhhaifet** [aws-amplify/amplify-ios#1024]
**Problem**
I wanted to subscribe a DynamoDB table but with condition owner=="mike". I can do it in JS as below. Currently, Swift SDK does not support, and only allow subscribe to all owner
_const subscribe = () => {
        API.graphql({
            query: onCreateSongFilter,
            variables: {
                owner: "mike"
            }
        })
            .subscribe({
                next: songData => {
                    console.log("subscribe songs ", songData.value.data)
                }
            })
    }_

**Expected solution**
currently, Swift does subscribe as below and listen to mutation onCreate of all owner 
_subscription = Amplify.API.subscribe(
            request: .subscription(of: Message.self, type: .onCreate),
            valueListener: { subscriptionEvent in
               ...
        },
            completionListener: { completion in 
               ....            
           }
        )
    }_

So I expect that Swift SDK enable subscribe to .onCreate(owner: "mike")

**What I am trying but still struggling** 
mysub = Amplify.API.subscribe(
            request: GraphQLRequest(apiName: apiName,
                                    document: "",
                                    variables: nil,
                                    responseType: Message.self,
                                    decodePath: "")

**Comment by ruiguoamz** [comment]
Hi, @tranminhhaifet 
Thanks for reaching out.

Could you provide the schema you use and elaborate on your use case? 

I wonder are you using a schema with `@auth` directive 
```graphql
type Message @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  title: String!
}
```
or a regular schema with explicit owner field like:
```graphql
type Message @model {
  id: ID!
  title: String!
  owner: String
}
```

If the first case, the user-specific subscription should be created automatically. 

If the second case, you may refer to: https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/ios

**Comment by tranminhhaifet** [comment]
@ruiguoamz Many thanks! Then link you sent works perfectly, then I am able to customize as wanted.
