### ISSUE TITLE
How often does DataStore sync local to cloud?

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-ios#1025]
Cannot find any info on how often DataStore syncs local changes to the cloud. Where is this info?

We are building an app that requires sub-second response times, so understanding sync frequencies is important for us.

Also, is there any info on sync frequency of cloud to local?

Thank you!

**Comment by ruiguoamz** [comment]
Hi, @skryshi 
Thanks for reaching out. 

Let me briefly explain the DataStore sync: When App is launched, probably you want to call `DataStore.start()` and it performs `InitialSync` to sync data from cloud to local. And referring to this [code comment](https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/DataStoreConfiguration.swift#L53-L58), you can customize sync interval how often you want to perform sync from cloud to local regularly. I believe this is the answer to your second question?

Regarding your asking of DataStore syncs local changes to the cloud. When you call `DataStore.save()`, it saves the instance to local database, and sync engine automatically performs sending local change to cloud on behalf of you if you have `API` configured: https://docs.amplify.aws/lib/datastore/sync/q/platform/ios#setup-cloud-sync

Can you elaborate on what info you want about "DataStore syncs local changes to the cloud".

**Comment by skryshi** [comment]
Thank you, @ruiguoamz 

To clarify my questions:

Imagine we have two users, A and B, using a chat app developed with AWS Amplify. Suppose user A sends a message to user B. Here is the flow:

1. User A does `DataStore.save()` on the message.
2. Sync Engine starts to sync the message from local storage of User A to the cloud.
3. The cloud receives the message.
4. The cloud starts to push the message to the local storage of User B.

I am trying to understand the delays between 1 & 2, and between 3 & 4.

Can the whole flow, from 1 to 4 happen in sub-second time? (assuming zero networking delays between the users and the cloud.)

**Comment by ruiguoamz** [comment]
Well. We don't have a precise calculation on the delay between 1 & 2, and between 3 & 4. But from what I observed, the latency between 1 & 4 should be very low (within second). 

As long as you [establish the subscription](https://docs.amplify.aws/lib/datastore/real-time/q/platform/ios#observe-data-in-real-time) properly
