### ISSUE TITLE
Multi-auth configuration is deleted upon `pull`

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/amplify-ios#1026]
This page https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios explains how you should modify the `amplifyconfiguration.json` file manually to add more API endpoints.

This works but the moment you run `amplify pull` this file gets overridden and the other endpoints you had setup get lost.
This wouldn't happen if either the `.gitignore` generated by amplify didn't include `amplifyconfiguration.json` or if it was diffed differently when `amplify pull` is run.

**Comment by ruiguoamz** [comment]
Hi, I think this issue is `Amplify CLI` related, maybe you want to create a new one in [CLI repo](https://github.com/aws-amplify/amplify-cli/issues)
