### ISSUE TITLE
Manually invalidate the session to make it expired

### ISSUE THREAD

**Issue by zhouhao27** [aws-amplify/amplify-ios#1028]
Is there a way to manually invalidate the session to make it expired so that the testing will be easier?

**Comment by ruiguoamz** [comment]
Hi, @zhouhao27 
Thanks for reaching out. 

For `hostedUI`, I may have a way:

In the code of your app somewhere, you can put 
```swift
UserDefaults.standard.set(true, forKey: "MockExpires")
```

and in `AWSCognitoAuth.m`, after `if(username){` (ie, [line 407](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCognitoAuth/AWSCognitoAuth.m#L407))

you can put something like the code below:
```objective-c
BOOL didExpired = [[NSUserDefaults standardUserDefaults] valueForKey:@"MockExpires"];
if (didExpired) {
    [self dismissSafariViewControllerAndCompleteGetSession:nil 
                                                                                               error:[self getError:@"error"
                                                                                                                      code:AWSCognitoAuthClientErrorExpiredRefreshToken]];
}
```
So that, once the code see `didExpired` is true and return error code `AWSCognitoAuthClientErrorExpiredRefreshToken`.

Feel free to reach out again if this is not the answer you are looking for.

**Comment by zhouhao27** [comment]
@ruiguoamz This works. But it only works after I kill the app and launched it again.

Then I got an error when I tried to call `fetchAuthSession`. This is the part of the error:

> Invoke Auth.signIn to re-authenticate the user

So does this mean my application has to store user name and password to relogin the user?

**Comment by ruiguoamz** [comment]
Normally, when a session has expired, you may want your user to login again. 

But I am not sure about your use case and what you are trying to test. Could you elaborate on that?

**Comment by zhouhao27** [comment]
> Normally, when a session has expired, you may want your user to login again.
> 
> But I am not sure about your use case and what you are trying to test. Could you elaborate on that?

What we want is to auto login again when the session expired.

**Comment by royjit** [comment]
@zhouhao27 

The code that @ruiguoamz mentioned above is just for testing purpose, and not for production app.

Amplify library will take care of session expiration and automatically refreshes the token if the refresh token is valid. Developer do not need to worry about handling this. But when the refresh token expires, the user has to sign in again, developer should ask the user to signIn when refresh token expires.

You can listen to auth events to know when the session expires as mentioned [here](https://docs.amplify.aws/lib/auth/auth-events/q/platform/ios). When you get the event `HubPayload.EventName.Auth.sessionExpired`, you should invoke the signIn flow again.

**Comment by zhouhao27** [comment]
@royjit Thanks for your reply. But the issue is I never get `HubPayload.EventName.Auth.sessionExpired` event. My admin told me the session time in server setting is 10 minute.

**Comment by royjit** [comment]
Can you check with your admin the timeout for **Refresh token**? You will get the event `HubPayload.EventName.Auth.sessionExpired` only when the refresh token expires and your app tries to fetch the session. Refresh token has a min expiry of 60 minutes.

Please find a screenshot of the values from AWS console. 

![Screen Shot 2021-02-09 at 9 40 40 AM](https://user-images.githubusercontent.com/51138777/107404466-29581880-6abb-11eb-9494-c3622e1bdd61.png)

---
**Access token / ID token expiry** 

10 minute session time that your Admin gave you might be that of Access token or ID token. When these token expire, Amplify will automatically refresh it for you. You can check this behavior by calling `Amplify.Auth.fetchAuthSession`.

1. SignIn to Cognito User pool
2. Call fetchAuthSession and note the access token
3. Wait for 10 min
4. Call fetchAuthSession again and note the value of access token
5. Tokens should be different from the one you got in step 2.

```swift
Amplify.Auth.fetchAuthSession { result in
    do {
        let session = try result.get()

        // Get cognito user pool token
        if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
            let tokens = try cognitoTokenProvider.getCognitoTokens().get()
            print("Id token - \(tokens.idToken) ")
            print("Access token - \(tokens.accessToken) ")
        }

    } catch {
        print("Fetch auth session failed with error - \(error)")
    }
}
```

---
**Refresh token expiry** 

Check with your admin to find out the refresh token expiry, let it be 60 minute. Follow the steps below to test the session expiry event:

1. SignIn to Cognito User pool
2. Call fetchAuthSession and note the access token
3. Wait for 60 min
4. Call fetchAuthSession again
5. Note that the hub event fired for `HubPayload.EventName.Auth.sessionExpired`
6. You should now re-authenticate the user.

**Comment by zhouhao27** [comment]
@royjit Thanks for you very detailed explanation and getting understand how access token and refresh token works now. Have more question which needs your advise.

Let's assume we have a 10 minutes for id token expiration (we use the id token for authorization), does this mean we have to call `fetchAuthSession` every 10 minutes to make sure our id token is always the latest?

**Comment by royjit** [comment]
Id Token and access token will be refreshed automatically by the library if refresh token is active. You do not need to call every 10 min, whenever id token is fetched or accessed, Amplify will try to refresh it if the token is expired.

Where are you using the id token for authorization? Are you manually calling `fetchAuthSession` to get id token and then use it somewhere to authorize?

**Comment by zhouhao27** [comment]
@royjit Yes, I manually call `fetchAuthSession` to get the **id token** every time when application launched. And will add this token to my http request header.

**Comment by royjit** [comment]
You are right `fetchAuthSession` should be called to refresh the token.

**Comment by zhouhao27** [comment]
@royjit Thanks for your confirmation.

I need to add the token into my header for every API call. But it's not a good approach to call `fetchAuthSession` every time I call my API, right? Then what is the best practice? Call `fetchAuthSession` with a timer? Or any other way?

**Comment by royjit** [comment]
If you are manually adding the token on every API call, feel free to call `fetchAuthSession ` and update the header. `fetchAuthSession` takes the cached credentials and return to you. It will only do a network fetch if the credentials are expired.

**Comment by zhouhao27** [comment]
@royjit Thanks. This is what I did now. It seems ok if I use email signin now. But I still get authentication error occasionally if I use third party such as FB, Google.

**Comment by royjit** [comment]
Looks like this is not related to the issue discussed here. Can you please open a new ticket with details of error and steps you followed so that we can debug further.
