### ISSUE TITLE
Xcode throws compile error if the data model contains a 1:1 relationship

### ISSUE THREAD

**Issue by treystudio3a** [aws-amplify/amplify-ios#1031]
**Describe the bug**
If you use AdminUI and create a 1:1 relationship between 2 models, when you generate models on the client using the CLI and try to compile for iOS using Xcode, it will not compile successfully. (I'm assuming this is not necessarily related to AdminUI but that is how I created the model - I'm assuming if it was defined in the schema.graphql it would have the same result but I have not tested it - I only used AdminUI).

**To Reproduce**
1. Create a new AdminUI backend.
2. Create 2 models (Model A and ModelB)
3. Create a 1:1 relationship between the 2 models
4. Use CLI to pull down backend
5. Create XCode project
6. Perform Pod Init, Pod install --repo-update
7. amplify codegen add
8. amplify codegen
9. Add generate model to xcode project
10. Compile Xcode

**Expected behavior**
Should compile successfully.

**Screenshots**
<img width="928" alt="Screen Shot 2021-01-21 at 2 41 49 PM" src="https://user-images.githubusercontent.com/75962490/105411221-bb75ab00-5bf8-11eb-8c54-537491642196.png">

![Screen Shot 2021-01-21 at 2 57 45 PM](https://user-images.githubusercontent.com/75962490/105411507-17d8ca80-5bf9-11eb-94cb-7f97530e778c.png)

<img width="900" alt="Screen Shot 2021-01-21 at 3 00 56 PM" src="https://user-images.githubusercontent.com/75962490/105411822-8027ac00-5bf9-11eb-9a1a-43ef4b21f6c0.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 4.41.2
 - Dependency Manager: [Cocoapods]
 - Swift Version :  version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) Target: x86_64-apple-darwin20.2.0
 - Xcode 12.3 (12C33)
 - Simulator: happens on any, i was trying iPhone 12 Pro Max (if I remove the models the project compiles)

**Comment by ruiguoamz** [comment]
Hi, @treystudio3a 
Thanks for reaching out.

My suggestion is to use lower case for the field name (use `modelB` instead of `ModelB`) which removes the complier warning.  I guess Xcode is not able to resolve this kind of confusion(having a field called `ModelB` and having a class called `ModelB`)

**Comment by treystudio3a** [comment]
That solved my problem thank you very much

**Comment by ruiguoamz** [comment]
You are welcome, feel free to reach out to use for other issues.

Closing this issue
