### ISSUE TITLE
Implement RandomAccessCollection protocol on List<ModelType:Model> in order to allow list to be used easily with SwiftUI's ForEach

### ISSUE THREAD

**Issue by treystudio3a** [aws-amplify/amplify-ios#1035]
**Is your feature request related to a problem? Please describe.**
I had trouble figuring out why I could not use an Amplify model's "child list" property in a ForEach (SwiftUI).  Most of the code examples in amplify documentation for swift show using a result from a datastore.query, but if you have a model and want to traverse it's children using the ForEach, it requires an object that implements the [RandomAccessCollection](https://developer.apple.com/documentation/swift/randomaccesscollection) protocol.  I was able to add an extension to get around this, but it required me to implement a missing index:before -> Int method to which I am unable to access the underlying elements since it's marked internal (and thus my implementation is not really correct).  My extension implementation just returns index - 1, and does not appear to cause issues and allows me to iterate on the child list property using the ForEach, but ideally this implementation would happen in the amplify framework.

This is my model's autogenerated type:
````
// swiftlint:disable all
import Amplify
import Foundation

public struct Menu: Model {
  public let id: String
  public var title: String?
  public var groups: List<MenuGroup>?
  
  public init(id: String = UUID().uuidString,
      title: String? = nil,
      groups: List<MenuGroup>? = [],
      self.id = id
      self.title = title
      self.groups = groups
  }
}

````

This is my extension code:
_(Side note:  Would be great if you could also go ahead and implement the Identifiable protocol too!)_

````
extension Menu: Identifiable {}
extension MenuGroup: Identifiable {}

extension List: RandomAccessCollection  {
    public func index(before i: Int) -> Int {
        return i-1
    }
}
````

If this extension is not in my project, then I get the following error:
`
Generic struct 'ForEach' requires that 'List<MenuGroup>' conform to 'RandomAccessCollection'
`

Here is the swift ui code for the body where the error occurs (but works if I add my extension code above):
````
    var body: some View {
        ForEach(viewModel.menu?.groups ?? List<MenuGroup>()) { group in
            Text("item: \(group.id) goes here")
        }
    }
`````

**Comment by ruiguoamz** [comment]
Hi, @treystudio3a 

Can you provide the schema you use? `Menu` and `MenuGroup`.

**Comment by treystudio3a** [comment]
type Menu @model @auth(rules: [{allow: public}]) @key(name: "byAppDef", fields: ["appDefID"]) {
  id: ID!
  title: String
  groups: [MenuGroup] @connection(keyName: "byMenu", fields: ["id"])
  appDefID: ID!
}

type MenuGroup @model @key(name: "byMenu", fields: ["menuID"]) @auth(rules: [{allow: public}]) {
  id: ID!
  title: String
  isExpanded: Boolean
  items: [MenuItem] @connection(keyName: "byMenuGroup", fields: ["id"])
  menuID: ID!
}

**Comment by treystudio3a** [comment]
Menu model generated by Amplify:
````
// swiftlint:disable all
import Amplify
import Foundation

public struct Menu: Model {
  public let id: String
  public var title: String?
  public var groups: List<MenuGroup>?
  public var appDefID: String
  
  public init(id: String = UUID().uuidString,
      title: String? = nil,
      groups: List<MenuGroup>? = [],
      appDefID: String) {
      self.id = id
      self.title = title
      self.groups = groups
      self.appDefID = appDefID
  }
}

````

**Comment by treystudio3a** [comment]
MenuGroup model generated by Amplify:
````
// swiftlint:disable all
import Amplify
import Foundation

public struct MenuGroup: Model {
  public let id: String
  public var title: String?
  public var isExpanded: Bool?
  public var items: List<MenuItem>?
  public var menuID: String
  
  public init(id: String = UUID().uuidString,
      title: String? = nil,
      isExpanded: Bool? = nil,
      items: List<MenuItem>? = [],
      menuID: String) {
      self.id = id
      self.title = title
      self.isExpanded = isExpanded
      self.items = items
      self.menuID = menuID
  }
}
````

**Comment by royjit** [comment]
Does this work for you, I do not think we might be adding `RandomAccessCollection` into the list property.

```swift
let groups = viewModel.menu?.groups ?? []
ForEach(0 ..< groups.count) {
          Text("item: \(groups[$0].id) goes here")
}
```
