### ISSUE TITLE
Cannot run ElasticSearch-backed query if auth is IAM, works with Cognito

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/amplify-ios#1036]
I have created an ElasticSearch-backed query, following this tutorial: https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable

This is the part of my schema I created following the tutorial:
```
type Query {
 nearbyItems(
   location: LocationInput!, 
   distanceInKm: Int, 
   limit: Int, 
   nextToken: String
 ): NearbyItemsConnection @aws_iam @aws_cognito_user_pools
}

input LocationInput {
  lat: Float!
  lon: Float!
}

type NearbyItemsConnection @aws_iam @aws_cognito_user_pools {
 items: [ItemData]
 total: Int
 nextToken: String
}
```

and I have also created a VTL resolver, which works.

If I then navigate to the AppSync console in my browser, and run the search by location query using an IAM role from the AWS AppSync query console in the browser, the query works and returns items as expected.

However if I then try to run the same query from my iOS app with the same IAM role, I get an `HTTPURLResponse` error, which says in its header:
```
"x-amzn-errortype" = (UnauthorizedException);
"x-cache" = ("Error from cloudfront");
```

among other things in the header which aren't relevant.

However if I then run the exact same query via the Cognito auth mode from the same iOS app, it executes fine, just like it did in the AppSync query console, although there I am able to run it even as my IAM role.

For context I have modified the Amplify library just slightly to allow me to specify which auth mode to use when executing a query. I can happily use the IAM auth mode for all other queries which the amplify CLI generated for me (e.g. `listItems`, etc) via this change, but for some reason I can't understand, not this query I created myself.
Also for more context I have created a custom `GraphQLRequest` factory method in my iOS app, as explained in the tutorials, nothing fancy. Such method, as I said above, if used with Cognito works fine, but not with IAM.

Any ideas what might be going on?

**Comment by lawmicha** [comment]
Hi @cosimtaiuz 

> For context I have modified the Amplify library just slightly to allow me to specify which auth mode to use when executing a query. I can happily use the IAM auth mode for all other queries which the amplify CLI generated for me (e.g. `listItems`, etc) via this change, but for some reason I can't understand, not this query I created myself.

Can you let us know what the modification is, and how you are specifying the auth mode?

**Comment by lawmicha** [comment]
I'll mark this as pending investigation as well, since there is some legwork that we can do to try this scenario out by following https://docs.amplify.aws/cli/graphql-transformer/resolvers#add-a-custom-geolocation-search-resolver-that-targets-an-elasticsearch-domain-created-by-searchable

**Comment by cosimtaiuz** [comment]
@lawmicha I don't have my code at handy atm but I resovled this by manually adding permission to access the new GraphQL query  (e.g. lookForNearbyThings) manually to the IAM policies for both the Auth and Unauth roles in IAM, the ones which Amplify generated for me. I hope this helps the investigation!

**Comment by lawmicha** [comment]
@cosimtaiuz good to know you were able to resolve your problem. @ruiguoamz attempted the docs you pointed out and had some other issues, which from the sounds of it, was not to the point that reproduced your environment. We'll follow up with that separately over in https://github.com/aws-amplify/amplify-cli 

Feel free to open another issue if you facing other issues!
