### ISSUE TITLE
Difference between requestLimitExceeded, limitExceeded, failedAttemptsLimitExceeded

### ISSUE THREAD

**Issue by royjit** [aws-amplify/amplify-ios#1041]
`AWSCognitoAuthError` has different types of error related to limit exceeded. Document the behavior of each and verify that the right errors are thrown at right scenarios.

**Comment by thisisabhash** [comment]
Removed the coupled case for handling `tooManyRequests` and `limitExceeded` in `AuthErrorHelper`. 
This bug is fixed with https://github.com/aws-amplify/amplify-ios/pull/1122.
