### ISSUE TITLE
Amplify.Auth.signOut() does not work in first time

### ISSUE THREAD

**Issue by lanlhvn** [aws-amplify/amplify-ios#1043]
**Describe the bug**
Logout process is not successful in first time open. It's successful in second time.

**To Reproduce**
1. Tap logout button, a webview is presented for a few secs with text "You signed out of your account, It's a good idea to close all browser windows".
2. Tap con Cancel button in Webview, an error occurs:
```
AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/xxx/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.apple.SafariServices.Authentication Code=1 "(null)"
  ▿ unknown : 2 elements
    - .0 : "An unknown error occurred"
    ▿ .1 : Optional<Error>
      - some : Error Domain=com.apple.SafariServices.Authentication Code=1 "(null)"
```

3. Then I tap on logout button a gain, a Webview will be presented then dismissed --> logout successfully.

**Expected behavior**
A webview will be presented and dismissed automatically to sign out user

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.3
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 8
 - iOS Version: iOS 14.3
 - Specific to simulators:

**Additional context**

**Comment by palpatim** [comment]
Canceling the webview will abandon the logout flow, so this is expected behavior. What happens if you let the webview close by itself after it completes the logout flow?

If you're still seeing a problem, please provide more detail including your user pool configuration (with sensitive information redacted) and code snippets showing how you are invoking the Auth.signIn and Auth.signOut methods.

**Comment by lanlhvn** [comment]
@palpatim : Thank you for reply! The webview is not closed by itself in first time. It's only closed by itself in second time then completes the logout flow.

Below is my amplifyconfiguration.json
```
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "***",
                        "AppClientId": "***",
                        "AppClientSecret": "***",
                        "Region": "***"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "OAuth": {
                            "AppClientId": "***",
                            "AppClientSecret": "***",
                            "WebDomain": "***",
                            "SignInRedirectURI": "**://***",
                            "SignOutRedirectURI": "**://****",
                            "Scopes": [
                                "email",
                                "openid",
                                "profile"
                            ]
                        }
                    }
                }
            }
        }
    }
}
```

```
Amplify.Auth.signInWithWebUI(presentationAnchor: presentationAnchor) { result in
            switch result {
            case .success:
                Amplify.Auth.fetchAuthSession { result in
                    do {
                        let session = try result.get()
                        // Get user sub or identity id
                        if let identityProvider = session as? AWSAuthCognitoSession {
                            let cognitoToken = try identityProvider.getCognitoTokens().get()
                            // save token to local
                        } else {
                            
                        }
                    } catch {
                        
                    }
                }
            case .failure(let authError):
                
            }
        }
```

```
Amplify.Auth.signOut() { result in
                switch result {
                case .success:
                    
                case .failure:
                    
                }
            }
```

**Comment by lawmicha** [comment]
Hi @lanlhvn, could you provide some details around your use case?
- When you launch the hosted UI, how are you signing in? email/username or social provider?
- When you sign out, can you access the `underlyingError` Error and print the localizedDescription? 
```swift
case .failure(let error): 
   if let underlyingError = error.underlyingError {
      print(underlyingError.localizedDescription)
   }
```
- We were thinking if there could be something wrong with the `SignOutRedirectURI`, what is it and is it the same as your `SignInRedirectURI`?

**Comment by lanlhvn** [comment]
Thank you @lawmicha for the reply!
We're having a problem now so I can not get the log for you this time.
Please keep this topic open and I will get back to this topic soon after solving our problem.
Thank you very much!

**Comment by lanlhvn** [comment]
Hi @lawmicha , we now can continue working on it and I have a logs for you:

> * When you launch the hosted UI, how are you signing in? email/username or social provider?

A webView is presented and I'm logging in with AzureAD account (not my personal email)

-----------------------------------

> * When you sign out, can you access the `underlyingError` Error and print the localizedDescription?

This is the error I got "The operation couldn’t be completed. (com.apple.SafariServices.Authentication error 1.)"

-----------------------------------

> * We were thinking if there could be something wrong with the `SignOutRedirectURI`, what is it and is it the same as your `SignInRedirectURI`?

I confirm that I'm using the right 'SignOutRedirectURI' and 'SignInRedirectURI'

Thank you in advance for your support!

**Comment by lawmicha** [comment]
Hi @lanlhvn, I'm not exactly sure or familiar with what it means to integrate with AzureAD. Could you expand on this? 

What are some provisioning steps you did to set up the backend? ie. `amplify add auth` or manual set up?

What are some configuration details you did? Did you manually craft the `amplifyconfiguration.json`, did you update the info.plist?


SafariServices.Authentication error 1 should correspond to noAttachmentFound (https://developer.apple.com/documentation/safariservices/sfauthenticationerror/sfauthenticationerror)
> The Content Blocker extension returned an NSExtensionItem that did not include an attachment.

**Comment by lanlhvn** [comment]
Hi @lawmicha ,


> What are some provisioning steps you did to set up the backend? ie. `amplify add auth` or manual set up?

This is manual setup and I setup amplifyconfiguration.json manually as my post above (https://github.com/aws-amplify/amplify-ios/issues/1043#issuecomment-770187092)  and I also updated the info.plist for RedirectURI 



> I'm not exactly sure or familiar with what it means to integrate with AzureAD. Could you expand on this?

The app login is using Microsoft account 
![155912371_1352534398464927_1216119417002098913_n](https://user-images.githubusercontent.com/17258403/109411143-79e3d700-79d2-11eb-9c4b-0b9fec76d9e6.jpg)

**Comment by lanlhvn** [comment]
Hi,
Sign out works well if I add preferPrivateSession option in sign in method:

`Amplify.Auth.signInWithWebUI(presentationAnchor: presentationAnchor, options: .preferPrivateSession())`

We can consider that this issue is solved.
Really appreciate you guys on this!

**Comment by palpatim** [comment]
Thanks for confirming @lanlhvn and I'm glad that solved your issue.
