### ISSUE TITLE
Why does `amplifyconfiguration.json` have multiple AppSync entries?

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/amplify-ios#1046]
I have noticed that on iOS the `amplifyconfiguration.json` file has multiple entries for the same APIs.
Once, in the `api : plugins` section, and again in `auth : plugins: AppSync:`.

Couldn't there be only one definition instead of 2?

**Comment by lawmicha** [comment]
Hi @cosimtaiuz, 

you can ignore the extra values from the `auth: plugins: AppSync` section. `Amplify.API` will use the configuration from `api: plugins` section. The reason they were added under auth plugin is part of the migration process that the plugins are undertaking. Currently, some of the plugins depend on the functionality provided by the high level SDKs (`AWSMobileClient`) which uses the `awsconfiguration.json` file, and so the entire contents of `awsconfiguration.json` is placed under the `auth: plugins` section for the Auth plugin to internally configure `AWSMobileClient`.

Let us know if you have more questions or if something isn't working

**Comment by cosimtaiuz** [comment]
Understood, thanks!
