### ISSUE TITLE
Difference between `awsconfiguration.json` and `amplifyconfiguration.json`?

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/amplify-ios#1047]
What's the difference between the twos? is `awsconfiguration.json` even used? Could one remove it?

**Comment by lawmicha** [comment]
`awsconfiguration.json` is the previous configuration file used by the SDKs (https://github.com/aws-amplify/aws-sdk-ios) and Appsync SDK (https://github.com/awslabs/aws-mobile-appsync-sdk-ios). It is not used by the Amplify libraries, and Amplify will use `amplifyconfiguration.json`

**Comment by cosimtaiuz** [comment]
I see, thanks for your explanation. So why does it generate both?

**Comment by royjit** [comment]
`awsconfiguration.json` is produced for backward compatibility, so that developer who would like to use the older SDK can import `awsconfiguration.json` into their app. If your app use only the Amplify apis, you can ignore `awsconfiguration.json` and just import `amplifyconfiguration.json`.
