### ISSUE TITLE
Signout is displaying signin message

### ISSUE THREAD

**Issue by Vivek205** [aws-amplify/amplify-ios#1050]
**Describe the bug**
For the federated login ( google/fb/apple), whenever the Auth.signout is called, `Signin` message is displayed instead of `signout` message. 

**To Reproduce**
1. Signin using federated login (google/fb/apple)
2. Do Signout
3. You will see the prompt with wrong message

**Expected behavior**
I should see Signout prompt on signout

**Screenshots**

![](https://trello-attachments.s3.amazonaws.com/6006a5ba81ac401770e511c6/750x1334/c2b77fc3f5a232b40bb66ee5f96cb063/IMG_4472.PNG.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 1.5.3]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version: [e.g. 5.0]
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Additional context**

**Comment by lawmicha** [comment]
Hi @Vivek205, please see the correpondence on the other issues here: https://github.com/aws-amplify/aws-sdk-ios/issues/3141 An enhancement to this is in the works. Will close this as a dedup
