### ISSUE TITLE
Missing `public` file access level? How to make assets really public?

### ISSUE THREAD

**Issue by ppave** [aws-amplify/amplify-ios#1053]
With Amplify iOS SDK https://docs.amplify.aws/lib/storage/upload/q/platform/ios I am able to upload files using  `Amplify.Storage.uploadData` - these files are available for authorized/guest users only. 
And I am able to generate a public link using `Amplify.Storage.getURL` - the generated link is too long to be usable meanwhile.

How to upload a file and get a public url using one step? Or that's supposed to be be managed on the bucket accessibility level?

**Comment by lawmicha** [comment]
Hi @ppave, could you explain why the generated link is too long to be usable? Just to note, this URL will expire and isn't something you can keep around and expect it to always resolve to the file so you should store the key and get the URL or get the data directly using the key.

If you make the bucket public, then the URL that you manually construct will not expire, but this is not recommended.

**Comment by ppave** [comment]
Got it, thank you. Closing the thread.
