### ISSUE TITLE
Amplify DataStore - fetch data and cache it locally without real-time updates?

### ISSUE THREAD

**Issue by ppave** [aws-amplify/amplify-ios#1056]
Amplify DataStore works using AppSync. AppSync has 2 pricing categories:
- Query and Data Modification Operations
- Real-time Updates

DataStore has queries and subscriptions, and as I see in logs, in both cases data is being synced under the hood in real time. The only difference - is that in case of subscriptions you are able to get this updated data in your app layer without querying again.

And as I see, queries just return local cached data and start syncing in the background. So f.e. to fetch all data from the backend, you first need to subscribe to DataStore Events like .modelSynced or .ready, and only after that perform queries.

So, seems like Amplify DataStore query != AppSync query, because as per https://aws.amazon.com/appsync/pricing/ AppSync Query Operations enable your app to fetch data and cache it locally. 

So, using Amplify DataStore, Is it possible to disable real-time updates and perform only queries when during these queries local data will be synced with cloud data? 

Question is kind of theoretical to get understanding of how it works.
Thank you.

**Comment by palpatim** [comment]
Hi @ppave,

DataStore is designed to support offline use cases, with synchronization to the cloud if desired (i.e., if the API category is configured) and available (i.e., the network is connected). As such, DataStore interactive operations like `query`, `save`, and `delete` are performed against the local store and then asynchronously reconciled with the cloud backend.

It is possible to manually control DataStore synchronization with the [`start()` and `stop()` methods](https://docs.amplify.aws/lib/datastore/sync/q/platform/ios#reevaluate-expressions-at-runtime), but these don't allow you to perform individual targeted queries and cache the data locally; they simply pause and resume synchronization for the entire data store. It sounds like what you're after would be better served using the API category directly to query, and managing persistence with some custom method; a local SQLite instance or CoreData setup, for example. The API category does support model-based query and mutation operations, so you at least get the benefit of a model-based approach to managing app data.

Apart from pricing considerations, is there a specific app use case you want to achieve with the setup you've described?

**Comment by ppave** [comment]
Hi @palpatim 
I've got all answers I need. Thank you, everything is clear. Closing.
