### ISSUE TITLE
Constant variable webDomain is nil - App crashes

### ISSUE THREAD

**Issue by fmigsystems** [aws-amplify/amplify-ios#1058]
**Describe the bug**
Trying to sign into iOS app and app crashes.

**To Reproduce**
Simply run the app in Xcode

**Expected behavior**
I expected to be able to login

**Screenshots**
<img width="1141" alt="Screen Shot 2021-02-06 at 1 53 20 PM" src="https://user-images.githubusercontent.com/57248794/107109305-b5cbc680-6882-11eb-8f93-019146dcd4e7.png">

**Environment(please complete the following information):**
 Mac OS Big Sur 11.2
Xcode Version 12.4 (12D4e)

<img width="796" alt="Screen Shot 2021-02-06 at 1 55 05 PM" src="https://user-images.githubusercontent.com/57248794/107109336-f75c7180-6882-11eb-900e-ae7aa4328ca6.png">

**Device Information (please complete the following information):**
 

**Additional context**
None

**Comment by lawmicha** [comment]
Hi @fmigsystems, what are some steps that you have followed to provision your backend? Ie. `amplify add auth` and high level use case you selected?

**Comment by fmigsystems** [comment]
> Hi @fmigsystems, what are some steps that you have followed to provision your backend? Ie. `amplify add auth` and high level use case you selected?

I am following the instructions on the link below:

https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/

I did steps 1-3. At the end of step 3, It says to verify that everything is correct by running the app in the simulator. I press the green sign-in button and that is when the app crashes. I ran the following commands from terminal:

npm install -g @aws-amplify/cli
amplify init
amplify add auth
amplify push

My current version of amplify:
<img width="187" alt="Screen Shot 2021-02-07 at 12 51 22 PM" src="https://user-images.githubusercontent.com/57248794/107136034-33efa200-6943-11eb-89f9-55f78a5e600a.png">

I haven't yet pushed to my github but would it help if I did push to my github and then you can run the app yourself when you git clone?

This used to work before I updated Xcode to 12.4. It worked on Xcode 12.3. Also there are no more app delegate files when creating a new project in Xcode but I created one because the AWS instructions says to put relevant code into app delegate.

**Comment by lawmicha** [comment]
Hi @fmigsystems , thanks for the details, I believe we need to run through that tutorial and make sure things are working. For example, we no longer guide developers to add `AmplifyTools` into the workflow.

- Could you confirm the contents of your `amplifyconfiguration.json` contains a valid web domain of the hosted UI endpoint? The configuration should have the key value pair the auth plugin section. And you should also be able to access this HostedUI webdomain from a browser to see a sign in screen.
- Can you update your Podfile to remove the version, and make sure the latest is installed (1.6.1)? The Podfile.lock should indicate which version is installed.
**Podfile**
```
target 'MyAmplifyApp' do
  use_frameworks!
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
end
```
And I believe you can remove the lock file `rm Podfile.lock` and install the pods again `pod install --repo-update`

Alternatively, you can follow the getting started steps anew from 
Getting Started: https://docs.amplify.aws/lib/project-setup/prereq/q/platform/ios
Authentication: https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios
DataStore: https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios

**Comment by fmigsystems** [comment]
> Hi @fmigsystems , thanks for the details, I believe we need to run through that tutorial and make sure things are working (Following up with @sebsto). For example, we no longer guide developers to add `AmplifyTools` in the workflow.
> 
> * Could you confirm the contents of your `amplifyconfiguration.json` contains a valid web domain of the hosted UI endpoint? The configuration should have the key value pair the auth plugin section. And you should also be able to access this HostedUI webdomain from a browser to see a sign in screen.
> * Can you update your Podfile to remove the version, and make sure the latest is installed (1.6.1)? The Podfile.lock should indicate which version is installed.
>   **Podfile**
> 
> ```
> target 'MyAmplifyApp' do
>   use_frameworks!
>   pod 'Amplify'
>   pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
> end
> ```
> 
> And I believe you can remove the lock file `rm Podfile.lock` and install the pods again `pod install --repo-update`
> 
> Alternatively, you can follow the getting started steps anew from
> Getting Started: https://docs.amplify.aws/lib/project-setup/prereq/q/platform/ios
> Authentication: https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios
> DataStore: https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios

My amplifyconfiguration.json before your recommended edit:
<img width="775" alt="amplifyconfig_current" src="https://user-images.githubusercontent.com/57248794/107321826-98973200-6ae6-11eb-939e-33b6ad87c136.png">

My amplifyconfiguration.json after your recommended edit:
<img width="799" alt="amplifyconfig_after" src="https://user-images.githubusercontent.com/57248794/107321904-c2505900-6ae6-11eb-91e3-d776a92a0a4c.png">

Even after making the changes to the podfile, I still cannot locate the web domain of the hosted UI endpoint in the new amplifyconfiguration.json file.

My new podfile:
<img width="710" alt="podfile_new" src="https://user-images.githubusercontent.com/57248794/107321960-df852780-6ae6-11eb-85ba-bd93bc416f57.png">

My new podfile.lock:
<img width="538" alt="podlock_after" src="https://user-images.githubusercontent.com/57248794/107321981-ea3fbc80-6ae6-11eb-9a57-0696df7d82ee.png">

I updated the podfile and it does not update to the newest version of 1.6.1. It stays at version 1.6.0.

I ran the app in the simulator and the end result is the same with the same exact errors as before. I will try the alternative getting started links you sent to me.

**Comment by royjit** [comment]
@fmigsystems Thank you for providing the information. I edited your screenshot to redact the configuration values. The current version of [Amplify is 1.6.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0), I think there was a typo in the reply above.

Your configuration does not have the required webdomain to invoke webUI signIn. Please note that you have two options to sign in to Cognito User pools and the `amplifyconfiguration.json` values will differ based on the question you answer in the CLI.

1. SignIn API - https://docs.amplify.aws/lib/auth/signin/q/platform/ios
2. SignIn via webUI - https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios

The configuration you provided looks like the one for "SignIn API", you might have missed a step in Amplify CLI that directs you to configure for "SignIn via webUI". I tried to see if there is any issue in CLI, but did not find any. I was able to create the right configuration, here are the steps I followed in the CLI:

```terminal
$ amplify --version
4.41.2

$ amplify add auth
 Using service: Cognito, provided by: awscloudformation
 The current configured provider is Amazon Cognito.

? Do you want to use the default authentication and security configuration? 
  Default configuration with Social Provider (Federation)
  Warning: you will not be able to edit these selections.

? How do you want users to be able to sign in? 
  Username

? Do you want to configure advanced settings? 
  No, I am done.

? What domain name prefix do you want to use? 
  <enter-your-domain-prefix>

? Enter your redirect signin URI: 
  <enter-your-signin-uri>

? Do you want to add another redirect signin URI 
  No

? Enter your redirect signout URI: 
  <enter-your-signout-uri>

? Do you want to add another redirect signout URI 
  No
 
? Select the social providers you want to configure for your user pool:
  // Did not select any

Successfully added auth resource xxx locally

$ amplify push
```

After successfully amplify push, I got the following `amplifyconfiguration.json`:

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "xxx",
                            "Region": "xxx"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxx",
                        "AppClientId": "xxx",
                        "AppClientSecret": "xxx",
                        "Region": "xxx"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxx.amazoncognito.com",
                            "AppClientId": "xxx",
                            "AppClientSecret": "xxx",
                            "SignInRedirectURI": "xxx",
                            "SignOutRedirectURI": "xxx",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

Please check whether you have followed the steps like I had. Especially the place where it ask for the domain prefix and redirect URIs.

**Comment by royjit** [comment]
I also verified the steps for "Module3: Add Authentication" in here - https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/module-three/ and they also succeeded for me.

**Comment by fmigsystems** [comment]
> I also verified the steps for "Module3: Add Authentication" in here - https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/module-three/ and they also succeeded for me.

Hi Royjit. I will go back and try the steps you have listed above!

**Comment by sebsto** [comment]
Hello @fmigsystems, from the above thread, looks like your config file was missing the OAuth steps, which comes from the Amplify CLI when configuring the Auth category.

I wrote the [tutorial](https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/module-three/) you did follow and I would like to understand how we can make it more bullet proof / more obvious to follow the instructions ?
