### ISSUE TITLE
Issue with generating a model through Xcode, generating random models

### ISSUE THREAD

**Issue by jmgawecki** [aws-amplify/amplify-ios#1062]
**Describe the bug**
When generating a model through Xcode, the model is different than the one I requested.

**Amplify CLI Version**
4.41.2

**To Reproduce**
Through Xcode,
1. Editing schema.graphql to my custom Model
2. in amplifytools.xcconfig: push=true, modelgen=true
3. Run the projects
4. Update Completed

**Expected behavior**
The generated custom model that I have created in schema.graphql. Instead I am getting some unknown to me models: Task and Note

**Screenshots**
Model created through Xcode for deployment:
<img width="213" alt="Screenshot 2021-02-09 at 20 41 42" src="https://user-images.githubusercontent.com/71930261/107425698-399de100-6b17-11eb-8a9a-586423b71ad5.png">

Configuration:
![Uploading Screenshot 2021-02-09 at 20.42.07.png…]()

Model changes in schema.graphql after successful deployment:
<img width="235" alt="Screenshot 2021-02-09 at 20 39 50" src="https://user-images.githubusercontent.com/71930261/107425507-f80d3600-6b16-11eb-91d2-bd6a9bbaea9e.png">

Model actually deployed visible from the Admin Console
<img width="667" alt="Screenshot 2021-02-09 at 20 42 46" src="https://user-images.githubusercontent.com/71930261/107425822-5fc38100-6b17-11eb-8778-0ccd25439c4a.png">

**Desktop (please complete the following information):**

- OS: Mac Apple M1 BigSur 11.2
- Node Version: 15.8.0

**Comment by jmgawecki** [comment]
Hi, 
I found a walkaround.

1. configure pods with libraries
2. init and push amplify
3. go to AWS console
4. Create a model from an admin console in aws amplify
<img width="721" alt="Screenshot 2021-02-14 at 13 52 14" src="https://user-images.githubusercontent.com/71930261/107878616-d96abe80-6ecb-11eb-9208-e7f64aabd327.png">
5. in Xcode:
6. configure Graphql file as you configured your model in an admin console
7. Modelgen to true
8. push to true
9. build and run project. In that step, Xcode will create the model that you have just modified. And in a halfway Xcode will cancel a build-up
10. Before you run again, change Modelgen to false in your config file
11. Run and build a project. 
12. All should work as supposed to.

Anyone ve met that issue before? May thanks for clues about what is wrong

**Comment by diegocstn** [comment]
hi @jmgawecki, thanks for reaching out. 

The build phase script provided by the `Amplify/Tools` pod is not longer recommended. It's *currently deprecated* and it will be completely removed in a future release.
The functionality provided by the `amplify-tools.sh` is currently integrated with the Amplify CLI and iOS projects can leverage it without any extra dependency.
`amplify codegen models` will correctly generate and add models to an `AmplifyModels` group in your Xcode project.
This Xcode integration was added to the CLI on version `4.40.0`.
We believe that relying on the CLI provides a fast and reliable developer experience.

I'd recommend to run `amplify codegen models` to generate Swift models out of your schema and `amplify push` to deploy your changes.
Please let us know if you have further questions.

**Comment by diegocstn** [comment]
Also starting from [Amplify v1.6.1](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.1), a deprecation warning will be issued when the `amplify-tools.sh` is invoked as part of an Xcode build script.
You can find more details about AmplifyTools deprecation [here](https://github.com/aws-amplify/amplify-ios/tree/main/AmplifyTools).
I'll optimistically close this issue but feel free to re-open if you have more questions.
