### ISSUE TITLE
Feature Request: Add AWS Kinesis support in the amplify SDK for IOS

### ISSUE THREAD

**Issue by Bogatinovski** [aws-amplify/amplify-ios#1063]
**Is your feature request related to a problem? Please describe.**
I need to collect streaming data on my mobile application and send it to AWS Kinesis. 

**Describe the solution you'd like**
Add AWS Kinesis back in the Analytics category of the SDK

**Describe alternatives you've considered**
I could access Kinesis through AWS API Gateway Proxy, as per [this documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-kinesis.html). However, that means I'd have to implement my own local batching logic inside the mobile app.

**Additional context**
I actually need this Kinesis support in the IOS SDK in order to build Flutter apps. The flutter apps only support SDKs which are also supported in both the IOS and Android SDKs. I already raised the feature request about the same in the [Amplify Android SDK repo](https://github.com/aws-amplify/amplify-android/issues/1162).

**Comment by diegocstn** [comment]
Hi @Bogatinovski, thanks for reaching out.
We currently offer Kinesis support only through our legacy [SDK](https://github.com/aws-amplify/aws-sdk-ios) but we'll keep this issue open so we can keep track of this feature request.
You can follow [this guide](https://docs.amplify.aws/sdk/analytics/kinesis/q/platform/ios) to setup your app.

**Comment by atierian** [comment]
> I actually need this Kinesis support in the IOS SDK in order to build Flutter apps.

>  that means I'd have to implement my own local batching logic inside the mobile app.

Can you please clarify these two points? We'd like to understand your use case better.
Thanks.

**Comment by royjit** [comment]
amplify-ios does not support Kinesis right now, you can use our low level SDK provided here - https://github.com/aws-amplify/aws-sdk-ios/tree/main/AWSKinesis

Also, if you are looking for a swift implementation of Kinesis SDK, AWS SDK for Swift is currently in alpha which you can find here - https://github.com/awslabs/aws-sdk-swift/tree/6b2c6336bf55ed352a7291fc42c85fb0c8ebba6a/release/AWSKinesis
