### ISSUE TITLE
Preferred way of subscribing to events

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#1069]
Hello,

I'm writing because I'm wondering what's the preferred way of subscribing to item-change events. I can see two methods:
1. To go via `Amplify.DataStore.publisher` as described [here](https://docs.amplify.aws/lib/datastore/real-time/q/platform/ios#usage)
2. Get notified via `Amplify.Hub.listen`, specifically `HubPayload.EventName.DataStore.syncReceived`, as described [here](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/ios#outboxmutationprocessed)

Currently, my project uses both as I believe method 1. was available before method 2. However, that seems like unnecessary overhead and I wonder whether there's any disadvantages just going with method 2, as I'll need `Amplify.Hub.listen` anyways.

Can any of the two methods be configured such that they don't fire on self-initiated events? Suppose, I call `Amplify.DataStore.delete`, then I get an event shortly afterwards (via both methods). Currently, I'm using a hand-written filter around the events to distinguish which ones are self-made and which do actually come from another client. However, this doesn't seem right...

Any hints are greatly appreciated.

Thank you!

**Comment by diegocstn** [comment]
Hi @anatomybook,
yes you're correct, we added support for DataStore hub events later. 

I believe there's no advantage of one over the other, but it's more a matter of APIs availability and app architecture. 
`Amplify.DataStore.publisher` is built on top of Apple's Combine thus is only available on iOS 13 or higher, while `Amplify.Hub.listen` is available from iOS 11 (there's also a `Amplify.Hub.publisher` Combine version).
So based on your app availability you may decide to use one or the other.

`Amplify.Hub` provides a central place to handle events across different Amplify categories, so you may decide to have a centralized logic to handle events vs a "distributed" approach or use both based your app architecture.
You should also consider the type and granularity of events you're interested in.

Unfortunately there's no configuration to filter out self-initiated events, but it'd be helpful to know what's your use case.

**Comment by anatomybook** [comment]
Thanks for your answer @diegocstn 

Then I'll probably go the `Amplify.Hub` way.

My case is the following:
First I should add, that my DataStore structure is a tree, i.e. every user has a root object, that contains all the other items.
After trying out various abstraction layers, I found that keeping extra layers in sync is a pain and not worth the benefit. Hence, my SwiftUI-Interface rests on a single DataStore root item, that is `@Published`. If the UI needs refresh, I re-query that item and everything re-draws. So far, so convenient.
In order to avoid unnecessary refreshes, I need to filter self-initiated events. So from my point of view, I'm only interested in events, that originate from other clients - since only then the GUI needs to be made aware of underlying changes.

Does this make sense?
Thanks again for your answer.

**Comment by anatomybook** [comment]
My initial question has been answered.

Thank you.
