### ISSUE TITLE
Unable to update pods to 1.6

### ISSUE THREAD

**Issue by mudilajaganios** [aws-amplify/amplify-ios#1082]
**Describe the bug**
I tried all ways possible to update the Amplify pods to latest version. I could succeed none so far.
1. pod install
2. pod install --repo-update
3. pod update

**Expected behavior**
Expected to update all the Amplify pods to the latest version current version is 1.5.0, needed 1.6.*

**Screenshots**
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
inhibit_all_warnings!

target 'TestApp' do
  use_frameworks!
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AWSPinpoint'
  pod "AWSSNS"
  pod "AWSCognito"
end

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 1.5.3]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version: [e.g. 5.0]
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Comment by palpatim** [comment]
The **AWSCognito** pod was removed from the AWS Mobile SDK for iOS in [the 2.20.0 release](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0) December 2020, after being deprecated for a couple of years. Since 2.19.1 is the last version that contains that pod, CocoaPods has to resolve the entire dependency graph to that version.

To fix, remove the **AWSCognito** pod and use Amplify Data Store to synchronize app data.

**Comment by mudilajaganios** [comment]
> The **AWSCognito** pod was removed from the AWS Mobile SDK for iOS in [the 2.20.0 release](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.20.0) December 2020, after being deprecated for a couple of years. Since 2.19.1 is the last version that contains that pod, CocoaPods has to resolve the entire dependency graph to that version.
> 
> To fix, remove the **AWSCognito** pod and use Amplify Data Store to synchronize app data.

Thanks a lot. It worked. I could update to the latest version.
