### ISSUE TITLE
Type is ambiguous without more context Amplify Passwordless Custom Auth Flow

### ISSUE THREAD

**Issue by mapworkmobile** [aws-amplify/amplify-ios#1087]
**Describe the bug**
When copying this code directly from the Amplify iOS documentation:

func signIn(username: String) {
    Amplify.Auth.signIn(username: username) { result in
        switch result {
        case .success:
            if case .confirmSignInWithCustomChallenge(_) = result.nextStep {
                // Ask the user to enter the custom challenge.
            } else {
                print("Sign in succeeded")   
            }
        case .failure(let error):
            print("Sign in failed \(error)")
        }
    }
}

I receive error 'Type is ambiguous without more context'

Screenshot here:

https://i.stack.imgur.com/mBfdb.jpg
**To Reproduce**
1. Copy the signIn code from the Amplify iOS documentation into an Xcode project

**Expected behavior**
No compile time errors

**Screenshots**
https://i.stack.imgur.com/mBfdb.jpg

**Environment(please complete the following information):**
 - Amplify Framework Version: How to find?
 - Dependency Manager: CocoaPods
 - Swift Version: 5.0
 - CLI Version: 4.24.2

**Device Information (please complete the following information):**
 - Device: macOS BigSur 11.0
 - iOS Version: iOS 14

**Comment by palpatim** [comment]
Hi @mapworkmobile, What version of Xcode are you running?

**Comment by mapworkmobile** [comment]
I was able to clear this bug by cleaning the build file. Strange one!

**Comment by palpatim** [comment]
@mapworkmobile 

Thanks for confirming--this is so common a fix working in Xcode that I have a command-line alias that I run a couple of times a day just to make sure my Derived Data folder is clean. :)
