### ISSUE TITLE
List not being properly stored in DynamoDB

### ISSUE THREAD

**Issue by bradlee96** [aws-amplify/amplify-ios#1091]
**Describe the bug**
When I upload a user's profile (Profile) and their interests (UserInterest) to DynamoDB, it is successful, but there is no entry in the table to access interests from the profile table despite being them connected through @connection/@key. The reverse is possible, since the profileId is properly stored in each UserInterest. I've noticed that in xcode, the interests are stored in Profile as List<UserInterest> for some reason, so maybe that has something to do with it?

**To Reproduce**
I've attached some screenshots below regarding my GraphQL schema. 
1. amplify codegen models to generate the models
2. Upload a sample Profile and some UserInterests to DynamoDB
3. Look at Profile table in DynamoDB; there won't be a field for storing UserInterests.
Please let me know if you have any questions!

**Expected behavior**
A list of type [UserInterest] in the Profile table of DynamoDB, so I can access interests given a user's profile.

**Screenshots**
<img width="606" alt="Screen Shot 2021-03-06 at 12 33 08 PM" src="https://user-images.githubusercontent.com/16856014/110217141-1cd79d80-7e78-11eb-8f8a-7804912fcaff.png">
<img width="563" alt="Screen Shot 2021-03-06 at 12 33 27 PM" src="https://user-images.githubusercontent.com/16856014/110217151-29f48c80-7e78-11eb-80bf-3e898edcf5ec.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.3
 - Dependency Manager: Cocoapods
 - Swift Version: 5
 - CLI Version: 4.40.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 14

**Comment by palpatim** [comment]
@bradlee96 

As of the [1.6.0 release](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0), Amplify has better support for navigating through `List` members of a loaded object. In your case, you could in your app code retrieve a `Profile` instance, then fetch the `interests` values for that profile.

(Behind the scenes, DataStore stores its `@model` annotated types in separate DynamoDB tables. That means if you want to find `UserInterests` for a given `Profile` outside of DataStore client code, you'd query your DDB `UserInterest` table by `profileId`.)

If this doesn't answer your question, could you clarify the use case you are trying to accomplish?

**Comment by bradlee96** [comment]
@palpatim

That's exactly what I was actually trying to do. I query my database for the `Profile` instance then try to get the `interests` values for the profile. However, I noticed that the `interests` values were nil. When I looked in the DynamoDB table, the profile didn't contain something like `profileInterestIds` or anything I could use to access the associated interests through that profile. 

I appreciate your quick response!

**Comment by palpatim** [comment]
Glad this helps! Please feel free to reopen this issue if you encounter a problem using the suggested flow.

**Comment by bradlee96** [comment]
@palpatim

Hello, I was actually saying that I was attempting to implement your solution, but I encountered troubles along the way.

> @palpatim
> 
> That's exactly what I was actually trying to do. I query my database for the `Profile` instance then try to get the `interests` values for the profile, but the values were nil. The expected entries are present in both the `Profile` and `UserInterest` tables. **It's just the connection between them that is missing it seems. When I looked in the DynamoDB table, the profile didn't contain something like `profileInterestIds` or anything I could use to access the associated interests through that profile.** So I'm trying to figure out how I can access `interests` through the `Profile`, just like you said.
> 
> I appreciate your quick response!

**Comment by palpatim** [comment]
Glad it worked for you!
