### ISSUE TITLE
Customizing authentication error messages

### ISSUE THREAD

**Issue by mapworkmobile** [aws-amplify/amplify-ios#1092]
**Is your feature request related to a problem? Please describe.**
I'm trying to display a custom error message to a user on a sign in form when their input does not pass validation, or for any other server-side error. The reason is that the messages currently are not very user-friendly.

**Describe the solution you'd like**
I would ideally like an enum that would say, for instance, error.type = .userNotFound, so that I can switch against that case and provide a custom error message.

**Describe alternatives you've considered**
None, I've no idea how to approach this and the docs are somewhat lacking.

**Comment by palpatim** [comment]
@mapworkmobile Can you clarify whether this is a custom sign in form displayed in your app? What mechanism are you using to sign in users? If you're using "Hosted UI" (that is, `Auth.signInWithWebUI`), then those error messages would either be displayed on the social provider's sign in, or by Cognito User Pools' HostedUI web interface; either way, not something under the Amplify library's or your app's control.

If you're using `Auth.signIn` to start a sign in with a username/password (or custom auth flow), then we return some errors already -- you can switch on the [`AuthError` enum values](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Auth/Error/AuthError.swift) and inspect the underlying errors (where present) for more detail.

We are aware that the error handling [needs some refinement](https://github.com/aws-amplify/aws-sdk-ios/issues/3431)--right now there are too many enums with not a lot of documentation around the conditions that will generate each of those conditions. We're considering the best ways of handling that, but don't have any specific guidance just now.

**Comment by mapworkmobile** [comment]
Palpatim, 

Thanks for the response! I am calling using Auth.signIn as I am attempting to implement a passwordless phone number Auth Flow. I saw that I can get access to underlyingError but I have no idea what the possible enum cases are that i can switch on that value. I'm either just very stupid or there isnt much documentation around for this.

**Comment by palpatim** [comment]
Thanks for clarifying. You're correct that there isn't much in the way of documentation, but the problem is deeper than that: the error messages can be difficult to interpret because error codes might represent different underlying conditions, differentiated only by the message returned by the service.

We're exploring better error handling as part of the [linked issue](https://github.com/aws-amplify/aws-sdk-ios/issues/3431), so I'd recommend following that thread for updates.
