### ISSUE TITLE
How to change amplify storage folder

### ISSUE THREAD

**Issue by yusuftor** [aws-amplify/amplify-ios#1105]
Currently, amplify storage stores the public files in the "/public" folder in a bucket. How can I change this so that it stores them in the root folder, without the need for that "/public" folder?

**Comment by royjit** [comment]
We already have a feature request here - https://github.com/aws-amplify/amplify-ios/issues/916 . Please follow this ticket https://github.com/aws-amplify/amplify-ios/issues/916 for further updates. Closing https://github.com/aws-amplify/amplify-ios/issues/1105 as duplicate
