### ISSUE TITLE
Fails to fetch tokens

### ISSUE THREAD

**Issue by AugustDev** [aws-amplify/amplify-ios#1108]
**Describe the bug**
Problem seems to manifest if user does not use the app frequently. At some point `Amplify.Auth.fetchAuthSession` returns success with case `session.isSignedIn`, however trying to fetch token fails with error `The operation couldn’t be completed. (Amplify.AuthError error 7.)`. Restarting the app doesn't help.

This completely bricks the app as we identify successful log in based on result of `Amplify.Auth.fetchAuthSession`, however since tokens cannot be obtained all network requests fail. The only solution is manual log out and log in.

**To Reproduce**
I am not able to reproduce the problem myself as I use app very frequently, however many of our users complain and I observed error messages in analytics.

**Expected behavior**
I expect that as long as `Amplify.Auth.fetchAuthSession` is successful the tokens can be obtained.
If I understand correctly if tokens cannot be obtained user should be logged out. If refresh token cannot be obtained then `Amplify.Auth.fetchAuthSession`  should fail?

![image](https://user-images.githubusercontent.com/5672094/111447759-a8b5b900-8705-11eb-813d-d98109431ab2.png)
Error 7 seems to be caused by expired session.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.4
 - Dependency Manager: Cocopods
 - Swift Version: 5.2
 - CLI Version: Not using CLI
 - Include any relevant log output under: Not using CLI

**Device Information (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: iOS 14

**Additional context**
My Cognito token config is
![image](https://user-images.githubusercontent.com/5672094/111447409-51afe400-8705-11eb-8e09-c4fc67b363d5.png)

**Our login flow**
During the start of the app:
If `Amplify.Auth.fetchAuthSession` fails we treat user as unauthenticated and present login screen.
If `Amplify.Auth.fetchAuthSession` succeeds we treat user as authenticated and present the main app.

**Comment by AugustDev** [comment]
Hi @royjit thank you very much for the reply and code samples.

I'm a little bit confused why Ampify does not try to reauthenticate automatically. I think as long as refresh token is not expired there should be no need for user to reauthenticate?

Do you have any insight how "session" is defined? I'm struggling to find exactly what it means in Amplify auth context.

**Comment by royjit** [comment]
Apologies for not being clear in my post `AuthError.sessionExpired` is fired only if the refresh token is expired or invalid. You are right, Amplify will automatically refresh the tokens if there is a valid refresh token.

**Comment by AugustDev** [comment]
Thanks for explanation @royjit. Problem solved.

**Comment by AndyMeagher** [comment]
@royjit I am experiencing this exact issue even though my Refresh Tokens are set to expire every 365 days. I get a `sessionExpired` error after about a week of not using it. How is this possible?

**Comment by ethan021021** [comment]
> @royjit I am experiencing this exact issue even though my Refresh Tokens are set to expire every 365 days. I get a `sessionExpired` error after about a week of not opening the app. How is this possible?

I am experiencing this exact issue with my refresh tokens set to expire every 365 days. Have you been able to find a workaround?

**Comment by 5d** [comment]
Hi @ethan021021 ,


Could you create a new issue ticket regarding the refresh token and make a reference to this one in the new ticket?

**Comment by devendra-thakur** [comment]
Hi 
I am experiencing this exact issue with my refresh tokens set to expire every 180 days. Have you been able to find a workaround?
We are facing this issue in both approaches (SDK & API)
