### ISSUE TITLE
iOS: Manually configure auth Amplify Configuration

### ISSUE THREAD

**Issue by paluka** [aws-amplify/amplify-ios#1111]
Hi, in my React Native app, I am able to configure amplify manually:

    const authConfig = { 
        mandatorySignIn: true,
        region: amplifyAuthConfig.region,
        userPoolId: amplifyAuthConfig.userPoolId,
        userPoolWebClientId: amplifyAuthConfig.userPoolWebClientId
    };

    Amplify.configure({
        Auth: authConfig,
    });
  
I am having difficulty doing the same with my native iOS app:

    let apiConfig = AuthCategoryConfiguration(plugins: [
            "awsCognitoAuthPlugin": [
                "CognitoUserPool": [
                    "Default": [
                        "PoolId": "xx",
                        "Region": "us-east-1",
                        "AppClientId": "xx",
                        "AppClientSecret": "xx"
                    ]
                ]
            ]
        ])
    
    do {
        try Amplify.add(plugin: AWSCognitoAuthPlugin())
        try Amplify.configure(AmplifyConfiguration(auth: apiConfig))
        print("Amplify configured with auth plugin")
    } catch {
        print("Failed to initialize Amplify with \(error)")
    }

Is this the correct `awsCognitoAuthPlugin` configuration keys? Saw this template from: https://gitmemory.com/issue/aws-amplify/amplify-ios/651/661269179

**Comment by royjit** [comment]
Thank you for reaching out, the format for using existing resource is shown here - https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios

**Comment by paluka** [comment]
Thanks for the quick response. 
(1) Does that mean that I should not configure it programmatically and should use a amplifyconfiguration.json file? 
(2) If the answer is yes, does that mean that I don't need to run `amplify init` in the project as I already have existing resources?

**Comment by royjit** [comment]
@paluka The link I gave is the reference for how the amplify config should look like for auth.  Looking at your code the configuration you passed is correct. So I tried to reproduce it myself, with your exact code and it worked for me without any issue. Seems like there is something else going on with your setup. Are you seeing any error? 

To answer your question:

1) You can do either way. Configure it programmatically or use the json file.

2) You do not need to call `amplify init`, just add the json file into your project `amplifyconfiguration.json`.

**Comment by paluka** [comment]
Thank you. I am closing the issue.
