### ISSUE TITLE
Get an alert "App wants to use "amazoncognito.com" to sign in" each time when I try to sign in\sign out using Google\FB etc.

### ISSUE THREAD

**Issue by hellopandaxx** [aws-amplify/amplify-ios#1120]
Guys, can you help me please. How can I get rid of this alert and how to control it? 
Also this alert appears even on sign out.
Or can it be accepted somehow once, in order to prevent it from appearing every time on sign in attempt?
![IMG_0250](https://user-images.githubusercontent.com/42697790/112018220-6cd48680-8b3f-11eb-9ecf-d1fdb555ae10.jpg)

Thank you,
Sergey

**Comment by jgale** [comment]
You can use this option, which will set `ASWebAuthenticationSession`'s `prefersEphemeralWebBrowserSession` to `true. This avoids the dialog, but means it won't share any cookies if the user is already signed in in Safari.

```swift
        let options = AuthWebUISignInRequest.Options(
            pluginOptions: AWSAuthWebUISignInOptions(
                preferPrivateSession: true
            )
        )

        Amplify.Auth.signInWithWebUI(for: provider, presentationAnchor: keyWindow, options: options) { result in
           ...
```

**Comment by palpatim** [comment]
@jgale is correct--that option will prevent the dialog on sign out for users running iOS 13+, at the expense of not sharing sign-in credentials from other login sessions. I believe users will always see a popup during sign in though, even if we set that flag. That dialog is displayed by iOS to ensure users understand the domain requesting permissions via the OAuth flow.

**Comment by palpatim** [comment]
> This will actually stop it showing up during sign in. 😃

Thanks for the clarification!

Do let us know if you continue to see an alert on sign out. As long as you are signing in with the `preferPrivateSession` flag to true, on a device running iOS 13+, on a device with the default browser set to one that supports the `prefersEphemeralWebBrowserSession` flag (i.e., Safari), we would not expect to see the popup on sign out. Do note that upgrading the SDK to a new version wouldn't be sufficient to not get the pop up--we evaluate `preferPrivateSession` flag during the sign in flow.
