### ISSUE TITLE
multi-language

### ISSUE THREAD

**Issue by dota2AndTI** [aws-amplify/amplify-ios#1126]
Predictions->Identify text 

Does it support multilingual recognition?
Does it support multilingual recognition for the same image?

**Comment by palpatim** [comment]
@dota2AndTI The AWS Rekognition service (which backs remote calls to detect text in images) basically just identifies strings of Latin characters. The [Rekognition service docs](https://docs.aws.amazon.com/rekognition/latest/dg/text-detection.html) specify:

> A _word_ is one or more ISO basic Latin script characters that aren't separated by spaces. `DetectText` can detect up to 50 words in an image, and `GetTextDetection` can detect up to 50 words per frame of video. Amazon Rekognition can also detect numbers and common symbols such as @, /, $, %. -, _, +, *, and #.

Based on that, my guess is that the service is going to return areas of an image that contain strings of characters, and it would be up to you to identify the language of the returned string, such as with a [`Predictions.interpret()`](https://docs.amplify.aws/lib/predictions/interpret/q/platform/ios) call.

Hope this helps.
