### ISSUE TITLE
cloudwatch describeLogStreams uploadsequencetoken empty

### ISSUE THREAD

**Issue by kavinsaravan** [aws-amplify/amplify-ios#1127]
**Describe the bug**
describeLogStreams uploadsequencetoken empty

**To Reproduce**
    AWSLogs.default().describeLogStreams(req!) { (response, error) in
        if ((error) != nil) {
            Logging.logError("ERROR: AWS CW describe Log Stream error: \(String(describing: error))")
        } else {
            self.nextSequenceToken = response?.logStreams?.first?.uploadSequenceToken
// ^^^^^ above value is nil
        }

**Expected behavior**
Upload sequence token should not be empty / nil

**Screenshots**
![Screen Shot 2021-03-25 at 1 43 40 PM](https://user-images.githubusercontent.com/66988352/112544658-8579b200-8d74-11eb-9b6c-5049cd9dd03e.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.0
 - Dependency Manager: cocoapods
 - Swift Version: 5
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Comment by palpatim** [comment]
Could you add some details around how you configure this? Amplify CLI does not includes any setup support for backend logs, so it would be up to you to configure appropriate IAM policies. You would also have to authenticate your AWSLogs client, which could be done by either the legacy SDK or Amplify.Auth. More details around this will help us investigate this. On the face of it, it's not clear that this belongs in the `amplify-ios` repo.

**Comment by palpatim** [comment]
Also, you're chaining several optionals in that statement. Which of the values is actually nil? It could be anything starting with `response`.

**Comment by saravr** [comment]
@palpatim looks like first need to send some events even if uploadSequenceToken is empty. After that I see that token is set and logging works. If this is the expected behavior, then the request should have been failed instead of returning success with token set to nil. Anyways, looks like I am set for now. Thanks.

**Comment by palpatim** [comment]
[The documentation](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_LogStream.html#CWL-Type-LogStream-uploadSequenceToken) is slightly ambiguous, but it seems reasonable that describing a log stream that has no data would return a successful response ("the log stream exists") with an empty token ("but has no data"). But that's supposition on my part--for more detailed discussion, I'd recommend asking on the [CloudWatch AWS Forum](https://forums.aws.amazon.com/forum.jspa?forumID=138).

Glad you were able to find a resolution for your particular issue, in any case. :)
