### ISSUE TITLE
Missing AmplifyModels from Xcode Project

### ISSUE THREAD

**Issue by Kilo-Loco** [aws-amplify/amplify-ios#1132]
**Describe the bug**
AmplifyModels doesn't always get added to Xcode project when using the `amplify pull --sandboxId` command. It also isn't something that is documented during the Sandbox flow that the files must be added to the Xcode project to get everything to work.  This can completely block a customer if the script doesn't update their Xcode project successfully.

<img width="346" alt="Screen Shot 2021-03-31 at 3 56 38 PM" src="https://user-images.githubusercontent.com/13292981/113221337-b0af4600-9239-11eb-9b49-b445f572d3bb.png">

**To Reproduce**
Customer reported... It was always reproducible on their machine but not on mine.

**Expected behavior**
Xcode project successfully updated with all required configuration files and models when following the Sandbox flow.

**Additional context**
This probably isn't enough to go on to resolve the bug, but the team should be aware of its existence.

**Comment by diegocstn** [comment]
Swift models files are being properly generated but the module that updates Xcode `project.pbxproj ` is not being invoked after a `pull` workflow.
PR: https://github.com/aws-amplify/amplify-cli/pull/7152

**Comment by diegocstn** [comment]
Fix released with amplify-cli [4.50.0](https://github.com/aws-amplify/amplify-cli/releases/tag/v4.50.0)
