### ISSUE TITLE
Question about Predictions: .detectText(.all) vs. .detectText(.plain)

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#1143]
Hello,

I've noticed the following:

When calling identify with .all `_ = Amplify.Predictions.identify(type: .detectText(.all), image: content_url)` the answer comes back as `IdentifyDocumentTextResult`.
When calling identify with .plain `_ = Amplify.Predictions.identify(type: .detectText(.plain), image: content_url)` the answer comes back either as `IdentifyTextResult` or `IdentifyDocumentTextResult`. Why is that?

But more importantly, within `IdentifyDocumentTextResult` the field `words` is always populated, but within `IdentifyTextResult` that is not always the case. `IdentifyTextResult` always seems to contain `identifiedLines`. This puzzles me, as words seem to be more basic than lines.
Anyways, currently I just run `.all`, but given that more testers use my app, this starts being expensive. All I care about is `words` being there. The post-processing I do myself, as I found the `identifiedLines` does not work well for my use-case. If I read the documentation of Textract correctly, `.plain` should be much cheaper.

Summarizing: Is there any way to always load the `words` field, such that I can only pay for what I actually use?

**Comment by thisisabhash** [comment]
When `.all` is passed to identify(), AWSTextract is used to analyze the image and the result is returned as `IdentifyDocumentTextResult`.
When `.plain` is passed to identify(), both AWSRekognition and AWSTextract are used to analyze the image. AWSRekognition has a word detection limit of 50 for an image and if an image contains more than 50 words, results from both AWSRekognition and AWSTextract are compared and whichever service  returns more detections, the appropriate result is returned. (`IdentifyDocumentTextResult` for AWSTextract/`IdentifyTextResult` for AWSRekognition)

The fields for `IdentifyDocumentTextResult` and `IdentifyTextResult` are populated based on the types(word or line) of text returned by the  service used for the query (AWSTextract/AWSRekognition). `.plain` is used primarily to detect text and '.all' is primarily used to detect  document type relationships(key-value pairs, forms, table).

**Comment by anatomybook** [comment]
@thisisabhash thank you very much for your answer. That makes sense. So I guess, I'll have to stick with `.all` to reliably obtain the words instead of the lines.
Or can you think of another way to always get the words without paying for lots of stuff I don't use? The words is really all I need. I'm not interested in key-value pairs, forms or tables.

**Comment by thisisabhash** [comment]
When `.plain` is passed to `identify()`, the result returned is taking into account both the Rekognition (DetectText API) and Textract (DetectDocumentText API) responses, when an image has more words than Rekognition limit.
Currently, there is no way to always get the `words` field populated as it depends on the responses from Rekognition and Textract.

**Comment by anatomybook** [comment]
@thisisabhash ,

Thank you very much for the clarification. This answers my question.
