### ISSUE TITLE
No such module 'AmplifyPlugins' when installed with Swift Package Manager

### ISSUE THREAD

**Issue by brightfuture** [aws-amplify/amplify-ios#1151]
I think i modified somewhere in Xcode project setting so i got this bug
I've checked all checkboxes when adding Amplify framework via SPM
what could be the cause ?

**Comment by brightfuture** [comment]
OK i solved it
didn't realize the import requirement is different from using Coacoa Pods
like this: 

> import SwiftUI
> import Combine
> import Amplify
> import AWSCognitoAuthPlugin
> import AWSAPIPlugin
> import AWSDataStorePlugin
> import AWSS3StoragePlugin
> import AWSPluginsCore

**Comment by palpatim** [comment]
Thanks for your followup. We did attempt to call out the revised import requirement in [the documentation](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios#n2-install-amplify-libraries).

Was there another place we could have updated that would have made this clearer for you?

**Comment by brightfuture** [comment]
@palpatim actually, it's on Github
here: https://github.com/aws-amplify/amplify-ios/issues/90#issuecomment-815308606
perhaps a little more emphasis on the changes ? 😅

**Comment by palpatim** [comment]
Thanks for the suggestion. I've edited my comment to specifically call out that there are changes in the way modules are imported in app code, so hopefully that will guide folks to the README better.
