### ISSUE TITLE
Amplify.Auth.fetchUserAttributes() in Xcode using combine framework returns unknown error

### ISSUE THREAD

**Issue by Wazambe** [aws-amplify/amplify-ios#1154]
**Describe the bug**
When trying to use Amplify.Auth.fetchUserAttributes() with combine, I receive error:

Auth_session_Manager: Fetch session failed with error AuthError: Unexpected error occurred with message: Unable to get valid sign in session from the end user.
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists.

Admittedly i'm no guru with combine, but have tried a couple of approaches to make sure that I don't lose the .sink.
To further verify I put the fetchUserAttributes() function between fetchAuthSession() and getCurrentUser() in the same class. All using same .resultPublisher.sink method, with .store to a Set<AnyCancellable>()

With above, both  fetchAuthSession() and  getCurrentUser() produce a positive receiveValue result (although it floods the debug console with weird Xcode comms error), but the fetchUserAttributes() produces the AmpliftAuth Error

**To Reproduce**
1. Using Xcode 12.4 for ios 14.1
2. Set up Amplify + AWSCognitoAuthPlugin()
3. Copy sample code from https://docs.amplify.aws/lib/auth/user-attributes/q/platform/ios
4. Run

**Expected behavior**
To return a positive receive value with .key & values for aut attributes

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 1.5.3]
 - Dependency Manager: Cocoapods
 - Swift Version: 5
 - CLI Version: 4.45.1
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Device Information (please complete the following information):**
 - Device:  iPhone8
 - iOS Version: iOS 14
 - Specific to simulators:

**Comment by palpatim** [comment]
Are you calling out Combine specifically because the behavior is different than using the "listener" flavor of the API, or are you simply noting it because that's the flavor of the API you happen to be using?

Can you share a code snippet of how you're actually invoking the Amplify.Auth APIs?

What version of the Amplify Framework are you using when you encounter this problem?

**Comment by Wazambe** [comment]
> Are you calling out Combine specifically because the behavior is different than using the "listener" flavor of the API, or are you simply noting it because that's the flavor of the API you happen to be using?
> 
> Can you share a code snippet of how you're actually invoking the Amplify.Auth APIs?
> 
> What version of the Amplify Framework are you using when you encounter this problem?

**Comment by Wazambe** [comment]
I'm just not sure about the specific function fetchUserAttributes() using combine.

Other functions return valid data in good time. Could be that it is an auth thing too, but to try and test that I nested the attributes call between the check session and get user functions. Both the aforementioned functions work fine.

The next test was to use listener callback on Get Attributes - and that does return valid attribute data.

Is ver 4.45  the version of framework (as is my impression), or limited to the CLI only?
