### ISSUE TITLE
Can't sign in again after performing sign out

### ISSUE THREAD

**Issue by brightfuture** [aws-amplify/amplify-ios#1156]
**To Reproduce**
1. sign out from a device
2. try to sign in again, MFA is enabled, receive an MFA SMS message
3. type in the verification code and confirm sign in
4. get error "Make sure that a valid challenge response is passed for confirmSignIn"

**Comment by palpatim** [comment]
Can you share your code that detects the MFA challenge and then sends the MFA? It would also be helpful to see your (appropriately redacted) **amplifyconfiguration.json** file to see how your User Pool is configured.

**Comment by brightfuture** [comment]
**code on MFA**
>      func signIn(username: String) {
>         Amplify.Auth.signIn(username: username, password: "123123123")
>             .resultPublisher
>             .receive(on: DispatchQueue.main)
>             .sink { [self] in
>                 if case let .failure(authError) = $0 {
>                     assertionFailure()
>                     inFocusPrompt = ("xmark.octagon.fill", authError.errorDescription)
>                     DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
>                         inFocusPrompt = nil
>                     }
>                 }
>             }
>             receiveValue: { [self] result in
>                 switch result.nextStep {
>                 case .done:
>                     Amplify.Auth.fetchAuthSession()
>                         .resultPublisher
>                         .receive(on: DispatchQueue.main)
>                         .sink { _ in
>                         } receiveValue: { [self] (session) in
>                             let identityProvider = session as! AuthCognitoIdentityProvider
>                             authIdentityId = try! identityProvider.getIdentityId().get()
>                             whatHappensAfterSignIn()
>                         }.store(in: &cancellables)
>                 default:
>                     break
>                 }
>             }.store(in: &cancellables)
>     }
>     
>     func confirmSignIn(smsCode: String) {
>         Amplify.Auth.confirmSignIn(challengeResponse: smsCode)
>             .resultPublisher
>             .receive(on: DispatchQueue.main)
>             .sink { [self] in
>                 if case let .failure(authError) = $0 {
>                     assertionFailure()
>                     inFocusPrompt = ("xmark.octagon.fill", authError.errorDescription)
>                     DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
>                         inFocusPrompt = nil
>                     }
>                 }
>             }
>             receiveValue: { [self] signInResult in
>                 Amplify.Auth.fetchAuthSession()
>                     .resultPublisher
>                     .receive(on: DispatchQueue.main)
>                     .sink { _ in
>                     } receiveValue: { [self] (session) in
>                         let identityProvider = session as! AuthCognitoIdentityProvider
>                         authIdentityId = try! identityProvider.getIdentityId().get()
>                         whatHappensAfterSignIn()
>                     }.store(in: &cancellables)
>             }.store(in: &cancellables)
>     }

**amplifyconfiguration.json**
> {
>     "UserAgent": "aws-amplify-cli/2.0",
>     "Version": "1.0",
>     "api": {
>         "plugins": {
>             "awsAPIPlugin": {
>                 "FRIENDSCAFE": {
>                     "endpointType": "GraphQL",
>                     "endpoint": "https://mksrmmcyuvcsnfc7f57cow545i.appsync-api.ap-northeast-1.amazonaws.com/graphql",
>                     "region": "ap-northeast-1",
>                     "authorizationType": "AMAZON_COGNITO_USER_POOLS"
>                 }
>             }
>         }
>     },
>     "auth": {
>         "plugins": {
>             "awsCognitoAuthPlugin": {
>                 "UserAgent": "aws-amplify/cli",
>                 "Version": "0.1.0",
>                 "IdentityManager": {
>                     "Default": {}
>                 },
>                 "AppSync": {
>                     "Default": {
>                         "ApiUrl": "https://mksrmmcyuvcsnfc7f57cow545i.appsync-api.ap-northeast-1.amazonaws.com/graphql",
>                         "Region": "ap-northeast-1",
>                         "AuthMode": "AMAZON_COGNITO_USER_POOLS",
>                         "ClientDatabasePrefix": "FRIENDSCAFE_AMAZON_COGNITO_USER_POOLS"
>                     },
>                     "FRIENDSCAFE_AWS_IAM": {
>                         "ApiUrl": "https://mksrmmcyuvcsnfc7f57cow545i.appsync-api.ap-northeast-1.amazonaws.com/graphql",
>                         "Region": "ap-northeast-1",
>                         "AuthMode": "AWS_IAM",
>                         "ClientDatabasePrefix": "FRIENDSCAFE_AWS_IAM"
>                     }
>                 },
>                 "CredentialsProvider": {
>                     "CognitoIdentity": {
>                         "Default": {
>                             "PoolId": "ap-northeast-1:f4658ead-3eb6-487d-8d63-534490cc0e58",
>                             "Region": "ap-northeast-1"
>                         }
>                     }
>                 },
>                 "CognitoUserPool": {
>                     "Default": {
>                         "PoolId": "ap-northeast-1_AXmyeE3n0",
>                         "AppClientId": "11ep0thbqptl3gk5v221da831k",
>                         "Region": "ap-northeast-1"
>                     }
>                 },
>                 "Auth": {
>                     "Default": {
>                         "authenticationFlowType": "USER_SRP_AUTH"
>                     }
>                 },
>                 "S3TransferUtility": {
>                     "Default": {
>                         "Bucket": "friends-cafe231147-prod",
>                         "Region": "ap-northeast-1"
>                     }
>                 }
>             }
>         }
>     },
>     "storage": {
>         "plugins": {
>             "awsS3StoragePlugin": {
>                 "bucket": "friends-cafe231147-prod",
>                 "region": "ap-northeast-1",
>                 "defaultAccessLevel": "guest"
>             }
>         }
>     }
> }

@palpatim let me know if you need more information

**Comment by brightfuture** [comment]
i also discovered the users that i deleted from Admin UI still exists on Cognito user pools

**Comment by brightfuture** [comment]
i found the problem 
it's a bug in my programm 😂
Auth is fine
it was very subtle so i never noticed it
thanks for the attention @palpatim
