### ISSUE TITLE
Getting "ITMS-90680: Invalid directory" errors when uploading binary to ASC after migrating to Swift Package Manager

### ISSUE THREAD

**Issue by roddymunro** [aws-amplify/amplify-ios#1160]
**Describe the bug**
After moving from Cocoapods to Swift Package Manager and then trying to upload my binary to the App Store, I am met with a whole host of errors relating to the Amplify packages being in an 'App Clips' folder. What is really strange is that I have no App Clips - I only have the iOS target in my project.

[Link to error logs](https://gist.github.com/roddymunro/4b0b358e5a8608861dadb99dc6769ca8)

**To Reproduce**
1. Deintegrate Cocoapods from an existing project that has just an iOS target
2. Remove the Xcode workspace file (I no longer needed it)
3. Add the desired Amplify packages via Swift Package Manager to the project (I needed them all)
4. Building and running works fine on device, as does Archive
5. When uploading the binary to App Store Connect, that's when the errors linked above show

**Expected behavior**
The binary should successfully be submitted to ASC for processing.

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.8.0
 - Dependency Manager: Migrated to SPM from Cocoapods
 - Swift Version: Swift 5
 - CLI Version: 4.46.2

**Device Information (please complete the following information):**
 - Device: iPhone X, but all devices
 - iOS Version: 14.4.2
 - Specific to simulators: N/A

**Additional context**

**Comment by roddymunro** [comment]
It turns out two extra build phases appeared under 'Build Phases' since doing the migration:
- Embed App Clips
- Embed App Extensions

I didn't have either of those before, so I'm wondering if this migration created them? Migrating to SPM from Cocoapods for my Amplify dependencies was all I did knowingly since my last upload, so I'm wondering if this is what created them.

Removing the above build phases fixed it for me

**Comment by royjit** [comment]
Glad you have figured out the issue. I tried migrating a sample app that was using Cocoapod to Swift Package Manager. Did not see anything new added to Build Phases. I am optimistically closing this issue, do let us know if you see this behavior again.
