### ISSUE TITLE
DataStore.stop followed by DataStore.start does not establish sync engine subscriptions

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#1177]
**Describe the bug**
DataStore.stop followed by DataStore.start is not working as expected. DataStore should be started successfully

Side note: DataStore.publisher's are completed when DataStore.stop is called. This is the current behavior, different from Android and Flutter, either this should be documented with expected call patterns or code updated to not complete the publishers.

**To Reproduce**
1. DataStore with sync to cloud enabled
2. subscribe to a single model
3. query all data for a particular model
4. perform mutations from AppSync console, ensure that subscriptions fire and query for all data returns data.

**Scenario 1 - Working state**
1. tap "stop" to call DataStore.stop, wait for console logging to finish
2. tap "start" to call DataStore.start, wait for console logging to finish
3. Perform mutation from console
4. query for all data, data should be more than before since sync engine subscriptions have been established, and starting the sync engine would catch the local store up to date with remote.
5. breakpoint on subscription, notice that subscriptions are not triggered from the mutation. the reason is because the subscription has been completed from stopping DataStore
6. tap "subscribe" to call DataStore.publisher and re-establish the subscription.
7. perform the mutation, subscription should trigger and query returns latest collection of data

**Scenario 2 - Not working state**
1. tap "stop-start" to call DataStore.stop, followed by DataStore.start in the success completion of the stop.
2. noticed a lot of logs with `ignoring data event for` coming from the AppSyncRealTimeClient
3. performing mutation from console
4. data is not updated, seems like subscriptions were not established correctly. This leds me to think that the two calls ran concurrently at some point. (completion of `stop` is not the correct time to call `start`)
5. tap "start" prints out `Start completed`. no way to get the sync engine back into a good start without restarting the app.
6. I can tap "stop" again followed by tapping "start", since they are so far apart in execution, I am able to get the sync engine back into a working state.

**Expected behavior**
What is the use case of calling `DataStore.stop` followed by `DataStore.start`? Sometimes an app will be backgrounded for a long time, and subscriptions are stale and becomes disconnected, then when the app goes back to foreground, DataStore should get back into a working state. What happens when it does not? For subscriptions, developers can make a single API call to reestablish a subscription connection. For DataStore's sync engine, developers want to try and "restart" the sync engine, to make sure things are working as expected. 

Should developers be trying to restart DataStore by calling `stop` followed by `start`? Whether this restart functionality should be available or not, the two APIs provided should interpolate with each other, as in the completion of "stop" should allow the developers to call "start" without the system breaking.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.8.2
 - Dependency Manager: [e.g. Cocoapods, Carthage]: SPM
 - Swift Version: [e.g. 5.0]
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]: 4.46.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]: Iphone12pro simluator
 - iOS Version: [e.g. iOS 11]: iOS 14.4
 - Specific to simulators: only tested on simulator

**Comment by richardmcclellan** [comment]
> What is the use case of calling DataStore.stop followed by DataStore.start? 

One important use case is to force re-evaluation of sync expressions at runtime: https://docs.amplify.aws/lib/datastore/sync/q/platform/ios#reevaluate-expressions-at-runtime

**Comment by lawmicha** [comment]
> > What is the use case of calling DataStore.stop followed by DataStore.start?
> 
> One important use case is to force re-evaluation of sync expressions at runtime: https://docs.amplify.aws/lib/datastore/sync/q/platform/ios#reevaluate-expressions-at-runtime

thanks for pointing this out @richardmcclellan !

**Comment by lawmicha** [comment]
PR out to fix websocket client code: https://github.com/aws-amplify/aws-appsync-realtime-client-ios/pull/46 

When DataStore.stop -> calls API's subscription operation.cancel() -> on the last subscription, AppSyncRealTimeClient will disconnect the websocket asynchronously from the unsubscribe.

The changes move the websocket disconnect within the same block of work as the last unsubscribe, so after an subscrition operation.cancel(), triggering DataStore.start -> subscribe, and connect to websocket will always come after the websocket disconnect from the DataStore.stop

**Comment by ruiguoamz** [comment]
The fix was released in `Amplify 1.9.1`.
