### ISSUE TITLE
 "amplify-ios" could not be resolved - has no Package.swift manifest for version 1.4.3

### ISSUE THREAD

**Issue by morgler** [aws-amplify/amplify-ios#1183]
**Describe the bug**
Trying to add the Swift package to an Xcode (12.4) project fails with error `"amplify-ios" could not be resolved`.

**To Reproduce**
1. Create a new SwiftUI iOS app in Xcode
2. Add Swift Package dependency
3. Insert this repos URL for the dependency
4. Choose either 1.8.0 or 1.8.1 as the version
5. Wait some time and see the "Package Resolution Failed" with the above detailed error message

**Expected behavior**
Instead of a failed package resolution, I should be able to pick the parts of the package I want to use (according to https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios#n2-install-amplify-libraries)

**Screenshots**
<img width="760" alt="Bildschirmfoto 2021-04-25 um 14 23 52" src="https://user-images.githubusercontent.com/101368/115993185-f9a4b100-a5d1-11eb-9002-39af18eb8bb4.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.8.1 (also tried 1.8.0)
 - Dependency Manager: Swift Package Manager
 - CLI Version: 4.49
 
**Device Information (please complete the following information):**
 - Device: MacBook Pro (Big Sur)
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Additional context**
The exact error shown is:

`https://github.com/aws-amplify/aws-appsync-realtime-client-ios.git has no Package.swift manifest for version 1.4.3`

**Comment by lawmicha** [comment]
Hi @morgler, I couldn't reproduce this issue and was able to get to the "Add Pacakge to [APP]" screen. Could you try again and let us know if you are still seeing this issue? I'm also using Xcode 12.4. 

`1.4.3` of Amplify does not have SPM support, what was the Rules that you picked on the previous screen?

**Comment by AllioNicholas** [comment]
I'm facing the same issue on Xcode 12.4. I tried with the following rules:
* exact 1.9.0
* upToNextMajor 1.9.0
* upToNextMinor 1.9.0
* exact 1.8.1
* exact 1.7.2

**Comment by ruiguoamz** [comment]
Hi, @morgler and @AllioNicholas 

I also could not reproduce this issue. Are you still seeing this issue?

**Comment by AllioNicholas** [comment]
> Hi, @morgler and @AllioNicholas
> 
> I also could not reproduce this issue. Are you still seeing this issue?

Now it seems to work, but I have a conflict of dependency versions with another package so I cannot confirm the full integration

**Comment by aurelien-m** [comment]
Hello, I'm also getting this error, is there anything I can try to debug this? I followed the [documentation](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/ios/#2-install-amplify-libraries). I tried using different versions of the project but none of them worked.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/29719028/130576012-2785bc47-14cf-4cb5-a639-51d2c44701ff.png">

Thanks.
