### ISSUE TITLE
API is executed with expired access token (401 status)

### ISSUE THREAD

**Issue by zmkokeshi** [aws-amplify/amplify-ios#1222]
**Describe the bug**
We are using API Gateway and amplify API methods.
In some cases, 401 is returned.
We believe it is caused due to expiration of access token because 401 is returned 1 hour after calling API
The access token expiration time is set to one hour.
Is it possible that the access token will not be refreshed?
In javascript, we can use “Auth.currentSession()" to refresh access token but is does not seem to work for IOS
Is there any way to force refresh access token?

**Expected behavior**
The access token will be updated when the API is run, even if it is not done manually.

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 1.9.1]
 - Amplify Categories:
   - [ ] Analytics
   - [ x ] API
   - [ ] Auth
   - [ ] DataStore
   - [ ] Predictions
   - [ ] Storage
 - Dependency Manager: [e.g. SwiftPM, Cocoapods]
 - Swift Version: [5]
 - Xcode Version: [12.5]

**Is this a regression (i.e. was this working before a version upgrade?)
I tried it with 1.6.0 and 1.9.1 and it reproduced both.

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6S+, Simulator]
 - iOS Version: [e.g. iOS 14.5]
 - Specific to simulators:

**Comment by palpatim** [comment]
A few questions:

1. What authorization mode is your API set up with? Can you give us the details of your configuration by pasting your `amplifyconfiguration.json` with your IDs redacted?
1. If you're using User Pools auth, what are the expiration times of each of the tokens (Refresh, Access, and ID) of your User Pools App client?
1. How are you calling the API in your app code? Have you set up any custom interceptors?

**Comment by zmkokeshi** [comment]
>What authorization mode is your API set up with? Can you give us the details of your configuration by pasting your amplifyconfiguration.json with your IDs redacted?

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-northeast-1:xxxxxxx,
                            "Region": "ap-northeast-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-northeast-1_xxxxxx",
                        "AppClientId": "xxxxxxxxxxx",
                        "Region": "ap-northeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxxxx.auth.ap-northeast-1.amazoncognito.com",
                            "AppClientId": "XXXXXX",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin",
                                "XXXXXXXXX/write"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    },
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "api49af8a61": {
                    "endpointType": "REST",
                    "endpoint": "https://xxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/xxx",
                    "region": "ap-northeast-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "XXXXXXXX",
                "region": "ap-northeast-1"
            }
        }
    }
}

```

>If you're using User Pools auth, what are the expiration times of each of the tokens (Refresh, Access, and ID) of your User Pools App client?

access token 60min
ID token 60min
refresh token 3650days

>How are you calling the API in your app code? Have you set up any custom interceptors

This is the code used for calling API :

```
        _ = Amplify.API.get(request: request) {[weak self] result in
            switch result {
            case .success(let data):
                let str = String(data: data, encoding: .utf8)
                print(str as Any)
                let decoder = JSONDecoder()
                do {
                    let target = try decoder.decode(T.self, from: data)
                    completion(.success(target))
                } catch {
                    completion(.failure(.responseParseError(error)))
                }
            case .failure(let error):
                if case let .httpStatusError(statusCode, response) = error {
                    switch statusCode {
                    case 401:
                        self?.moveToLogin()
                        return
                    default:
                        print(error)
                    }
                }

                print("Failed", error)
                completion(.failure(.apiError(error)))
            }
        }


```

**Comment by zmkokeshi** [comment]
I'm able to access the API.
However, sometimes there are users who cannot access the API due to 401.

It may be related to this issue.
https://github.com/aws-amplify/aws-sdk-ios/issues/2854

Ideally, the access token should be updated on API request.
For now, we would like to avoid throwing a request with an expired access token.

Is there any way to force the access token to be refreshed?

By deleting the access token in the keychain, I've confirmed that  a new access token with a new expiration date will be issued.
But i don't know the impact it will cause so i would like to avoid it.

**Comment by royjit** [comment]
`Amplify.Auth.fetchAuthSession` can be used to trigger token refresh. The api internally [calls Cognito refresh token api](https://github.com/aws-amplify/aws-sdk-ios/blob/4e67100e93bfaafef4a49a7faf9ec8e9d737da5c/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L254) if either idtoken or accesstoken is about to expire. This api refreshes the token if there is 2 min or less for the tokens to expire. 

The API plugin also internally calls this api while making an API request. So we expect the token to be refreshed.

I tried to reproduce the issue:

1. Created an app with `AMAZON_COGNITO_USER_POOLS` as authorization for API
2. Set the access token and id token expiry to 5 minutes
3. Signed in and made a call to api
4. Waited 3/4 min and made the call again 
5. Waited for 1 hr and made the call again

Not able to get the 401 error code.


1. Are you making a lot of api calls together?
2. Did you use hosted UI to sign in the user? `Amplify.Auth.signInWithWebUI` ?

Deleting the accessToken from keychain should be okay, the SDK will use the refresh token to fetch the token again if it cannot find one. But we cannot guarantee if this would break in the future implementation of the SDK.

**Comment by royjit** [comment]
I again gave a round of testing by signing in via `Amplify.Auth.signInWithWebUI`, but still could not reproduce the issue. Do you have any app logs when the issue happens?  Logs might give us more information regarding why the issue happens and helps us in debugging further. You can enable logs by:

```swift

import AWSCore

AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```
 
Redact sensitive information before posting the logs here.
