### ISSUE TITLE
could not initialize Amplify PluginError: Unable to decode configuration Recovery suggestion: Make sure the plugin configuration is JSONValue

### ISSUE THREAD

**Issue by dzeitman** [aws-amplify/amplify-ios#1227]
**Describe the bug**

could not initialize Amplify PluginError: Unable to decode configuration
**Recovery suggestion: Make sure the plugin configuration is JSONValue**
Amplify/AuthCategory.swift:18: Fatal error: **Authentication category is not configured.** Call Amplify.configure() before using any methods on the category.
2021-05-12 20:03:47.747589-0700 TheByList[2005:946853] Amplify/AuthCategory.swift:18: Fatal error: Authentication category is not configured. Call Amplify.configure() before using any methods on the category.

**To Reproduce**
Follow the official steps in the tutorial.
https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/module-two/?e=gs2020&p=build-a-react-app-one

** off-topic but important:  Tutorial is incomplete -- begins as a SwiftUI tutorial, mid-way provides cocopods instructions.  

 private func configureAmplify() {
        do {
         
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.configure()
            print("Amplify configured successfully")
            
        } catch {
            print("could not initialize Amplify", error)
        }
    }

This line fails:       try Amplify.add(plugin: AWSCognitoAuthPlugin())

Clearly unable to read the JSON.    

amplifyconfiguration.json : 

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0"
}

awsconfiguration.json
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    }
}

**Expected behavior**
It should have loaded the plugin and and proceeded with configuration.   This same bug was previously reported and erroneously closed.  

Completely blocked. 
 
SwiftUI using package Manager.
iOS 14.5 
iPhone 12 Pro

**Comment by dzeitman** [comment]
Same issue as mentioned here https://github.com/aws-amplify/amplify-ios/issues/586 (noted it was prematurely closed as it still persists.

**Comment by dzeitman** [comment]
Ok guys -- the error message is not developer friendly.    The issue was you need to configure at least one category before running.   So The error message should state that versus the obtuse error message.   Recovery suggestion: Make sure the plugin configuration is JSONValue isn't clear.  Fatal error: Authentication category is not configured. Means nothing if this concept isn't explained in the documentation tutorial.

**Comment by kervonryan** [comment]
For anyone who still may not get it, you probably forgot to call amplify push as I did.

**Comment by AliJ91** [comment]
> For anyone who still may not get it, you probably forgot to call amplify push as I did.

and how should this be called?

**Comment by afern247** [comment]
For me it was `amplify pull` since I have 2 env. Reading above + mine it all seems sync configuration issues

**Comment by ayemereodia2** [comment]
neither pull nor push worked for me.
