### ISSUE TITLE
Cannot use @versioned with iOS app

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1238]
I am trying to add versioning to an amplify project that does not use the local datastore.  I am adding the @versioned directive after @model as suggested in the documentation.
```graphql
type Message
  @model
  @versioned
  @auth(
    rules: [
      { allow: owner, operations: [create, delete, update] }
    ]
  )
  id: ID!
  owner: String
  text: String!
}
```
The problem is when I codegen the version field is not added to the local model.  And as such I have no way to access the version.

If I add `version: Int!` to the schema: 

```graphql
type Message
  @model
  @versioned
  @auth(
    rules: [
      { allow: owner, operations: [create, delete, update] }
    ]
  )
  id: ID!
  version: Int!
  owner: String
  text: String!
}
```
the codegen works fine and I can check the version locally.  But every time I create an object I have to add the version number myself.  Additionally, the provisioned backend does not add the version field to the input and I get an error message every time I try to create an object:

"The variables input contains a field name \'version\' that is not defined for input object type \'CreateMessageInput\' "

So I am not able to create objects.   And I imagine since the same issue exists with expectedVersion I will have no way to add the expectedVersion when updating.  

So how can I add versioning to my schema to use with an iOS project?

I am using the very latest cli.

**Comment by royjit** [comment]
Hi @alionthego ,

Are you using Datastore to update the data? `@versioned` directive is not compatible with datastore as mentioned here - https://docs.amplify.aws/cli/graphql-transformer/versioned.

**Comment by alionthego** [comment]
I am not using Datastore as mentioned in the question. Thx.

**Comment by diegocstn** [comment]
hi @alionthego,
it'd be helpful to know how you have generated your Swift models. Unfortunately `@versioned` isn't fully supported on models generated via `amplify codegen models`.

**Comment by alionthego** [comment]
I have used amplify codegen models to generate my swift models.

**Comment by diegocstn** [comment]
We can't take this as a feature request at the moment, but we'll monitor possible use-cases and re-evaluate it in the future if needed. I've also updated the documentation https://github.com/aws-amplify/docs/pull/3316
