### ISSUE TITLE
Generic parameter 'R' could not be inferred

### ISSUE THREAD

**Issue by tobitech** [aws-amplify/amplify-ios#1243]
I'm trying to use the AWSAPIPlugin with this function
`Amplify.API.mutate(request: .create(transaction)) { event in }`
But I keep getting these errors
`Generic parameter 'R' could not be inferred`
`Type 'GraphQLRequest<_>' has no member 'create'`
How do I resolve this?

**Comment by lawmicha** [comment]
Hi @tobitech, have you tried following the API docs and gotten a create mutation for the Todo model working? https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/ios#create-a-todo

What schema are you using? for example:
```
type Transaction @model {
  id: ID!
 // other fields?
}
```

Could you expand on the rest code snippet such as how are you instantiating the `transaction` object?  It should be an instance of the Transaction swift class generated from `amplify codegen models`

**Comment by tobitech** [comment]
Hello @lawmicha I couldn't get any create mutation to work. I tried to pass the `.create()` in the `mutate` method but Xcode not even showing any suggestion for that and I think that's where the problem is. Notice the second line of the Xcode error says `Type 'GraphQLRequest<_>' has no member 'create'`
The Transaction model is a generated one 
```
// swiftlint:disable all
import Amplify
import Foundation

public struct Transaction: Model {
  public let id: String
  public var amount: Double
  public var description: String
  
  public init(id: String = UUID().uuidString,
      amount: Double,
      description: String) {
      self.id = id
      self.amount = amount
      self.description = description
  }
}
```
This is how I'm instantiating the model `let transaction = Transaction(amount: 100, description: "Money for coffee")`

A similar thing was reported here - https://stackoverflow.com/a/67342606/6866285

**Comment by lawmicha** [comment]
Hi @tobitech, `.create()` comes from AWSPluginsCore: https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLRequest/GraphQLRequest%2BModel.swift#L131

so perhaps you need `import AWSPluginsCore` at the top of your file where you are trying to make the `Amplify.API` call. If you're having troubles with autocompletetion, you can try splitting it out:
```
let request = GraphQLRequest<Transaction>.create(transaction)
Amplify.API.mutation(request: request) { event in }
```

**Comment by tobitech** [comment]
@lawmicha I just imported `AWSPluginsCore` and the error is gone. I thought importing `Amplify` would be sufficient 🤦‍♂️ 
Thanks for the support.

**Comment by lawmicha** [comment]
sorry for the inconvenience caused! i'll run through the docs to see if using SPM requires an explicit mention of `AWSPluginsCore` but doesn't

**Comment by lawmicha** [comment]
related docs improvement PR: https://github.com/aws-amplify/docs/pull/3288

**Comment by lawmicha** [comment]
Let us know if you run into any other issues!
