### ISSUE TITLE
pause/resume/cancel upload

### ISSUE THREAD

**Issue by huluyige** [aws-amplify/amplify-ios#1249]
**Describe the bug**
I can't find docs about pause/resume/cancel uploads

Hello I'am studying the storage plugin to test if i can pause/resume uploads like the old sdk, unfortunately I didn't find it. I just find a simple method: 

```
        let dataString = "My Data"
        let fileNameKey = "myFile.txt"
        let filename = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent(fileNameKey)
        do {
            try dataString.write(to: filename, atomically: true, encoding: String.Encoding.utf8)
        } catch {
            print("Failed to write to file \(error)")
        }

        Amplify.Storage.uploadFile(
            key: fileNameKey,
            local: filename,
            progressListener: { progress in
                print("Progress: \(progress)")
            }, resultListener: { event in
                switch event {
                case let .success(data):
                    print("Completed: \(data)")
                case let .failure(storageError):
                    print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
                }
            }
        )
```

Could you please make it clear if the amplify sdk allows to do these? if yes, Could you provide some samples "? 
Thank you !

**Comment by lawmicha** [comment]
Hi @huluyige, thanks for bring this to our attention. Please take a look at https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Storage/AWSS3StoragePluginFunctionalTests/ResumabilityTests/AWSS3StoragePluginGetDataResumabilityTests.swift and let us know if this works for you. 

Hold onto the operation
```swift
let operation = Amplify.Storage.downloadData(
            key: key,
            options: nil,
            progressListener: { progress in
            // To simulate a normal scenario, fulfill the progressInvoked expectation after some progress (30%)
            if progress.fractionCompleted > 0.3 {
                progressInvoked.fulfill()
            }
        }, resultListener: { result in
            switch result {
            case .success:
                completeInvoked.fulfill()
            case .failure(let error):
                XCTFail("Failed with \(error)")
            }
        })
```

pause
```swift
```

**Comment by lawmicha** [comment]
related doc improvements https://github.com/aws-amplify/docs/pull/3290

**Comment by huluyige** [comment]
Hello @lawmicha  thank you for reply. Is there a doc talking about resuming after app restart ?  like something amplify.getTasks

**Comment by palpatim** [comment]
Hi @huluyige,

Amplify doesn't currently support resuming background tasks after app restart. You can see a [discussion here](https://github.com/aws-amplify/amplify-ios/issues/1096) and the associated [feature request](https://github.com/aws-amplify/amplify-ios/issues/1102).
