### ISSUE TITLE
Unable to fetch AuthCognitoTokensProvider after login 

### ISSUE THREAD

**Issue by harshchitrla** [aws-amplify/amplify-ios#1254]
I'm unable to fetch AuthCognitoTokensProvider right after login, it throws me an error "Obtaining an identity id in another thread failed or didn't complete within 5 seconds." 

I'm using Amplify version 1.9.0. 

Here is the method I'm using to fetch Cognito tokens 

```swift 
func getCognitoTokens() -> Future<AuthCognitoTokens, Error> {
        Future { promise in
            Amplify.Auth.fetchAuthSession { result in
                do {
                    let session = try result.get()
                    if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
                        promise(.success(try cognitoTokenProvider.getCognitoTokens().get()))
                    }
                } catch {
                    promise(.failure(error))
                }
            }
        }
    }
```

It goes to catch block all the time.

It only works if I add some delay of 2 seconds. Please find the code below after adding a delay. 

```swift
   func getCognitoTokens() -> Future<AuthCognitoTokens, Error> {
        Future { promise in
            DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
                Amplify.Auth.fetchAuthSession { result in
                    do {
                        let session = try result.get()
                        if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
                            promise(.success(try cognitoTokenProvider.getCognitoTokens().get()))
                        }
                    } catch {
                        promise(.failure(error))
                    }
                }
            }
        }
    }
```

I don't think adding delay is the correct option. Please help me with an alternative solution.

**Comment by lawmicha** [comment]
Hi @harshchitrla, could you provide us more details as to the steps you took to configure Auth and what your amplify configuration looks like (with values redacted). Also, if you don't use the Combine's Future and just do something like this: https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios does it work?
```
import AWSPluginsCore

Amplify.Auth.fetchAuthSession { result in
    do {
        let session = try result.get()
        // Get cognito user pool token
        if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
            let tokens = try cognitoTokenProvider.getCognitoTokens().get()
            print("Id token - \(tokens.idToken) ")
        }

    } catch {
        print("Fetch auth session failed with error - \(error)")
    }
}
```

**Comment by lawmicha** [comment]
Also if you had to add a delay, do you know what other calls you are making when you call `getCognitoTokens`? that may be the reason why another thread has obtained a lock

**Comment by edwinwong90** [comment]
> I'm unable to fetch AuthCognitoTokensProvider right after login, it throws me an error "Obtaining an identity id in another thread failed or didn't complete within 5 seconds."
> 
> I'm using Amplify version 1.9.0.
> 
> Here is the method I'm using to fetch Cognito tokens
> 
> ```swift
> func getCognitoTokens() -> Future<AuthCognitoTokens, Error> {
>         Future { promise in
>             Amplify.Auth.fetchAuthSession { result in
>                 do {
>                     let session = try result.get()
>                     if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
>                         promise(.success(try cognitoTokenProvider.getCognitoTokens().get()))
>                     }
>                 } catch {
>                     promise(.failure(error))
>                 }
>             }
>         }
>     }
> ```
> 
> It goes to catch block all the time.
> 
> It only works if I add some delay of 2 seconds. Please find the code below after adding a delay.
> 
> ```swift
>    func getCognitoTokens() -> Future<AuthCognitoTokens, Error> {
>         Future { promise in
>             DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
>                 Amplify.Auth.fetchAuthSession { result in
>                     do {
>                         let session = try result.get()
>                         if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
>                             promise(.success(try cognitoTokenProvider.getCognitoTokens().get()))
>                         }
>                     } catch {
>                         promise(.failure(error))
>                     }
>                 }
>             }
>         }
>     }
> ```
> 
> I don't think adding delay is the correct option. Please help me with an alternative solution.

@harshchitrla adding delay is correct way. even in Apple Doc also mention https://developer.apple.com/documentation/combine/using-combine-for-your-app-s-asynchronous-code
