### ISSUE TITLE
Receiving 403 error when downloading file 

### ISSUE THREAD

**Issue by testflyjets** [aws-amplify/amplify-ios#1264]
Using Amplify Storage in an iOS Swift app, we are able to upload files from the mobile app to S3 with the access level set to `private`. However, trying to download a file from the same bucket fails with a 403 error. Attempting to download the same file that was uploaded from the app also fails with a 403.

We have tried downloading to in-memory data and to a file with the same results.

Here's the relevant file download code, taken almost directly from the current Amplify iOS documentation:

```
        let options = StorageDownloadFileRequest.Options(accessLevel: .private)
        
        let downloadToFileName = FileManager.default.urls(
            for: .documentDirectory,
            in: .userDomainMask)[0]
            .appendingPathComponent(attachment.filename)
        
        let storageOperation = Amplify.Storage.downloadFile(
            key: attachment.key,
            local: downloadToFileName,
            options: options)
        
        progressSink = storageOperation.progressPublisher.sink { progress in print("download progress: \(progress)") }
        resultSink = storageOperation.resultPublisher.sink {
            if case let .failure(storageError) = $0 {
                print("Storage download failed: \(storageError.errorDescription)")
            }
        }
        receiveValue: { data in
            print("Storage Download Completed: \(data)")
        }
```

Debugging into the AWS code I can see that the current user's Cognito Identity ID, correct access level, and S3 file key are all being used.

Turning on verbose logging for Amplify didn't appear to provide any helpful information about the failure.

Any help from AWS would be appreciated.

**Comment by testflyjets** [comment]
Additional information:

I switched the app over to use the CocoaPods libraries instead of Swift Package Manager to see if that made a difference -- it did not, still getting the 403 error.

Also, I attempted to look at the IAM policies associated with Amplify Storage to see if something looked awry there. However, I cannot find the policy in IAM. Should I be able to find it? The policy name in the nested Amplify Storage CloudFormation stack does not seem to exist in IAM, or at least, I cannot find it.

Finally, I looked at the permissions and ACL on the Storage S3 bucket to see if something was off. Here's what I see -- is this correct for a bucket created by Amplify Storage? Should there be additional permissions listed here? This AWS account is owned by the client and I have occasionally found some permissions were not available in various AWS services, so please confirm if this ACL looks correct per what Amplify Storage expects?

![s3_bucket_ACL](https://user-images.githubusercontent.com/160552/121053796-93828080-c770-11eb-8378-bfff6a8c8c03.png)

**Comment by testflyjets** [comment]
Digging into this further I discovered the root issue. The inline IAM policy that should give read access (`s3:GetObject`) does not exist and is not associated with the `authRole` used by Cognito.

The readPolicy is listed as a parameter in the CloudFormation template but is not referenced anywhere else. Also, note that the first letter of the read policy is not capitalized like the others -- this hints at the fact it may not have been modified or updated when the other policies were. Just a guess on my part.

![storage_CF_params-2](https://user-images.githubusercontent.com/160552/121074587-ed8f4000-c788-11eb-99e7-2cb4f495d0a0.png)

The CloudFormation resources show the read policy was not created:

![storage_CF_resources](https://user-images.githubusercontent.com/160552/121074919-5d9dc600-c789-11eb-84dc-e0eacdf159b6.png)

Looking at the resulting policies attached to the IAM authRole show the read policy is in fact missing:

![iam_authRole](https://user-images.githubusercontent.com/160552/121074983-760de080-c789-11eb-9bdc-4a0dfcafd062.png)

I added the `s3:GetObject` permission to the private policy:

![iam_private_policy](https://user-images.githubusercontent.com/160552/121075056-90e05500-c789-11eb-9a1e-d0cc7c49e68b.png)

With this addition, Amplify Storage now successfully downloads the files from the storage bucket. Prior to making this change I added the AWS S3FullAccess policy to this role to test it out, and when that was successful I looked for a more granular fix.

It seems that the read policy is not being generated or attached to the authRole as would be expected. Please investigate why this is as the expectation is that all of the permissions required to perform reads and writes should be setup properly by the Amplify framework. 

While making this change has fixed the immediate issue, any updates we make to Amplify Storage or Auth are likely to overwrite this, so we need this fixed in the tool.

**Comment by lawmicha** [comment]
hi @testflyjets, could you let us know which answers did you provide to the questions related to the kind of access for the users when you provisioned S3 through `amplify add storage`?

```
What kind of access do you want for Authenticated users? `create/update, read, delete`
```

I suspect if you only allowed "create/update" for Authenciated users then they won't be able to read the data.

**Comment by testflyjets** [comment]
@lawmicha  Great question, and I wondered that myself, but I didn't see any way to go back and check that since I did it weeks ago. I vaguely recall thinking to myself, "Shouldn't `create/update` include `read`?" but that may just be hindsight.

Is there a way to update this now without trashing the existing auth + storage configuration if that was the case?

**Comment by lawmicha** [comment]
Hi @testflyjets, could you try `amplify update storage` to update the options and then `amplify push` to apply the changes. Let us know if this works!

**Comment by testflyjets** [comment]
Thanks @lawmicha that's exactly what I did. I turned on `read` as well as `delete` since we'll need both of those. All is well now, so thanks for pointing the issue out to me. I appreciate you speedy response.

**Comment by lawmicha** [comment]
glad it is working for you! Closing this for now, with doc update issue over here https://github.com/aws-amplify/docs/issues/3317
