### ISSUE TITLE
Unexpected Error shouldNotHappenReportBugToAWS() for Cognito/Amplify using Azure OIDC Auth on iOS

### ISSUE THREAD

**Issue by gabimo** [aws-amplify/amplify-ios#1266]
**Describe the bug**
Trying to set up OIDC Auth with Azure/Cognito/Amplify for iOS and the sign in returns me an error: 

```
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't.
```

**To Reproduce**
1. Setup OIDC Cognito/Azure Auth for amplify and consume via iOS
2. Perform Login `Amplify.Auth.signInWithWebUI(for: .oidc, presentationAnchor: self.view.window!)` 
3. Log in with valid credentials
4. receive error message

**Expected behavior**
I expect it to tell me I'm logged when I try again or check auth status, OR tell me something is wrong besides "unexpected error", OR fail because of not returning token but still succeed and not return an error.

**Screenshots**
Please let me know what would help, I am getting the correct hosted UI for login and am able to log in correctly
<img width="885" alt="Screen Shot 2021-06-08 at 12 31 06 PM" src="https://user-images.githubusercontent.com/9092155/121223467-8f7c5e80-c855-11eb-8b48-4c62f6685578.png">
<img width="1125" alt="Screen Shot 2021-06-08 at 12 30 25 PM" src="https://user-images.githubusercontent.com/9092155/121223688-c94d6500-c855-11eb-80f2-90d0bebc78d7.png">
<img width="1383" alt="Screen Shot 2021-06-08 at 12 27 37 PM" src="https://user-images.githubusercontent.com/9092155/121223476-90ad8b80-c855-11eb-8ac2-484858564a1d.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.9.3
 - Amplify Categories:
   - [X] Auth only
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0
 - CLI Version: Manual
 - Xcode Version: [12.4 (12D4e)
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log` **** Cant find

**Is this a regression (i.e. was this working before a version upgrade?)
*If applicable provide the versions used before and after the upgrade.*
Never worked yet, new app

**Device Information (please complete the following information):**
 - Device: iPad Mini Simulator
 - iOS Version: 14.4
 - Specific to simulators: Yes maybe

**Additional context**
New to Amplify/AWSCognito/OIDC. We want to set up Auth and have had challenges with the AmplifyConfiguration.json for iOS not being documented thoroughly and lack of tutorials or sample apps for OIDC with Cognito/Amplify for iOS

```
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": { "WebDomain": "https://APPNAME.auth.us-east-1.amazoncognito.com/" }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_xxxxxxx",
                        "AppClientId": "xxxxxxx",
                        "AppClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "PoolId": "us-east-1_xxxxxxx",
                            "WebDomain": "APPNAME.auth.us-east-1.amazoncognito.com",
                            "AppClientId": "xxxxxxxxxxxx",
                            "SignInRedirectURI": "domain.APP-NAME://auth/",
                            "SignOutRedirectURI": "domain.APP-NAME://auth/",,
                            "Region": "us-east-1",
                            "Scopes": [ "aws.cognito.signin.user.admin", "email", "openid", "profile", "phone" ],
                            "ResponseType": "code",
                        }
                    }
                }
            }
        }
    }
}
```

Thanks

**Comment by royjit** [comment]
Hi,

Can you check whether the associated type in the unknown error field has any value in it? It might have more details regarding the error.

```
if case AuthError.unknown(let description, let underlyingError) = error {
                        print (underlyingError)
 }
```

**Comment by gabimo** [comment]
Update: Removed Client Secret by making a new instance or environment or whatever and the problem is gone
