### ISSUE TITLE
Remove unknown and notInProcess async event cases

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#127]
Talk to android team, agree if removing unknown and notInProces AsyncEvent cases--these aren't useful, and add to clutter at call sites

**Comment by palpatim** [comment]
I'm calling this a bug--if Android currently isn't doing it then we're breaking platform parity.

**Comment by jamesonwilliams** [comment]
Very little of our category/plugin logic is currently integrated with the `AsyncEvent` stuff.

https://github.com/aws-amplify/amplify-android/tree/master/core/src/main/java/com/amplifyframework/core/async

I believe the original intention was to have a centralized mechanism to do async work, with standard lifecycle events being communicated via Hub -- but this is, for the most part, not implemented, in practice.

**Comment by drochetti** [comment]
@palpatim did the `AsyncEvent` refactor fix this?

**Comment by palpatim** [comment]
Sure did. Closing.
