### ISSUE TITLE
iOS signInWithWebUI Hosted UI crashing 

### ISSUE THREAD

**Issue by meavydev** [aws-amplify/amplify-ios#1276]
**Describe the bug**
Amplify.Auth.signInWithWebUI is crashing with the same EXC_BAD_INSTRUCTION first reported in https://github.com/aws-amplify/amplify-ios/issues/550 
I am opening this issue, as 550 has been closed.

This is on the iPhone 14.4 simulator, but Amplify.Auth.signIn with a username and password works.
This suggests that it's not a problem with the amplifyconfiguration.json, but possibly something to do with the presentationAnchor parameter to signInWithWebUI.
I haven't tried on a real iPhone yet, just the sim.

**To Reproduce**
Just call signInWithWebUI with a presentationAnchor parameter.

**Expected behavior**
Hosted UI login should work

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.10.0
 - Amplify Categories:
   - [ ] Analytics
   - [ ] API
   - [x] Auth
   - [ ] DataStore
   - [ ] Predictions
   - [ ] Storage
 - Dependency Manager: [e.g. SwiftPM, Cocoapods]
 - Swift Version: 5
 - Xcode Version: 12.4

**Is this a regression (i.e. was this working before a version upgrade?)
*If applicable provide the versions used before and after the upgrade.*

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 14,4
 - Specific to simulators:

**Comment by meavydev** [comment]
Just to confirm signInWithWebUI is also crashing on an iPhone 7 running iOS 14.5.
![Screenshot 2021-06-15 at 14 27 07](https://user-images.githubusercontent.com/9558404/122060915-ecdc5680-cde5-11eb-8b11-dff42723d4ef.png)

**Comment by radianttap** [comment]
I am seeing the same crash on iOS 14.5 Simulator, using latest Amplify 1.10

I attempted to use social sign-in with `AuthProvider.google`, passing correct `UIWindow` instance. It crashes with `EXC_BAD_INSTRUCTION`, here's the call stack:

```
#0	0x0000000110b5afae in ___lldb_unnamed_symbol299$$AWSMobileClientXCF ()

#1	0x0000000110b598e1 in AWSMobileClient.showSignIn(presentationAnchor:hostedUIOptions:_:) ()

#2	0x000000010fde5dcf in AWSMobileClientAdapter.showSignIn(uiwindow:hostedUIOptions:_:) at /Users/aleck/Library/Developer/Xcode/DerivedData/RogerCoach-ecrpzsblbyduvnempckxipwuhdji/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Service/AWSMobileClient/AWSMobileClientAdapter.swift:111

#3	0x000000010fde702b in protocol witness for AWSMobileClientBehavior.showSignIn(uiwindow:hostedUIOptions:_:) in conformance AWSMobileClientAdapter ()

#4	0x000000010fda3a5d in AuthenticationProviderAdapter.launchASWebAuthenticationSession(presentationAnchor:hostedUIOptions:preferPrivateSession:completionHandler:) at /Users/aleck/Library/Developer/Xcode/DerivedData/RogerCoach-ecrpzsblbyduvnempckxipwuhdji/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift:186

#5	0x000000010fda1ccb in AuthenticationProviderAdapter.showSignInWebView(presentationAnchor:request:completionHandler:) at /Users/aleck/Library/Developer/Xcode/DerivedData/RogerCoach-ecrpzsblbyduvnempckxipwuhdji/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift:140

#6	0x000000010fda11d8 in closure #1 in AuthenticationProviderAdapter.signInWithWebUI(request:completionHandler:) at /Users/aleck/Library/Developer/Xcode/DerivedData/RogerCoach-ecrpzsblbyduvnempckxipwuhdji/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthenticationProviderAdapter+SignIn.swift:70

```

<img width="1897" alt="Screenshot 2021-06-15 at 21 37 12" src="https://user-images.githubusercontent.com/80697/122113025-da800e00-ce21-11eb-8fe0-a5b1d4e5114d.png">

**Comment by radianttap** [comment]
Further note - user/pass login on same AWS environment works. FetchAuthSession, signup, login etc - all work.

**Comment by palpatim** [comment]
> passing correct `UIWindow` instance

Where are you retrieving the `UIWindow` that you pass as the presentation anchor? What does your call site look like? The nature of the crash seems like you might be force-unwrapping an optional.

**Comment by radianttap** [comment]
I take `self.view.window` from the currently shown view controller. You can see in my screenshot that it's valid UIWindow instance and I made sure to check that, placing a breakpoint in your code at `awsMobileClient.showSignIn` line and checking the instance.

**Comment by radianttap** [comment]
Call site:

```
guard let window = controller?.view.window else {
	return
}

accountManager.socialSignIn(using: socialIdentity, onQueue: .main, inside: window) {
	result in

}
```

**Comment by meavydev** [comment]
I'm an Android dev, not iOS, but the code I am using was from a sample that must have worked at some point, as it showed a video of it logging in.
`    private var window: UIWindow {
        guard
            let scene = UIApplication.shared.connectedScenes.first,
            let windowSceneDelegate = scene.delegate as? UIWindowSceneDelegate,
            let window = windowSceneDelegate.window as? UIWindow
        else { return UIWindow() }
        
        return window
    }

    func webSignIn() {
            _ = Amplify.Auth.signInWithWebUI(presentationAnchor: window) { result in
                switch result {
                case .success:
                    print("Signed in")

                case .failure(let error):
                    print(error)
                }
            }
    }`

**Comment by palpatim** [comment]
> I take `self.view.window` from the currently shown view controller. You can see in my screenshot that it's valid UIWindow instance and I made sure to check that, placing a breakpoint in your code at `awsMobileClient.showSignIn` line and checking the instance.

Thanks for clarifying. I do see the UIWindow in the debug inspector--I missed that before!

We'll dig into this again to see if we're able to repro the issue.

**Comment by radianttap** [comment]
Any news on this..? We are nearing end of project and this is only remaining blocker.

**Comment by radianttap** [comment]
@palpatim I tried using local CocoaPods integration, hoping to ping point the issue.
When I tried Google login, it crashed attempting to force-unwrap webDomain here:

<img width="872" alt="Screenshot 2021-06-29 at 17 22 16" src="https://user-images.githubusercontent.com/80697/123824789-a1a26780-d8fe-11eb-8bf5-fcf116c0ddf1.png">

Stack trace:

<img width="913" alt="Screenshot 2021-06-29 at 17 21 34" src="https://user-images.githubusercontent.com/80697/123824801-a36c2b00-d8fe-11eb-92c2-a8861b749bbf.png">

**Comment by radianttap** [comment]
Huh, [found it](https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios), it apparently needs a whole `OAuth` block, inside `Auth.Default`.

With this, `AWSMobileClient` used through CocoaPods does not crash.

But this same configuration, when using `Amplify` integrated through SwiftPM, crashes at the same spot. Thus I guess you still have some force-unwrapping or something happening inside `AWSMobileClientXCF`.

**Comment by radianttap** [comment]
Whatever is crashing Amplify seems to be fixed, but release with the fix is not yet tagged, thus SPM does not get it.

1. Keep Amplify added as SPM package in your project.
2. Clone this entire repo somewhere locally
3. Drag & drop the `amplify-ios` folder into Xcode project, as [explained here](https://developer.apple.com/documentation/swift_packages/editing_a_package_dependency_as_a_local_package)
4. Clean and re-build

It will work just fine. Of course, you need to have the configuration JSON updated with proper OAuth setup, as I already previously linked.

**Comment by lawmicha** [comment]
hey @radianttap glad you were able to get pass the crash. Which commit are you pulling in there that is fixing things and which is the previous version? (Still 1.10.0?). trying to narrow down which commit fixed things

**Comment by radianttap** [comment]
Honestly, I can't tell. I pulled SPM package from master branch instead of per version. So it's certainly something after 1.10.0.

Do note that `AWSMobileClient` code I highlighted will still crash if you try to use social sign and WebDomain is not present in awsconfiguration.json

**Comment by palpatim** [comment]
Thanks for the update. We're closing this for now, but please feel free to open a new issue with relevant details if you hit another error.
