### ISSUE TITLE
How can I delete a specific S3 folder and all of its contents with Amplify/iOS/Swift5? 

### ISSUE THREAD

**Issue by TerremceK** [aws-amplify/amplify-ios#1278]
This example function in the documentation 

```
Amplify.Storage.list { event in
    switch event {
    case let .success(listResult):
        print("Completed")
        listResult.items.forEach { item in
            print("Key: \(item.key)")
        }
    case let .failure(storageError):
        print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
    }
}
```

Shows me everything like below....

s3://mybucket/public/folder1/
s3://mybucket/public/folder2/
s3://mybucket/public/folder3/
s3://mybucket/public/**folderIwantToDelete**/
s3://mybucket/public/folderIwantToDelete/pic1@3x.png
s3://mybucket/public/folderIwantToDelete/pic2@3x.png
s3://mybucket/public/folderIwantToDelete/pic3@3x.png

How can I list **only the folder contents of a specific directory** in Swift5? I haven't found one working example or any documentation on how to do this.  

I'd like to be able to only list 
s3://mybucket/public/**folderIwantToDelete**/
s3://mybucket/public/folderIwantToDelete/pic1@3x.png
s3://mybucket/public/folderIwantToDelete/pic2@3x.png
s3://mybucket/public/folderIwantToDelete/pic3@3x.png

Then remove all 3 of those picture files so the folder deletes.

I'm looking for something like this, but this does not work.
```
        Amplify.Storage.list("folder/", result1 -> {
            for (StorageItem item : result1.getItems()) {
                Amplify.Storage.remove(item.getKey(),
                    result -> Log.i("MyAmplifyApp", "Successfully removed: " + result.getKey()),
                    error -> Log.e("MyAmplifyApp", "Remove failure", error)
                );
            }
        }, error -> Log.e("MyAmplifyApp", "List failure", error));
```

**Comment by palpatim** [comment]
Currently, the Amplify interface doesn't support "bulk" deletes, so the pattern you listed would be the right way to do this. The example you listed looks like Kotlin, which of course doesn't work for iOS

In Swift (using callbacks), it'd look something like:

```swift
func deleteObjects(from prefix: String) {
    let options = StorageListRequest.Options(path: prefix.isEmpty ? nil : prefix)
    Amplify.Storage.list(options: options) { result in
        guard case .success(let storageResults) = result else {
            print("Failed to list: \(result)")
            return
        }

        let allObjects = storageResults.items.map { $0.key }
        let prefixObjects = allObjects.filter { $0.starts(with: prefix) }

        guard !prefixObjects.isEmpty else {
            print("Nothing to delete")
            return
        }

        DispatchQueue.concurrentPerform(iterations: prefixObjects.count) { iter in
            let key = prefixObjects[iter]
            Amplify.Storage.remove(key: key) { result in
                switch result {
                case .failure(let error):
                    print("Error deleting \(key): \(error.localizedDescription)")
                case .success(let successValue):
                    print("Deleted \(key): \(successValue)")
                }
            }
        }
    }
}
```

**Comment by TerremceK** [comment]
Hey Tim thanks for your response! You rock, this works perfect.  It looks like you filtered the results of the list to get the name of the folder desired and then took action from there.  Nice! 👍🏻 I would have been stuck trying to figure that one out for a wile. 😅 many thanks!

**Comment by palpatim** [comment]
Glad it helped!
