### ISSUE TITLE
Storage: Add missing doc comments

### ISSUE THREAD

**Issue by brennanMKE** [aws-amplify/amplify-ios#1280]
**Describe the bug**

Doc comments are missing.

**To Reproduce**
1. View docs website for API reference.

**Expected behavior**

All public interfaces should be documented.

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 1.5.3]
 - Amplify Categories:
   - [ ] Analytics
   - [ ] API
   - [ ] Auth
   - [ ] DataStore
   - [ ] Predictions
   - [x] Storage
 - Dependency Manager: [e.g. SwiftPM, Cocoapods]
 - Swift Version: [e.g. 5.0]
 - CLI Version: [e.g. 4.41.2, Run `amplify version`]
 - Xcode Version: [e.g. 12.4 (12D4e), Run `xcodebuild -version`]
 - Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Comment by lawmicha** [comment]
I believe this is completed as per #1280
