### ISSUE TITLE
AWS-Amplify deprecations warning 

### ISSUE THREAD

**Issue by MaxGiesbers** [aws-amplify/amplify-ios#1289]
Hi everyone, 
I’ve installed the following packages from aws-amplify with CocoaPods: 
•	Pod ‘Amplify’
•	Pod ‘AmplifyPlugins/AWSCognitoAuthPlugin’
•	Pod ‘AmplifyPlugins/AWSS3StoragePlugin’
But for some reason I have a lot of deprecated functions when I build the code. See screenshot below: 

![image](https://user-images.githubusercontent.com/26543706/122921551-e9574b00-d362-11eb-860d-e214eff721e8.png)
![image](https://user-images.githubusercontent.com/26543706/122921579-eeb49580-d362-11eb-9650-0a98e51acd38.png)

I already updated my CocoaPods but this didn’t fix my issue.  Is this a known issue or did I forget something in my pod file?

**Comment by diegocstn** [comment]
hey @MaxGiesbers, 
most of these warnings are coming from 3rd party dependencies that we imported long ago. 
We are currently evaluating what's the best way to handle this.
I'm gonna close this issue in favour of https://github.com/aws-amplify/aws-sdk-ios/issues/3025 but feel free to reopen if you have any other questions.
