### ISSUE TITLE
Unexpected error: could not get valid token from the user

### ISSUE THREAD

**Issue by jackstenglein** [aws-amplify/amplify-ios#1315]
### Describe the bug

I use `Amplify.Auth.signInWithWebUI(for: provider, presentationAnchor: window, options: .preferPrivateSession())` to sign in users. I am using Google as the provider. After the user is signed in, I use `Amplify.Auth.fetchUserAttributes()` to fetch the user's attributes. At this point, I receive the following error:

```
AuthError: Unexpected error occurred with message: Could not get valid token from the user. Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists.
```

### Steps To Reproduce

```swift
I have actually not been able to reproduce this error myself. I have received numerous reports of it from actual users though. The only steps I can give are to use the two functions listed above (`Amplify.Auth.signInWithWebUI` and `Amplify.Auth.fetchUserAttributes`).
```

### Expected behavior

When I test on my own device, the account name and email address are fetched. No error is generated.

### Amplify Framework Version

1.12.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

5.1.0

### Xcode version

12.5.1

### Is this a regression? (i.e. was this working before a version upgrade)

No, I also saw this bug with earlier versions.

### Device

iPhone 12 Pro

### iOS Version

iOS 14.6

### Specific to simulators

No

**Comment by royjit** [comment]
The user session might be expired, you can listen to auth event and let the user re-authenticate if session expired. https://docs.amplify.aws/lib/auth/auth-events/q/platform/ios

**Comment by jackstenglein** [comment]
@royjit Thanks for the quick response. This issue is occurring right after the user has logged in, so the session shouldn't be expired. The app returns the user to the log in screen on encountering an AuthError, so the users see a continuous cycle of logging in and then being immediately returned to the log in screen.

**Comment by jackstenglein** [comment]
@royjit Turns out you were right, and the problem was caused by an expired refresh token. It seems that if the refresh token is expired, then the call `Amplify.Auth.signInWithWebUI(for: provider, presentationAnchor: window, options: .preferPrivateSession())` was failing with the error message `An unknown error occurred`. I solved the issue by calling the sign out function if the sign in function failed with that error. The user is then able to sign in. This seems like a bug to me, but maybe I am misunderstanding how to handle the refresh token expiration?

**Comment by royjit** [comment]
Can you please verify that you are using the latest version of the SDK. We had made some fix related to this in the underlying auth SDKs https://github.com/aws-amplify/aws-sdk-ios/pull/3565

**Comment by tuancuong009** [comment]
Hi @royjit @jackstenglein I have some issues with the token if I logged in with Google, after logged in with Google, I put the app for more than 1 day, when I open it again the token is expired and how can I Re-authenticate the user without showing the login popup?

**Comment by jackstenglein** [comment]
Hi @royjit, I was using version 1.12.0. I've just updated to version 1.13.0 and confirmed that the bug no longer occurs.

**Comment by jackstenglein** [comment]
@tuancuong009 In Cognito, you can change the expiration of the refresh token. That will allow you to stay logged in for longer.

**Comment by tuancuong009** [comment]
@jackstenglein Thanks I already set the refresh token to 30 days, you can see the attached image. 
If I logged in with email/password I can refresh the token without issues, but if I logged in with Google, after 1 day it ask me to login again, can you share the code that you use to login and refresh token? I'm struggling with this :( 

![image](https://user-images.githubusercontent.com/21256858/127795810-f0c14504-5218-4c20-8e0f-e9675d309524.png)

**Comment by lawmicha** [comment]
similar issue related to sign in with google https://github.com/aws-amplify/amplify-ios/issues/1344

**Comment by royjit** [comment]
Since the original issue in this thread is resolved, I am closing this. We can followup the other issue in #1344
