### ISSUE TITLE
Does the Amplify Datastore sync the entire server Model to each client device?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1316]
I am using AWS Amplify for an iOS project.

I would like to use DataStore to manage front end persistence on my client's device.  However I don't really understand the syncing of Datastore.  

Does DataStore sync the entire Model from the server to each and every client device?

For example if there are 10,000 users in a chat app, will each user's device contain all 10,000 users chat messages even though they are not in those chat rooms?

I really love the idea of DataStore to manage offline uses and conflict resolution but not sure how the syncing works for the client.

**Comment by ashiemke** [comment]
Yep, that's the default, and there's also a default sync limit (I think it's 10k), so amplify won't store more than 10k models in your local storage.

You can limit was is synched with the remote db through the use of sync expressions - https://docs.amplify.aws/lib/datastore/sync/q/platform/ios#selectively-syncing-a-subset-of-your-data

**Comment by diegocstn** [comment]
@alionthego you can adjust the sync limit using DataStore configuration as illustrated [here](https://docs.amplify.aws/lib/datastore/conflict/q/platform/ios#custom-configuration).

DataStore downloads from the cloud all the available data but you can use [sync expressions](https://docs.amplify.aws/lib/datastore/sync/q/platform/ios#selectively-syncing-a-subset-of-your-data) to selectively persist only a subset.
The closure passed as parameter of a sync expression gets re-evaluated each time DataStore starts.

**Comment by alionthego** [comment]
Thanks very much.  I didn't know about sync expressions which is exactly what I need.
