### ISSUE TITLE
Getting error when performing codegen models

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1318]
Recently when performing codegen models I am getting the following generated file:

```
public struct Conversation: Model {
  public let id: String
  public var version: Int
  public var owner: String?
  public var createdAt: String?
  public var updatedAt: String?
  public var text: String?
  
  public init(id: String = UUID().uuidString,
      version: Int,
      owner: String? = nil,
      createdAt: String? = nil,
      updatedAt: String? = nil,
      text: String? = nil) {
    self.init(id: id,
      version: version,
      owner: owner,
      createdAt: createdAt,
      updatedAt: updatedAt,
      text: text)
  }
  internal init(id: String = UUID().uuidString,
      version: Int,
      owner: String? = nil,
      createdAt: String? = nil,
      updatedAt: String? = nil,
      text: String? = nil) {
      self.id = id
      self.version = version
      self.owner = owner
      self.createdAt = createdAt
      self.updatedAt = updatedAt
      self.text = text
  }
}

```
Previously I never had this internal init and it is throwing an error: "Invalid redeclaration of 'init(id:version: ..."

My previous projects with exact same schema were only generating one init so I'm just wondering if I am doing something wrong.  I am using the following schema and importing Auth user pools and identity pool:

```
type Conversation
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, update] }
    ]
  ) {
  id: ID!
  version: Int!
  owner: String
  userId: ID!
  conversationId: ID!
  createdAt: String
  updatedAt: String
  text: String
}
```

**Comment by diegocstn** [comment]
hi @alionthego,
which version of the amplify CLI are you on? 

I believe the error you're experiencing has been already addressed and the fix should be available in a more recent version of the CLI https://github.com/aws-amplify/amplify-codegen/pull/177.

**Comment by alionthego** [comment]
I am using version 5.1.1 of cli.  When I try to upgrade I get following errors which I'm not sure if it's leading to problem:  

```
npm WARN deprecated event-to-promise@0.8.0: Use promise-toolbox/fromEvent instead
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @graphql-toolkit/common@0.9.7: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated @graphql-toolkit/common@0.9.7: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated @graphql-toolkit/common@0.6.6: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

**Comment by diegocstn** [comment]
Looks like you're already using the latest version of the CLI but I just noticed that you have a `createdAt` and `updatedAt` fields in your schema, so it seems like a codegen issue. 
We've recently added support to auto-generate those two fields as "read-only fields", so generated and updated by the cli/backend.
What's the content of `amplify/cli.json` in your project directory? The CLI uses that file to store values of [feature flags ](https://martinfowler.com/articles/feature-toggles.html) to enable/disable new or experimental features.
As a workaround you should be able to set the value of the `addtimestampfields` feature flag under the `codegen` key to `true` and remove the two extra field from your schema as follow:

```
type Conversation
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, update] }
    ]
  ) {
  id: ID!
  version: Int!
  owner: String
  userId: ID!
  conversationId: ID!
  text: String
}
```

```json
{
  "features": {
    ...
    "codegen": {
      ...
      "addtimestampfields": true,
    }
    ...
  }
}
```

**Comment by diegocstn** [comment]
I've opened a codegen issue: https://github.com/aws-amplify/amplify-codegen/issues/201, in the meanwhile let us know if the provided workaround works.

**Comment by alionthego** [comment]
I've done what you suggested and removed the createdAt and updatedAt fields in the schema for all types and updated the cli.json to include the "addtimestampfields": true.  At the moment it compiles without error but the init method doesn't look any different to me.  Still has the public init and internal init so not sure this will be a recurring issue.  It is a strange error and in the past the project has compiled with the error present in red and the error seems to come and go.  In a previous project with the exact same schema my init method did not have the internal init.  So just confused what exactly is going on there.  But seems to compile for now.

**Comment by diegocstn** [comment]
@alionthego the internal init is being used by Amplify to decode/encode from/to JSON, and should accept the two additional `createdAt` and `updatedAt` parameters. The reason why is being marked as `internal` is to give the framework a way to set the two "read-only" fields without publicly exposing any setter.
The public initializer should instead only accept values for the properties you've declared in your schema.

**Comment by diegocstn** [comment]
@alionthego as the workaround seems to be working for you, I'm gonna close this issue in favour of https://github.com/aws-amplify/amplify-codegen/issues/201 but feel free to re-open and/or comment.
