### ISSUE TITLE
Why is codegen models creating files with target membership in tests?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1319]
I have an iOS amplify project and added a graphql api using amplify add api.  I updated schema file and pushed.  When I run amplify codegen models, the files are created and added to my project but their target membership is AppNameTests rather than AppName.  Why is this happening and how can I fix that?

**Comment by diegocstn** [comment]
@alionthego we've identified the issue and we're actively working on it https://github.com/aws-amplify/amplify-ios/pull/1313
