### ISSUE TITLE
Swift syntax error in generated model files

### ISSUE THREAD

**Issue by nielsautrata** [aws-amplify/amplify-ios#1327]
### Describe the bug

The generated models are having partly some syntax error: 

> 'Invalid redeclaration of 'init(XXX'. 

I cleaned the workspace, re(installed) pods for this project, deleted the generated models and run again '**amplify codegen models'**
In the case, you want to download my graph.ql this my app id dl91s1m9oit3p and the region is us-east-1.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:

Project Dependencies: 
AWSAuthCore (2.24.3)
AWSCognitoIdentityProvider (2.24.3)
AWSCognitoIdentityProviderASF (2.24.3)
AWSCore (2.24.3)
AWSMobileClient (2.24.3)
AWSPluginsCore (1.12.0)
AWSS3 (2.24.3)
Amplify (1.12.0)
AmplifyPlugins (1.12.0)
AppSyncRealTimeClient (1.5.0)
SQLite.swift (0.12.2)
Starscream (3.1.1)

Pulling from backend and generating model files:
1. $ amplify pull --appId dl91s1m9oit3p --envName staging
✔ Successfully received Amplify Admin tokens.
2.Choose your default editor: Xcode (Mac OS only)
3.Choose the type of app that you're building iOS
4.Do you plan on modifying this backend? Yes
✔ Successfully pulled backend environment staging from the cloud.
-- ✅ Amplify project found.
-- ✅ Amplify config files found.
-- ✅ Successfully updated project
🚫 folderNotFound: Amplify generated models not found 
$ amplify codegen models

GraphQL schema compiled successfully.
Successfully generated models.

Open Xcode, build and run: Syntax error..
```

### Expected behavior

Compiling the Xcode project successful.

### Amplify Framework Version

1.12.0

### Amplify Categories

API

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

5.1.2

### Xcode version

12.5.1 

### Device

iPhone 12 - simulator

### iOS Version

14.5

**Comment by nielsautrata** [comment]
We have to keep our fields 'updatedAt', 'createdAt' as we use them as key in the indices. The flag `addtimestampfields` is already set to true.


> ✖ An error occurred when pushing the resources to the cloud
> You cannot specify a nonexistent field 'updatedAt' in @key 'sortByUpdatedAt' on type 'Report'.

**Comment by diegocstn** [comment]
@nielsautrata even though manually editing generated models is something we usually discourage, as a temp workaround you can manually remove the internal initializer while the fix in this PR gets released https://github.com/aws-amplify/amplify-codegen/pull/205#pullrequestreview-714074600

**Comment by diegocstn** [comment]
I'll optimistically close this issue as a [PR](https://github.com/aws-amplify/amplify-codegen/pull/205) has been published, but feel free to re-open it if you have further questions
