### ISSUE TITLE
Cannot save many to many in datastore

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1337]
I have the following many to many structure:

```
type User
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, delete, update] }
    ]
  ) {
  id: ID!
  owner: String
  username: String!
  comments: [UserComment] @connection(keyName: "byUser", fields: ["id"])
}

type UserComment
  @model
  @auth(
  rules: [
      { allow: owner, operations: [create, delete, update] }
    ]
  )
  @key(name: "byUser", fields: ["userId", "commentId"])
  @key(name: "byComment", fields: ["commentId", "userId"]) {
  id: ID!
  liked: Boolean!
  userId: ID!
  commentId: ID!
  user: User! @connection(fields: ["userId"])
  comment: Comment! @connection(fields: ["commentId"])
}

type Comment
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, delete, update] }
    ]
  ) {
  id: ID!
  title: String!
  content: String!
  users: [UserComment] @connection(keyName: "byComment", fields: ["id"])
} 

```
The problem is when I save the 'join' table UserComment using the following:

```
// user and comment are extracted elsewhere in code

let userComment = UserComment(id: UUID().uuidString, liked: false, user: user, comment: comment)

Amplify.DataStore.save(userComment!) { event in
    DispatchQueue.main.async {
        switch event {
        case .success(let result):
            print("Successfully saved or updated userComment: \(result)")
        case .failure(let error):
            print("Got failed event with error \(error)")
        }
    }
}
```

this creates the UserComment fine in the database however the comment is not added to the users comments array and the user is not added to the comments users array.  

also I have no way to query this UserComment directly from the datastore as I cannot do the following:

```
let keys = UserComment.keys
let predicate = keys.user.id == user.id && keys.comment.id == comment.id  // doesn't work
let predicate = keys.user == user && keys.comment == comment // doesn't work
Amplify.DataStore.query(UserPort, where: predicate) { event in
    ...
}
```

Neither one of those predicates are allowed and I am not able to query the userId or commentId of the UserComment directly.  

Where am I going wrong here??

**Comment by anatomybook** [comment]
I've a similar situation. The first issue I address by just manually inserting the user object, the comment object and finally the link (UserComment) between them.
The second issue I address by fetching, depending on where I come from, either the user or the comment. From there I use the accessors to obtain the linked users / comments.
Suppose you retrieved a user. From there I'd go:
```
if let links = user.comments
{
    for comment in links.map({$0.comment})
    {
         // do something with comment
    }
}
```
As far as I understand / read, the comments will loaded upon access. And no, I haven't tested the code above :)

**Comment by lawmicha** [comment]
Hi @alionthego, thanks for opening this issue. Can you verify that you have first saved the dependent models (User and Comment, separately) before saving the joining model (UserComment)? As @anatomybook  mentioned, inserting the objects beforehand is the expected procedure

1. [save the comment](https://github.com/lawmicha/amplify1337/blob/main/amplify1337/ContentView.swift#L24)
2. [save the user](https://github.com/lawmicha/amplify1337/blob/main/amplify1337/ContentView.swift#L40)
3. [save the user comment](https://github.com/lawmicha/amplify1337/blob/main/amplify1337/ContentView.swift#L56)
4. [query for user and lazy load the comments](https://github.com/lawmicha/amplify1337/blob/main/amplify1337/ContentView.swift#L76)
5. [or query for comment and lazy load the users](https://github.com/lawmicha/amplify1337/blob/main/amplify1337/ContentView.swift#L99)

Let us know if you are still having troubles with accessing the models
