### ISSUE TITLE
How can I query datastore. passing array of ID's

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1338]
I have an array of userId's and I want to query the DataStore. to retrieve all User's with id's in the array.

Is there any way to do that with a. predicate?

let arrayOfUserId's = ["UserId1",  "UserId2", "UserId3", "UserId4", "UserId5" ]
let u = User.keys
let predicate = ...???
Amplify.DataStore.query(User.self where: predicate) { 
...
}

**Comment by royjit** [comment]
Hi @alionthego , you can do something like this:

```swift
let arrayOfUserIds = ["UserId1", "UserId2", "UserId3", "UserId4", "UserId5" ]

Amplify.API.query(
    request: .paginatedList(
        User.keys,
        where: QueryPredicateGroup(type: .or, predicates: arrayOfUserIds),
        limit: 1_000
    )
) { queryResult in
...
}
```

**Comment by diegocstn** [comment]
I'll optimistically close this, but feel free to re-open if you need more help.
