### ISSUE TITLE
Single app, Multiple User pools: App crashes when loading a new amplifyconfiguration.json

### ISSUE THREAD

**Issue by rafaelbuiu** [aws-amplify/amplify-ios#1341]
### Describe the bug

My application has multiple tenants and it was designed to configure the Amplify with the user pool information of that particular tenant which the user belongs to.

The problem is that when the user signs out and tries to authenticate using  credentials of a user in different user pool the application crashes saying that the configure function was already performed.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Amplify.configure() using a valid amplifyconfiguration.json
2. Authenticate using a valid user of that User pool
3. Sign out
4. Amplify.configure() with a amplifyconfiguration.json of a different user pool
5. The app crashes
```

### Expected behavior

I need to know how to unload a amplifyconfiguration.json in order to load a new file of a different User pool

### Amplify Framework Version

1.5.5

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

4.0

### CLI version

4.41.2

### Xcode version

12.5.1 (12E507)

### Device

iPad

### iOS Version

14+

**Comment by royjit** [comment]
Calling multiple configuration during runtime is not currently supported in Amplify iOS. Closing this as duplicate to this ticket - https://github.com/aws-amplify/amplify-ios/issues/527
