### ISSUE TITLE
Refresh token from social login it shows the Login popup again

### ISSUE THREAD

**Issue by tuancuong009** [aws-amplify/amplify-ios#1344]
### Describe the bug

I set the Token expiration time on Amazon amplify is 8mins
I open my Swift app -> click **Login with Google** -> I logged in successfully
I put the app in the background mode for more than 10mins
When I reopen the app -> the token is expired (it's fine) and I call **Amplify.Auth.fetchAuthSession** to refresh new token -> but it shows the popup asks me to login again (the attached image)
![image](https://user-images.githubusercontent.com/21256858/127473268-c22705dc-007d-4a1b-807b-31c8b2be20db.png)

it does not happen every time, sometimes I can refresh the new token without the popup.

So is this fine or a bug? So every time users open the app (and the token(logged in with Google) is expired) they will need to login again?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to Amplify set the Token expiration time to 8mins
2. Click login with Google on the Swift app 
3. Put the app in the background mode over 10mins
4. Re-open the app and call refresh token **Amplify.Auth.fetchAuthSession** 
5. It shows the popup to login
```

### Expected behavior

It should refresh token without showing the popup asks to login

### Amplify Framework Version

1.12.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

5.0.1

### Xcode version

12.4

### Device

iPhone XS

### iOS Version

14.4

**Comment by randomizedlife01** [comment]
I am using flutter but I have the same problem. This issue occurs when calling Amplify.Auth.fetchAuthSession.

I implemented the login function by referring to the Amplify Document. However, the update of the document is late. How can I fix this?

**Comment by allan-qts** [comment]
@randomizedlife01 did you find anything to resolve that?

**Comment by allan-qts** [comment]
@lawmicha can you please help us on this issue? thanks in advance, we are still struggling with it :(

**Comment by lawmicha** [comment]
Can you claify, when it works- the token gets refreshed when you call fetchAuthSession. For the times that you mentioned doesn't work, how does the pop up show up? is it because of the `fetchAuthSession` call or something else?

**Comment by allan-qts** [comment]
Thanks @lawmicha 
Yes I think `fetchAuthSession` caused the popup ask to login google again, here are my steps:
 
1.  Call `Amplify.Auth.signInWithWebU`I and log in via Google. Login is successful.
 2.  Put the app in the background mode in more than 10 mins ( I set the token expired time on Cognito as 8mins)
 3.  Open the app it detected the token is expired (it's correct)
 4.  So I want to refresh the token then I call `Amplify.Auth.fetchAuthSession`
 5.  It shows the popup asks to login with google again but it should not, I expected to get the new token without showing popup to ask login again.

This is the popup
![image](https://user-images.githubusercontent.com/14176004/129368789-b0c0b6b7-148c-4e71-a821-6b3fce6c693c.png)

And sometimes it works fine without showing the popup, what is the reason? can you check?

**Comment by royjit** [comment]
@allan-qts Are you also using Flutter Library ?

I tried different scenarios and was not able to reproduce the issue. Here are the settings I used:
AccessToken Expiry: 5min
IDToken Expiry: 5min
RefreshToken Expiry: 60min

1. Sign in and call fetchAuthSession after 5 min - Fetched successfully
2. Sign in to 2 devices with same user, signout from one device and call fetchAuthSession in another - Fetched successfully
3. Sign in and call fetchAuthSession after 60 min - Returned error session expired (no UI is shown)

- Can you please check what version of AWSMobileClient you are using? Please update to the latest libraries and see if this error was reproducible.

- Also when the popup is show, does it go to the Google SignIn page?

- @tuancuong009  mentioned that "When I reopen the app -> the token is expired (it's fine) " how did you verify that the token is expired? Amplify.Auth only inform us when the refresh token is expired.

**Comment by allan-qts** [comment]
@royjit thanks for your check.
I'm use iOS Swift library 

`
Can you please check what version of AWSMobileClient you are using? Please update to the latest libraries and see if this error was reproducible.`
AWSMobileClient (2.24.4)

`Sign in and call fetchAuthSession after 60 min - Returned error session expired (no UI is shown)`
-> Yes in this case, what should we do to get the new token for the next API call without asking user to login again?

`Also when the popup is shown, does it go to the Google SignIn page?`
-> if I open the app after a few hours it shows the popup -> click Continue -> it goes to Google Sign in page like this
![image](https://user-images.githubusercontent.com/14176004/129431673-cce5a53f-c9fb-4375-9756-d5dd39e02723.png)
-> if I open the app after a day it shows the popup -> click Continue -> it open the Auth page like this
![image](https://user-images.githubusercontent.com/14176004/129431685-5864975f-6493-46af-ba51-e76e0fffb480.png)

`@tuancuong009 mentioned that "When I reopen the app -> the token is expired (it's fine) " how did you verify that the token is expired? Amplify.Auth only inform us when the refresh token is expired.`
-> After logged in google we have the token, I use this token to call API via Apollo (GraphQL) -> the API return error "jwt expired" -> so I will call fetchAuthSession to get the new token. Is it correct? or do we have code to check if the token is valid or not via Amplify?

**Comment by tuancuong009** [comment]
Thanks @royjit it works fine now after I upgraded the new version for AWSMobileClient and Amplify.
Thanks for your support, I will close this issue.
