### ISSUE TITLE
Storage does not resume or retry upload with loss of network connectivity

### ISSUE THREAD

**Issue by testflyjets** [aws-amplify/amplify-ios#1346]
### Describe the bug

If an Amplify Storage file upload is requested while the device does not have a network connection the upload fails as expected. However, the upload is not retried once network connectivity is restored. Our expectation is that Storage would behave similarly to DataStore and attempt to synchronize the upload request back to S3 once the device reestablished a network connection.

From a separate issue (https://github.com/aws-amplify/amplify-ios/issues/1324), @brennanMKE provided additional information, though it is unclear if our assumptions that Storage should automatically retry the upload are correct. See the Additional Context section for his reply.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Turn off all network connections on the device.
2. Upload a file via `Amplify.Storage.uploadData` and note that the upload fails.
3. Restore the device's network connection.
4. Note that the upload is not retried, resulting in the file not being transferred to S3.
```

### Expected behavior

The expectation is that the Storage upload would behave similar to DataStore and that it would automatically retry the upload when the framework detects the restoration of network connectivity.

### Amplify Framework Version

1.12.1

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

5.3.2

### CLI version

4.47.1

### Xcode version

12.4 (12D4e)

### Relevant log output

```shell
2021-07-29 13:54:29.726269-0700 Mobile FSD[60189:4605897] Connection 7: failed to connect 1:50, reason -1
2021-07-29 13:54:29.726358-0700 Mobile FSD[60189:4605897] Connection 7: encountered error(1:50)
2021-07-29 13:54:29.729119-0700 Mobile FSD[60189:4605904] Task <3EC3157B-EEA4-467E-A7F8-E58F6F2973DE>.<1> HTTP load failed, 0/0 bytes (error code: -1009 [1:50])

2021-07-29 13:54:29.731708-0700 Mobile FSD[60189:4605904] Task <3EC3157B-EEA4-467E-A7F8-E58F6F2973DE>.<1> finished with error [-1009] Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x6000026dd170 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <3EC3157B-EEA4-467E-A7F8-E58F6F2973DE>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <3EC3157B-EEA4-467E-A7F8-E58F6F2973DE>.<1>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://mobilefieldingattachments144832-dev.s3.us-west-2.amazonaws.com/private/us-west-2%3A66b6ab42-399d-4fd7-8646-249fea8debfe/4F9296C4-838A-4C56-B5CC-C85DE7989F5A_YellowLeaf_offline.png?uploads=, NSErrorFailingURLKey=https://mobilefieldingattachments144832-dev.s3.us-west-2.amazonaws.com/private/us-west-2%3A66b6ab42-399d-4fd7-8646-249fea8debfe/4F9296C4-838A-4C56-B5CC-C85DE7989F5A_YellowLeaf_offline.png?uploads=, _kCFStreamErrorDomainKey=1}
Storage Upload Failed: Unexpected error occurred with message: Domain: [NSURLErrorDomain
Code: [-1009
LocalizedDescription: [The Internet connection appears to be offline.
```

### Is this a regression? (i.e. was this working before a version upgrade)

We had not tested this previously so we are not sure if this is a regression or not.

### Device

iPhone 12 simulator and iPhone 12 device

### iOS Version

14.6

### Specific to simulators

No

### Additional context

@testflyjets

You can skip to the recommendation in the last section if you like. This first section offers some context for the AWS SDK and Amplify SDK.

## Context

In the [underlying implementation](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSS3/AWSS3TransferUtility.m#L441-L443) you can see it allows for passing in values for [allowsCellularAccess](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1409406-allowscellularaccess) and [timeoutIntervalForResource](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408153-timeoutintervalforresource). This configuration is used for all network activity run through Transfer Utility. You can see the default for `allowsCellularAccess` is set in [AWSNetworking](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCore/Networking/AWSNetworking.m#L113) to allow by default. Without it all of these network tasks would not be allowed unless WiFi is connected. It could be set in `amplifyconfiguration.json` or `awsconfiguration.json`.

From the Amplify Storage side you can see the [upload options](https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Storage/Operation/Request/StorageUploadDataRequest.swift#L30-L58) do not include these properties so it is not possible to specify unique behavior per request.

There is a property called [waitsForConnectivity](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/2908812-waitsforconnectivity) which will either fail immediately if there is no access or queue the upload and let it start when a viable network path is available. All requests run by Transfer Utility are created with a background session and so the last line is relevant here.

> This property is ignored by background sessions, which always wait for connectivity.

## Recommendation

You can take control of this behavior by directly starting or canceling network operations based on connectivity status.

If your Deployment Target is iOS 12.0 or later you could use Apple's Network framework to monitor the network path and start or cancel operations in response to changes. If you need to support earlier versions you could use a package that I prepared called [Connectivity](https://github.com/brennanMKE/Connectivity) which falls back to using the Reachability library. It does not work as well as Apple's modern framework designed for mobile scenarios which were not common when Reachability was first created, but your app metrics likely show a small percentage of your users are using a version of iOS before 12. It will be sufficient for those users while giving the majority of your users the optimal behavior. 

That package includes a demo app that you can use to observe changes in your device's network path. You can put the app on an iPhone, disable the cellular radio and walk out of range of your WiFi network to see it change, or just turn on Airplane Mode. One feature you'll likely want to use to benefit your users is [isExpensive](https://developer.apple.com/documentation/network/nwpath/2998722-isexpensive). It is designed to be intelligent about the current network path. If you are on regular WiFi the value will be false. If you are a cellular connection, which likely involves data rates, it will be true. And if you happen to be using a WiFi hotspot which connects via cellular the value will also be true. This is one feature of the Network framework which is missing from Reachability. This package sets this property based on the [network status alone](https://github.com/brennanMKE/Connectivity/blob/main/Sources/ConnectivityKit/ReachabilityMonitor.swift#L21) with the Reachability implementation. You can avoid large uploads when your users are not on WiFi and save them both battery life and potentially higher data rates.

When the network path changes from `.unsatisfied` to `.satisfied` your network operations can run while if the opposite happens your can choose to cancel those network activities and start them again when a viable path is available. In my experience these interruptions are often momentary, like going through a tunnel or riding in an elevator. And when I get off the elevator it also means I will switch from cellular to WiFi or vice versa. You can make your code behavior exactly how you choose with this framework.

_Originally posted by @brennanMKE in https://github.com/aws-amplify/amplify-ios/issues/1324#issuecomment-889623701_

**Comment by rmitchell-iii** [comment]
Is there an update on this issue?

**Comment by brennanMKE** [comment]
@testflyjets We are taking this issue as a feature request and will update this ticket when we have more information.

**Comment by brennanMKE** [comment]
See [Monitoring Network Connectivity with Swift](https://gist.github.com/brennanMKE/4b04a6eb0f3428a48b1285acbb63fef4) for a recommendation on how to control behavior in response to changes in network connectivity.

**Comment by brennanMKE** [comment]
Closing as this is not a feature of Storage. DataStore is a different category which does behave differently. The above comment from Aug 9 is one way to have your app react to changes in network connectivity.
