### ISSUE TITLE
Cognito Sign In Error - Sign In Web UI not appearing after token expiry

### ISSUE THREAD

**Issue by kitlogan** [aws-amplify/amplify-ios#1357]
### Describe the bug

Hi all, I've got a strange Sign In error with Amplify + Cognito on iOS.
Until about 25/07/21 it worked fine, however afterwards, the standard 'Sign In' amplify function no longer works. Instead I get the error in the image below.

Standard sign in function:
```
`    // signin with Cognito web user interface
    public func signIn() {

        _ = Amplify.Auth.signInWithWebUI(presentationAnchor: UIApplication.shared.windows.first!) { result in
            switch result {
            case .success(_):
                print("Sign in succeeded")
            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }
    }`
```
Any ideas?

![image](https://user-images.githubusercontent.com/61054641/128341037-0a3be4ee-2a29-41f5-8230-bb33fecbed1f.png)

### Steps To Reproduce

```swift
1. On an iOS
2. Use Amplify.Auth.signInWithWebUI function after the log in session / refresh token has expired
```

### Expected behavior

It should bring up the Cognito WebUI sign in. On an iPhone 12 Pro, the button appears to do nothing and the error in the image attached is produced.

### Amplify Framework Version

1

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

4.51.2

### Xcode version

12.5.1

### Relevant log output

```shell
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/Kit/Documents/EF/avie/Build/avie2/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-7000 "(null)" UserInfo={error=invalid_grant}
```

### Is this a regression? (i.e. was this working before a version upgrade)

This used to work before the 25th July 2021.

### Device

iPhone

### iOS Version

iOS 14

### Specific to simulators

No

**Comment by lawmicha** [comment]
The error says `invalid_grant`, which i've seen similarly in other issues like https://github.com/aws-amplify/amplify-ios/issues/1204 that had a fix that was released in the SDK 2.24.2. If you pull in the latest Amplify 1.13.3, it will pull in that change. Can you verify which versions of Amplify you are using, and if possible you can also check the SDK version (version pulled in for AWSCore for example)? It should be in the Podfile.lock

**Comment by kitlogan** [comment]
Hi, thank you very much for your response and help.
To update you on the issue - it is no longer just iPhone 12 Pros (this was a very unlikely coincidence!). The webUI just doesn't appear when users try to re-login after an expired session, now on a variety of devices.

My amplifyconfiguration.json file says I am using Amplify `"Version": "1.0"`
and
my podfile looks like this:
`PODS:
  - Amplify (1.9.2):
    - Amplify/Default (= 1.9.2)
  - Amplify/Default (1.9.2)
  - Amplify/Tools (1.9.2)
  - AmplifyPlugins/AWSAPIPlugin (1.9.2):
    - AppSyncRealTimeClient (~> 1.4)
    - AWSCore (~> 2.24.0)
    - AWSPluginsCore (= 1.9.2)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.9.2):
    - AWSAuthCore (~> 2.24.0)
    - AWSCognitoIdentityProvider (~> 2.24.0)
    - AWSCognitoIdentityProviderASF (~> 2.24.0)
    - AWSCore (~> 2.24.0)
    - AWSMobileClient (~> 2.24.0)
    - AWSPluginsCore (= 1.9.2)
  - AmplifyPlugins/AWSS3StoragePlugin (1.9.2):
    - AWSCore (~> 2.24.0)
    - AWSPluginsCore (= 1.9.2)
    - AWSS3 (~> 2.24.0)
  - AppSyncRealTimeClient (1.5.0):
    - Starscream (~> 3.1.1)
  - AWSAuthCore (2.24.1):
    - AWSCore (= 2.24.1)
  - AWSCognitoIdentityProvider (2.24.1):
    - AWSCognitoIdentityProviderASF (= 2.24.1)
    - AWSCore (= 2.24.1)
  - AWSCognitoIdentityProviderASF (2.24.1)
  - AWSCore (2.24.1)
  - AWSMobileClient (2.24.1):
    - AWSAuthCore (= 2.24.1)
    - AWSCognitoIdentityProvider (= 2.24.1)
    - AWSCognitoIdentityProviderASF (= 2.24.1)
    - AWSCore (= 2.24.1)
  - AWSPluginsCore (1.9.2):
    - Amplify (= 1.9.2)
    - AWSCore (~> 2.24.0)
  - AWSS3 (2.24.1):
    - AWSCore (= 2.24.1)
  - ReachabilitySwift (5.0.0)
  - Starscream (3.1.1)

DEPENDENCIES:
  - Amplify (~> 1.0)
  - Amplify/Tools (~> 1.0)
  - AmplifyPlugins/AWSAPIPlugin (~> 1.0)
  - AmplifyPlugins/AWSCognitoAuthPlugin (~> 1.0)
  - AmplifyPlugins/AWSS3StoragePlugin (~> 1.0)
  - ReachabilitySwift`

**Comment by kitlogan** [comment]
I can see that my AWSCore is a variety of 2.24.0 and 2.24.1, but not 2.24.2. Hopefully this is the issue?

Would you mind providing instructions with how I am best to update this? I'm in experiences with Amplify and don't want to damage the product I've built! I installed it to the project using cocoapods.

Thank you!

**Comment by royjit** [comment]
Can you try running `pod update` in your project root?
This SO has some details regarding doing a complete Cocoapod clear https://stackoverflow.com/questions/46428752/how-to-clear-or-clean-specific-pod-from-the-local-cocoapods-cache
