### ISSUE TITLE
iOS Amplify Cognito Auth Hosted Web UI for OIDC login does not show logo of app on iOS, but does show logo on web/browser

### ISSUE THREAD

**Issue by gabimo** [aws-amplify/amplify-ios#1359]
### Describe the bug

When I open my Amplify Cognito Auth hosted web UI login screen on iOS it doesn't show a logo as I've put on there. It does show for web 

How can I fix this? We'd like our users to know they're using a company approved login service by seeing the logo.

<img width="683" alt="Screen Shot 2021-08-05 at 10 13 50 AM" src="https://user-images.githubusercontent.com/9092155/128511863-6028bf4a-255f-4175-846d-862899449372.png">
<img width="874" alt="Screen Shot 2021-08-05 at 8 54 39 AM" src="https://user-images.githubusercontent.com/9092155/128511874-c748fb7c-3064-4dce-9e3e-224183a80beb.png">

### Steps To Reproduce

```swift
Setup a Cognito iOS/Amplify Auth service, launch/invoke Hosted Web UI sign in, no branding on iOS
```

### Expected behavior

I should see a Logo of my app on iOS

### Amplify Framework Version

1.9.3

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

not using

### Xcode version

13.0 Beta 3 and 12.5.1

### Is this a regression? (i.e. was this working before a version upgrade)

No

### Device

iPad 9.7"

### iOS Version

14+

### Specific to simulators

No

### Additional context

This ticket might belong elsewhere, please help submit this issue to the correct place if so! Thanks

**Comment by gabimo** [comment]
where could I find assistance for this?

**Comment by royjit** [comment]
Thanks for reaching out, we have reached out to the service team to get more information regarding this.

**Comment by royjit** [comment]
Amazon Cognito does not support displaying provider logos for OIDC providers at the current time.
We have heard this request from other customers and will consider it in future updates to the service.
