### ISSUE TITLE
Field owner not inserted in DynamoDb from Amplify IOS Datastore plugin, even with @auth owner rule

### ISSUE THREAD

**Issue by maremoto** [aws-amplify/amplify-ios#1371]
### Describe the bug

I insert a new entry in a table with @auth owner rule from an IOS app with successful login, but the field owner is not inserted in the DynamoDb table, causing further auth errors with query on the entry:

`GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access getUsers on type Query", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: Optional([Amplify.JSONValue.string("getUsers")]), extensions: Optional(["errorType": Amplify.JSONValue.string("Unauthorized"), "errorInfo": Amplify.JSONValue.null, "data": Amplify.JSONValue.null]))]`

This error persist util you manually insert the owner field in the new entry using the DynamoDB web.

### Steps To Reproduce

1. Create a Amplify enviroment with:
  - Cognito phone auth 
  - Datastore API with Cognito Authorization default mode
  - Codegen
  
2. Create a table like this:

```
type Users @model @auth(rules: [{allow: private, operations: [create]}, {allow: owner}]) {
  id: ID!
  phone: AWSPhone!
  firstName: String!
}
```
3. Create a IOS app with Xcode,
-  integrate with backend and API codegen and modesl
-  login with Amplify.Auth
-  and then sucessfully insert a row in the table:

```swift
let userdata = Users(
                          id: "f165654d-c5e6-4438-83cc-a2f448893392", //cognito subID
                          phone: "+34666666666",
                          firstName: "Maremoto")
Amplify.Datastore.save(userdata) {
[...]
} 
```

4. At the end, check in DynamoDB console that the owner field is not inserted, and **if you manually insert it, the query then starts working**.
```


### Expected behavior

I expect that the IOS SDK inserts owner field to make the insertion usable to owner.

### Amplify Framework Version

1.12.0

### Amplify Categories

API, Auth, DataStore

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

5.3.0

### Xcode version

12.5

### Relevant log output

```shell
GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access getUsers on type Query", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: Optional([Amplify.JSONValue.string("getUsers")]), extensions: Optional(["errorType": Amplify.JSONValue.string("Unauthorized"), "errorInfo": Amplify.JSONValue.null, "data": Amplify.JSONValue.null]))]
```

### Is this a regression? (i.e. was this working before a version upgrade)

No, it never worked.

### Device

IPoneSE and Simulator

### iOS Version

IOS 13.0

### Additional context

PODS
  - Amplify (1.12.0):
  - Amplify/Default (1.12.0)
  - Amplify/Tools (1.12.0)
  - AmplifyPlugins/AWSAPIPlugin (1.12.0):
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.12.0):
  - AmplifyPlugins/AWSDataStorePlugin (1.12.0):
  - AmplifyPlugins/AWSS3StoragePlugin (1.12.0):
  - AppSyncRealTimeClient (1.5.0):
  - AWSAppSync (3.2.1):
  - AWSAuthCore (2.24.4):
  - AWSCognitoIdentityProvider (2.24.4):
  - AWSCognitoIdentityProviderASF (2.24.4)
  - AWSCore (2.24.4)
  - AWSMobileClient (2.24.4):
  - AWSPluginsCore (1.12.0):
  - AWSS3 (2.24.4):
  - SQLite.swift (0.12.2):
  - SQLite.swift/standard (0.12.2)
  - Starscream (3.1.1)

**Comment by maremoto** [comment]
I have found empirically that if I declare the owner field in the schema it works.

But I had read in documentation and forums that the field is inserted "automagically" as well as other metadata.

I am a bit confused, should I explicitly declare in the schema other fields as _version, _lastChangedAt, __typename?, because those are indeed automatically being inserted, but maybe not being explicitly in the graphql schema will generate further issues.

And I am also concerned that if the owner field is automatically inserted in the next IOS SDK version, if it will be problematic to have it explicit now.

**Comment by diegocstn** [comment]
@maremoto thanks for reporting this to us.
On which [version of Amplify](https://github.com/aws-amplify/amplify-ios/releases) are you on?

As you said, the `owner` field should be automatically populated by the library with the appropriate value when a user is signed in.
Unless you'd like to give the owner field a name different than the default ("owner"), you don't need to declare it in your schema.
In addition to that, the following two schemas are functionally equivalent
```graphql
type Users @model @auth(rules: [{allow: private, operations: [create]}, {allow: owner}]) {
  id: ID!
  phone: AWSPhone!
  firstName: String!
}
```

```graphql
type Users @model @auth(rules: [{allow: private, operations: [create]}, {allow: owner, ownerField: "owner"}]) {
  id: ID!
  phone: AWSPhone!
  firstName: String!
  owner: String!
}
```

To rule out a possible race condition between Auth and DataStore plugins, can you share a snippet of code about how you're invoking Auth and DataStore.query?
