### ISSUE TITLE
`amplify import auth` does not add an `OAuth` entry to the amplifyconfiguration.json

### ISSUE THREAD

**Issue by Bersaelor** [aws-amplify/amplify-ios#1374]
### Describe the bug

When going through the process using `amplify import auth` to import an existing Cognito pool, the section `OAuth` with the `WebDomain` is missing and ` Amplify.Auth.signInWithWebUI` fails (because WebDomain is nil).

### Steps To Reproduce

1. use `amplify import auth` to import an existing Cognito pool to Amplify
2. look at the amplifyconfiguration.json:

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "***",
                            "Region": "***"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "***",
                        "AppClientId": "***",
                        "Region": "***"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
```

### Expected behavior

According to https://github.com/aws-amplify/amplify-ios/issues/1058#issuecomment-776105649 it should look like this:

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "xxx",
                            "Region": "xxx"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxx",
                        "AppClientId": "xxx",
                        "AppClientSecret": "xxx",
                        "Region": "xxx"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxx.amazoncognito.com",
                            "AppClientId": "xxx",
                            "AppClientSecret": "xxx",
                            "SignInRedirectURI": "xxx",
                            "SignOutRedirectURI": "xxx",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

### Amplify Framework Version

1.13.3

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5

### CLI version

5.3.0

### Xcode version

13.0

### Device

iPhone 12

### iOS Version

iOS 14.1

**Comment by Bersaelor** [comment]
I managed to get a UI to show by manually filling all the missing values above, but it took me while to figure out the correct values.

(Also sorry for the above bad formatting, I had posted this during a GitHub service outage so I couldn't edit it anymore)

**Comment by lawmicha** [comment]
good to hear you were able to get the UI to show, for reference there's https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios 

I'm not aware of the questions that `amplify import auth` will ask, but i think if it asked for something and you had provided some values, but it was not translated over to the configuration then there is an issue.

**Comment by lawmicha** [comment]
Could you open an issue over there if there is an issue in the `amplify import auth` workflow? https://github.com/aws-amplify/amplify-cli/issues I don't have access to transfer this one

**Comment by Bersaelor** [comment]
Mhmm, I don't think the command line ever asked me to put any web-domainr elated info in, thats why I was wondering/

I can run `amplify remove auth` and import it again tomorrow.

I also created a ticket over in the amplify-cli issues under https://github.com/aws-amplify/amplify-cli/issues/7947

**Comment by diegocstn** [comment]
@Bersaelor I'm closing this in favor of https://github.com/aws-amplify/amplify-cli/issues/7947, but feel free to reopen if you need more help.
