### ISSUE TITLE
App crashes when calling confirmSignIn with new password (intermittent)

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-ios#1376]
### Describe the bug

When executing `signIn` for a Cognito user record in the `FORCE_CHANGE_PASSWORD`, the amplify-ios library returns a `FORCE_CHANGE_PASSWORD` `nextStep`. 

Typically, the `confirmSignIn` method can be called with a new password, the Cognito user record updates, and the next state is returned. However, the `confirmSignIn` API seems to intermittently crash the application:

```
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot set the result on a completed task.'
CoreSimulator 732.18.6 - Device: iPhone 12 (01D66578-B2F8-4EBF-890E-B96C587E12CB) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12
terminating with uncaught exception of type NSException
```

Please note this was observed via an amplify-flutter application; however, [amplify-ios customers appear to experience it as well](https://stackoverflow.com/questions/64342214/nsinternalinconsistencyexception-cannot-set-the-result-on-a-completed-task).

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to the Cognito console and create a use with all required attributes marked as verified.
2. Call the signIn method.
3. The method will return `FORCE_CHANGE_PASSWORD` as the `nextStep` 
4. Call confirmSignIn with a valid password.

You may need to do this multiple times. I have never observed this after opening the app on a clean device and executing this flow for the first time. You may need to create multiple users and go through the signup -> signin flow repeatedly.
```

### Expected behavior

The confirmSignIn API should consistently allow password change.

### Amplify Framework Version

1.11.0

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

unspecified

### CLI version

n/a

### Xcode version

12.4

### Device

iphone 12 simulator

### iOS Version

ios 11

**Comment by lawmicha** [comment]
I believe @dnys1 may have something in AWSMobileClient to fix this- we'll reference the PR here whenever that is ready from the iOS SDK, looking forward to it!

**Comment by dnys1** [comment]
@lawmicha Opened a PR in the SDK for this: https://github.com/aws-amplify/aws-sdk-ios/pull/3732

**Comment by royjit** [comment]
PR is merged closing
