### ISSUE TITLE
DataStore locally contains data that was deleted in DynamoDB table.

### ISSUE THREAD

**Issue by SvyatHoly** [aws-amplify/amplify-ios#1379]
### Describe the bug

Local DataStore in my app never clears items that don't exist in the cloud.

### Steps To Reproduce

```swift
1. Crate item via Amplify.API.mutate(request: .create(todo))
2. reload app (for sync)
2. Fetch data from DataStore Amplify.DataStore.query(Todo.self)
3. Created items exist
4. Delete item from Todo's table (via console.aws interface)
5. reload the app for sync.
6. Item still exists in DataStore.
```

### Expected behavior

Local data must be consistent with the remote table.

### Amplify Framework Version

1.12.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5

### CLI version

4.52.0

### Xcode version

Xcode 12.5

### Device

IPhone 11

### iOS Version

Ios 13

**Comment by lawmicha** [comment]
> 4. Delete item from Todo's table (via console.aws interface)

is this from the DynamoDB console interface?

DataStore keeps the local store in sync with the cloud via subscriptions, so if you clear items from the dynamoDB table directly, there won't be a subscription event to reconcile with the local store and delete the item. To trigger the subscription, you'll have to perform the deletion from the app using `Amplify.DataStore.delete` (which will send the delete mutation) or through AppSync console and perform the delete mutation. When performing the delete mutation from the AppSync console, keep in mind to populate the selection set fully to ensure the subscription event contains all the data needed for the app to reconcile

**Comment by SvyatHoly** [comment]
@lawmicha Ok, thanks. I'll try to mutate data only with AppSync

**Comment by lawmicha** [comment]
Free free to open another issue if something is not working as expected
