### ISSUE TITLE
[NSTaggedPointerString objectForKey:]: unrecognized selector sent to instance when configuring AWSCognitoAuthPlugin

### ISSUE THREAD

**Issue by cesarbess** [aws-amplify/amplify-ios#1382]
### Describe the bug

Hi. I'm creating a Swift Package which uses Amplify (AWSCognitoAuthPlugin) as a dependency, this project already had an Android counterpart so I've just reused the amplifyconfiguration.json that the Android project uses.

However when configuring the Amplify SDK, when i add the AWSCognitoAuthPlugin i get the following error:

<img width="978" alt="Screen Shot 2021-08-16 at 13 49 28" src="https://user-images.githubusercontent.com/19217059/129599970-9423a995-865a-43cf-aea3-0c5c4104d4bf.png">

This is the call stack:

<img width="345" alt="Screen Shot 2021-08-16 at 13 50 20" src="https://user-images.githubusercontent.com/19217059/129600056-aaa6ae99-847a-4be2-931c-3fd408ac6b85.png">

And this is the code I'm running to configure the SDK

```
let file = try resourceLoader.loadResourceURL(fromFileNamed: File.amplify.rawValue) // This returns a URL for  the amplify.json file i have locally
let configuration = try AmplifyConfiguration(configurationFile: file) // Need to pass the URL to my config file since the library can't find on its own like on a regular xcode project.
try Amplify.add(plugin: AWSCognitoAuthPlugin()) // It works if i don't try to add this plugin
try Amplify.configure(configuration)
```

I've been looking around but haven't found a similar issue, am I doing something wrong in the setup? Do we need to do something different for using it on a Package?

Any kind of help is appreciated 

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create a new Swift Package with an example app
2. Add Amplify as a dependency of your package

.package(name: "Amplify", url: "https://github.com/aws-amplify/amplify-ios", .exact("1.13.3")),


Add Amplify and AWSCognitoAuthPlugin to your target dependency:
```swift
dependencies: ["Amplify", product(name: "AWSCognitoAuthPlugin", package: "Amplify")]
```

3. Import an existing amplifyconfiguration.json file to your project
4. Specify as a resource in your Package.swift file 
```swift
resources: [
                .copy("Config/amplifyconfiguration.json")
            ]
```
4. Configure the SDK with the AWSCognitoAuthPlugin
5. Build app and see the error
```


### Expected behavior

SDK is configured successfully

### Amplify Framework Version

1.13.3

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.3

### CLI version

Not using (used existing config file)

### Xcode version

Version 12.5 (12E262)

### Relevant log output

_No response_

### Is this a regression? (i.e. was this working before a version upgrade)

No

### Device

iPhone 12 Simulator

### iOS Version

iOS 14.5

### Specific to simulators

No

### Additional context

* Using Amplify as a dependency of a Swift Package
* Reusing the amplifyconfiguration.json from the existing Android project 
* Didn't configure the CLI tool locally since I already had the config files

Not sure if those are relevant to the issue.

**Comment by cesarbess** [comment]
UPDATE: I've noticed that if I remove the "IdentityManager" object from my amplifyconfiguration.json file the crash doesn't happen

**Comment by brennanMKE** [comment]
@cesarbess Thanks for reporting this issue. Can you provide the stack frames so we can see the method signatures and line numbers? That will help us track down where this is happening.

**Comment by cesarbess** [comment]
@brennanMKE  Sure, I think it's important to highlight that this only happens when I have "IdentityManager" object in my amplify.configuration.json file, so here's a sample of my JSON file in case it helps:

```
{
  "Version": "1.0",
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "some-pool-id",
        "Region": "some-region"
      }
    }
  },
  "IdentityManager": {
    "Default": "default"
  },
  "CognitoUserPool": {
    "Default": {
      "AppClientSecret": "",
      "AppClientId": "some-client-id",
      "PoolId": "some-pool-id",
      "PinpointAppId": "some-app-id",
      "Region": "some-region"
    }
  },
  "PinpointAnalytics": {
    "AppId": "some-app-id",
    "Region": "some-region"

  },
  "AppSync": {
    "Default": {
      "ApiUrl": "some-url",
      "Region": "some-region",
      "AuthMode": "AMAZON_COGNITO_USER_POOLS"
    }
  }
}
```

And here's the stack:

````
2021-08-20 15:19:44.739559-0300 iOS Example[73708:2048328] -[NSTaggedPointerString objectForKey:]: unrecognized selector sent to instance 0x90fc44a649c541b6
2021-08-20 15:19:44.915139-0300 iOS Example[73708:2048328] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString objectForKey:]: unrecognized selector sent to instance 0x90fc44a649c541b6'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20431d2f +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff204274cf ___forwarding___ + 1455
	4   CoreFoundation                      0x00007fff204297a8 _CF_forwarding_prep_0 + 120
	5   AWSCore                             0x00000001033619a8 AWSCore + 63912
	6   AWSCore                             0x00000001033617df AWSCore + 63455
	7   AWSMobileClientXCF                  0x00000001034c6543 globalinit_33_9ADE1B81584EC510664F8EA44BD58CC5_func4 + 9475
	8   AWSMobileClientXCF                  0x00000001034cd261 globalinit_33_9ADE1B81584EC510664F8EA44BD58CC5_func4 + 37409
	9   AWSMobileClientXCF                  0x00000001034c69de globalinit_33_9ADE1B81584EC510664F8EA44BD58CC5_func4 + 10654
	10  libdispatch.dylib                   0x00000001036d274e _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001036e18c5 _dispatch_lane_barrier_sync_invoke_and_complete + 132
	12  AWSMobileClientXCF                  0x00000001034c4b5c globalinit_33_9ADE1B81584EC510664F8EA44BD58CC5_func4 + 2844
	13  iOS Example                         0x00000001027c7b74 $s20AWSCognitoAuthPlugin22AWSMobileClientAdapterC10initializeyyKF + 228
	14  iOS Example                         0x00000001027c96aa $s20AWSCognitoAuthPlugin22AWSMobileClientAdapterCAA0dE8BehaviorA2aDP10initializeyyKFTW + 26
	15  iOS Example                         0x0000000102766115 $s20AWSCognitoAuthPluginAAC9configure5usingyypSg_tKF + 2117
	16  iOS Example                         0x000000010276b383 $s20AWSCognitoAuthPluginAAC7Amplify0C0AacDP9configure5usingyypSg_tKFTW + 19
	17  iOS Example                         0x00000001026fbead $s7AmplifyAAC9configure7plugins5usingySayAA6Plugin_pG_AA21CategoryConfiguration_pSgtKFZ + 1629
	18  iOS Example                         0x00000001026240e8 $s7Amplify12AuthCategoryC9configure5usingyAA0C13Configuration_pSg_tKF + 600
	19  iOS Example                         0x0000000102624621 $s7Amplify12AuthCategoryC9configure5usingyAA0A13ConfigurationV_tKF + 97
	20  iOS Example                         0x00000001026246dd $s7Amplify12AuthCategoryCAA0C12ConfigurableA2aDP9configure5usingyAA0A13ConfigurationV_tKFTW + 13
	21  iOS Example                         0x00000001026fb0c8 $s7AmplifyAAC9configure33_1FE8FA22C6D8688F03EE8B91288E41F3LL_5usingyAA8Category_p_AA0A13ConfigurationVtKFZ + 456
	22  iOS Example                         0x00000001026f9df9 $s7AmplifyAAC9configureyyAA0A13ConfigurationVSgKFZ + 1433
	23  iOS Example                         0x00000001023cc439 $s11SpectrumSdk23ConfigureAmplifyCommandV9configure029_B2C48D24F0BF6F8447C1D344FBC8G2BDLLyyF + 969
	24  iOS Example                         0x00000001023cc069 $s11SpectrumSdk23ConfigureAmplifyCommandV7executeyyF + 9
	25  iOS Example                         0x00000001023cc9b9 $s11SpectrumSdk23ConfigureAmplifyCommandVAA0E0A2aDP7executeyyFTW + 9
	26  iOS Example                         0x00000001023d7b22 $s11SpectrumSdkAACAByc33_A80088BDA89A38360B0832642F2FEEE0LlfcyAA7Command_pXEfU_ + 66
	27  libswiftCore.dylib                  0x00007fff2f107ced $sSTsE7forEachyyy7ElementQzKXEKF + 413
	28  iOS Example                         0x00000001023d7aa2 $s11SpectrumSdkAACAByc33_A80088BDA89A38360B0832642F2FEEE0Llfc + 242
	29  iOS Example                         0x00000001023d7861 $s11SpectrumSdkAACAByc33_A80088BDA89A38360B0832642F2FEEE0LlfC + 33
	30  iOS Example                         0x00000001023d782c $s11SpectrumSdkAAC6shared_WZ + 28
	31  libdispatch.dylib                   0x00000001036d274e _dispatch_client_callout + 8
	32  libdispatch.dylib                   0x00000001036d3c9b _dispatch_once_callout + 66
	33  libswiftCore.dylib                  0x00007fff2f3a059a swift_once + 26
	34  iOS Example                         0x00000001023d78a4 $s11SpectrumSdkAAC6sharedABvau + 52
	35  iOS Example                         0x00000001023c889e $s11iOS_Example01ia1_B3AppVACycfC + 30
	36  iOS Example                         0x00000001023c8b89 $s11iOS_Example01ia1_B3AppV7SwiftUI0C0AadEPxycfCTW + 9
	37  SwiftUI                             0x00007fff562e5376 $s7SwiftUI3AppPAAE4mainyyFZ + 47
	38  iOS Example                         0x00000001023c8b21 $s11iOS_Example01ia1_B3AppV5$mainyyFZ + 33
	39  iOS Example                         0x00000001023c8ba4 main + 20
	40  libdyld.dylib                       0x00007fff2025abbd start + 1
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString objectForKey:]: unrecognized selector sent to instance 0x90fc44a649c541b6'
CoreSimulator 757.5 - Device: iPhone 12 (8C2A33BB-E6A7-49A5-91AF-71096FF7996F) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 12
terminating with uncaught exception of type NSException
(lldb) 


```

**Comment by cesarbess** [comment]
@brennanMKE Thanks for the reply. What i'm trying to achieve is building an iOS app and a Swift Package that handles the authentication logic. Since in the future i can have other apps that would need to reuse this same authentication logic.

So can i still have the amplify related code inside my Swift Package and then the client app that uses this package will have the amplifyconfiguration.json file in its bundle and will inform the Package the file location by a URL? I'd appreciate if you could point me to the best direction to go with this.

**Comment by cesarbess** [comment]
@brennanMKE Thanks for the reply. What i'm trying to achieve is building an iOS app and a Swift Package that handles the authentication logic. Since in the future i can have other apps that would need to reuse this same authentication logic.

I've done what you suggested, and added the .json file to the client app that is using the Swift Package. But can i still have all the amplify related code inside the Package and then the client can inform the Package which URL contains the .json file? I've done that and apparently it works the same, but  I'd appreciate if you could point me to the best direction to go with this, right now i haven't found other sources that have a Package using Amplify. Thanks in advance

**Comment by brennanMKE** [comment]
With an app there is the app bundle which contains all of the resources and binaries for the app. It is the [main bundle](https://developer.apple.com/documentation/foundation/nsbundle/1410786-mainbundle) and this is where these .json files are expected to be. Swift Packages only support libraries, not apps. So you normally have to create a project with Xcode for an app and it can include Swift Packages as dependencies. See the linked docs from Apple below. 

 * [Adding Package Dependencies to Your App](https://developer.apple.com/documentation/swift_packages/adding_package_dependencies_to_your_app)

What I like to do is put as much code as possible into Swift Packages so very little code is in the Xcode project. I do this because an Xcode project file references every source file and changes to this shared file can often result in merge conflicts. For Swift packages the folder structure is used to associate source files with the build target. And with a modern SwiftUI app the code referenced in the Xcode project itself can be as simple as the code below.

```swift
import SwiftUI
import MyAppPackage

@main
struct MyApp: App {
    var body: some Scene {
        WindowGroup {
            MyAppMainView()
        }
    }
}
```

In this code `MyAppPackage` is imported which is the Swift Package. Much of your code can go into that package and any other package dependencies you like. With the Storage category you'll need to support [background transfers](https://docs.amplify.aws/sdk/storage/transfer-utility/q/platform/ios/#background-transfers) on iOS by adding the following code to the source code above. It passes along background events so they can be processed.

```swift
#if canImport(UIKit)
@UIApplicationDelegateAdaptor private var appDelegate: AppDelegate
#endif
```

Below is the code for `AppDelegate` to support the property shown above.

```swift
import Foundation
import UIKit
import AWSS3

class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        print(#function)
        return true
    }

    func application(_ application: UIApplication, handleEventsForBackgroundURLSession identifier: String, completionHandler: @escaping () -> Void) {
        print(#function)
        AWSS3TransferUtility.interceptApplication(application, handleEventsForBackgroundURLSession: identifier, completionHandler: completionHandler)
    }
}
```

Once you have run the `amplify pull` command you want to ensure that .json files are added to the Xcode project for the app and are included as resources and selected with that build target. You can see in [AWSInfo](https://github.com/aws-amplify/aws-sdk-ios/blob/2ce94a7fda175ed6ffd86c993b0ace219b926ac2/AWSCore/Service/AWSInfo.m#L91) that the AWS configuration file is loaded from the main bundle. For the Amplify configuration, [it also](https://github.com/aws-amplify/amplify-ios/blob/02ac2ba5c417883ea90f3d59b3cd28e63d2a1d39/Amplify/Core/Configuration/Internal/Amplify%2BResolve.swift#L17) is loaded from the main bundle.

You can think of the main bundle as a shared resource and it will allow you to define a Swift package which works with the [Authentication category](https://docs.amplify.aws/sdk/auth/getting-started/q/platform/ios/) and use that package as a dependency from multiple apps. Each app would have a unique Xcode project for the app and copy of these .json files. I'd encourage you to include unit tests to ensure your code is working as intended for that package and you can even have an app that you use for integration testing so you can work out updates to your auth package and prepare releases of it for all of your apps.
