### ISSUE TITLE
How do I properly update my SwiftUI view using datastore

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1383]
I am using datastore in an SwfitUI amplify project and unsure how to properly update my view to reflect changes in the datastore.  Particularly remote changes.

What I can gather from the documentation is that I need a listener for datastore in my model class and listen for events such as:

```
@Published var myModelItems: MyModelItems = []

init() {
    let _ = Amplify.Hub.listen(to: .dataStore) { event in
        DispatchQueue.main.async {
            ...query datastore and update myModelItems
        }
    }
}
```

This approach is updating the model for all events which is great.  Except when a user initially logs in and the entire datastore syncs.  Then this breaks down as each sync event is causing the datastore query and it gets into a recursive pattern that freezes the UI.

So I thought to modify to something like this to avoid the datastore syncing issue:

```

@Published var myModelItems: MyModelItems = []
private var syncQueriesReady = true

init() {
    let _ = Amplify.Hub.listen(to: .dataStore) { event in
        DispatchQueue.main.async {
            if event.eventName == HubPayload.EventName.DataStore.syncQueriesStarted {
                self.syncQueriesReady = false
            }
            if event.eventName == HubPayload.EventName.DataStore.syncQueriesReady {
                self.syncQueriesReady = true
            }
            if self.syncQueriesReady == true {
                ...query datastore and update myModelItems
            }
        }
    }
}
```

I'm wondering what is the best approach as it is not included in the documentation other than an example for networkMonitor.

I am aware that I can further constrict the hub event by model name but I've omitted that for simplicity.  I just really want to know what is the standard practice to listen for remote events and keep the view's up to date.

**Comment by lawmicha** [comment]
If your app can wait until DataStore has finished syncing, you can register a listener to listen to the `.ready` event. When you receive the `.ready` event, this means datastore is done syncing and subscriptions are active.  Perform the query at this time to get the latest snapshot of the data and then register listeners for model changes using the [`Amplify.DataStore.publisher` API](https://docs.amplify.aws/lib/datastore/real-time/q/platform/ios/). When you receive a model update, first check if `myModelItems` contains the item. If it exists, replace it with the updated model (or remove it if it was deleted) or insert it if it does not exist, which will rerender your UI. 

If you want to show data from the local store before DataStore has finished syncing.. one option is to perform the query first, then listen to the ready event before performing another query and subscribing to model changes. This way, your app does not have to handle the model changes during the sync process.

**Comment by afern247** [comment]
> If your app can wait until DataStore has finished syncing, you can register a listener to listen to the `.ready` event. When you receive the `.ready` event, this means datastore is done syncing and subscriptions are active. Perform the query at this time to get the latest snapshot of the data and then register listeners for model changes using the [`Amplify.DataStore.publisher` API](https://docs.amplify.aws/lib/datastore/real-time/q/platform/ios/). When you receive a model update, first check if `myModelItems` contains the item. If it exists, replace it with the updated model (or remove it if it was deleted) or insert it if it does not exist, which will rerender your UI.
> 
> If you want to show data from the local store before DataStore has finished syncing.. one option is to perform the query first, then listen to the ready event before performing another query and subscribing to model changes. This way, your app does not have to handle the model changes during the sync process.

Hi, is there any example of how to do this? I was looking for answers and came upon this. When the user downloads the app for the first time on a device (but with existing data), and I try to fetch on the view the data it says that it doesn't exist. However if I fetch it after a couple of seconds it does find it. Is there a proper example on how to handle this initial sync and subscribe to changes?

**Comment by afern247** [comment]
Also how do I query for a specific ID on the subscription? On the docs it says subscribe to a model but what if I have a model linked to another one? (1-many). I just want to subscribe for the ones that the specific user has

**Comment by alionthego** [comment]
hi @lawmicha  
Your answer is quite helpful, but it would be really great to see an example.  Specifically how to get the item that is being added or removed from the data that is returned.  I didn't see any example for this.
Thanks

**Comment by afern247** [comment]
@alionthego how did you do it to get the data at app start? When I do "give me the datastore data" it doesn't find it as it takes some time to initialize, can you share a code snippet?

@lawmicha can someone from the Amplify team address this and provide some examples...?

**Comment by ashiemke** [comment]
Here's a bit of combine to wait for specific tables to load: ```        
let events = Amplify.Hub.publisher(for: .dataStore)
            .filter { $0.eventName == HubPayload.EventName.DataStore.modelSynced }
            .compactMap { $0.data as? ModelSyncedEvent }
            .share()
            
        let userSync = events.filter { $0.modelName == "User" }
        let profileSync = events.filter { $0.modelName == "Profile" }

let complete = userSync.combineLatest(profileSync)
            .first()
```
add more models there as necessary, or just look for the .ready event in the initial publisher. We use this to show a loading indicator until the necessary data has been pulled down. The code above is called when we get the login event, then republished so we can hook it in to the UI.

Also - you may want to use sync expressions to avoid pulling unnecessary data, which will slow down the initial sync.

For updating views, we mostly use the Datastore publishers, e.g. 
```
Amplify.DataStore.publisher(for: User.self)
.compactMap { event in
                try? event.decodeModel(as: User.self)
            }
```
or to re-query the data store when changes happen, you can
```
Amplify.DataStore.publisher(for: User.self)
.flatMap { _ in
                Amplify.DataStore.query(User.self, <your predicates>)
            }
```

You can use combine's `debounce` and `throttle` to avoid slamming your UI, since these can get noisy when doing incremental syncs.

**Comment by lawmicha** [comment]
To recap, when the app is launched, DataStore will start syncing remote models to the local store. After DataStore has finished syncing and established the subscriptions, "ready" event would be sent. After this point, a query from the local store would result in data that is in sync with the remote store. 

1. On .ready event, mark the state as “ready” 
2. On items changed
    1. if "notReady”, incoming data is at a high rate due to syncing in progress. 
        1. if consistency over availability is required, do nothing/display “loading”
        2. if availability over consistency is required, perform a query and re-render the UI 
    2. If “ready”
        1. query for the full dataset, mark as “readyAndQueried”, re-render the UI
    3. if “readyAndQueried”
        1. apply the items changed to the data in memory, UI is partially re-rendered on each item applied.
        2. or ignore the items change and query for the full dataset, re-render the UI

In this [gist](https://gist.github.com/lawmicha/4a1d9afc60e1fc9d01911e9f27d0486f) (work in progress) i've represented the three states "notReady", "ready", and "readyAndQueried", and in those three states the app can take an appropriate action. For 2.iii.a. apply the items changed to the data in memory, can be done to an in-memory dictionary or the existing `post` array. If using a dictionary, you'll have to create an array to back the UI. Hopefully this answers some of the questions here.

**Comment by lawmicha** [comment]
> Also how do I query for a specific ID on the subscription? On the docs it says subscribe to a model but what if I have a model linked to another one? (1-many). I just want to subscribe for the ones that the specific user has

In this case, you would have to listen to all the events, decode the mutation event to the model and check for the field that you want to filter on.

**Comment by alionthego** [comment]
Why do I need to use amplify.DataStore.publisher API when the DataStore has hub even't for sync received?  Why not just intercept those events?  If I use the publishers then do I need to worry about stop starting them when the app enters background and foreground?  Honestly why not just have a working example for people to see?

**Comment by lawmicha** [comment]
Hi @alionthego, `DataStore.publisher` API is useful for providing a real-time user experience as described [here](https://docs.amplify.aws/lib/datastore/real-time/q/platform/ios/). The [hub events for DataStore](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/ios/) can be used as an indication that the sync process has completed and your app can perform a query to get the latest synced data. After the query, you may want to keep the query results up to date by applying the changes you get from the publisher. Alternatively you can use the publisher events as an indication that the data you have in memory is out-of-date and you can perform a new query to refresh the data. The `DataStore.publisher` is a Combine publisher that is established in memory so I believe you can leave it open when the app goes into background. Hopefully that answered some of your questions. Please let us know if something isn't clear or the [code snippet](https://gist.github.com/lawmicha/4a1d9afc60e1fc9d01911e9f27d0486f) above. If you're looking for a sample app, I know we have one in the works that show usage across multiple categories, including DataStore and I can make sure we follow up here once we release that.

**Comment by atierian** [comment]
To follow up, you can find example code in the sample project.
https://github.com/aws-amplify/amplify-ios-samples
