### ISSUE TITLE
App crashing after failure to query DataStore.

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#1388]
### Describe the bug

When loading an item from DataStore during regular operation, i.e .not initial sync, the app tripped over an assertion and crashed.

![130348808-9dc71b13-3559-4e86-867d-4730a2360966](https://user-images.githubusercontent.com/67764399/130350696-38d00d86-9048-4db4-b191-7ba1d8ed5ca8.png)

I've included the console log below.

Question: Is DataStore query thread-safe? Reason why I'm asking: In order to keep the GUI snappy, I'm preloading items with different threads. Hence, there could be many threads at the same time querying DataStore. 

### Steps To Reproduce

I can reproduce it 100%. So it's probably not threading related. I strongly suspect that's the old orphaned item issue, given the console error message (see below). I have ten of thousands of items spread across different tables in DataStore. So I guess in my scenario it's not unusual that DataStore operations will not complete, because the user turns the phone off.

Here are the steps to reproduce:
Prepare a scheme with n:m relationships, like so (a greatly simplified version of my actual scheme, slightly redacted):

```
type RxyZ @model @auth(rules: [{ allow: owner }])
{
  id: ID!
  caption: String!
  groups: [RxyVsGroupZ] @connection(keyName: "byRxy", fields: ["id"])
}

type RxyVsGroupZ @model(queries: null) @auth(rules: [{ allow: owner }])
@key(name: "byRxy", fields: ["rxyId", "groupId"])
@key(name: "byGroupA", fields: ["groupId", "rxyId"])
{
  id: ID!
  rxyId: ID!
  groupId: ID!
  rxy: RxyZ! @connection(fields: ["rxyId"])
  group: GroupZ! @connection(fields: ["groupId"])
}

type GroupZ @model @auth(rules: [{ allow: owner }])
{
  id: ID!
  name: String!
  description: String
  buyer: BuyerZ @connection(name: "LinkToGroups")
  rxys: [RxyVsGroupZ] @connection(keyName: "byGroupA", fields: ["id"])
}
```

Populate a database and run queries. The crash happens for me during a query for one of the "connection" items, i.e. `RxyVsGroupZ`. I suspect it has to be with either RxyZ or GroupZ being gone. I'll confirm this later.

### Expected behavior

Please give me an error messages instead of crashing the app. If you make it crash, at least provide exact information what item ID was the problem. Descriptive error messages would help a lot.

### Amplify Framework Version

77b932a3725ae1099aef422ba52f47639b3c6f27

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

5.3.0

### Xcode version

12.5.1

### Relevant log output

Amplify log doesn't contain anything. Here's the console log before the crash:

```
2021-08-22 10:40:36.337770+0200 WhatsLeft[14549:462080] [DataStore] Der Vorgang konnte nicht abgeschlossen werden. (Amplify.DataStoreError-Fehler 8.)
2021-08-22 10:40:36.338549+0200 WhatsLeft[14549:462080] [DataStore] Der Vorgang konnte nicht abgeschlossen werden. (Amplify.CoreError-Fehler 0.)
AmplifyPlugins/DataStoreListProvider.swift:61: Assertion failed: Failed to Query DataStore.
2021-08-22 10:40:36.338949+0200 WhatsLeft[14549:462080] AmplifyPlugins/DataStoreListProvider.swift:61: Assertion failed: Failed to Query DataStore.
```

Sorry for the German. I believe DataStore error 8 has something to do with orphaned items again. At least that's what I remember from the past.

### Device

iPhone-12 Simulator

### iOS Version

iOS 14.5

**Comment by anatomybook** [comment]
I can confirm that the problem was due to orphaned items once more.

Do you have any hints where I can catch the problem in the non-debug app, i.e. issue a delete request for the offending ID? This way I could make the app clean its database instead of me going through it via script. Eventually this won't scale anymore and I'd rather have to app clean after itself in case of orphaned items.

**Comment by lawmicha** [comment]
Hi @anatomybook, i've been trying to reproduce an orphaned children scenario and couldn't do this successfuly with the latest version of DataStore. The observe behavior I saw was that SQLite is pretty resilient to getting into a foreign key constraint issue. When I try to make a commit in various ways (directly using a DB viewer / in code with access to the SQLite adapter), it will successfully remove both the parent and child models or it will fail to commit such as 
```
An error occurred while committing the data: FOREIGN KEY constraint failed
```

When there is a change to the remote store such that there is a deleted parent data where a child row now points to a non-existent parent (or parent has `_deleted` true flag), the sync will fail to reconcile the child object with the foreign key constraint failed and not save the data to local store.

In regards to the issue you described, 

1. Do you have additional logs to what failed when that query happened?
2. You can also use the asynchronous version of lazy loading the associated model by calling `fetch` before accessing the elements. For example, for a post model with many comments:
```swift
post.comments?.fetch({ result in
      switch result {
      case .success:
          print("success")
          if let comments = post.comments?.elements {
              print("Got comments \(comments)")
          }
      case .failure(let error):
          print("\(error)")
      }
  })
```

This way, you can catch the failure and let the app continue to operate

**Comment by lawmicha** [comment]
Feel free to re-open with more recent experience if this is still an issue!
