### ISSUE TITLE
dyld: Library not loaded when using SPM

### ISSUE THREAD

**Issue by OliverNielsen** [aws-amplify/amplify-ios#1392]
### Describe the bug

Hello,

I have a project which had Amplify integration using Cocoapods. This worked fine.
I have now converted to Swift Package Manager and it works fine on simulator.

Unfortunately, when I try to run the app on device I get an error:
```
dyld: Library not loaded: @rpath/AWSCore.framework/AWSCore
  Referenced from: /private/var/containers/Bundle/Application/SOME_ID/XXX.app/Frameworks/ZZZ.framework/ZZZ
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/SOME_ID/XXX.app/Frameworks/ZZZ.framework/Frameworks/AWSCore.framework/AWSCore: code signature in (/private/var/containers/Bundle/Application/SOME_ID/XXX.app/Frameworks/ZZZ.framework/Frameworks/AWSCore.framework/AWSCore) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

The values "SOME_ID", "XXX" and "ZZZ" is to hide sensitive client data. Not the actual names. This is also why I cannot provide the actual project to you for testing.

The project is structured with a target and two frameworks.
It is only one of the frameworks (not the target!) which has the dependency to Amplify (e.i. is linked in the build phase "Link Binary With Libraries".
The target doesn't link in any way to Amplify beside having embedded the framework which has the Amplify dependency.

The Amplify frameworks linked is "Amplify", "AWSPluginsCore", "AWSAPIPlugin" and "AWSCognitoAuthPlugin".

I would love to hear some suggestions.

I have tried the "obvious" closing of Xcode and deleting `DerivedData`. This did not work unfortunately.

### Steps To Reproduce

```swift
1. Add "Amplify", "AWSPluginsCore", "AWSAPIPlugin" and "AWSCognitoAuthPlugin" as a SPM dependency
2. Run app on device
3. Crash
```

### Expected behavior

The app should successfully run

### Amplify Framework Version

1.13.3

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.4

### CLI version

0

### Xcode version

12.5.1

### Device

iPhone 12 Pro

### iOS Version

14.7.1

### Specific to simulators

No

**Comment by diegocstn** [comment]
@OliverNielsen did you manually migrate your project from Cocoapods to SPM or by using an automated tool like [cocoapods-deintegrate](https://github.com/CocoaPods/cocoapods-deintegrate)?

**Comment by atierian** [comment]
Thanks for the further information.
This can occur when Swift Package target dependencies are not added as products.
Here is an example of a working Package.swift file that should suite your needs.
```swift
// swift-tools-version:5.4
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

typealias Requirement = Package.Dependency.Requirement

enum Packages {
  enum AWS {
    static let PackageName = "AWSiOSSDKV2"
    static let PackageURL = "https://github.com/aws-amplify/aws-sdk-ios-spm"
    static let Requirement: Requirement = .upToNextMinor(from: "2.25.0")
    static let Package: Package.Dependency = .package(
      name: Packages.AWS.PackageName,
      url: Packages.AWS.PackageURL,
      Packages.AWS.Requirement)
  }
  enum Amplify {
    static let PackageName = "Amplify"
    static let PackageURL = "https://github.com/aws-amplify/amplify-ios"
    static let Requirement: Requirement = .upToNextMinor(from: "1.13.4")
    static let Package: Package.Dependency = .package(
      name: Packages.Amplify.PackageName,
      url: Packages.Amplify.PackageURL,
      Packages.Amplify.Requirement)
  }
}

let package = Package(
  name: "MyLibrary",
  platforms: [.iOS(.v14)],
  products: [
    .library(name: "MyLibrary", targets: ["MyLibrary"]),
  ],
  dependencies: [
    Packages.AWS.Package,
    Packages.Amplify.Package
  ],
  targets: [
    .target(
      name: "MyLibrary",
      dependencies: [
        .product(name: "Amplify", package: Packages.Amplify.PackageName),
        .product(name: "AWSCore", package: Packages.AWS.PackageName),
        .product(name: "AWSPluginsCore", package: Packages.Amplify.PackageName),
        .product(name: "AWSAPIPlugin", package: Packages.Amplify.PackageName),
        .product(name: "AWSCognitoAuthPlugin", package: Packages.Amplify.PackageName),
      ]),
    .testTarget(
      name: "MyLibraryTests",
      dependencies: ["MyLibrary"]),
  ]
)
```

Additionally here is a working example of a workspace with a Swift Package including the listed Amplify 
dependencies attached.

[1392.zip](https://github.com/aws-amplify/amplify-ios/files/7108129/1392.zip)

Please let us know if this helped.

**Comment by OliverNielsen** [comment]
Thank you for the response.

Unfortunately, I didn't get it to work. I am getting the same issue as described [here](https://github.com/aws-amplify/amplify-ios/issues/1392#issuecomment-905727398).

I decided to make a test project with my setup since I think it might result in some confusion.
In the test project, I have an app, and two dynamic frameworks.

- `AmplifyIssueTestProject` (The app)
- `AmplifyIssueTestProjectKit` (Dynamic framework)
- `AmplifyIssueTestProjectUIKit` (Dynamic framework)

I need the `Amplify` SDK to be linked with `AmplifyIssueTestProjectKit` since that is the only place I have interact with the SDK.
This works fine on simulator but will crash on device with the same error as described in the original message.


This isn't in the test project but I have tried adding a Swift Package, with the `Package.swift` file you wrote, and linked it to my `AmplifyIssueTestProjectKit`. Same experience, simulator runs fine, device crashes.

The only thing I haven't tried is replacing `AmplifyIssueTestProjectKit` with a Swift Package and move all my files into that. This is a huge task for this project and doesn't seem like the correct solution, since the structure/setup works perfectly fine with Firebase and various other SDK's.

Can you see what I am doing wrong here?

[AmplifyIssueTestProject.zip](https://github.com/aws-amplify/amplify-ios/files/7115935/AmplifyIssueTestProject.zip)

**Comment by Namedix** [comment]
@OliverNielsen Currently, we have the same problem in the project, did you manage to bring it to live?

**Comment by OliverNielsen** [comment]
@Namedix Unfortunately, no. I am waiting for response from the maintainers, so I had to stash the stuff I had for now.

**Comment by atierian** [comment]
Thanks for the follow up with more information @OliverNielsen.
We were able to replicate the issue you're describing and track it down to an issue with how Xcode handles dependencies and code signing.

Here is a [Swift forums post](https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953) that discusses the issue.
As well as two filed bugs ( [SR-13343](https://bugs.swift.org/browse/SR-13343) and [13345](https://bugs.swift.org/browse/SR-13345 )

One option would be separately adding the Swift package to your app's frameworks. However this is not an ideal solution because it will duplicate the frameworks, including them both in your application and your dynamic framework.

Another option you can explore is writing a build script that moves the frameworks from AmplifyIssueTestProject/Frameworks/AmplifyTestProjectKit.framework/Frameworks to AmplifyIssueTestProject/Frameworks.

**Comment by OliverNielsen** [comment]
@atierian Thank you for your response.

I will try to develop a script which moves the frameworks. Not sure when I will have time to try it out though.

Until Apple prioritises to fix the bugs in SPM, I would consider this closed.
Thanks for your help.

**Comment by atierian** [comment]
Thanks for your response @OliverNielsen.
We tested with Xcode 13 RC as well; unfortunately the issue persists.
We'll monitor this and update your issue if we see a fix come through in the future.

**Comment by 4brunu** [comment]
I have the same issue.
Did anyone developed a script that could share please?
Thanks
