### ISSUE TITLE
DataStore query predicate operator ne doesn't return expected results 

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-ios#1401]
### Describe the bug

Original amplify-flutter issue: https://github.com/aws-amplify/amplify-flutter/issues/823

Let's say I have table
```
| id    | str         |
| 1     | "name1"     |
| 2     | "name2"     |
| 3     | null        |
```
When I run this query 
```java
let sink = Amplify.DataStore.query(MyModel.self, where: MyModel.keys.str.ne("name2")).sink {
    if case let .failure(error) = $0 {
        print("Error - \(error.localizedDescription)")
    }
}
receiveValue: { result in
    print("MyModel: \(result)")
}
```
I'm expecting the query returns results:
``` json
[
  {
    "id": "1",
    "str": "name1"
  },
  {
    "id": "3",
    "str": null
  }
]
```
But it returned only
```json
[
  {
    "id": "1",
    "str": "name1"
  }
]
```
Rows with `null` somehow got excluded.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. query with described query predicated on a column that has null values
2. Observe the results
```

### Expected behavior

When query with predicate `MyModel.keys.str.ne("name2")` the result should also include `MyModel.keys.str.eq(null)`

### Amplify Framework Version

1.13.3

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5

### CLI version

5.3.0

### Xcode version

12.5.1

### Device

iPhone 12 simulators

### iOS Version

iOS 14.5

**Comment by diegocstn** [comment]
This behavior is dictated by the storage adapter implementation currently used by DataStore, SQLite :) We should verify whether all platforms behave consistently and decide how to address this.

**Comment by HuiSF** [comment]
Discussion of unifies API behavior cross platform: https://github.com/aws-amplify/amplify-android/issues/1468#issuecomment-912120703

**Comment by undefobj** [comment]
Closing as we are tracking platform alignment internally
