### ISSUE TITLE
Can I change serverSideEncryption and pointInTimeRecovery after project already running in production environment?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1408]
I have a running production amplify project.  I didn't know there was point in time database recovery and server side encryption options when I set up the project.   Is it possible to add this in a running production environment without losing data?

My understanding from another post is that we should go to the parameters file in amplify/backend/api/<projectName>/parameters.json and modify to look like below:

{
    "AppSyncApiName": "<api-name>",
    "DynamoDBBillingMode": "PAY_PER_REQUEST",
    "DynamoDBEnableServerSideEncryption": "false",
    "DynamoDBEnablePointInTimeRecovery": "true"
}

So my question is if I add the line "DynamoDBEnablePointInTimeRecover": "true" which doesn't exist now and change the bool for DynamoDBEnableServerSideEncryption": to "true" will that work?  And will any data be lost in the process?

**Comment by ameter** [comment]
closing in favor of this ticket with the CLI team:
https://github.com/aws-amplify/amplify-cli/issues/8104
