### ISSUE TITLE
Amplify Auth hostedUI - On reinstall with different configuration

### ISSUE THREAD

**Issue by royjit** [aws-amplify/amplify-ios#1410]
### Describe the bug

Amplify.Auth.fetchAuthSession is showing the Apple dialog if we reinstall the app with different configuration

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Install an app with HostedUI configuration
2. Sign in to the app
3. Overwrite the app with a different userpool configuration
4. Call Amplify.Auth.fetchAuthSession 
5. See the Apple dialog showing up
```

### Expected behavior

Amplify.Auth.fetchAuthSession should not show the Apple dialog

### Amplify Framework Version

Latest

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.4

### CLI version

NA

### Xcode version

12.4

### Device

iPhone Simulator

### iOS Version

IOS 12

**Comment by haverchuck** [comment]
dander11/amplify-flutter#848

**Comment by haverchuck** [comment]
dander11/aws-amplify/amplify-flutter#848

**Comment by royjit** [comment]
I was able to reproduce the issue. 

We rely on AWSMobileClient to get the tokens and credentials. The root cause lies in the fact that :

*  AWSMobileClient depends on a single method getSession inside AWSCognitoAuth for signing in and getting token
* Amplify (AWSMobileClient internally) sees that the user is signed in (because we use the same keychain value) and proceed to get the token for a “signedIn” user.

Internally, when `Amplify.Auth.fetchAuthSession` is called the following happens:

1. Amplify sees that the user is signed In , because of the related issue - https://github.com/aws-amplify/amplify-ios/issues/1016
2. Amplify proceeds to get the token for the signed in user - [Code Ref](https://github.com/aws-amplify/amplify-ios/blob/6b1395409f6f763ba32030250ef4b57e252b332b/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Dependency/AuthorizationProviderAdapter%2BSignedInSession.swift#L40)
3. AWSMobileClient proceeds to get the session from Cognito - [Code Ref](https://github.com/aws-amplify/aws-sdk-ios/blob/e5c21d5b8b042e55e51f8f184a4e06915648d285/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift#L852)
4. Cognito SDK does not find the username for the app client id - [Code Ref](https://github.com/aws-amplify/aws-sdk-ios/blob/e5c21d5b8b042e55e51f8f184a4e06915648d285/AWSCognitoAuth/AWSCognitoAuth.m#L439)
5. Cognito SDK proceed to launch the sign in UI - [Code Ref](https://github.com/aws-amplify/aws-sdk-ios/blob/e5c21d5b8b042e55e51f8f184a4e06915648d285/AWSCognitoAuth/AWSCognitoAuth.m#L483)

**Comment by royjit** [comment]
Next step: Possible fix is to use different APIs for getToken, ie Amplify.Auth should use an api that **DO NOT** automatically sign in when `getToken` api is called.

**Comment by royjit** [comment]
Draft PR to handle getSession without launching signIn view - https://github.com/aws-amplify/aws-sdk-ios/pull/3764/files

**Comment by royjit** [comment]
Adding namespace to the AWSMobileClient to fix the issue. Previous PR was deleted since it require a lot of change in the underlying SDK - https://github.com/aws-amplify/aws-sdk-ios/pull/3853

**Comment by thisisabhash** [comment]
This was released in [https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.27.2](https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.27.2).
