### ISSUE TITLE
Amplify.API.query with Request .list() and .paginatedList() falis with FieldUndefined and not using pluralName of the table from generated Table+Schema.swift

### ISSUE THREAD

**Issue by maremoto** [aws-amplify/amplify-ios#1419]
### Describe the bug

When trying to list a full table with Amplify.API and the table has a name that is a plural, the generated code in Tablename+Schema.swift recognizes that the plural name is the same as the table and declares it properly:

Example, tablename = "Wishes", then at generated code Wishes+Schema.swift you see:

``` 
model.pluralName = "Wishes"
```

But when using IOS SDK and executing an Amplify.API.query call with request .list() or .paginatedList() it fails with this error:

```
failure(GraphQLResponseError<Array<Posts>>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Validation error of type FieldUndefined: Field \'**listWishess**\' in type \'Query\' is undefined @ \'**listWishess**\'", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: nil, extensions: nil)]
```

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create a table (@model) with a plural name e.g. "Wishes"
2. Using IOS SDK try to list the table with Amplify.API.query function
3. See error
```

### Expected behavior

Working properly and using pluralName var.

### Amplify Framework Version

1.12.1

### Amplify Categories

API

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

5.5.0

### Xcode version

12.5

### Relevant log output

```shell
failure(GraphQLResponseError<Array<Posts>>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Validation error of type FieldUndefined: Field \'listWishess\' in type \'Query\' is undefined @ \'Wishess\'", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: nil, extensions: nil)]
```

### Is this a regression? (i.e. was this working before a version upgrade)

No

### Device

IPoneSE and Simulator

### iOS Version

IOS 13.0

### Additional context

```graphql
type Wishes @model 
@key(name: "byUsers", fields: ["idUser"]) 
@auth(rules: [{allow: owner}, 
{allow: private, operations: [create]}]) {

  id: ID!
  date: AWSDateTime!
  idUser: ID!
  ev: ID! 
  deprecated: Boolean!  # needed for logical deletion, as no real deletion exists
  owner: String         # needed as current IOS SDK do not insert it
}

```

**Comment by lawmicha** [comment]
Hi @maremoto, thanks for opening this issue, it looks like the library is not compatible with the latest Amplify CLI provisioning of the list query. The investigation can be followed here: https://github.com/aws-amplify/amplify-cli/issues/8350 The workaround right now may be to downgrade to use the provisioning done by the CLI before 5.3.0 which will generate a different list query name, which the library is aligned on.

**Comment by sebsto** [comment]
my workaround at the moment is to comment out the `.pluralize()`call at line 19 here 
https://github.com/aws-amplify/amplify-ios/blob/v1.14.0/AmplifyPlugins/Core/AWSPluginsCore/Model/Support/ModelSchema%2BGraphQL.swift#L19

**Comment by lawmicha** [comment]
An easier way to bypass this is to set the feature flag to false

> The feature flag to turn off this pluralization is features.graphqltransformer.improvepluralization in your project's amplify/cli.json file.

https://github.com/aws-amplify/amplify-cli/issues/8350#issuecomment-933757747

**Comment by lawmicha** [comment]
please track this issue for the same resolution https://github.com/aws-amplify/amplify-ios/issues/1443
