### ISSUE TITLE
iOS Hosted UI *Still Not Working*

### ISSUE THREAD

**Issue by meavydev** [aws-amplify/amplify-ios#1424]
### Describe the bug

Please see https://github.com/aws-amplify/amplify-ios/issues/1276
It still fails the same way when trying to use hosted UI, so I'm not sure how you closed it...

I waited to try with the latest libs, just in case.
![Screenshot 2021-09-16 at 12 41 10](https://user-images.githubusercontent.com/9558404/133606021-bf26e565-b921-47da-a742-04fe52097d11.png)
![Screenshot 2021-09-16 at 12 40 57](https://user-images.githubusercontent.com/9558404/133606049-5c047450-044f-45e3-a310-ad55bc85e39c.png)
![Screenshot 2021-09-16 at 12 40 41](https://user-images.githubusercontent.com/9558404/133606073-4202cadb-f15e-445f-88c4-199770da8d1c.png)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
Try logging in with :
    func webSignIn() {
            _ = Amplify.Auth.signInWithWebUI(presentationAnchor: window) { result in
                switch result {
                case .success:
                    print("Signed in")

                case .failure(let error):
                    print(error)
                }
            }
    }
```

### Expected behavior

Login works with hosted UI.

### Amplify Framework Version

2.25.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5

### CLI version

1.13.4

### Xcode version

12.5.1

### Relevant log output

```shell
Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value
```

### Device

iPhone12 Pro Max simulator

### iOS Version

14.5

### Specific to simulators

No

**Comment by meavydev** [comment]
Actually the full code is:
`    private var window: UIWindow {
        guard
            let scene = UIApplication.shared.connectedScenes.first,
            let windowSceneDelegate = scene.delegate as? UIWindowSceneDelegate,
            let window = windowSceneDelegate.window as? UIWindow
        else { return UIWindow() }
        
        return window
    }

    func webSignIn() {
            _ = Amplify.Auth.signInWithWebUI(presentationAnchor: window) { result in
                switch result {
                case .success:
                    print("Signed in")

                case .failure(let error):
                    print(error)
                }
            }
    }`

**Comment by meavydev** [comment]
Also tried with the code from Amplify for IO13+:
`func signInWithWebUI() -> AnyCancellable {
    Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!)
        .resultPublisher
        .sink {
            if case let .failure(authError) = $0 {
                print("Sign in failed \(authError)")
            }
        }
        receiveValue: { _ in
            print("Sign in succeeded")
        }
}`

**Comment by meavydev** [comment]
It isn't being caused by a missing WebDomain in the OAuth section, as mentioned in #1276 
Our awsconfiguration.json looks like this (with actual values replaced by ...)
`{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
   "CredentialsProvider":{
      "CognitoIdentity":{
         "Default":{
            "PoolId":"...",
            "Region":"..."
         }
      }
   },
   "CognitoUserPool":{
      "PoolId":"...",
      "AppClientId":"...",
      "AppClientSecret":"...",
      "Region":"..."
   },
   "Auth":{
      "OAuth":{
         "WebDomain":"...",
         "AppClientId":"...",
         "AppClientSecret":"...",
         "SignInRedirectURI":"...",
         "SignOutRedirectURI":"...",
         "Scopes":[
            "openid",
            "email"
         ]
      }
   }
}`

**Comment by royjit** [comment]
`awsconfiguration.json` is used by the legacy SDK AWSMobileClient. Can you please make sure that your `amplifyconfiguration.json` has the required parameters?

**Comment by meavydev** [comment]
Yes it does as the contents are identical...

**Comment by meavydev** [comment]
I'm assuming that  signIn(username: username, password: password) uses the same JSON configuration and changing to this rather than singInWithWebUI() works, so hosted UI is definitely broken.
Before you ask, we also have the plist changes.

**Comment by lawmicha** [comment]
Hi @meavydev, can you clarify, HostedUI not working at all, right? If that's the case, then there may be a configuration issue. 

Here's the doc for parameters required when using your own configuration: https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios/ we should definitely take this opportunity to improve it once we are able to identify what configuration is mismatched.

To get a working HostedUI backend and configuraiton, you can follow these steps: https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios/ It will also help with cross checking against your current configuration/backend set up.

The image with the AWSMobileClient crash at 570 corresponds to https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift#L570 . There seems to be some confusion around which file should be used, could you provide the configuration code that you are doing? `amplifyconfiguration.json` should be used with Amplify. You can make sure by deleting `awsconfiguration.json`.

**Comment by meavydev** [comment]
I don't have permission to run Amplify to do the push, but I can say that the hosted UI works fine from Android and as I said using signIn works fine on iOS.
I don't have any confusion about JSONs, as I said that the contents are identical.

**Comment by lawmicha** [comment]
The same configuration works on Android but not iOS? Can you show us the configuration for `amplifyconfiguration.json`? The [doc here](https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios/) shows the structure of `auth.plugins.awsCogntioAuthPlugin.Auth.Deafult.OAuth`. If your `amplifyconfiguration.json` is the same as the `awsconfiguration.json` you mentioned earlier then this looks incorrect:
```
"Auth":{
      "OAuth":{
```

Might need to update it to
```
"Auth":{
    "Default": {
         "OAuth":{
```

**Comment by meavydev** [comment]
Damn... that was it.
Shame the error wasn't more useful ;) 
The Android app is using the AWSConfig JSON BTW.
