### ISSUE TITLE
Very bad performance due to date decoding

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#1428]
### Describe the bug

Technically speaking this is not really a bug, but merely an observation. Nevertheless, it's very annoying as in the presence of many items, operations take forever.

In my case initial sync takes about a minute - which is user waiting for that long for everything to be ready?

For example consider this screenshot I obtained by just randomly pausing initial sync. Two threads busy doing date operations?! My point is that taking screenshots like this isn't hard, because it's almost always busy decoding dates.

![Screenshot 2021-09-18 at 14 23 33](https://user-images.githubusercontent.com/67764399/133889097-bf29d06f-6d9c-4ff4-a9c5-90e62740135a.png)

Another screenshot, that I obtained when going through a list of items. Again, it's almost always busy decoding the date. Given that the decoding happens in the inner loop, I wonder whether something can be done to accelerate the process?

![Screenshot 2021-09-18 at 14 46 14](https://user-images.githubusercontent.com/67764399/133889279-4b9a5d06-5224-48b3-8987-69978dcc6540.png)

### Steps To Reproduce

Load up a database with many items and observe where the time is spent during initial sync or general operation, such as going through lists.

Another good one is sorting. Make a simple model containing a string and AWSDateTime. Make several hundred objects and sort them. Observe that sorting according to the string is much faster than using AWSDateTime.

### Expected behavior

I expect the date decoding not to slow down my app significantly.

### Amplify Framework Version

6dca41c8620c27d9da2749187957808a19cdafb3

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)

### CLI version

5.3.0

### Xcode version

12.5.1

### Is this a regression? (i.e. was this working before a version upgrade)

Performance was always bad, as far as I recall.

### Device

iPhone 12 Pro Max, but same everywhere

### iOS Version

iOS 14.8

### Specific to simulators

no

**Comment by lawmicha** [comment]
Thanks for bringing this to our attention @anatomybook , we'll look into testing the performance of decoding DateTime and seeing if we can optimized this. In JS, the datetime's are stored as strings in the local store and are not decoded until the caller queries for them. We'll look into taking a similar approach after getting a baseline of the performance. Every model would be affected by this since it's each model contains `createdAt` and `updatedAt` system level fields.

**Comment by brennanMKE** [comment]
@anatomybook We have identified a potential cause for the added cost of this sync process. See the issue linked below.

https://github.com/aws-amplify/amplify-ios/issues/1734

**Comment by anatomybook** [comment]
Thank you very much. I can't wait for the patch to arrive!

**Comment by atierian** [comment]
Hey @anatomybook  we've including [significant performance improvements](https://github.com/aws-amplify/amplify-ios/pull/1760) for date decoding / formatting in [Amplify 1.26.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.26.0) released yesterday.

We are still exploring other areas in which we can improve sync performance.

**Comment by anatomybook** [comment]
Thank you very much!!
