### ISSUE TITLE
Guest Access not working as it should?

### ISSUE THREAD

**Issue by Leinadzet** [aws-amplify/amplify-ios#1447]
### Describe the bug

I want to retrieve a unique Identity ID from Cognito to identify my users. With that ID I would like to store data for the users without signing them up. So if a user stores a Todo, the would look like this:

model ToDo{

userID: String
id: ID
text: String
description: String 

}

reading the docs here: https://docs.amplify.aws/lib/auth/guest_access/q/platform/ios/ I would expect to receive a unique identity per device per app for my user, which does not change. 

I would like to move my app from Firebase to AWS and this is the missing piece to store the data. 

If there is another way - please let me know. The idea is to store user specific content and also only retrieve this content for each specific user. I would do that with this unique identity ID. 

### Steps To Reproduce

1. Start with the auth process here: https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/ 
2. Then adapt it to Guest Access: https://docs.amplify.aws/lib/auth/guest_access/q/platform/ios/ 
3. Try to retrieve credentials like so: https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios/

If I then call Amplify.Auth.fetchAuthSession I receive _Fetch auth session failed with error - AuthError: There is no user signed in to retrieve user sub_

and 

_Recovery suggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession_

The docs say "That's it! Now as long as you are online, you will automatically gain guest credentials (which are then cached for offline use as well)." so I thought no signup necessary?

### Expected behavior

Retrieving a unique identity ID per device per user to store data for that user. 

### Amplify Framework Version

1.13.4

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.4

### CLI version

6.0.0

### Xcode version

12.5. (12E262)

### Relevant log output

```shell
2021-10-02 09:33:25.082879+0200 DataModelTest[10267:560165] [Amplify] Adding plugin: AWSCognitoAuthPlugin.AWSCognitoAuthPlugin)
2021-10-02 09:33:25.084039+0200 DataModelTest[10267:560165] [Amplify] Configuring
2021-10-02 09:33:25.084305+0200 DataModelTest[10267:560165] [Amplify] Configuration: nil
2021-10-02 09:33:25.117970+0200 DataModelTest[10267:560165] [Amplify] No plugin found for configuration key `awsAPIPlugin`. Add a plugin for that key.
2021-10-02 09:33:26.368246+0200 DataModelTest[10267:562321] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
Fetch auth session failed with error - AuthError: There is no user signed in to retreive user sub
Recovery suggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession
```

### Device

iPhine 12 Simulator 

### iOS Version

14.5.

**Comment by royjit** [comment]
FetchAuthSession returns different types of credentials, the error that you see is for user sub, but if you try to retrieve the identityid/credentials, you will be able to get it. https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios/

Can you try the following code:

```swift
import AWSPluginsCore

Amplify.Auth.fetchAuthSession { result in
    do {
        let session = try result.get()

        // Get user sub or identity id
        if let identityProvider = session as? AuthCognitoIdentityProvider {
            let identityId = try identityProvider.getIdentityId().get()
            print("Identity id \(identityId)")
        }

        // Get aws credentials
        if let awsCredentialsProvider = session as? AuthAWSCredentialsProvider {
            let credentials = try awsCredentialsProvider.getAWSCredentials().get()
            print("Access key - \(credentials.accessKey) ")
        }

    } catch {
        print("Fetch auth session failed with error - \(error)")
    }
}
```

**Comment by Leinadzet** [comment]
Hey Roy,

thanks for taking a look.

I added your snippet to an onAppear function in my ContentView and it seems to work. 

What I now get is an identity id and an access key. Can you confirm that this is the unique identity per device per app? So this should be the unique identity ID described in the docs?

Thanks

Daniel

**Comment by royjit** [comment]
PR change to update the documentation - https://github.com/aws-amplify/docs/pull/3764

**Comment by Leinadzet** [comment]
Awesome thanks! Just saw the update.
