### ISSUE TITLE
App crashes when logging out during initial sync.

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#1459]
### Describe the bug

When logging out during initial sync, the app may crash.

I reported [here](https://github.com/aws-amplify/amplify-ios/issues/1458) that my initial sync doesn't stop anymore. So I tried to log out of my account into another one to see if the issue persists. The app crashed and I caught it in the debugger.

```
DataStore cleared
DataStore stopped
2021-10-09 00:17:07.961499+0200 WhatsLeft[29087:8904078] [logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /Users/ben/Library/Developer/CoreSimulator/Devices/022BC081-DF16-46BD-B269-24A2644B6C3C/data/Containers/Data/Application/059DD4E4-8DE2-446E-86CF-9C3530DACF6A/Documents/WhatsLeft.db
2021-10-09 00:17:07.961639+0200 WhatsLeft[29087:8904078] [logging] invalidated open fd: 9 (0x11)
AmplifyPlugins/StorageEngineAdapter+SQLite.swift:261: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2021-10-09 00:17:07.965681+0200 WhatsLeft[29087:8904099] AmplifyPlugins/StorageEngineAdapter+SQLite.swift:261: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

```

![Screenshot 2021-10-09 at 00 23 06](https://user-images.githubusercontent.com/67764399/136630852-913c51a0-2fca-4152-a4ed-ab01c1ac830d.png)

![Screenshot 2021-10-09 at 00 24 54](https://user-images.githubusercontent.com/67764399/136630932-c7832471-07dd-4307-83d9-7f9f54684d73.png)

### Steps To Reproduce

During initial sync, log out of the app, i.e. call

```swift
Amplify.Auth.signOut
```

### Expected behavior

I expect my app not to crash under any circumstance.

### Amplify Framework Version

2339458fc86f6a5d1d866d92146fea1f8b3fadf6

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)

### CLI version

6.1.1

### Xcode version

12.5.1

### Is this a regression? (i.e. was this working before a version upgrade)

Unsure, I never really tried to log out during initial sync.

### Device

observed on simulator.

### iOS Version

15

### Specific to simulators

don't know

**Comment by thisisabhash** [comment]
Hello, 
I tried to reproduce the issue but couldn't. Here are the steps I followed :
- Setup Datastore, API and Auth Plugins. Launch the app. Sign up a user. Save 100 Todo items using `Datastore.save` and let it sync. Clear datastore using `clear()`.
- Launch the app. Sign in the user and call `Datastore.start()` to start sync. Call `Amplify.Auth.signout()` during sync. 

Could you please share your reproduction steps and `schema.graphql` file so that I can have a similar reproduction path?

**Comment by anatomybook** [comment]
Hello @thisisabhash ,

it's been a while. I tried to reproduce it, but couldn't manage anymore. Perhaps it was related to [this](https://github.com/aws-amplify/amplify-ios/issues/1458) issue and only occurred when there were orphaned items around. I'm not sure, since I can't verify this anymore.

Can @egonomee-katma still reproduce this?

**Comment by lawmicha** [comment]
Hi @anatomybook this has been released in this has been released in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.22.0 please let us know if you have any issues
