### ISSUE TITLE
codes for authError Errors

### ISSUE THREAD

**Issue by eyadmask** [aws-amplify/amplify-ios#1473]
### Is your feature request related to a problem? Please describe.

Just wondering if there a specific code posting to the type of AuthError returned by  (Amplify.Auth)...for cases like the below  :

- when the user submit the wrong username (one that does not exists on Cognito )  using the API (Amplify.Auth.resetPassword) , the error returned is  something like  (....Username/client id combination not found..) which is of course a description not a unique error code making it difficult to be used  for invoking different UI .. 

### Describe the solution you'd like

I think there should be some kind of error codifying ...it will make error handling better for both developers and end users

### Describe alternatives you've considered

alternatively .. of course we can check against the AuthError Description but I guess this is so risky as the description can change anytime 

### Is the feature request related to any of the existing Amplify categories?

Auth

**Comment by lawmicha** [comment]
Amplify.Auth.resetPassword calls down into Cognito's [ForgotPassword](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html) action. When you get AuthError from Amplify, you can check the underlying error as `AWSCognitoAuthError`. 

1. For a user that hasn't been signed up yet, Cognito returns
```
{"__type":"UserNotFoundException","message":"Username/client id combination not found."}
```
This can be checked in code using the underlying error
```swift
Amplify.Auth.resetPassword(for: username) { result in
        do {
            let resetResult = try result.get()
            switch resetResult.nextStep {
            case .confirmResetPasswordWithCode(let deliveryDetails, let info):
                print("Confirm reset password with code send to - \(deliveryDetails) \(info)")
            case .done:
                print("Reset completed")
            }
        } catch {
            print("Reset password failed with error \(error)")
            if let authError = error as? AuthError,
               let cognitoAuthError = authError.underlyingError as? AWSCognitoAuthError {
                print(cognitoAuthError)
                switch cognitoAuthError {
                case .userNotFound:
                    print("User not found")
```


2. User has signed up already, but not yet confirmed.

{"__type":"InvalidParameterException","message":"Cannot reset password for the user as there is no registered/verified email or phone_number"}
```
Check for `AWSCognitoAuthError.invalidParameter`

**Comment by lawmicha** [comment]
Please let us know if this works for you. We should update this section of the documentation regarding `AWSCognitoAuthError` https://docs.amplify.aws/lib/auth/password_management/q/platform/ios/#reset-password
