### ISSUE TITLE
[DataStore] Cannot create SQLite table with name that is SQL keyword

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-ios#1477]
### Describe the bug

Original issue: https://github.com/aws-amplify/amplify-flutter/issues/968

Testing schema:

```graphql
type Contact @model {
  id: ID!
  name: String!
  email: String!
  relationship: String
  groups: [ContactGroup] @connection(keyName: "byContact", fields: ["id"])
}

type Group @model {
  id: ID!
  name: String!
  contacts: [ContactGroup]! @connection(keyName: "byGroup", fields: ["id"])
}

type ContactGroup
  @model
  @key(
    name: "byContact"
    fields: ["contactId", "groupId"]
    queryField: "groupsByContact"
  )
  @key(
    name: "byGroup"
    fields: ["groupId", "contactId"]
    queryField: "contactsByGroup"
  ) {
  id: ID!
  contactId: ID!
  groupId: ID!
  contact: Contact! @connection(fields: ["contactId"])
  group: Group! @connection(fields: ["groupId"])
}
```

When creating SQLite table for model `ContactGroup`, amplify-ios generates below SQL command:

```sql
create table if not exists "ContactGroup" (
  "id" text primary key not null,
  "contactId" text not null,
  "groupId" text not null,
  foreign key("contactId") references Contact("id")
    on delete cascade
  foreign key("groupId") references Group("id")
    on delete cascade
);
```

Note that `Group` is a SQL reserved keyword,. This causes below error:

```
near "Group": syntax error in "create table if not exists "ContactGroup" (
  ...
```

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

In generated SQL command, all table name should be wrapped with back-ticks to ensure SQL keyword can be used as table name.

### Amplify Framework Version

1.15.2

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

6.3.1

### Xcode version

13.0

### Device

iPhone 13 simulators

### iOS Version

iOS 15

**Comment by diegocstn** [comment]
Released in [Amplify v1.18.2 ](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.18.2)
