### ISSUE TITLE
API Category - Separate protocol for Model based GraphQL

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#148]
I was thinking of adding each Protocol conformance in its own file, so `Model`-based and `GraphQLRequest`-based APIs are defined and implemented in isolation. Thoughts?

_Originally posted by @drochetti in https://github.com/aws-amplify/amplify-ios/pull/133_

**Comment by jamesonwilliams** [comment]
I have had this thought, as well.

Right now in the Android code base, we have this data modeling stuff, in the core library. Then, in API and in DataStore, we expose APIs that use it.

So right now, data modeling is a cross-cutting concern to Amplify. But, maybe it should be more tightly contained.

In practice, our data models are tightly architecturally coupled to AppSync features. So, the Data Modeling stuff is, in actuality, more like something that belongs in (a new version of) the AppSync SDK.

**Comment by lawmicha** [comment]
> I have had this thought, as well.
> 
> Right now in the Android code base, we have this data modeling stuff, in the core library. Then, in API and in DataStore, we expose APIs that use it.
> 

in iOS, i believe this is the same, AmplifyCore contains Model related classes while API and DataStore exposes ways to use it. 

> So right now, data modeling is a cross-cutting concern to Amplify. But, maybe it should be more tightly contained.
> 

> In practice, our data models are tightly architecturally coupled to AppSync features. So, the Data Modeling stuff is, in actuality, more like something that belongs in (a new version of) the AppSync SDK.

my current thinking is that AppSync SDK does delta sync and all of the graphQL functionalities, so AWS's implementation of API Plugin and DataStore would essentially solve the same use cases and be the replacement it for new customers.

My overall goal for API plugin, considering that it is tightly couple to Amplify GraphQL Transform and AppSync service, is that we provide the tools necessary, decorators, Model class for deserialization, that developers can use based on their use case defined by their schema and directives that they used.

**Comment by lawmicha** [comment]
i'm running pass all of the issues i've opened and seeing what can be closed, i think this issue can be closed for the API Plugin work that is on-going in general, and dicussion can continue else where, and thanks for your input here
