### ISSUE TITLE
Getting this error Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-3000 "(null)"

### ISSUE THREAD

**Issue by parthmodi605** [aws-amplify/amplify-ios#1492]
### Getting above error when trying to sign in using this function 
Amplify.Auth.signInWithWebUI(for: .facebook, presentationAnchor: self.view.window!) { result in
            switch result {
            case .success:
                print("Sign in succeeded")
            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }
        
        
I have also set amplifyconfiguration.json according to https://github.com/aws-amplify/amplify-ios/issues/664

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "",
                            "Region": ""
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "",
                        "AppClientId": "",
                        "AppClientSecret": "",
                        "Region": ""
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "",
                            "AppClientId": "",
                            "AppClientSecret": "",
                            "SignInRedirectURI": "myapp://callback/",
                            "SignOutRedirectURI": "myapp://signout/",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "loginMechanisms": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}

Issue faced : 

Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: Root/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-3000 "(null)" UserInfo={error=invalid_request: Bad id_token issuer https://www.facebook.com}  

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
I have followed steps provided in this docs for Facebook

https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios/
```

### Expected behavior

according to this doc it should have worked https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios/

### Amplify Framework Version

1.15.3

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

6.3.1

### Xcode version

13.0

### Is this a regression?

No

### Device

iphone8 - simulator

### iOS Version

15.0

**Comment by zalihm** [comment]
same issue here on Facebook , working perfect with google

**Comment by RoustamManookian** [comment]
Same issue on signInWithWebUI for google

`Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: window){result in
            switch result {
            case .success:
                print(#file + " - Line# \(#line)")
                print("Signed in")
                
            case .failure(let error):
                print(#file + " - Line# \(#line)")
                print(error)
            }
        }`

**Comment by RoustamManookian** [comment]
In my case
I had a lamda function trigger on signUp which has to add the new user with username into the RDB, and there was a unique username conflict.
So the signing in action was not completed

**Comment by royjit** [comment]
@parthmodi605 Could you please check the solution posted here - https://github.com/aws-amplify/amplify-js/issues/9264#issuecomment-977060126

@RoustamManookian Looks like the signUp lambda failed, can you check if the lambda is working properly?

**Comment by Sancho66** [comment]
> Same issue on signInWithWebUI for google
> 
> `Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: window){result in switch result { case .success: print(#file + " - Line# (#line)") print("Signed in")
> 
> ```
>         case .failure(let error):
>             print(#file + " - Line# \(#line)")
>             print(error)
>         }
>     }`
> ```
> 
> AuthError: Unexpected error occurred with message: An unknown error occurred Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at: file: /Users/a1/Library/Developer/Xcode/DerivedData/SCS-chczusrgjwqpnjadpdxjuszmwpnx/SourcePackages/checkouts/amplify-ios/Amplify/Categories/Auth/Error/AuthError.swift function: recoverySuggestion line: 80 Caused by: Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-3000 "(null)" UserInfo={error=invalid_request: PreSignUp failed with error ERROR: . }

I get the same error when I try to signin with amplify and google on flutter : 
```
Future<void> signInWithSocialWebUI(AuthProvider provider ) async {
    try {
      //Amplify.Auth.signOut();
      final result = await Amplify.Auth.signInWithWebUI(provider: AuthProvider.google);
      print('Result: $result');
    } on AmplifyException catch (e) {
      print(e.message);
    }
  }
```
`The operation couldn’t be completed. (com.amazon.cognito.AWSCognitoAuthErrorDomain error -3000.)`
 Is the issue resolved ?

**Comment by ruisebas** [comment]
Hi @Sancho66,

I see you also created https://github.com/aws-amplify/amplify-flutter/issues/1920.  Given that you are using Flutter, that sounds like the right place to follow up on your issue.

Thanks
