### ISSUE TITLE
Getting this issue, "Fetching identity id on another thread failed. Please retry by calling getIdentityId() method" when signing with apple using AWS federation Api 

### ISSUE THREAD

**Issue by parthmodi605** [aws-amplify/amplify-ios#1493]
Getting this issue when signing with apple using AWS federation Api

 func getJWT(Token: String) {
               
           AWSMobileClient.default().initialize { (userState, error) in
                   if let userState = userState {
                       print("userState at init " + userState.rawValue)
                   } else if let error = error {
                       print(error.localizedDescription)
                   }
               }
               
           AWSMobileClient.default().federatedSignIn(providerName: IdentityProvider.apple.rawValue, token: Token) { (userState, passedError)  in
                   if let error = passedError {
                       print("Federated Sign In failed: \(error)")
                   }else{
                       print("Federated sign in succeeded: \(String(describing: userState))")
                           self.fetchIdentity()
                   }
               }
           }
    
    func fetchIdentity(){
        AWSMobileClient.default().getIdentityId().continueWith { task in
            if let error = task.error {
                print("Get IdentityId error: \(error)")
            }
            if let result = task.result {
                print("Identity id: \(result)")
                AWSMobileClient.default().getAWSCredentials { (credentials, error) in
                    if let error = error {
                        print("\(error.localizedDescription)")
                    } else if let credentials = credentials {
                        print("Access Key : \(credentials.accessKey)")
                        print("Secret Key : \(credentials.secretKey)")
                        print("Session Key : \(credentials.sessionKey ?? "")")
                    }
                }
                // Need to get JWT here
            }
            return nil
        }
    }

Issue faced :
userState at init signedIn
Federated sign in succeeded: Optional(AWSMobileClient.UserState.signedIn)
Get IdentityId error: identityIdUnavailable(message: "Fetching identity id on another thread failed. Please retry by calling getIdentityId() method.")

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
I have followed steps provided in this docs for Facebook

https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/#set-up-sign-in-with-apple
```

### Expected behavior

according to this doc it should have worked https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/#set-up-sign-in-with-apple

### Amplify Framework Version

1.15.3

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

6.3.1

### Xcode version

13.0

### Is this a regression?

No

### Device

iPhone SE 

### iOS Version

14.6

**Comment by atierian** [comment]
Closing this as a duplicate in favor of https://github.com/aws-amplify/amplify-ios/issues/1822.
Please follow along and post any updates you have there. Could you please run this with the thread sanitizer enabled and post any relevant logs. Thanks.
