### ISSUE TITLE
I am trying to do email verification , for that i am trying to get access token but i am getting below error.

### ISSUE THREAD

**Issue by prakash-ikabit** [aws-amplify/amplify-ios#1495]
### Describe the bug

Sign in succeeded
Fetch auth session failed with error - AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/prakashkumar/Library/Developer/Xcode/DerivedData/Testing-gfzuwohbhegeligxlootapipemyk/SourcePackages/checkouts/amplify-ios/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80
Caused by:
Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=0 "(null)" UserInfo={__type=ValidationException, message=1 validation error detected: Value 'us-west-2_wdLXbCQIZ' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+}
Fetch auth session failed with error - AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/prakashkumar/Library/Developer/Xcode/DerivedData/Testing-gfzuwohbhegeligxlootapipemyk/SourcePackages/checkouts/amplify-ios/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80
Caused by:
Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=0 "(null)" UserInfo={__type=ValidationException, message=1 validation error detected: Value 'us-west-2_wdLXbCQIZ' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+}
Fetch auth session failed with error - AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/prakashkumar/Library/Developer/Xcode/DerivedData/Testing-gfzuwohbhegeligxlootapipemyk/SourcePackages/checkouts/amplify-ios/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80
Caused by:
Error Domain=com.amazonaws.AWSCognitoIdentityErrorDomain Code=0 "(null)" UserInfo={__type=ValidationException, message=1 validation error detected: Value 'us-west-2_wdLXbCQIZ' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+}

### Steps To Reproduce

```swift
func fetchAuthSession(){
    Amplify.Auth.fetchAuthSession { result in
        do {
            let session = try result.get()

            // Get user sub or identity id
            if let identityProvider = session as? AuthCognitoIdentityProvider {
                let usersub = try identityProvider.getUserSub().get()
                let identityId = try identityProvider.getIdentityId().get()
                print("1111111111111111111111111111111111111111111")
                print("User sub - \(usersub) and identity id \(identityId)")
            }

            // Get aws credentials
            if let awsCredentialsProvider = session as? AuthAWSCredentialsProvider {
                let credentials = try awsCredentialsProvider.getAWSCredentials().get()
                print("2222222222222222222222222222222222222222222")
                print("Access key - \(credentials.accessKey) ")
            }

            // Get cognito user pool token
            if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
                let tokens = try cognitoTokenProvider.getCognitoTokens().get()
                print("333333333333333333333333333333333")
                print("Id token - \(tokens.idToken) ")
                
            }

        } catch {
            print("Fetch auth session failed with error - \(error)")
        }
    }
```

### Expected behavior

it will provide an access token id token

### Amplify Framework Version

1.5.3

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

4.42

### Xcode version

11

### Is this a regression?

No

### Device

iphone 11 simulator

### iOS Version

ios 11

### Additional context

i am using for mobile device for ios .

**Comment by Withney** [comment]
Any solution?

**Comment by prakash-ikabit** [comment]
Amazon api is there to print access token and id token at a time kindly check ios / amplify section

**Comment by royjit** [comment]
I think you have passed the user pool id in place of identityPool from the error from above. Can you please check the configuration file is correct?
