### ISSUE TITLE
Identity Provider not automatically chosen with signInWithWebUI & popup occurring with prefersPrivateSession enabled

### ISSUE THREAD

**Issue by jeffrrogers** [aws-amplify/amplify-ios#1498]
### Describe the bug

Issue #1
With AD Integration configured with Amplify, we would like our identityProvider, "Azure-IoT-T", to be automatically selected when the signInWithWebUI web UI is shown so that the user doesn't have to click the "Azure-IoT-T" button and proceed to their federated sign-in. 

We have tried including the identityProvider within the AWSAuthWebUISignInOptions for the signInWithWebUI call, we've also tried using a custom Provider in the signInWithWebUI call (for: .custom("Azure-IoT-T")), as well as a combination of those two approaches.

Issue #2
We are intermittently getting the "App wants to use amazoncognito.com to sign in" popup alert when signing in or signing out. As far as I am aware, as long as we enable preferPrivateSession for our AWSAuthWebUISignInOptions, we should not receive these popups. Is that correct?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create a AWSAuthWebUISignInOptions object with idpIdentifier set as "Azure-IoT-T" and preferPrivateSession set to true
2. Create a AuthWebUISignInRequest.Options object passing in the pluginOptions object from step 1
3. Call Amplify.Auth.signInWithWebUI(for: .custom("Azure-IoT-T", presentationAnchor: keyWindow, options: options) with the options object from step 2
```

### Expected behavior

The web UI should display with the federated sign-in automatically to allow users to sign-in via their company credentials and no amazoncognito.com popup alerts should be displayed.

Actual Behaviour
Users have to tap the "Azure-IoT-T" button to get to the federated sign-in screen:
![Image from iOS](https://user-images.githubusercontent.com/13265885/139364173-c5c0a890-00ff-4465-b4c9-fa0c6911adf7.png)

Popup is displayed even when preferPrivateSession is enabled:
![Image from iOS (1)](https://user-images.githubusercontent.com/13265885/139364241-69216a5b-5ad7-43df-be3f-be752675334e.png)

### Amplify Framework Version

1.12.0

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.3

### CLI version

6.2.1

### Xcode version

12.5.1

### Is this a regression?

No

### Device

iPhone 12 Pro, iPad Pro 11" (2nd Gen)

### iOS Version

iOS 14.5.1, iOS 15.0

### Specific to simulators

Both simulators and devices

**Comment by royjit** [comment]
The popup will be shown for signIn, it will not be shown for signOut.  We do not have control over the popup, it is system provided by Apple. 

Are you using the same key that you have given in the Cognito Userpool while providing the identity provider value? ie "Azure-IoT-T" should match the configuration you have on Cognito User Pool

**Comment by jeffrrogers** [comment]
@royjit Yes we are passing the same key. I've confirmed that.

Also please note the popup is no longer occurring for us, we have made sure all flows use the prefersPrivateSession flag and that part is working correctly. 

The only outstanding issue now is the provider still not being automatically chosen.

**Comment by jeffrrogers** [comment]
@royjit Heard back from AWS support and resolved the issue. Here is how the sign in should be setup:

```
let pluginOptions = AWSAuthWebUISignInOptions(preferPrivateSession: true)
let options = AuthWebUISignInRequest.Options(pluginOptions: pluginOptions)

Amplify.Auth.signInWithWebUI(for: .custom("Azure-IoT-T"), presentationAnchor: keyWindow, options: options)
```

We had been including idpIdentifier in the AWSAuthWebUISignInOptions object, which was causing the issue. Removing idpIdentifier and including the "for: .custom("Azure-IoT-T")" parameter in the signInWithWebUI() call resolved our issue.

Thanks for the help!

**Comment by ten-skv** [comment]
I'm using Android, exactly facing the same issue. I don't find the way to pass custom provider in signInWithWebUI

**Comment by ten-skv** [comment]
Do we have preferPrivateSession for Android SDK?
