### ISSUE TITLE
Redirect fails after Sign in with Apple, gets stuck in failure loop

### ISSUE THREAD

**Issue by corleymj** [aws-amplify/amplify-ios#1524]
### Describe the bug

A small percentage of our application's users have reported an issue when signing in with Apple.  The issue is persistent for these particular users - force quitting the app, even uninstall/reinstall and retrying does not fix the issue.  While the majority of users who sign in with Apple do not experience this, our Apple App Store reviewer is one of the few who does, and it's currently blocking our release to App Store.  

A video is worth a thousand words (pardon the black box - redacting our user's email address):

https://user-images.githubusercontent.com/4743542/142263364-9031461b-91f7-4728-88fb-7aef3091017f.mp4

As you can see, they are redirected to the web login UI which is unexpected.  The redirect URI in the webview is:  `https://id.colorca.st/login?redirect_uri=colorcastapp%3A%2F%2Foauth%2Fcallback&response_type=code&client_id=****`

Where `colorcastapp` is the URL scheme we've defined in our Info.plist per the Amplify documentation.

We've tried having the user go into iOS Settings > Apple ID > Password & Security > Apps Using Apple ID and removing our app.  We've also tried removing them from our Cognito user pool. In both cases, the issue still persists.

Here's the code we're using to sign in:

```
Amplify.Auth.signInWithWebUI(for: .apple, presentationAnchor: window, 
      options: .preferPrivateSession()) { result in
. . . 
}
```

We don't get a failure result until the user has closed out of the webview - at which point it's an `AuthError.unknown`.   

Here's our Amplify config:

```
  let authConfiguration: [String: JSONValue] = [
      "awsCognitoAuthPlugin": [
          "CredentialsProvider": [
              "CognitoIdentity": [
                  "Default": [
                      "PoolId": JSONValue(stringLiteral: AmazonConstants.COGNITOIDENTITYPOOLID),
                      "Region": JSONValue(stringLiteral: AmazonConstants.REGION)
                  ]
              ]
          ],
          "IdentityManager": [
              "Default": [:]
          ],
          "CognitoUserPool": [
              "Default": [
                  "AppClientId": JSONValue(stringLiteral: AmazonConstants.COGNITOCLIENTID),
                  "PoolId": JSONValue(stringLiteral: AmazonConstants.COGNITOUSERPOOLID),
                  "Region": JSONValue(stringLiteral: AmazonConstants.REGION)
              ]
          ],
          "Auth": [
              "Default": [
                  "authenticationFlowType": JSONValue(stringLiteral: "CUSTOM_AUTH"),
                  "OAuth": [
                      "WebDomain": JSONValue(stringLiteral: AmazonConstants.COGNITOAUTHBASEURL),
                      "AppClientId": JSONValue(stringLiteral: AmazonConstants.COGNITOCLIENTID),
                      "SignInRedirectURI": JSONValue(stringLiteral: AmazonConstants.COGNITOCALLBACKURL),
                      "SignOutRedirectURI": JSONValue(stringLiteral: AmazonConstants.COGNITOLOGOUTURL),
                      "Scopes": ["openid", "aws.cognito.signin.user.admin", "email", "profile"]
                  ]
              ]
          ]
      ]
  ]
  
  let apiConfiguration: [String: JSONValue] = [
      "awsAPIPlugin": [
          "Colorcast": [
              "endpointType": "REST",
              "endpoint": JSONValue(stringLiteral: baseUrl),
              "region": JSONValue(stringLiteral: AmazonConstants.REGION),
              "authorizationType": "AWS_IAM"
          ]
      ]
  ]
  
  let storageConfiguration: [String: JSONValue] = [
      "awsS3StoragePlugin": [
          "bucket": JSONValue(stringLiteral: AmazonConstants.S3UPLOADBUCKET),
          "region": JSONValue(stringLiteral: AmazonConstants.REGION),
          "defaultAccessLevel": "private"
      ]
  ] 
```

It's worth noting that we use the same Apple service ID for our dev, staging, and production environments (separate User Pools in separate AWS accounts).  However, the users experiencing this are only in production, and we've had no issues internally using the same Apple logins across all environments.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:

This behavior is intermittent and seems linked to specific user identities.

1. Invoke Amplify.Auth.signinWithWebUI for Apple
```

### Expected behavior

Redirect should succeed and user should be able to sign in with Apple.

### Amplify Framework Version

1.15.5

### Amplify Categories

API, Auth, Storage

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

N/A

### Xcode version

13.1

### Is this a regression?

No

### Device

iPhone 12 Pro Max, iPad 

### iOS Version

iOS 14.4, iOS 15.1

### Specific to simulators

no

**Comment by atierian** [comment]
Thanks for opening this issue.
The AWSCognito team is currently investigating this. We'll provide an update when one is available.

**Comment by royjit** [comment]
As per the internal investigation, this looks like an issue from the Apple side. Please raise a bug report with Apple. Reopen the issue or open a new one if you see an issue from the Amplify iOS side.
