### ISSUE TITLE
How can I send data in a Amplify.API.mutate request that is not saved on the database?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1540]
I am trying to save an image to an S3 bucket from an app extension.  The extension does not work with the Storage framework but works fine with API.

As a workaround and since the data I want to store in S3 are relatively small, I would like to have a trigger in my DynamoDB table on create that will call a lambda that stores the data on my S3.

This also works fine.  The only problem is I can only pass the data  (base64) as a field in the schema and as such it will be saved in DynamoDB which I don't want.

How can I send data in my Amplify.API.mutate request that will not be saved in the database?  If there is not way to do that, is there another workaround for this?  The iOS amplify library for some reason doesn't allow me to call lambda functions directly so that's out.  What else can I do?

**Comment by royjit** [comment]
You could use REST api to send data to the api end point - https://docs.amplify.aws/lib/restapi/update/q/platform/ios/

**Comment by alionthego** [comment]
> You could use REST api to send data to the api end point - https://docs.amplify.aws/lib/restapi/update/q/platform/ios/

Can I use this test api along with the graphql api I am already using in my application?  If not I need another solution. Thx.

**Comment by alionthego** [comment]
I have tested and I can use Rest with GraphQL.  Closing this.
