### ISSUE TITLE
S3 Credentials Provider

### ISSUE THREAD

**Issue by HilaRaveh** [aws-amplify/amplify-ios#1543]
### Is your feature request related to a problem? Please describe.

When uploading an item to an S3 bucket, I don't want to use the logged in users credentials, but I also don't want the request to be unauthenticated.
In the aws-amplify/aws-sdk-ios package, there is an AWSCognitoCredentialsProvider which can be passed to the S3 class, and then by building my own identityProvider class, I can get the credentials for my identity pool and use it to authenticate the request.

### Describe the solution you'd like

I want to have this capability in the amplify library, or know if there's already some other similar flow which answers this requirement.

### Describe alternatives you've considered

I can go back to the aws-amplify/aws-sdk-ios package

### Is the feature request related to any of the existing Amplify categories?

Auth, Storage

**Comment by royjit** [comment]
Similar request - https://github.com/aws-amplify/amplify-ios/issues/1543

**Comment by royjit** [comment]
Closing this as a duplicate - https://github.com/aws-amplify/amplify-ios/issues/1412
