### ISSUE TITLE
Cancelling the sign out flow results in revoked access token

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-ios#1552]
### Describe the bug

When a user cancels the sign out flow after signing in with web UI, the access token is still revoked.

### Steps To Reproduce

1. Sign in with web UI
2. Call signOut and then tap cancel. A UserCancelledException is thrown.
3. Call Amplify.Auth.fetchUserAttributes(). A NotAuthorizedException is thrown with the message that the access token has been revoked.

### Expected behavior

The access token should not be revoked if the user cancels the sign out flow.

### Amplify Framework Version

1.15.5

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

6.1.0

### Xcode version

13.1

### Is this a regression?

No

### Device

iPhone 13 simulator

### iOS Version

15.0

**Comment by ameter** [comment]
Thanks for reporting this.  We fixed this in [this PR](https://github.com/aws-amplify/aws-sdk-ios/pull/3964).  The fix will be released next week.

**Comment by harsh62** [comment]
The feature has been released in https://github.com/aws-amplify/aws-sdk-ios/releases/tag/2.27.0. Please validate if this fix works for you.
