### ISSUE TITLE
Not able to install AWS cocoa pod with IOS 11.0

### ISSUE THREAD

**Issue by rajput09** [aws-amplify/amplify-ios#1561]
**I am going to implement AWS amplify in my IOS project and getting issue while installing the pods file **

**It's gives the error like  :-
CocoaPods could not find compatible versions for pod "AWSPredictionsPlugin":
  In Podfile:
    AWSPredictionsPlugin

There are only pre-release versions available satisfying the following requirements:

	'AWSPredictionsPlugin', '>= 0'

You should explicitly specify the version in order to install a pre-release version**

**i am using below pods for AWS Services :-
        pod 'Amplify'
        pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
        pod 'AWSPredictionsPlugin'
        pod 'CoreMLPredictionsPlugin'

<img width="650" alt="Screenshot 2021-12-07 at 12 42 28 PM" src="https://user-images.githubusercontent.com/87544220/145157659-0ecc0040-8607-47b5-b5b8-e1fcb13a5669.png">
<img width="582" alt="Screenshot 2021-12-07 at 12 46 05 PM" src="https://user-images.githubusercontent.com/87544220/145157669-56c065e6-8a6d-43a1-ace4-2834252e4381.png">
**

**if i am installing with IOS 13.0 it's working fine but it's not installing with IOS 11.0 we don't want to set minimum deployment target to 13.0. Is it possible to install these pods with IOS 11.0 or is it mandate to 13.0**

**Comment by atierian** [comment]
Hi @rajput09, thanks for opening this issue.

The `AWSPredictionsPlugin` has a minimum supported deployment target of iOS 13.0 because it relies on iOS APIs that were made available in iOS 13.0. Here are the listed [prerequisites](https://docs.amplify.aws/lib/predictions/getting-started/q/platform/ios/#prerequisites) in for Predictions. So to answer your question, no it is not possible use `AWSPredictionsPlugin` with a minimum deployment target below iOS 13.0.

**Comment by rajput09** [comment]
Hi @atierian Thanks for your response 
For your information we are not using any  "AWSPredictionsPlugin" .  we are using these pods so my question is:-  Is it apply for these also with a minimum deployment target below iOS 13.0 :-

pod 'Amplify'
pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
pod 'AmplifyPlugins/AWSAPIPlugin'
pod 'AmplifyPlugins/AWSDataStorePlugin'

**Comment by atierian** [comment]
Those four pods listed all have a minimum target of iOS 11.0 and will work fine if your app is targeting iOS 11.0.
If you're seeing issues installing those pods, please post the contents of your Podfile. (You can omit the `target` name if you prefer to keep that private).

**Comment by rajput09** [comment]
Hi @atierian thanks for your support listed pods are working fine .
