### ISSUE TITLE
Unable select google accounts with preferPrivateSession on signInWithWebUI on iOS

### ISSUE THREAD

**Issue by naruhito-ozawa-adglobe-co-jp** [aws-amplify/amplify-ios#1564]
Hi team

I implemented to prevent pop-ups using the method described in this link.
[issue745](https://github.com/aws-amplify/amplify-ios/issues/745#issuecomment-774162694)
i use amplify-ios version 1.14.0, but it's the same even if I update 1.17.0

but, After clicking the [Continue with Google] button, 
the Google account selection screen can no longer be displayed.
it will always see a field where you can enter your Google email address
in the image below.

<img src="https://user-images.githubusercontent.com/44634638/146094311-b200c83c-0882-4658-89b3-b09975a2c603.png" width="150">

I would like to use preferPrivateSession to hide pop-ups.
Is there a way to display the Google account selection screen like the image below?

<img src="https://user-images.githubusercontent.com/44634638/146095003-602bb660-4045-4c26-8f50-299c775e1ffb.png" width="150">

The execution environment is as follows.
xcode12.5.1
swift5

**Comment by royjit** [comment]
Since it is a private session, the UI will not show any existing google accounts. If you need to bring up the existing logged in user in the Safari session you have to disable privateSession.
