### ISSUE TITLE
[Auth] Getting "Cognito User Pools is not configured" when trying to register a user

### ISSUE THREAD

**Issue by orkhan-huseynov** [aws-amplify/amplify-ios#1565]
### Describe the bug

I set up a clean project and added the Auth plugin like described here: https://docs.amplify.aws/lib/auth/signin/q/platform/ios/

Upon calling `Amplify.Auth.signUp(username: username, password: password, options: options)` I get the following error:

> An error occurred while registering a user AuthError: Unexpected error occurred with message: Cognito User Pools is not configured in `awsconfiguration.json`. Please add Cognito User Pools before using this API.
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't.

The `awsconfiguration.json` file is present, belongs to app target and looks like this:

```
{
  "UserAgent": "aws-amplify/cli",
  "Version": "0.1.0",
  "IdentityManager": {
    "Default": {}
  },
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "<>",
        "Region": "US-East-2"
      }
    }
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "<>",
      "AppClientId": "<>",
      "Region": "US-East-2"
    }
  },
  "Auth": {
    "Default": {
      "authenticationFlowType": "USER_SRP_AUTH",
      "socialProviders": [],
      "usernameAttributes": [
        "EMAIL"
      ],
      "signupAttributes": [
        "EMAIL"
      ],
      "passwordProtectionSettings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
      },
      "mfaConfiguration": "OFF",
      "mfaTypes": [
        "SMS"
      ],
      "verificationMechanisms": [
        "EMAIL"
      ]
    }
  }
}

```

The real issue is the region name "US-East-2" instead of "us-east-2". Moreover it has to be specified correctly in `amplifyconfiguration.json` file and not in `awsconfiguration.json` to which the error is pointing to.

### Steps To Reproduce

```swift
1. Set up a clean project
2. Add Auth plugin
3. Provide incorrect region name (e.g. "US-East-2" instead of "us-east-2") in `amplifyconfiguration.json` file
4. Call `Amplify.Auth.signUp`
```

### Expected behavior

The error does not misleadingly point to missing Cognito User Pools in `awsconfiguration.json` file

### Amplify Framework Version

1.17.0

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.5

### CLI version

7.6.3

### Xcode version

13.1

### Is this a regression?

No

### Device

iPhone 13 Pro Simulator

### iOS Version

15.0

**Comment by diegocstn** [comment]
@orkhan-huseynov just to clarify, did you manually change the value of "Region" to `US-East-2` in `amplifyconfiguration.json` and you were expecting the error message to point to the right file?
`awsconfiguration.json` file is used by the "legacy" SDKs and AWSMobileClient is one of them, that should explain the misleading error message.

**Comment by orkhan-huseynov** [comment]
> @orkhan-huseynov just to clarify, did you manually change the value of "Region" to `US-East-2` in `amplifyconfiguration.json` and you were expecting the error message to point to the right file?

Yes, exactly

> `awsconfiguration.json` file is used by the "legacy" SDKs and AWSMobileClient is one of them, that should explain the misleading error message.

Correct. The point of this issue is the misleading error message

**Comment by diegocstn** [comment]
Thanks for reporting this to us.
I'll close this for now as `AWSMobileClient` is part of the legacy SDKs and we don't have a reliable way to verify whether AWSMobileClient is being used in isolation or within Amplify, but feel free to reopen if you have more concerns.
