### ISSUE TITLE
Continue email registration in another session or on another device

### ISSUE THREAD

**Issue by hellopandaxx** [aws-amplify/amplify-ios#1566]
Hello, guys! Need some advice about email registration (sign up with by email) flow.

Basically we call Amplify.Auth.signUp(username: .., password: .., options: ..)
and after that Amplify.Auth.confirmSignUp(for: .., confirmationCode: ..).

But in case an app was closed before the confirmation code was entered, it seems like context is lost and we unable to continue the registration precess with that email. When I call Amplify.Auth.signUp second time, I just have an error "An account with the given email already exists", there is no any flag about email is used but I can continue with confirmSignUp step.

How would you suggest me to handle this situation? Maybe I missed something?

Thank you,
Sergey

**Comment by harsh62** [comment]
Can you please elaborate your following comment?

> there is no any flag about email is used but I can continue with confirmSignUp step.

Are you able to confirm sign up after the error is thrown by utilizing the `AWSMobileClientError` `usernameExists(message: String)` or `userNotConfirmed(message: String)`?

But if you can elaborate the question a little more. That would be really nice.

**Comment by hellopandaxx** [comment]
Hi @harsh62, yes, sorry for confusing.

I mean the flow like this:
1. I want to register for the first time with email and password and call Amplify.Auth.signUp
2. Now I should enter confirmation code but I just close my app instead
3. Later I decide to continue registration and open app again. For this point, as I understand, the only option is to call Amplify.Auth.signUp again, but this call returns error "An account with the given email already exists". I would expect here some sign or flag that given email not just already exists but also needs confirmation and I should go to confirmSignUp step.

So how could I continue the registration with that email in such situation?
Is there a way to determine current status(step) of registration for given email? For example for the case when I start registration on the one device and want to enter a confirmation code on another device.

**Comment by hellopandaxx** [comment]
@harsh62, could you provide any advise on this please?

**Comment by sushil7271** [comment]
@harsh62 or @hellopandaxx  Any solution or workaround for this?

**Comment by thisisabhash** [comment]
Hello,

In this case, you'd need to call `Amplify.Auth.confirmSignUp()` with the username and confirmationCode to confirm the user in Step 3.

**Comment by harsh62** [comment]
@hellopandaxx sorry for responding late to the question..

If you tried signing up a user and did not confirm, the `signUp` will keep failing with a `usernameExists` error. 
Instead of `signUp` you should try to use the `signIn` api which would provide you with more context and provide the next step too. In this particular scenario the `signIn` API will respond with a next step in the response which would be `(Amplify.AuthSignInStep) nextStep = confirmSignUp`.. And if you encounter this, you could proceed with the confirmation step. 


An example of how you can inspect the confirmation.

```
func signIn(username: String, password: String) {
    Amplify.Auth.signIn(username: username, password: password) { result in
        do {
                let signinResult = try result.get()
                switch signinResult.nextStep {
                case .confirmSignUp(let info):
                    print("Confirm signup additional info \(info)")
                    
                    // User was not confirmed during the signup process.
                    // Invoke `confirmSignUp` api to confirm the user if
                    // they have the confirmation code. If they do not have the
                    // confirmation code, invoke `resendSignUpCode` to send the
                    // code again.
                    // After the user is confirmed, invoke the `signIn` api again.
                case .done:
                    
                    // Use has successfully signed in to the app
                    print("Signin complete")
                }
            } catch {
                print ("Sign in failed \(error)")
            }
    }
}
```

Hope this answers your question. 

More [documentation](https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/ios/) on how sign in next steps work.
