### ISSUE TITLE
AWS Amplify Plugins for Swift Package Manager Dependency

### ISSUE THREAD

**Issue by dkman94** [aws-amplify/amplify-ios#1572]
### Is your feature request related to a problem? Please describe.

The documentation has instructions on how to pull down plugins when installing Amplify through Swift Package Manager, however has no info for when the library is installed via Swift Package Manager dependency. 

Is this possible? And if so, can the documentation be updated? 

e.g.
```
dependencies: [
        .package(name: "Amplify", url: "https://github.com/aws-amplify/amplify-ios", from: "1.17.0")
    ],
``` 

### Describe the solution you'd like

Allowing additional plugins to be pulled in as dependencies, or have an alternative mechanism for Swift Package Manager/SDKs. 

### Describe alternatives you've considered

The swift package could use a Podfile, however it's best to support Swift Packages for future development.

**Comment by diegocstn** [comment]
@dkman94 to clarify, are you trying to consume Amplify as a dependency of another Swift Package?
If so, you should be able to declare the Amplify plugins as a dependency of your target as follows:
```swift
let package = Package(
    name: "MyPackage",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: "MyPackage",
            targets: ["MyPackage"]),
    ],
    dependencies: [
        .package(name: "Amplify",
                 url: "https://github.com/aws-amplify/amplify-ios",
                 from: "1.17.0")
    ],
    targets: [
        .target(
            name: "MyPackage",
            dependencies: [
                .product(name: "Amplify", package: "Amplify"),
                .product(name: "AWSPluginsCore", package: "Amplify"),
                .product(name: "AWSDataStorePlugin", package: "Amplify")
            ])
    ]
)
```
Note that here "MyPackage" is a library.

Our documentation covers how to consume Amplify through Xcode UI: 
https://docs.amplify.aws/start/getting-started/setup/q/integration/ios/#create-a-new-ios-application

**Comment by dkman94** [comment]
Ahh yes this is exactly what I'm trying to do. Thanks for the help! It seems to have worked
