### ISSUE TITLE
Not able to install the AWS pods fie 

### ISSUE THREAD

**Issue by rajput09** [aws-amplify/amplify-ios#1575]
I am trying to install the following pods it's gives me error like that attaching the screenshot as well please look into it on priority
<img width="682" alt="ErrorScreenShot" src="https://user-images.githubusercontent.com/87544220/146533778-3529ae07-e595-416e-9a3d-ddc622814e99.png">
 :- 

These are the pods  :-
 pod 'Amplify'
 pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
 pod 'AmplifyPlugins/AWSAPIPlugin'
 pod 'AmplifyPlugins/AWSDataStorePlugin'

[!] CocoaPods could not find compatible versions for pod "Amplify":
  In snapshot (Podfile.lock):
    Amplify (= 1.18.1)

  In Podfile:
    Amplify

    AmplifyPlugins/AWSCognitoAuthPlugin was resolved to 1.0.0, which depends on
      AWSPluginsCore (= 1.0.0) was resolved to 1.0.0, which depends on
        Amplify (= 1.0.0)

CocoaPods could not find compatible versions for pod "AmplifyPlugins/AWSCognitoAuthPlugin":
  In Podfile:
    AmplifyPlugins/AWSCognitoAuthPlugin

There are only pre-release versions available satisfying the following requirements:

	'AmplifyPlugins/AWSCognitoAuthPlugin', '>= 0'

You should explicitly specify the version in order to install a pre-release version
CocoaPods could not find compatible versions for pod "Starscream":
  In snapshot (Podfile.lock):
    Starscream (= 3.0.6, ~> 3.0.6)

  In Podfile:
    AmplifyPlugins/AWSAPIPlugin was resolved to 1.18.1, which depends on
      AppSyncRealTimeClient (~> 1.4) was resolved to 1.4.3, which depends on
        Starscream (~> 3.1.0)

    Starscream (~> 3.0.6)

My mac os : -  macOS big sur 
Version : 11..6 
Xcode : 12.5
Deployment target is : 11.0
Apple ID - info@vindhyainfotech.com
Region - India

**Comment by diegocstn** [comment]
@rajput09 what's in your `Podfile.lock`?
Can you try update your installed pods (and therefore re-generate the lock file) by running `pod install --repo-update`?
