### ISSUE TITLE
Session expires when using preferPrivateSession to sign in 

### ISSUE THREAD

**Issue by naruhito-ozawa-adglobe-co-jp** [aws-amplify/amplify-ios#1577]
### Describe the bug

After sigin in with the code below and leaving it for a few hours.

```
Amplify.Auth.signInWithWebUI(presentationAnchor:UIApplication.shared.windows.first!,
							options:.preferPrivateSession()) 

```
Session expires when restarting the app.
I confirmed expire using the following method.

```
Amplify.Auth.fetchAuthSession(listener: { (result) in
do {
	---
	} catch AuthError.sessionExpired {
	---  <--- here
	} catch
	---
}

```

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. lunch app
2. sign in with Amplify.Auth.signInWithWebUI with preferPrivateSession
   sign in by entering your google email address
3. stay running for a few hours
4. restart the app
5. catch session expiered by using method (Amplify.Auth.fetchAuthSession)
```

### Expected behavior

The session will not expire when the app is restarted

### Amplify Framework Version

1.14.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.5

### CLI version

N/A

### Xcode version

12.5.1

### Is this a regression?

No

### Device

iphone12 mini 

### iOS Version

ios 14.8

**Comment by lawmicha** [comment]
Hi @naruhito-ozawa-adglobe-co-jp, I'm not too familiar with the auth flow regarding hosted UI. cc @royjit

Do you have any special configuration set up in your Cognito backend?
what is your Cognito's token expiry configuration set to? 
I was looking around and read mentions of when using implicit grants, the refresh token is not retrievable. Could you verify there's a refresh token after the user signs in? The refresh token should be used automatically to refresh the other tokens

```swift
Amplify.Auth.fetchAuthSession { result in
       do {
           let session = try result.get()

           guard session.isSignedIn else {
               print("Not signed in")
               return
           }

           // Get cognito user pool token
           if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
               let tokens = try cognitoTokenProvider.getCognitoTokens().get()
               print("Id token - \(tokens.idToken) ")
               print("Refresh token - \(tokens.refreshToken)")
           }

       } catch {
           print("Fetch auth session failed with error - \(error)")
       }
   }
```

**Comment by naruhito-ozawa-adglobe-co-jp** [comment]
@lawmicha 
Thank you for your comment!
I solved it by using [Amplify.Auth.fetchAuthSession].
