### ISSUE TITLE
DataStore Temporal cannot persist precision of micro seconds and nano seconds

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-ios#1583]
### Describe the bug

Using schema

```graphql
type Blog @model {
  name: String!
  awsDateTime: AWSDateTime
}
```

Run below sample code

```swift
let models = [
    try Blog(name: "1", awsDateTime: Temporal.DateTime.init(iso8601String: "2020-01-01T19:30:45.000000000Z")),
    try Blog(name: "2", awsDateTime: Temporal.DateTime.init(iso8601String: "2020-01-01T19:30:45.100000000Z")),
    try Blog(name: "3", awsDateTime: Temporal.DateTime.init(iso8601String: "2020-01-01T19:30:45.100250000Z")),
    try Blog(name: "4", awsDateTime: Temporal.DateTime.init(iso8601String: "2020-01-01T19:30:45.1000Z")),
    try Blog(name: "5", awsDateTime: Temporal.DateTime.init(iso8601String: "2020-01-01T19:30:45.111Z")),
    try Blog(name: "6", awsDateTime: Temporal.DateTime.init(iso8601String: "2020-01-01T19:30:45.111+00:00")),
    try Blog(name: "7", awsDateTime: Temporal.DateTime.init(iso8601String: "2020-01-01T19:30:45.111+01:00")),
    try Blog(name: "7", awsDateTime: Temporal.DateTime.init(iso8601String: "2020-01-01T19:30:45.111222333Z")),
]

for model in models {
    Amplify.DataStore.save(model) { result in
        switch(result) {
        case .success(let savedItem):
            print("Saved item: \(savedItem.name)")
        case .failure(let error):
            print("Could not save item to DataStore: \(error)")
        }
    }
}
```

The `awsDateTime` values stored in local SQLite DB drops the micro seconds and nano seconds specified in the input.
<img width="165" alt="image-20220104105222805" src="https://user-images.githubusercontent.com/10602282/148110508-e4b290c8-dc5e-4a8e-b829-5235ae46f250.png">

The fractional seconds dropping seems to be done by this format string:

https://github.com/aws-amplify/amplify-ios/blob/2c57ccce43d60789183f3737e44226a453eae969/Amplify/Categories/DataStore/Model/Temporal/TemporalFormat%2BDateTime.swift#L21

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Run the sample code
2. Observe the records inserted in SQLite DB
```

### Expected behavior

When records are inserted into SQLite, the DateTime column should persist micro seconds and nano seconds following user input.

### Amplify Framework Version

1.18.1

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5

### CLI version

7.6.5

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone 13 simulators

### iOS Version

15.2

**Comment by atierian** [comment]
Thanks for opening this issue @HuiSF.

This is an OS limitation that we unfortunately can't work around. `Temporal.Date` and `Temporal.DateTime` are backed by `Foundation.Date`, which only supports down to millisecond granularity.

For example:
```swift
let dateString = "2020-01-01T19:30:45.111222333Z"
let formatter = DateFormatter()
formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSZZZZZ"

let date = formatter.date(from: dateString)
date // "Jan 1, 2020 at 2:30 PM"
date?.debugDescription // "2020-01-01 19:30:45 +0000"

let backToString = date.map(formatter.string(from:))
backToString // "2020-01-01T14:30:45.11100000-05:00"
```

This means we lose micro and nanosecond precision once the iso string gets converted to a `Foundation.Date`, which happens in the `Temporal.DateTime` implementation.

**Comment by HuiSF** [comment]
Thanks for the explanation @atierian .

This causes platform discrepancy though between AppSync, and amplify-android.

**Use case 1:**
A customer wants to use data from AppSync produced by other Apps, AppSync is capable to persist micro and nanosecond. In this case, amplify-ios may mutate existing data unexpectedly.

**Use case 2:**
A customer wants to create an Android App and an iOS App which can communicate each other real time via DataStore, if two devices modify the same model, the way ampliy-ios handling DateTime may cause data inconsistency between the two platforms.

Considering above use cases, is that possible to extract micro and nanosecond from the original input initiating `Temporal.DateTime`, and merge the info back after getting the ISO8601 string before writing the value into local DB?

**Comment by atierian** [comment]
Thanks for the explanation of use cases, that's helpful. This is something that should have platform parity.
I'll take this on as a feature request; considering this is an expected limitation on iOS, I don't believe it should be classified a bug, unless there's a standard or API contract we're violating.

I'll dig into this and update here.

**Comment by atierian** [comment]
Due to the system constraints mentioned above - `Temporal.DateTime` is backed by`Foundation.Date`, which doesn't support micro- or nanoseconds - we'll have to revisit this feature request at a later time. The Swift [Clock, Instant, and Duration Proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0329-clock-instant-duration.md) that is currently under review may open up the possibility for us to support micro- and nanoseconds. We'll revisit this feature request when/if these changes make it possible to do so.
