### ISSUE TITLE
iOS : Login with Facebook Error

### ISSUE THREAD

**Issue by devronins** [aws-amplify/amplify-ios#1586]
### Describe the bug

I am trying to implement login with facebook. I have followed all steps as mentioned here https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios/

But when I try to login using below code

       ```
 Amplify.Auth.signInWithWebUI(for: .facebook, presentationAnchor: view.window!) { result in
                switch result {
                case .success:
                    print("Sign in succeeded")
                case .failure(let error):
                    print("Sign in failed \(error)")
                }
        }
```
I received below error logs:

_**Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred

Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/laxmansingh/Desktop/Surjeet/git/Zapp/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift

function: recoverySuggestion
line: 80
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-3000 "(null)" UserInfo={error=invalid_request: Facebook Error - 400 error getting token}**_

Below are my AWSConfiguration file structure:

```

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "xxxx",
                            "Region": "us-east-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxx",
                        "AppClientId": "xxxx",
                        "Region": "us-east-2",
                        "AppClientSecret": "xxxx"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxx",
                            "AppClientId": "xxxx",
                            "AppClientSecret": "xxxx",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "aws.cognito.signin.user.admin",
                                "email",
                                "openid",
                                "phone",
                                "profile"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "FACEBOOK"
                        ],
                        "usernameAttributes": [
                            "PHONE_NUMBER"
                        ],
                        "signupAttributes": [
                            "PHONE_NUMBER"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_UPPERCASE",
                                "REQUIRES_NUMBERS",
                                "REQUIRES_SYMBOLS"
                            ]
                        },
                        "mfaConfiguration": "OPTIONAL",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "PHONE_NUMBER"
                        ]
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "xxxx",
                        "Region": "us-east-2"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "xxxx",
                "region": "us-east-2",
            }
        }
    }
}

```

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
I have followed steps provided in this docs for Facebook

https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios/
```

### Expected behavior

After calling Amplify.Auth.signInWithWebUI()

Should be logged in using facebook with success response.

### Amplify Framework Version

Amplify (1.17.0)

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

7.6.5

### Xcode version

Version 13.2.1 (13C100)

### Is this a regression?

No

### Device

IPhone simulator

### iOS Version

iOS 15.2

**Comment by s-surjeet** [comment]
Any update on this ? @ameter

**Comment by ameter** [comment]
We have not been able to reproduce this error.  Our config and calling function is nearly identical, and our sign-in calls have been successful.  It's likely the issue is in the configuration on either the Facebook or Cognito backend.  Can you double check that all settings follow [this guidance](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios/)?  For example, make sure domains are appended with `/oauth2/idpresponse` as appropriate, etc.

**Comment by s-surjeet** [comment]
@ameter  Yes, I tried it multiple times and have cross checked all config again as per documentation. But still getting this issue.
 Just wondering if this config can cause this issue to occur
 
 "socialProviders": [
"FACEBOOK"
],
"usernameAttributes": [
"PHONE_NUMBER"
],
"signupAttributes": [
"PHONE_NUMBER"
],

**Comment by ameter** [comment]
The `PHONE_NUMBER` **signupAttribute** is not supported by Facebook.  You can still allow users to sign in via their phone number and specify `PHONE_NUMBER` as a **usernameAttribute**, but the above configuration is not supported and will result in this error.

The current version of the Amplify CLI (`7.6.9`) calls this out and prevents selecting any social provider other than Google if `PHONE_NUMBER` has been selected as a **signupAttribute**:

<img width="795" alt="Screen Shot 2022-01-19 at 9 21 01 AM" src="https://user-images.githubusercontent.com/29186822/150177556-a856294b-ea56-4d7b-a7fa-ec9d0f84522b.png">

<img width="915" alt="Screen Shot 2022-01-19 at 9 22 44 AM" src="https://user-images.githubusercontent.com/29186822/150177664-7f6fcda1-6a18-4d27-9956-ae706b0a59ca.png">
