### ISSUE TITLE
Removing ApiGatewayRequestInterceptor from Amplify Configuration on signOut

### ISSUE THREAD

**Issue by markfraserr** [aws-amplify/amplify-ios#1591]
My project has implemented a re-authentication solution using Amplify which retrieves valid **Authorization** + **Identification** tokens when challenged by a REST service call. After validating and receiving the tokens, we are adding a **ApiGatewayRequestInterceptor** to our Amplify configuration so that all future calls will include these valid tokens in their headers to avoid the need to authenticate as long as those tokens are valid. 
`Amplify.API.add(interceptor: interceptor, for: self.apiName)`

However, when we call **signOut** and login with a new user this **ApiGatewayRequestInterceptor** is persisting in our Amplify configuration. Since these persisting tokens would still be considered valid from our backend we are no longer prompted for re-authentication until the tokens expire or Amplify is configured again on app start.

I haven't found a way to clear this interceptor when logging out. Any suggestions?

**Comment by lawmicha** [comment]
Hi @markfraserr, there currently isn't a way to remove an interceptor from the APIPlugin. Are you able to change the implementation of **ApiGatewayRequestInterceptor** to check if the user is signed out to stop intercepting the request with the token? Another workaround may be to stop using the interceptor all together and do the logic before you create the request and pass the information through `RESTRequest.headers` field

**Comment by lawmicha** [comment]
Feel free to let us know if you ended up solving the problem with one of the mentioned solutions or if you have any more questions
