### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-ios#1592]
Currently when the user signs in using cognito pool, I have a lambda function Post email confirmation so a a field on DynamoDB is created.

Apple is soon going to enforce account deletion. How can I do the same but backwards so when I hit delete on the app, it deletes the cognition account? The dynamodb part doesn't seem complicated, but how would I delete the cognito email?

Thanks

**Comment by ameter** [comment]
Thanks for the question.  We are preparing a feature to support Cognito User Pool account deletion in Amplify to enable compliance with Apple's mandate.  We hope to have this functionality ready for release within the next week.  We will post an update here when it's available.

**Comment by ameter** [comment]
Amplify v1.19.0 was just released with support for Cognito User Pool account deletion.  Additional documentation will be released soon, but in the meantime, here's an example usage:
```swift
        Amplify.Auth.deleteUser { result in
            switch result {
            case .success:
                print("Successfully deleted user")
            case .failure(let error):
                print("Failed to delete user with error: \(error)")
            }
        }
```

**Comment by afern247** [comment]
> Amplify v1.19.0 was just released with support for Cognito User Pool account deletion. Additional documentation will be released soon, but in the meantime, here's an example usage:
> 
> ```swift
>         Amplify.Auth.deleteUser { result in
>             switch result {
>             case .success:
>                 print("Successfully deleted user")
>             case .failure(let error):
>                 print("Failed to delete user with error: \(error)")
>             }
>         }
> ```

Excellent! Thank you

**Comment by afern247** [comment]
Is there any trigger for this? I see we have a post verification signup trigger (which is what I'm using to create the dynamodb table):

```
Do you want to configure Lambda Triggers for Cognito? Yes
Which triggers do you want to enable for Cognito?  Post Confirmation
```

Do we have anything like this for deletion? If not how can I implement it?

@ameter @royjit
