### ISSUE TITLE
AWS Amplify AUTH with Cognito - Social sign in with web UI, returns "Invalid relay state from identity provider"

### ISSUE THREAD

**Issue by Wazambe** [aws-amplify/amplify-ios#1602]
### Describe the bug

I've set up social sign-in with web ui. (Xcode ios SwiftUI)
All of that works fine, till after Login, where the social provider (Google and facebook) returns with error 
[ Invalid relay state from identity provider ]

To simplify I ran the CLI 'Amplify Status' to get the test for endpoint. Also there I then get the error [ Invalid state ]

So redirect URI is correct, but obviously something wrong with with the endpoint. 

Went to Cognito console to see if I can identify any issues, but clearly I'm missing something. 
It does however look like this may be a Cognito identity previously associated with an  earlier app, possibly (although I an not able to categorically say that it is in fact the case). 

This does not seem to be a generic bug, but more like situation conditional.

### Steps To Reproduce

```swift
-In terminal, go to app directory.

-Run'Amplify Status'
-Copy test link from "Test Your Hosted UI Endpoint:" into browser.

-Click Facebook signIn = receive 'Invalid state' response.

-Click Google signIn = receive 'Invalid state' response.
```

### Expected behavior

Would expect a resolve, I suppose.

Issue may be instance specific, but could be worth investigating the link to federated identities arn for amplify projects. 
(i may be way off the mark)

If someone can point me to some workflow/checklist for the Cognito federated identities, or know the cause of this state error, it would help a lot

### Amplify Framework Version

current?

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

7.6.11

### Xcode version

13.2.1 (13C100)

### Relevant log output

```shell
'User Cancelled' - The web UI View
```

### Is this a regression?

No

### Device

all

### iOS Version

15

### Specific to simulators

no

**Comment by royjit** [comment]
Hi @Wazambe 
Did you setup amplify using Amplify CLI by calling `amplify add auth`. Can you provide the following info:
1. Content of `amplifyconfiguration.json` after redacting sensitive info
2. Code sample on how you are invoking webui
3. Did you setup call back url for the iOS app
