### ISSUE TITLE
Make Logging and Hub categories available at initialization

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#161]
Right now, it is impossible for callers to use the Logging or Hub categories until we've called `Amplify.configure`. This needs to be changed so that default plugins can use the logger and hub during initialization and configuration flows.

We've made partial progress toward that--the Hub and Logging categories are the first to be `configure`d, but that isn't sufficient for (for example) setting up a Plugin that uses the logger during its initialization.

**Comment by jamesonwilliams** [comment]
On Android, I did sort of a hack, to support this. The Logging category will internally call a `getLoggingPlugin()` method, whenever it delegates a behavior from its API surface:
```
@NonNull
private LoggingPlugin<?> getLoggingPlugin() {
    try {
        return getSelectedPlugin(); // If someone added a plugin, use it
    } catch (IllegalStateException pluginAccessException) {
        return new AndroidLoggingPlugin(); // Otherwise, fallback to ours.
    }
}
```
So, if someone _does_ do:
```
Amplify.addPlugin(new CustomLoggingPlugin());
Amplify.configure(context);
```
That will work.

But, if they don't, we just use our internal default (which is defined in the Core module.)

**Comment by drochetti** [comment]
@palpatim it seems like this one is fixed, can you confirm?

**Comment by palpatim** [comment]
Yep, confirmed.
