### ISSUE TITLE
Cognito "RESET_REQUIRED"  is not Working for ios SDK

### ISSUE THREAD

**Issue by eyadmask** [aws-amplify/amplify-ios#1616]
### Describe the bug

- using Amplify iOS SDK, Cognito console  "Reset Password" is not working as expected
- There is no way of reading Cognito "Account Status" using Amplify iOS SDK

### Steps To Reproduce

```swift
- Go to Cognito Console
- Click on"Reset password" Button for a User 
- The "Account Status" then will be changed to "RESET_REQUIRED"
- Then try signing-In to the same account using existing password thru  Amplify iOS API and it will let you in with nothing to notify you to reset the password first
```

### Expected behavior

- the sign-In API call should fail with notification to Reset existing password first
- There should be away to read Cognito "Account Status" using Amplify iOS SDK

### Amplify Framework Version

1.19.1

### Amplify Categories

API, Auth

### Dependency manager

Swift PM

### Swift version

5.3

### CLI version

7.6.13

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPad & iPhone

### iOS Version

15.2

**Comment by atierian** [comment]
Hi @eyadmask, thanks for opening this issue. I was able to reproduce this issue. 
Interestingly, these steps will result in a `passwordResetRequired` error:
1. Sign in
2. Set `RESET_REQUIRED` in Cognito User Pool
3. Sign out

We'll take a closer look at this and update the issue.

**Comment by ruisebas** [comment]
Hi @eyadmask!

I followed the steps to reproduce and while it's true that the signIn API returns a `Success` result, its associated value is a [`AuthSignInResult`](https://aws-amplify.github.io/amplify-ios/docs/Structs/AuthSignInResult.html) object consisting of an `isSignedIn` flag and a `nextStep` enum. 

On this particular case, this was the response I got:

```
▿ result: Amplify.AuthSignInResult
  - isSignedIn: false
  ▿ nextStep: Amplify.AuthSignInStep.resetPassword
    - resetPassword: nil
```

Could you please confirm if you are getting a different result on your use case? You can use something like this to quickly check:

```
Amplify.Auth.signIn(username: username, password: password) { result in
    switch result {
    case .success(let signInResult):
        dump(signInResult.isSignedIn, name: "isSignedIn")
        dump(signInResult.nextStep, name: "nextStep")
    case .failure(let error):
        dump(error, name: "Error")
    }
}
```

More detailed information about the sign in steps is available [here](https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/ios/).

**Comment by ruisebas** [comment]
I've created a separate issue for the situation described by @atierian [above](https://github.com/aws-amplify/amplify-ios/issues/1616#issuecomment-1027022537), as it's not directly related to the one being discussed here:  https://github.com/aws-amplify/amplify-ios/issues/1633
