### ISSUE TITLE
DataStoreError: The key `__typename` was not found

### ISSUE THREAD

**Issue by LeoReubelt** [aws-amplify/amplify-ios#1618]
### Describe the bug

I had a schema and app that was working. I added two string fields to the schema and pushed. Now I get the following...

DataStoreError: An error occurred syncing DicomImageGroup
Caused by:
DataStoreError: failed to process graphqlResponseData
Caused by:
APIError: failed to process graphqlResponseData
Caused by:
DataStoreError: The key `__typename` was not found
Recovery suggestion: Check if the parsed JSON contains the expected `__typename`

I have very little confidence that the steps to reproduce provided below will not work for you, but that is all i changed and i was not getting the errors before so something was changed in that push.  There is already an issue for this, but it was closed without a solution.  https://github.com/aws-amplify/amplify-ios/issues/507. 

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Start with the schema below...
type DicomImageGroup @model @auth(rules: [{allow: private}]) {
  id: ID!
  description: String!
  patientId: ID @index(name: "byPatient", sortKeyFields: ["description"])
  dicomImages: [DicomImage] @hasMany(indexName: "byGroup", fields: ["id"])
  anatomies: [Anatomy] @manyToMany(relationName: "DicomImageGroupAnatomy")
}

2. Change the the schema below...
type DicomImageGroup @model @auth(rules: [{allow: private}]) {
  id: ID!
  assignedToId: String!
  description: String!
  patientId: ID @index(name: "byPatient", sortKeyFields: ["description"])
  dicomImages: [DicomImage] @hasMany(indexName: "byGroup", fields: ["id"])
  anatomies: [Anatomy] @manyToMany(relationName: "DicomImageGroupAnatomy")
}

```

### Expected behavior

Adding two strings to the schema wouldn't break the app.

### Amplify Framework Version

1.19.1

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

7.6.12

### Xcode version

13.2.1

### Relevant log output

```shell
This error is logged repeatedly for every model in the schema.

One or more errors occurred syncing models. See below for detailed error description.
2022-02-01 15:52:15.773355-0500 ScissorsaurusRex[4268:2732220] [RemoteSyncEngine] DataStoreError: An error occurred syncing DicomImageGroup
Caused by:
DataStoreError: failed to process graphqlResponseData
Caused by:
APIError: failed to process graphqlResponseData
Caused by:
DataStoreError: The key `__typename` was not found
Recovery suggestion: Check if the parsed JSON contains the expected `__typename`
```

### Is this a regression?

No

### Device

iPad pro 11 inch

### iOS Version

15.2.1

**Comment by LeoReubelt** [comment]
i got it. it was because i pushed a new string that was required and there was existing data.

**Comment by RikiZimbakov** [comment]
can you elaborate please? this started happening to me randomly and I didnt change the schema or my code in anyway

**Comment by vgribok** [comment]
> i got it. it was because i pushed a new string that was required and there was existing data.

That was it. The error message is not at all informative.

**Comment by frnzgmbh** [comment]
Error:
DataStoreError: The key __typename was not found

General root cause:
There is an inconsistency with database/tables/items/entry value. This means that you have an entry that does not match your defined schema structure, or the database on the cloud is in contradict with the database on the device.

Solution:
You need to find that particular non-conforming table, or item, or entry value and amend/delete that from database on the cloud. Restart, and you are good to go.
