### ISSUE TITLE
AWSDataStoreObserveQueryOperation Delete does not trigger snapshot

### ISSUE THREAD

**Issue by heyltsjay** [aws-amplify/amplify-ios#1627]
### Describe the bug

User impact:
Delete events do not trigger snapshot observation

Technical issue:
When `initialQuery()` is run at the beginning of a snapshot subscription, the result is placed into
```
currentItems.sortedModels
```
but the `currentItems.modelIds` are not set alongside it.

As a consequence `SortedList.remove` fails to lookup the model object because it first checks
```
modelIds.contains(model.id)
```
but `modelIds` was never populated.

### Steps To Reproduce

```swift
1. `DataStore.observeQuery` some model array
2. `DataStore.delete` some model
3.  observeQuery does not receive update
```

### Expected behavior

Deletes trigger new snapshot

### Amplify Framework Version

1.9.2

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

5.5

### CLI version

N/A

### Xcode version

13.2.1

### Is this a regression?

Yes

### Regression additional context

Introduced in https://github.com/aws-amplify/amplify-ios/pull/1522

### Device

N/A

### iOS Version

15+

**Comment by lawmicha** [comment]
Hi @heyltsjay thanks for bringing this to our attention. I'm working on a fix here https://github.com/aws-amplify/amplify-ios/pull/1663

**Comment by lawmicha** [comment]
Hi @heyltsjay this has been released in this has been released in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.22.0 please let us know if you have any issues
