### ISSUE TITLE
Amplify.Auth.signInWithWebUI does not redirect back to SceneDelegate after login

### ISSUE THREAD

**Issue by roberthartman** [aws-amplify/amplify-ios#1629]
### Describe the bug

I am proving out a "Sign in with Google" feature using Amplify. I can successfully login and login out using:
`Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: window, options: nil)` and
`Amplify.Auth.signOut(options: .init(globalSignOut: false, pluginOptions: nil))`
The hosted UI is shown, the app screen that launches the request is returned to after login, I can successfully fetch the session etc. All is well, except that neither of these functions are called after the login completes:
`SceneDelegate.scene(_:openURLContexts:)`
`SceneDelegate.scene(_:willConnectTo:options:)`

I've verified that I can open the app via the custom URL scheme by entering the `SignInRedirectURI` from `amplifyconfiguration.json` into Safari on a phone; when I do so, iOS prompts to open the page in the app: "Open this page in "App name"?" Tapping "Open" causes the app to open, with one of the above `SceneDelegate` functions being called to launch the app. To me, that indicates the app is properly configured in `Info.plist` with the custom URL scheme.

Getting the SceneDelegate callbacks after the WebUI signin is required for this application, so without them, I am stuck. I haven't been able to find anyone who has similarly encountered this issue in my web searches.

Am I incorrect in assuming that one of the `SceneDelegate` callbacks will be invoked?

Should I be passing certain `AuthWebUISignInRequest.Options` in the call to `Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: window, options: nil)`?

### Steps To Reproduce
See the above description.

### Expected behavior

`SceneDelegate.scene(_:openURLContexts:)` or `SceneDelegate.scene(_:willConnectTo:options:)` would be called after logging via `signInWithWebUI()`

### Amplify Framework Version

1.19.2

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.5.1

### CLI version

NA - Amplify config was pre-provided by the customer

### Xcode version

13.1

### Is this a regression?

No

### Device

iPhone SE 2020

### iOS Version

15.2.1

**Comment by roberthartman** [comment]
I have a little more insight into this now. I think that the reason the `SceneDelegate` functions are not called is because the app is never "left". It seems like `signInWithWebUI` simply presents a modal WebView of some sort _inside_ the app. So there is no need to relaunch the app with the custom URL. This makes me wonder then how or in what circumstances `SignInRedirectURI` comes into play at all.

**Comment by royjit** [comment]
Amplify uses ASWebAuthenticationSession internally to show the signIn UI. the signInRedirectURI is used as the callback URL scheme here: 

https://github.com/aws-amplify/aws-sdk-ios/blob/67973f8e011e4307fe61966fe1d86539dedf3673/AWSCognitoAuth/AWSCognitoAuth.m#L619
