### ISSUE TITLE
App not synced immediately with API

### ISSUE THREAD

**Issue by nyeu** [aws-amplify/amplify-ios#1631]
### Describe the bug

I am using Amplify for `Auth`, `Function`, `Storage` and `Api` and I am encountering a very annoying issue where some things are not up to date until 2-3 hours later.

My user case is, from the iOS app I create an object `Metadata` that has a `status` enum set to `uploading`. Once I upload a video to S3 this is set to `uploaded`. Then a lambda function is triggered, does some work and changes the state to `OK`. This change is never reflected immediately in the app, I have to wait 2-3 hours to see it changed. I kill/open the app, I refresh the queries, etc and nothing happens. This happens about 50% of the times I would say. 

I cleared all my db and I have even narrowed down the schemas to make sure there's nothing failing under the hood. Objects used to be related between them and I even removed all of that. It's just a bunch of strings, enums and booleans.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create an object with a field `status` that is an `enum`.
2. Save it to with Amplify in an iOS app
3. Perform a lambda operation that changes `status` to something.
4. See that the data in the app is not getting that change no matter what.
```

### Expected behavior

The data should be up to date immediately when performing a query.

### Amplify Framework Version

1.19.0

### Amplify Categories

API, DataStore

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

7.6.10

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone 13 Pro

### iOS Version

15.0

### Additional context

This is exactly my model:
```
type Metadata @model @auth(rules: [{ allow: owner } {allow: public, operations: [create, read, update]}]) {
  id: ID!
  creatorUserID: String!
  process_status: ProcessStatus!
  has_keypoints: Boolean!
  date_uploaded: String!
  date_processed: String!
  summary_url: String
}

```

This is how I do the query:

```

guard let userID = UserService.shared.user?.id else {
            return
        }
        
        let keys = Metadata.keys
        Amplify.DataStore.query(Metadata.self, where: keys.creatorUserID == userID) {
            switch $0 {
            case .success(let metas):
                metas = metas
            case .failure(let error):
                print(error.recoverySuggestion)
            }
        }
```

**Comment by nyeu** [comment]
Yea, S3 sends an event to the lambda function that modifies the DynamoDB table using `boto3`, which is the Python SDK for AWS.

Everything seems aligned and working well, the "only" issue is that we have to wait 3-4 hours to see the changes made by the lambda into the app. This has cause us a lot of issues with our current users and while we had some workarounds, we really need to have this working.

**Comment by lawmicha** [comment]
Hi @nyeu, by making direct modifications to the DynamoDB table within your lambda, there isnt any events sent back to the clients. For the changes to show up in the app, you'll have to directly send the mutations in your lambda. The client apps with DataStore internally set up subscribers to the corresponding subscriptions. When the mutation is triggered from another client then the subscription event with the mutation response is sent to the subscribers. 

When sending the mutation, it is important to put in all the necessary fields in the selection set, please see https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/ios/#writing-data-from-the-appsync-console for more details. Let us know if you have more questions

**Comment by lawmicha** [comment]
Feel free to let us know if you have other issues
