### ISSUE TITLE
No such module Amplify 

### ISSUE THREAD

**Issue by ngocdtph03070** [aws-amplify/amplify-ios#1643]
### Describe the bug

Error no such module Amplify 
<img width="1391" alt="Screenshot 2022-02-23 at 12 10 10 PM" src="https://user-images.githubusercontent.com/20571021/155265037-b5a8b789-eb6f-4325-91c6-b7e045e09533.png">

<img width="1398" alt="Screenshot 2022-02-23 at 12 26 41 PM" src="https://user-images.githubusercontent.com/20571021/155266079-2a1a3895-af7a-44a6-93d1-b568336f54e1.png">
### Steps To Reproduce

```swift
I use cocoapods to install amplify but when the installation is done execute build then error no such module amplify


```

### Expected behavior

Xcode can build app 

### Amplify Framework Version

1.19.2

### Amplify Categories

Analytics

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

7.6.21

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone XR 

### iOS Version

15.2.1

**Comment by diegocstn** [comment]
Hi @ngocdtph03070 , thanks for reaching out to us.
Based on the screenshot you provided, looks like the Amplify product hasn't been produced correctly (Xcode is highlighting that in red).
Is `pod install` returning you any error or warning?

Also `Amplify/Tools` has been deprecated, you can safely remove it from your `Podfile`.
