### ISSUE TITLE
Upgrade pluralName

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-ios#1645]
I'm seeing the following warning all over my code:

`'pluralName' is deprecated: Use of pluralName is deprecated, use syncPluralName instead.`

![image](https://user-images.githubusercontent.com/34192856/155453416-84ef04d1-8cee-49e2-88b0-63133a50811b.png)

Here's an example:

`model.pluralName = "Users"`

just rename it to:

`model.syncPluralName = "Users"`

These warnings are happening in the GraphQL models generated when using DynamoDB

**Comment by diegocstn** [comment]
hi @afern247,
we introduced `syncPluralName` and deprecated `pluralName` to workaround a CLI issue. 
You can safely ignore those warnings, usage of `pluralName` will be removed in a future iteration of the codegen module and therefore removed from your models the next time you run `amplify codegen models`.

**Comment by diegocstn** [comment]
I'm optimistically closing this but feel free to reopen if you have additional concerns.

**Comment by aarku** [comment]
I'm just trying out Amplify DataStore to potentially replace Realm over a year later and found the same exact issue in version 11.0.3 of the Amplify CLI. Am I doing something wrong, or has this not been fixed? It couldn't be that hard to fix?

**Comment by julianworden** [comment]
> I'm just trying out Amplify DataStore to potentially replace Realm over a year later and found the same exact issue in version 11.0.3 of the Amplify CLI. Am I doing something wrong, or has this not been fixed? It couldn't be that hard to fix?

You're not doing anything wrong, it's still not fixed. Same issue here.

**Comment by afern247** [comment]
Why is this even closed then?

**Comment by johnnyabercrombie** [comment]
can this be reopened? still an issue

**Comment by afern247** [comment]
@johnnyabercrombie it seems there is already a ticket open for this, we should follow that one and stop commenting on this one. Here's the ticket:

https://github.com/aws-amplify/amplify-swift/issues/2460

**Comment by elusivestudio** [comment]
CLI still give us 'pluralName'. Any update on this warning?

**Comment by afern247** [comment]
> CLI still give us 'pluralName'. Any update on this warning?

You need to open a new ticket, they don't check the ones that are closed
