### ISSUE TITLE
Unable to use combine framework for deleting user

### ISSUE THREAD

**Issue by charlie-luple** [aws-amplify/amplify-ios#1647]
### Describe the bug

When I tried to use the below code as [Amplify Docs](https://docs.amplify.aws/lib/auth/delete_user/q/platform/ios/) described,
```
func deleteUser() -> AnyCancellable {  
   Amplify.Auth.deleteUser()  
        .resultPublisher  
        .sink {  
            if case let .failure(authError) = $0 {
                print("Delete user failed with error \(authError)")
            }
        }
        receiveValue: {
            print("Successfully deleted user")
        }
}
```

the following error occurs. **No exact matches about property 'resultPublisher'**.

So I looked into a file named 'AmplifyOperation+AuthPublishers' which I jumped from using the below code .`Amplify.Auth.signOut(options: .init(globalSignOut: true)).resultPublisher.`

```
    func signOutGlobally() -> AnyPublisher<Void, AuthError> {
        let resultPublisher = Amplify.Auth.signOut(options: .init(globalSignOut: true))
            .resultPublisher
        return resultPublisher
    }
```
And I found out that there was **no AmplifyOperation extension for deleting user** in  'AmplifyOperation+AuthPublishers' whereas AuthSignOutOperation, AuthSignUpOperation, and other AmplifyOperation extensions were defined. I guess this is the reason why I can't use `Amplify.Auth.deleteUser().resultPublisher`.

**Comment by ameter** [comment]
Thanks for bringing this to our attention!  We'll create a fix for this and provide an update here when it's available.

**Comment by ameter** [comment]
This issue has been fixed and will be included in the next release.

**Comment by royjit** [comment]
Released - https://github.com/aws-amplify/amplify-ios/releases/tag/v1.22.0
