### ISSUE TITLE
403 Error making Rest Post call.

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1648]
I have an Amplify project using both GraphQl and Rest API with Cognito User Pools.  The Auth User Pool has been imported.

GraphQL works fine but I can't get Rest to work.

I keep getting a 403 error and the lambda is not called.

I have selected only authorized users during the rest setup and enabled CRUD for authorized users only and no guest access.

I see the config file has authorization type set to "AWS_IAM".  Changing this to AMAZON_COGNITO_USER_POOLS and adding a custom Authorizer in console for user pools is not working.

I'm not sure why this is not working or how to fix it.

**Comment by royjit** [comment]
You might need to update the APIGateway to use UserPool as the authorizer. Navigate to API Gateway console, select your API:

1. Add Cognito User Pool as an authorization mechanism. Select Authorizers, click on "+ Create New Authorizer",
type in a Name like <UserPoolAuthorizer>
1. Select Cognito as the type
1. Select the Cognito UserPool, the name corresponds to the name of the user pool at the top left corner when on the User Pool console.
1. For Token Source, enter Authorization
Once completed, refresh the page.
