### ISSUE TITLE
How can I model a @manyToMany with same table?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1649]
I have a User table in my schema.  I would like users to be able to add other users as contacts.  To do this I want a manyToMany relation with a user to another user but I can't figure out how to use the @manyToMany to achieve this.  I have tried:

```
type ServerUser
  @model
  @auth(
    rules: [
      { allow: private, operations: [read] },
      { allow: owner, operations: [create, delete, update] }
    ]
  ) {
  id: ID!
  owner: String
  username: String!
  contacts: [ServerUser] @manyToMany(relationName: "UserContacts")
  contactOfOthers: [ServerUser] @manyToMany(relationName: "UserContacts")
}
```

but got the error serverUserID cannot reference itself.  

How can I setup a relation between users similar to what you see in any chat app?

**Comment by diegocstn** [comment]
@alionthego due to internal CLI naming conventions, `@manyToMany` relationships between the same model are not supported. I've created an issue in the CLI repository https://github.com/aws-amplify/amplify-cli/issues/10074.

**Comment by diegocstn** [comment]
I'll close this in favour of https://github.com/aws-amplify/amplify-cli/issues/10074, but feel free to reopen if you need more help.
