### ISSUE TITLE
How can I auto generate createdAt and updatedAt and also be able to query those fields

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-ios#1651]
I am using GraphQL API with iOS sdk.

The only way I can query with a date predicate on createdAt or updatedAt is by explicitly including those fields in the schema.  The problem is when I do that, those fields are no longer auto generated and I have to supply values which allows the user to change their time on the client and create problems.

How can I have the server automatically add the createdAt and updatedAt timestamps but also be able to have a date predicate?

**Comment by royjit** [comment]
Which version of the Amplify CLI are you using? You can check the version by running:

```
amplify -v
```

Also can you give us the following details as well:
- Amplify iOS version 
- Are you using DataStore or API?
- Example of their schema

**Comment by brennanMKE** [comment]
@alionthego Please reach out to us on Discord as well and we could set up a time to work with you.

https://discord.com/invite/amplify

**Comment by lawmicha** [comment]
Hi @alionthego, please see above questions and let us know in a new issue with more info if you are still looking to achieve your query use case
