### ISSUE TITLE
Documentation of GraphQL is not accurate

### ISSUE THREAD

**Issue by carl0sLOL** [aws-amplify/amplify-ios#1657]
### Describe the bug

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/42389884/156503123-8c1b334a-d58a-443e-a182-4d061f2573f6.png">

As seen above, Project @hasOne Team which @belongsTo Project. This does not work in real life implementation. 
Error: Value type 'Project' cannot have a stored property that recursively contains it

### Steps To Reproduce

```swift
Copy and paste the code in the documentation into schema.graphql
Run 'amplify codegen models'
Move 'models' folder to project
Build project
```

### Expected behavior

It should work as documented in the documentation.

### Amplify Framework Version

1.21.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

7.6.22

### Xcode version

13.2.1 (13C100)

### Relevant log output

```shell
error is within XCode.
```

### Is this a regression?

No

### Device

Iphone 12ProMax

### iOS Version

15

### Specific to simulators

No

**Comment by thisisabhash** [comment]
Hello,

This is a known issue in iOS in case of bi-directional connections where one model has hasOne and other model has belongsTo relationship. Models are `struct` in Amplify iOS and therefore are value types. Swift doesn't allow recursive value types. We are continuously trying to improve DataStore and will post here when we have further updates for this issue.

**Comment by atierian** [comment]
Thanks for opening this issue @carl0sLOL.
We've updated the documentation here https://github.com/aws-amplify/docs/pull/4339.
We're also tracking the underlying issue here https://github.com/aws-amplify/amplify-ios/issues/1541.

**Comment by atierian** [comment]
Closing this issue in favor of #1541 to track the underlying issue.
Documentation issue addressed as noted above.
