### ISSUE TITLE
Incorrect isSignedIn property in Amplify.Auth.fetchAuthSession when Cognito session has expired.

### ISSUE THREAD

**Issue by onizine** [aws-amplify/amplify-ios#1660]
### Describe the bug

If isSignedIn in Amplify.Auth.fetchAuthSession is Subsequent CognitoTokens throw an exception despite it being true

### Steps To Reproduce

Incorrect isSignedIn property in Amplify.Auth.fetchAuthSession when Cognito session has expired.

Subsequent CognitoTokens throws exception even though isSignedIn is true in Amplify.Auth.fetchAuthSession

1. create a user in Cognito. Set the minimum update token expiration time to 60 minutes in the app client settings.

2. Sign in with Amplify.Auth.SignIn from iOS app.

3. Let 60 minutes pass. No explicit logout is performed.

4. call Amplify.Auth.getchAuthSession from iOS app.

5. The result of the callback isSignedIn is true.

6. calling getCognitoTokens method of AuthCognitoTOkenProvider raises an exception.

### Expected behavior

The result of Amplify.Auth.getchAuthSession should be isSignedIn = false.

### Amplify Framework Version

1.20.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5

### CLI version

6.3.1

### Xcode version

13.0

### Is this a regression?

No

### Device

iphone8

### iOS Version

iOS 14.3

### Additional context

Sample Code is here
``` swift

import Amplify
import AWSPluginsCore

func fetchAuth() {
  Amplify.Auth.fetchAuthSession { result in 
    do {
      let session = try result.get()

      // It is false if the session has expired.
      print(session.isSignedIn)

    } catch {
      print(error.localizedDescription)
    }
  }
}
```

**Comment by royjit** [comment]
That is the expected behavior of the library. `isSignedIn` will only turn to false when you call Amplify.Auth.SignOut. During session expiration, you are still signed in to Amplify.Auth, you would just need to re-authenticate for valid tokens/credentials.

**Comment by onizine** [comment]
royjit

Thanks for the reply.

I take isSignedIn as if it represents a state.
However, I believe it is only a flag that only represents the history of actions.

For example, in the AWS workshop, isSignedIn is used to determine if a user is already logged in. I don't think this is an appropriate use of isSignedIn.
My point is that I am concerned that isSignedIn may be misleading.

https://amplify-ios-workshop.go-aws.com/30_add_authentication/20_client_code.html



Translated with www.DeepL.com/Translator (free version)

**Comment by royjit** [comment]
The `isSignedIn` is meant to be used to see whether the user had authenticated with Amplify. It can be used in a scenario where the app stays signed in always and just shows cached content. Only when the app tries to access restricted section, it will check the tokens and find that they are expired and then invoke Amplify.Auth.signIn.

If you would always want the app to be with valid session, you would invoke `Amplify.Auth.fetchAuthSession` at start up and either listen to the sessionExpired hub event or check the `AuthCognitoTokensProvider` result. If the result is session expired error, ask the user to signIn again.
