### ISSUE TITLE
Query and Subscription Error after app goes to background then back

### ISSUE THREAD

**Issue by YuantongL** [aws-amplify/amplify-ios#1672]
### Describe the bug

Press home button and let app goes to background, then bring it back after a few seconds, I see failure on both Subscription and Query

### Steps To Reproduce

Subscription:
(I see the issue only on real device, simulator always works)
1. Have a ViewModel and call API's subscribe to a modal creation event.
2. Verify subscription works well.
3. Press "home" button and put the app into background.
4. After a few seconds (amount of time can vary), tap app icon and bring app back to live
5. Subscription will throw have exception (I'm using Combine, so this was caught in `.sink(completion)`)
```swift
Thread 1: Fatal error: Subscribe to conversation failure APIError: Subscription item event failed with error
Caused by:
connection
```

Query:
1. Have a ViewModel and have a function to perform a Query.
2. Verify query works well.
3. I want the query to perform during app becomes live, so
```swift
NotificationCenter.default
            .publisher(for: UIApplication.didBecomeActiveNotification)
            .sink { [weak self] _ in
                self?.performQuery()
            }
            .store(in: &cancellables)
```
3. Press "home" button and put the app into background.
5. After a few seconds (amount of time can vary), tap app icon and bring app back to live.
6. performQuery() fails with the following failure.
```swift
Thread 1: Fatal error: APIError: The network connection was lost.
Recovery suggestion: The network connection was lost.
Caused by:
Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=53, NSUnderlyingError=0x28304a520 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=53, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <68E8F86B-5F28-4199-AF30-12F42FF66356>****
```

Note:
All above was performed on physical device, with stable wifi connection, the device was never locked and app only goes to background no more than 10 seconds.

### Expected behavior

Subscription and Query should resolve just like normal.

### Amplify Framework Version

1.21.0

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5

### CLI version

7.6.22

### Xcode version

13.1

### Is this a regression?

Yes

### Regression additional context

Not 100% sure was a regression, since this is a newly implmented feature on my project.

### Device

iPhone X max

### iOS Version

15.3.1

**Comment by ameter** [comment]
Thanks for reporting this.  We will investigate and provide an update here when we have additional information.

**Comment by lawmicha** [comment]
Hi @YuantongL, a short-ish update here. I've been experimenting with a sample app launched on a device, while connected to Xcode for debugging. With a normal bootstrapped App project, I suspect there isn't any background permissions set up for the library to successfully finish the query using the URLSession. The subscription is also receiving a websocket disconnect event from our underlying dependency Starscream websocket client. I'll check in with the team to discuss this behavior and see if there's some things the library can do. 

For now, would this work for your app use cases? call `createSubscription` if the subscription receives an error.
```swift
func createSubscription() {
        subscription = Amplify.API.subscribe(request: .subscription(of: Todo.self, type: .onCreate))
        dataSink = subscription?.subscriptionDataPublisher.sink {
            if case let .failure(apiError) = $0 {
                print("Subscription has terminated with \(apiError)")
                self.createSubscription()
            } else {
                print("Subscription has been closed successfully")
                
            }
        }
        receiveValue: { result in
            switch result {
            case .success(let createdTodo):
                print("Successfully got todo from subscription: \(createdTodo)")
            case .failure(let error):
                print("Got failed result with \(error.errorDescription)")
            }
        }
    }
```

**Comment by YuantongL** [comment]
Hi @lawmicha, thanks for looking in to this.
I actually took a different route, I will cancel the subscription on `didEnterBackgroundNotification` and re-set up subscription again on `didBecomeActiveNotification`, so far it works fine for me.

**Comment by lawmicha** [comment]
Thanks for the update @YuantongL, i believe what you did is needed since the app may not have network connection in the background and is up to the system to determine when that happens. This is the same case for an in-progress query. In my sample app, I also saw the in-flight queries fail when the app is in the middle of a query and is sent to the background. I was able to successfully perform a query in the `didBecomeActiveNotification` notification closure. Are you still seeing any issues regarding the query use case?

**Comment by YuantongL** [comment]
It is working fine for me with use of `didBecomeActiveNotification` as indication of starting the query and subscription so far.

**Comment by YuantongL** [comment]
However, that means we should disconnect every subscription, cancel every query on receiving `didEnterBackgroundNotification` to make sure no error was caught. Is this how we suppose to use it?

**Comment by lawmicha** [comment]
Hi @YuantongL, I would just let the query fail and perform the query when you need the data. This may be when the app is just entering foreground as you have, or due to a user action or transition to another view appearing. You can also replace the existing subscription with a new subscription when the app goes into foreground, without calling unsubscribe on the `didEnterBackgroundNotification`
