### ISSUE TITLE
AWSLocationXCF.build/all-product-headers.yaml not found

### ISSUE THREAD

**Issue by YuantongL** [aws-amplify/amplify-ios#1694]
### Describe the bug

got error when `po` anything in debugger
```
error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/AWSiOSSDKv2-bvcffhrgbfjnfybjecennhscmaho/Build/Intermediates.noindex/ArchiveIntermediates/AWSLocationXCF/IntermediateBuildFilesPath/AWSiOSSDKv2.build/Release-iphonesimulator/AWSLocationXCF.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/AWSiOSSDKv2-bvcffhrgbfjnfybjecennhscmaho/Build/Intermediates.noindex/ArchiveIntermediates/AWSLocationXCF/IntermediateBuildFilesPath/AWSiOSSDKv2.build/Release-iphonesimulator/AWSLocationXCF.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```
I suspect its Amplify only because this is the only aws package my project uses. Now `po` is unusable.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. import amplify-ios 1.21.0 in the project through SPM
2. run the project
3. trigger breakpoint
4. try `po` anything
5. observe above error and no value was printed out
```

### Expected behavior

`po` shoud print out value

### Amplify Framework Version

1.21.0

### Amplify Categories

API, Auth

### Dependency manager

Swift PM

### Swift version

5.5.1

### CLI version

7.6.22

### Xcode version

13.2.1

### Is this a regression?

No

### Device

simulator

### iOS Version

15.3.1

**Comment by harsh62** [comment]
@YuantongL [This blog](https://andresalla.com/en/fixing-virtual-filesystem-overlay-file-all-product-headers-yaml-not-found-error/) very nicely explains how this issue could be fixed. Can you please run through the steps and see if this gets resolved. If the issue still persists, let us know and we will further investigate it.

**Comment by YuantongL** [comment]
Thanks for looking into this issue, the issue went away after I updated Amplify to 1.22.0, the issue persist all the time with me during 1.21.0.
