### ISSUE TITLE
Xcode 13.3 - Swift 5.6

### ISSUE THREAD

**Issue by ryancrunchi** [aws-amplify/amplify-ios#1697]
### Is your feature request related to a problem? Please describe.

Xcode 13.3 ships with Swift 5.6. It seems Xcode 13.3 does not have toolchains option to change swift version to compile the project. So we are stuck with Swift 5.6 and can't downgrade to 5.5.

With Swift 5.6 project is not compiling due to dependency with ClientRuntime package :
```swift
#if swift(>=5.6)
      #error("Cannot use a version of Swift greater than available. Please create a Github issue for us to add support for the version of Swift you want to use.")
```

### Describe the solution you'd like

Allow building with Swift 5.6

### Describe alternatives you've considered

Downgrading Swift version for compilation seems not easily feasible in Xcode 13.3.

### Additional context

Xcode 13.3
Swift Package Manager
branch dev-preview

**Comment by atierian** [comment]
Thanks for opening this issue @ryancrunchi.
A new dev preview version that fixes this was just released as `1.23.0-dev-preview.0`.
You can use this version or continue using the `dev-preview` branch.

I'm going to close this issue now, but feel free to re-open it if you have any issues.
