### ISSUE TITLE
The first model saved when device becomes offline never gets synced to cloud

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-ios#1717]
### Describe the bug

Original issue: https://github.com/aws-amplify/amplify-flutter/issues/1440

* Condition
  - Run App with DataStore when the device was online
  - Then turn off network (turning off cellular and WIFI, not switching to Airplane mode)
  - Save 3 models say Todo1, Todo2 and Todo3
* Observation
  - DataStore saved all 3 models into local DB
  - DataStore pushed all 3 models into mutationOutBox
  - DataStore invoked sync engine attempting sync saved model into cloud
  - The first underlying GraphQL mutation for Todo1 failed due to no network connection
  - Sync engine thought this is an unrecoverable issue (need to confirm this with amplify-ios), hence it removed mutationOutBox event for Todo1
  - Turn on network again, DataStore resumed API sync automatically
  - Todo 2 and Todo 3 mutationOutBox events were processed and these two models synced to cloud
  - Restart App with network on, Todo 1 remained in local DB but no sync happened to it

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
See above description
```

### Expected behavior

All offline saved models should be synced to cloud when device is back online.

### Amplify Framework Version

1.22.0

### Amplify Categories

API, DataStore

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

The latest

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone 13 simulators

### iOS Version

15.2

**Comment by lawmicha** [comment]
Hi @HuiSF, thanks for the details. I recently looked into the retryability of failed sync mutations (https://github.com/aws-amplify/amplify-ios/pull/1722) 

In that PR, I tried a slightly different scenario- network on, `DataStore.save`, breakpoint in code before making the API call, turn off wifi, let the API request fail. In your details, it looks like you have network turned off already, before `DataStore.save` is called.

Will update with more details when I get a chance to reproduce this and answer the question
> Sync engine thought this is an unrecoverable issue (need to confirm this with amplify-ios), hence it removed mutationOutBox event for Todo1

**Comment by royjit** [comment]
Are these issue related - https://github.com/aws-amplify/amplify-ios/issues/1718 ? I see that 1718 is fixed, can we retest and see if we are seeing the issue here?

**Comment by lawmicha** [comment]
I believe so, the SyncToCloudOperation uses the same retry policy, which was updated in https://github.com/aws-amplify/amplify-ios/pull/1791 so the first failed mutation should now be classified as a retryable network error. we shoud retest the scenario on a physical device to verify

**Comment by chrisbonifacio** [comment]
@HuiSF could you try this again on with the latest code and let us know if the issue persists?

**Comment by thisisabhash** [comment]
I tested this scenario in [v1.26.1](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.26.1) and all 3 models were syncing well. I was not able to reproduce it.
