### ISSUE TITLE
Best way to make changes on GraphQL API

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-ios#1729]
I have a dev/prod env. and I need to make some changes such as creating new Models.

Once I create the new model on the cloud the iOS client seems to start giving errors (without crashing) about the schema not being right.

So I wonder, what's the standard process to make GraphQL API changes so it syncs with already published in the App Store clients

**Comment by lawmicha** [comment]
Hi @afern247 @nyeu, thanks for opening this issue. Can you clarify the schema upgrade scenarios and the dependencies you are using on the iOS client? If through DataStore and the codegen process, existing clients won't be aware of the new model until `amplify codegen models` is ran against the updated backend. Updated clients (after running `amplify codegen models`, and released, will start syncing down data for the new model. I don't believe there is a way to version the graphQL backend so changes you make have to be forward compatible. Not forward compatible changes are changes that break existing clients, such as adding a new enum case to a enum type or making a field optional from required. There isn't a way to version the AppSync GraphQL backend to my knowledge and to make changes to production environments, you'll have to introduce changes in two stages, for example, a new model that is a replica of the old model plus the updated fields you need and deprecate the old model.

**Comment by alharris-at** [comment]
@afern247 What Michael is saying above is accurate. There are types of GraphQL Schema modifications that would be considered 'breaking' and those which should be compatible. In general the following actions are backwards incompatible:
* Adding a new `required field`
* Removing a field
* Marking an optional field required
* Adding an enum value
* Changing a field type

While the following are compatible.
* Adding a new optional field
* Marking a required field optional

Where possible, we'd recommend working to keep your mutations to the latter list while you're developing in production. 

If the issues you're seeing aren't related to making backwards incompatible schema mutations, feel free to reopen this issue w/ a specific mutation.
