### ISSUE TITLE
Amplify API Gateway Error Message iOS

### ISSUE THREAD

**Issue by iThink32** [aws-amplify/amplify-ios#1735]
### Describe the bug

On iOS when the lambda function to which the API Gateway is linked to returns a custom error message with an error code of 404 I am unable to get the message sent by the lambda function , I always get 
the following error object
```
(lldb) po print(error)
APIError: The HTTP response status code is [404].
Recovery suggestion: The metadata associated with the response is contained in the HTTPURLResponse.
For more information on HTTP status codes, take a look at
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
```

Is there any way I can get the error message that is sent from lambda 

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Make the lambda function return a 404 error with a custom error message
2. check on iOS , the message is always the operation could not be completed
```

### Expected behavior

The error message that is received from lambda should be shown on iOS

### Amplify Framework Version

1.18.1

### Amplify Categories

API

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

7.6.26

### Xcode version

13.3

### Is this a regression?

No

### Device

iPhone 8

### iOS Version

15.4

### Specific to simulators

Nope

**Comment by iThink32** [comment]
@lawmicha after multiple attempts was able to get the error message by using the following

```
                guard case let APIError.httpStatusError(_, urlResponse) = error,
                      let awsURLResponse = urlResponse as? AWSHTTPURLResponse,
                      let messageBody = awsURLResponse.body,
                      let message = try? JSONDecoder().decode(String.self, from: messageBody) else{
                    completion(nil,NetworkingError.genericError)
                    return
                }
                print(message)
```

Please let me know if wrong

**Comment by iThink32** [comment]
@lawmicha this was hard for me to find , pls add this to the documentation if it is the right approach

**Comment by lawmicha** [comment]
Hi @iThink32, that looks correct, this is the corresponding documentation  https://docs.amplify.aws/lib/restapi/fetch/q/platform/ios/#handling-non-2xx-http-responses we'll improve the documentation to include the decoding logic as you have there. Let us know if you have any more questions

**Comment by iThink32** [comment]
@lawmicha cool but a suggestion pls add it to amplify iOS documentation as well or at least provide a link to the above.
https://docs.amplify.aws/lib/restapi/fetch/q/platform/ios/
