### ISSUE TITLE
iOS - Private session option on AWS Amplify Social Login

### ISSUE THREAD

**Issue by AdiPomelo** [aws-amplify/amplify-ios#1750]
Hi

We are logging in using the social sign-in options on AWS Amplify on iOS.

We require the user to login to our app using a different social login from the same provider.

Is it possible to achieve this on iOS?

```
 var authProvider: AuthProvider!
        switch provider {
        case .google:
            authProvider = .google
        case .facebook:
            authProvider = .facebook
        }

Amplify.Auth.signInWithWebUI(for: authProvider, presentationAnchor: window) { result in
            switch result {
            case .success:
                success?((AwsSignInRes(step: .done)))
            case .failure(let error):
                failure?(error.errorDescription)
            }
        }
```

### Steps To Reproduce

```swift
Logged in with Gmail account

Sign out

Choose again Logged in Gmail account

**Actual Result:**

When a user clicks Gmail account, it always remembers the old user logged in
```

### Expected behavior

Every time user trying to signin with google, It should open a web view for users to choose the Gmail account they want to log in.

### Amplify Framework Version

1.23.0

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

1.23.0

### Xcode version

13.2.1

### Is this a regression?

No

### Regression additional context

Please reply ASAP.

### Device

Iphone 13 

### iOS Version

iOS 15

### Specific to simulators

Iphone 13 Pro

**Comment by harsh62** [comment]
@AdiPomelo 
Could you try using the `preferPrivateSession` in the options when signing in? An example would be as follows:
```
Amplify.Auth.signInWithWebUI(for: authProvider, presentationAnchor: window,
                             options: .preferPrivateSession()) { ... }
```

**Comment by AdiPomelo** [comment]
> @AdiPomelo Could you try using the `preferPrivateSession` in the options when signing in? An example would be as follows:
> 
> ```
> Amplify.Auth.signInWithWebUI(for: authProvider, presentationAnchor: window,
>                              options: .preferPrivateSession()) { ... }
> ```
Thank you for quick reply 
If I try with private session option accounts which are logged in using Gmail App on iPhone not showing and every-time customer needs to enter details manually (username & password)

**Comment by harsh62** [comment]
@AdiPomelo That is something which is controlled by google. Amplify doesn't control sessions created by social providers like Google, FB, Apple.. 

There have been similar issues that have been created such as https://github.com/aws-amplify/amplify-ios/issues/958.
