### ISSUE TITLE
Handle plural in list and sync GraphQL queries

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/amplify-ios#176]
Unfortunately there's no consistent behavior in the current GraphQL transformer for plural handling. The `list` queries just append an "s" whereas the `sync` queries use the actual plural form: `listPersons` vs `syncPeople`. This will be changed in the future and we will need to handle the fallback logic accordingly.

_Originally posted by @drochetti in https://github.com/aws-amplify/amplify-ios/pull/175/review_comment/create_

**Comment by drochetti** [comment]
This is fixed in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.0

**Comment by lawmicha** [comment]
please track https://github.com/aws-amplify/amplify-ios/issues/1707#issuecomment-1079413894 - closing as duplicate now
