### ISSUE TITLE
Amplify.Storage does not invoke "resultListener" block while Application is in Background

### ISSUE THREAD

**Issue by chintan1891** [aws-amplify/amplify-ios#1762]
### Describe the bug

I have implemented "Amplify.Storage.uploadFile" for File upload. But if my app goes in background, then my "resultListener" block is not getting called.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Implement "Amplify.Storage.uploadFile"
2. Start File Uploading
3. Put Application in Background
4. Check S3 Console, File is not being uploaded there
```

### Expected behavior

File should get uploaded in background

### Amplify Framework Version

1.23.0

### Amplify Categories

Storage

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

-

### Xcode version

13.3.1

### Is this a regression?

No

### Device

iPhone 7

### iOS Version

15.4

**Comment by ameter** [comment]
Hi @chintan1891, can you share a snippet of the code you're using to perform the upload?  Also, does the upload work correctly when the app remains in the foreground?

**Comment by chintan1891** [comment]
@harsh62  any update on this?

**Comment by harsh62** [comment]
Hey @chintan1891 sorry for the late reply. From what I can observe is that you are using a semaphore, can you share the entire context of the usage and also try without using semaphore.

**Comment by harsh62** [comment]
@chintan1891 Amplify Storage doesn't currently support background transfers. You might need to take a look at [Transfer Utility documentation](https://docs.amplify.aws/sdk/storage/transfer-utility/q/platform/ios/). Also linking [background transfers documentation](https://docs.amplify.aws/sdk/storage/transfer-utility/q/platform/ios/#background-transfers) if you want to look at managing background transfers.

We are tracking support for background operations in Amplify.Storage in https://github.com/aws-amplify/amplify-ios/issues/1102
