### ISSUE TITLE
Download URL for existing objects in AWS S3 in iOS app using Amplify isn't working.

### ISSUE THREAD

**Issue by ImranRazak1** [aws-amplify/amplify-ios#1767]
I am trying to get the objects inside my S3 bucket URLs so my iOS app can download them. I do not have a login so I didn't use Cognito, my api URLs right now for the objects are individually coded and are publicly accessible. So I can just download the JSON data to be decoded from the URL but I am trying to use Amplify to do that in code rather than having to input the URL itself.

Here is an example of an API without amplify:

```
//Healthy and Simple Recipes
@MainActor
class HealthyAPI: ObservableObject {
    @Published var recipes: [Recipe] = []
    
    func fetchRecipes() async {
        guard let healthyAPIURL = URL(string: "https://recipesstore.s3.eu-west-2.amazonaws.com/Healthysimple.json") else {
            
            print("Invalid URL")
            return
            
        }

          do {
              let (data, _) = try await URLSession.shared.data(from: healthyAPIURL)
              let decoder = JSONDecoder()
              recipes = try decoder.decode([Recipe].self, from: data)
          } catch {
              print(error)
          }
      }
    
}
```
I am now looking to use Amplify to access the S3 bucket and get the correct URL for the recipe category for the API like the class above except call in the URL from my S3 bucket to the Object via Amplify. I have download the Amplify using SPM to the Xcode file. Added an App Delegate as such:

```
import Foundation
import SwiftUI
import Amplify
import AWSS3StoragePlugin

class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

        do {
            try Amplify.add(plugin: AWSS3StoragePlugin())
            try Amplify.configure()
            print("Amplify configured with storage plugin")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }

        return true
    }
}
and a Amplify configuration json as follows from the AWS amplify documentation:

{
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                  "bucket": "xxxx", //S3 Bucket name
                  "region": "xxxx" //Region of Bucket
            }
        }
    }
}
```
and I have finally added to my App Main file too as the docs said to do:

```
import SwiftUI

@main
struct WeCookedApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    var body: some Scene {
        WindowGroup {
            RecipeContentView()
            
        }
    }
```
My code is 100% written in Swift and SwiftUI, so I don't really want to stray of it.

The app hasn't got any logins or authentication.

Hope you can help because I am baffled of what to do. It configures in the debug area but then when I replace the URL part to be like this:

```
//Testing Amplify
class AmplifyAPI: ObservableObject {
    @Published var recipes: [Recipe] = []

    func fetchRecipes() async {
        guard let amplifyAPI = URL(string: "\(Amplify.Storage.getURL(key: "Breakfast.json"))") else {
            
            print("Invalid URL")
            return
            
        }

          do {
              let (data, _) = try await URLSession.shared.data(from: amplifyAPI)
              let decoder = JSONDecoder()
              recipes = try decoder.decode([Recipe].self, from: data)
          } catch {
              print(error)
          }
      }
}
```

The app just crashes saying "fatal error in StorageCategory.swift at line 19. Storage Category is not configured. Call Amplify.Configure() before using any methods on the category". Which is confusing since the debug said amplify with storage plugin configured.

**Comment by thisisabhash** [comment]
Hello,
You'd need to add auth to your project in order to add storage for user files. 
Please provision your backend by following the steps here : https://docs.amplify.aws/lib/storage/getting-started/q/platform/ios/
where you can add different access to Guest users without logging in.
When you've done that, make sure to add `AWSCognitoAuthPlugin` before calling `Amplify.configure()`.
```
class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

        do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSS3StoragePlugin())
            try Amplify.configure()
            print("Amplify configured with storage plugin")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }

        return true
    }
}
```

Let us know if you have more questions.

**Comment by thisisabhash** [comment]
I have also redacted your `amplifyconfiguration.json` file. Please make sure you redact sensitive configuration information before posting questions.

**Comment by ImranRazak1** [comment]
Is the authentication necessary? Because it's public anyways the json files. And with regards to the API call that I intend to make would that work as I have proposed above.

**Comment by thisisabhash** [comment]
Yes, it is needed as when you configure Amplify to add storage, the CLI configures appropriate IAM policies on the bucket using a Cognito Identity Pool Role. https://docs.amplify.aws/lib/storage/overview/q/platform/ios/#accessing-aws-services
For `getURL()`, you'd need to pass a closure to receive results: https://docs.amplify.aws/lib/storage/download/q/platform/ios/#generate-a-download-url

**Comment by ImranRazak1** [comment]
This is the issue I keep facing whenever I use CLI to provision the backend. I used SPM to setup amplify. 
`
imranrazak@Imrans-MacBook-Pro avocadotoast % sudo curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL
Password:

 Installing the AWS Amplify CLI...

 Downloading binary...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  176M  100  176M    0     0  12.0M      0  0:00:14  0:00:14 --:--:-- 13.7M
 Download complete!
 Extracting binary...
 Extraction complete!

Successfully installed the Amplify CLI.
Run 'amplify help' to get started!
imranrazak@Imrans-MacBook-Pro avocadotoast % amplify help
zsh: command not found: amplify
imranrazak@Imrans-MacBook-Pro avocadotoast %

`

Avocadotoast is where my Xcode project lives?

**Comment by thisisabhash** [comment]
Hello,
Please follow steps here to configure Amplify CLI : https://docs.amplify.aws/cli/start/install/
Make sure you have the pre-requisites installed.
Here is a step by step video guide from the above link: https://youtu.be/fWbM5DLh25U

**Comment by ImranRazak1** [comment]
> Yes, it is needed as when you configure Amplify to add storage, the CLI configures appropriate IAM policies on the bucket using a Cognito Identity Pool Role. https://docs.amplify.aws/lib/storage/overview/q/platform/ios/#accessing-aws-services
> 
> For `getURL()`, you'd need to pass a closure to receive results: https://docs.amplify.aws/lib/storage/download/q/platform/ios/#generate-a-download-url

I've setup CLI. Configured the app using SPM. Do I have to run Amplify add storage in order to access the download URL, or can I just get the download URL using the docs provided?
