### ISSUE TITLE
Amplify.Storage.uploadFile causes app to crash when trying to upload a large file

### ISSUE THREAD

**Issue by sagarjoshi** [aws-amplify/amplify-ios#1775]
To reproduce , try uploading a 2.4 GB file . Memory usage keeps on increasing and the app crashes when it reaches around 2 GB. I was trying this on an iPhone 11. From what I was able to gather it has 4 gb of memory and iOS will only let it grow till around 2GB. 

![image](https://user-images.githubusercontent.com/1082515/166486228-f5351e49-2859-4cb6-9a6a-5e7d400901cb.png)

**Comment by sagarjoshi** [comment]
@brennanMKE  as you requested. Please let me know if you need anymore information

**Comment by ameter** [comment]
Per discord discussion, @brennanMKE is investigating this issue.

**Comment by sagarjoshi** [comment]
Other folks alluding to the same issue on Apple developer forums 

https://developer.apple.com/forums/thread/118912 

Don't know how accurate this is, but max memory budget per device

https://stackoverflow.com/questions/5887248/ios-app-maximum-memory-budget

**Comment by sagarjoshi** [comment]
Any update ? Trying to figure out my options if this isn't going to be fixed soon.

**Comment by brennanMKE** [comment]
I've created a repro build and was able to observe this memory spike just as the multipart upload process is starting. This will be investigated to eliminate the spike so it won't cause a runtime exception when the app runs out of memory.

<img width="985" alt="Memory Spike" src="https://user-images.githubusercontent.com/277419/167180308-5a1209cb-422d-4f08-b942-b14ab4a5d9b1.png">

**Comment by sagarjoshi** [comment]
Thanks a lot @brennanMKE  . I really appreciate this. Please keep me in the loop, I am actively trying to figure out how I can mitigate this from a product perspective and the choices aren't that great.

**Comment by brennanMKE** [comment]
See PR below.

https://github.com/aws-amplify/aws-sdk-ios/pull/4129

**Comment by sagarjoshi** [comment]
Thanks a lot @brennanMKE ! Hopefully it will be part of a build soon. Also, will be useful if you paste a screenshot in that PR that doesn't show a spike for the same test :)

**Comment by atierian** [comment]
This fix was including in [Amplify v1.25.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.25.0).
Let us know if this works for you or if you're still experiencing any issues.

**Comment by sagarjoshi** [comment]
It works ! Thanks a lot 🙏🏽
