### ISSUE TITLE
createdAt and updatedAt of DataStoreResult are nil?

### ISSUE THREAD

**Issue by morisobaa** [aws-amplify/amplify-ios#1785]
### Describe the bug

When I create an object, the createdAt and updatedAt of the DataStoreResult object defined in DataStoreCallback.swift are nil.
And they are not nil when queried.

This can happen in any model.
I understand that createdAt and updatedAt are assigned in the resolver Mutation.createModel.init.1.req.vtl.

Is the content of the DataStoreResult not an object synced to DynamoDB?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Define any model
2. Create an object of the model
3. See that the createdAt of the DataStoreResult object is nil
```

### Expected behavior

When Create, createdAt is not nil and updatedAt is nil.

### Amplify Framework Version

8.0.1

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

swift-driver version: 1.45.2 Apple Swift version 5.6

### CLI version

8.0.1

### Xcode version

13.3(13E113)

### Is this a regression?

No

### Device

iPhone12 Simulator

### iOS Version

iOS 15.4

**Comment by lawmicha** [comment]
Hi @morisobaa, they will be generated if nothing is passed in for them on the server side as you mentioned regarding resolver. When interacting with DatasStore, the model is persisted locally in the SQLite database first and returned to you on the callback of the API, so the `createdAt` and `updatedAt` will not have any values if you did not pass it into the model. You can pass in `.now()` when creating the model instance to generate a new Temporal.DateTime if you like. Once the data is persisted to the local store, then DataStore will asynchronously sync these models to AppSync. The data is reconciled to all clients of the newly created model and you can subscribe to these changes on the `publisher(modelType)` API to get real time updates: https://docs.amplify.aws/lib/datastore/real-time/q/platform/ios/

The incoming change that contains `createdAt` and `updatedAt` populated is the model received from AppSync.

**Comment by morisobaa** [comment]
I am convinced. Thank you very much for your careful solution.
