### ISSUE TITLE
Auth confirmSignIn error "Invalid attributes given, name is missing"

### ISSUE THREAD

**Issue by ChadyG** [aws-amplify/amplify-ios#1786]
### Describe the bug

According to the docs, we should be able to call Amplify.Auth.confirmSignIn with just the new password given by the user when .confirmSignInWithNewPassword auth challenge is returned.  However, calling this method with just the password returns the following error:
"Invalid attributes given, name is missing"

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Add user via Cognito AWS console
2. User is added with force change password status
3. Log in using Amplify.Auth.signIn
4. Auth returns .confirmSignInWithNewPassword 
5. Request new password from user, call Amplify.Auth.confirmSignIn(challengeReponse: newPassword)
6. Auth returns error "Invalid attributes given, name is missing"
```

### Expected behavior

Auth should return a successful response for changing user password.

### Amplify Framework Version

1.18.1, 1.24.0

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

8.0.2

### Xcode version

13.3.1

### Is this a regression?

Yes

### Regression additional context

I want to say this worked in the past, but haven't tested in quite a while.

### Device

iPhone 13 pro max

### iOS Version

15.4.1

**Comment by atierian** [comment]
Thanks for opening this issue @ChadyG. We'll take a closer look at this and come back to you.

**Comment by royjit** [comment]
Probably your userpool configuration might have the attribute `name` as required parameter. You can pass this value by:

```
let pluginOptions = AWSAuthConfirmSignInOptions(userAttributes: [.init(.name, value: name)])
let options = AuthConfirmSignInRequest.Options(pluginOptions: pluginOptions)

Amplify.Auth.confirmSignIn(challengeResponse: newPassword, options: options) { result in
    ...
}
```
