### ISSUE TITLE
Auth socialSignInWithWebUI error

### ISSUE THREAD

**Issue by SefyDev** [aws-amplify/amplify-ios#1796]
### Describe the bug

After I use "socialSignInWithWebUI" I am faced with google log in flow, after I complete it I get a grey screen with the text "An error was encountered with the requested page" (when I inspect through the developer window I can see a 403 error)

At that point the user is added successfully to the user pool however the signed in status does not update and the login sheet is no dismissed.

I provided the redirection URI that was given in the Amplify studio to the google web client.
I also put it as "Sign-in & sign-out redirect URLs"

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to Amplify Studio

2. Set up a google web client 

3. Launch Social Web UI Sign In

4. Use credentials to logIn 

4. See error
```

### Expected behavior

The screen should dismiss after completing the sign in and should also change the signed in status.

### Amplify Framework Version

8.2.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5

### CLI version

8.2.0

### Xcode version

13.3.1

### Is this a regression?

No

### Device

All simulators and iPhones Xs and 12

### iOS Version

iOS 15.4

### Additional context

I am ready confused about the part of the documentation where I need to change the plist file.

**Comment by atierian** [comment]
The part of the documentation that's confusing, is it this? 
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios/#update-infoplist

What value are you using there?
It should be the app scheme entered into Amplify Studio in the Sign-in and Sign-out redirect URLs minus the `://`.

**Comment by SefyDev** [comment]
Yes it is. 

I am using:
 
  <key>CFBundleURLTypes</key>
  <array>
      <dict>
          <key>CFBundleURLSchemes</key>
          <array>
              <string>com.googleusercontent.apps.XXXXXXXXXXXX-*******************************</string>
          </array>
      </dict>
  </array>
  
I also used just the url that was given by amplify studio:
  https://XXXXXXXXXXXX-staging.auth.eu-west-2.amazoncognito.com
I used
  https://XXXXXXXXXXXX-staging.auth.eu-west-2.amazoncognito.com/oauth2/idpresponse
Also thought I was overthinking it and simply put:
  myapp

**Comment by SefyDev** [comment]
Update on this, I remove auth and re-added it using the CLI and now it works fine. The issue was the "Sign-in & sign-out redirect URLs" box 

<img width="555" alt="image" src="https://user-images.githubusercontent.com/98397079/168469596-5de1a58c-91cd-489e-9d90-734ff0b3dba6.png">

I was providing the .amazoncognito.com URL given above instead of just that. I think it should be more clear, (note: it could be clear as is given I have a limited knowledge of login flows)
