### ISSUE TITLE
Get cached device key

### ISSUE THREAD

**Issue by joe-netcenter** [aws-amplify/amplify-ios#1806]
### Is your feature request related to a problem? Please describe.

I'm looking for a feature similar to the javascript getCachedDeviceKeyAndPassword() in iOS so that I can access the device key before the user is authenticated; we send this information during sign in to determine if the user's device is remembered. Is it possible to gather this information on mobile? Using Amplify or AWSMobileClient.

I've also requested this separately in the Android repo: https://github.com/aws-amplify/amplify-android/issues/1734

### Describe the solution you'd like

Ability to fetch device key prior to user sign in.

### Describe alternatives you've considered

Building a custom solution to generate and store our own device Ids. Would prefer to use what is already built in Cognito.

### Is the feature request related to any of the existing Amplify categories?

Auth

**Comment by atierian** [comment]
You can use the `fetchDevices` [API](https://aws-amplify.github.io/amplify-ios/docs/Protocols/AuthCategoryDeviceBehavior.html#/s:7Amplify26AuthCategoryDeviceBehaviorP12fetchDevices7options8listenerAA0b5FetchG9Operation_pAA0bjG7RequestV7OptionsVSg_ys6ResultOySayAA0bD0_pGAA0B5ErrorOGcSgtF) to retrieve an [AuthDevice](https://aws-amplify.github.io/amplify-ios/docs/Protocols/AuthDevice.html). Here's a simple example:
```swift
Amplify.Auth.fetchDevices { result in 
  switch result { 
  case .success(let devices):
    print("device IDs", devices.map(\.id))
  case .failure(let error):
    print("error", error)
  }
}
```
The `AWSCognitoAuthPlugin` implementation returns the `AuthDevice` conforming type `AWSAuthDevice`, which has an `id` in the form of `<region>_<GUID>` along with other attributes.

Please let us know if you have any issues or if this works for you. Thanks!

**Comment by joe-netcenter** [comment]
Thanks! I'll go and test that asap.

My main concern is that, as with the other platform SDKs, Auth.fetchDevices requires an authenticated user.

**Comment by atierian** [comment]
Re-reading your issue I see that you're asking about a cached device ID that's accessible without being logged in. This API doesn't support that. I don't believe we currently cache / persist the ID anywhere accessible without being logged in, but I'll double check and circle back to you on this.

**Comment by joe-netcenter** [comment]
We decided we'll use iOS `UserDefaults` (and sharedPrefs on Android) to store the device key locally after the user chooses to remember the device. `AWSMobileClient.DeviceOperations.get()` will get us the current device when the user is logged in, and we can retrieve this from `UserDefaults` during `CUSTOM_AUTH` sign in flow to check device remember status in the defineChallenge lambda. Should be set. Thanks much!
