### ISSUE TITLE
Auth sign-out after Google sign-in does not clear the browser session.

### ISSUE THREAD

**Issue by iluvdadong** [aws-amplify/amplify-ios#1932]
### Describe the bug

Auth sign-out after google sign-in does not clear the browser session.

After using the below sign-in method,
```
 Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: self.view.window!) { result in
            switch result {
            case .success:
                print("Sign in succeeded")
            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }
```

I use both listener and combine methods to sign out.

```
func signOutGlobally() -> AnyCancellable {
    let sink = Amplify.Auth.signOut(options: .init(globalSignOut: true))
        .resultPublisher
        .sink {
            if case let .failure(authError) = $0 {
                print("Sign out failed with error \(authError)")
            }
        }
        receiveValue: {
            print("Successfully signed out")
        }
    return sink
}
```
```
func signOutGlobally() {
    Amplify.Auth.signOut(options: .init(globalSignOut: true)) { result in
        switch result {
        case .success:
            print("Successfully signed out")
        case .failure(let error):
            print("Sign out failed with error \(error)")
        }
    }
}

```
But even after signing out, users still can sign in automatically with the previous user's google account without choosing a google account or typing ID and password.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

After `Amplify.Auth.signout`, the google sign-in browser session should be cleared

### Amplify Framework Version

1.19.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.5

### CLI version

-

### Xcode version

13.3

### Is this a regression?

No

### Device

iphone 13 pro simulator

### iOS Version

iOS 15

**Comment by royjit** [comment]
Amplify cannot control the signIn happened inside Google, so signing out from Amplify.Auth does not signOut the use from third part services like Google. You could try signIn via private session so that the signIn happens in a private Safari session:

Login via [private session](https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios/#launch-web-ui-sign-in)
```swift
Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: self.view.window!, options: .preferPrivateSession()) 
``

Let us know if this resolves your issue.

**Comment by iluvdadong** [comment]
Hi, thank you for the reply. Using `options: .preferPrivateSession()` resolved the issue. Signing In via a private browser doesn't save the authentication data, so the user needs to type ID and password again after signing out.
