### ISSUE TITLE
EXC_BAD_ACCESS Crash in AWSMobileClient.getTokens()

### ISSUE THREAD

**Issue by pierceglennie** [aws-amplify/amplify-ios#1974]
**Describe the bug**

Our iPad app is used by staff, each of whom will have it open for ~8 hours per day. We're facing intermittent crashes with the stack traces like the below, which point to an issue with the AWSMobileClient.getTokens() method.

We haven't been able to find any way to reproduce the crash, except leaving an iPad open on the app for a long time. We've been running a test fleet of iPads continuously to try to reproduce it. Occasionally the crash will occur quickly after launching (we've seen it within half an hour) and sometimes not for a week or two. It affects all devices and is not triggered by any user input – it happens on device left on the app with no input for days. On average, it occurs roughly weekly per device.

Our app is making frequent authenticated network requests (every few seconds) so we are continuously using Amplify.Auth.fetchAuthSession to get the tokens.

The issue has occurred with multiple versions of Cognito. We're on version 1.26.2 but have seen issues when running older versions of the SDK, at least as far back as 1.22.0.

Unfortunately, given the intermittent nature it's been really hard to trace down the crash any further so we're wondering if anyone has any ideas where to start.

**Observed Behavior**

EXC_BAD_ACCESS Crash

**Expected Behavior**

App should not crash.

**Stack Trace**

```
OS Version: iOS 15.5 (19F77)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x0000000015553220
Crashed Thread: 17

Application Specific Information:
Exception 1, Code 357904928, Subcode 8 >
Attempted to dereference garbage pointer 0x15553220.

Thread 17 Crashed:
0   libobjc.A.dylib                 0x332dc3120         objc_retain
1   AWSMobileClientXCF              0x1056e0d6c         [inlined] Array._getElement
2   AWSMobileClientXCF              0x1056e0d6c         Array.subscript.getter
3   AWSMobileClientXCF              0x1056e0f14         AWSMobileClient.getTokens (AWSMobileClient+Tokens.swift:51)
4   AWSMobileClientXCF              0x1056c8e50         thunk for closure
5   Foundation                      0x306b9d71c         __111+[__NSOperationInternalObserver _observeValueForKeyPath:ofObject:changeKind:oldValue:newValue:indexes:context:]_block_invoke_2
6   libdispatch.dylib               0x303723090         _dispatch_call_block_and_release
7   libdispatch.dylib               0x303724090         _dispatch_client_callout
8   libdispatch.dylib               0x3036c6854         _dispatch_queue_override_invoke
9   libdispatch.dylib               0x3036d3b90         _dispatch_root_queue_drain
10  libdispatch.dylib               0x3036d4398         _dispatch_worker_thread2
11  libsystem_pthread.dylib         0x3b81e1dd0         _pthread_wqthread
```

**Redacted amplifyconfiguration.json File**

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxxxx",
                        "AppClientId": "xxxxxx",
                        "AppClientSecret": "xxxxxx",
                        "Region": "xxxxxx"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
````

**Redacted awsconfiguration.json File**

```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "xxxxxx",
            "AppClientId": "xxxxxx",
            "AppClientSecret": "xxxxxx",
            "Region": "xxxxxx"
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}

**Comment by royjit** [comment]
Thank you for contacting us,  I could not reproduce this issue at my side. But looking at the crash log the error might have happened while it tried to access a deallocated object? I made this PR that might potentially fix this issue: https://github.com/aws-amplify/aws-sdk-ios/pull/4205

**Comment by harsh62** [comment]
@pierceglennie  A new version of Amplify was released today. Can you validate if this fixed your issue.

**Comment by pierceglennie** [comment]
Hi @harsh62. Looks like that has fixed it, we've gone about a week with no crashes whereas we were getting one every couple of days before. Thanks
