### ISSUE TITLE
Get AuthUser in the authsignup result

### ISSUE THREAD

**Issue by cmason9** [aws-amplify/amplify-ios#1991]
### Is your feature request related to a problem? Please describe.

I have noticed that in Android there is an AuthUser object in the AuthSignupResult object so when a new user signs up with their email and password the userId cognito generates gets set when that signup result is returned. On iOS this is not the case and I need to get the userId back when the user successfully completes a signup

### Describe the solution you'd like

Add the AuthUser object to the AuthSignUpResult so we can get back the user id

### Describe alternatives you've considered

Needed for my work flow

**Comment by royjit** [comment]
Thank you for reaching out to us, we will look into this and will update here with the next steps.
