### ISSUE TITLE
buildUserPoolConfiguration causes app to crash on launch despite having the required configuration

### ISSUE THREAD

**Issue by tjcarrel** [aws-amplify/amplify-ios#2151]
### Describe the bug

We are using the Analytics and Auth libraries to record various events within our app. 

However, we are experiencing an issue with a very small number of devices where our app immediately crashes on launch due to Amplify throwing the following exception in `buildUserPoolConfiguration` on launch:

```
    if (!poolId || !clientId) {
        @throw [NSException exceptionWithName:NSInternalInconsistencyException
                                       reason:@"The service configuration is `nil`. You need to configure `Info.plist` before using this method."
                                     userInfo:nil];
    }
```

The issue persists even after we prompt users to delete the app, restart their device, and then re-install. It came to a point where we had to remove the library entirely to ensure that our users were able to use our app. We tried to look into moving our configuration values from the JSON file into `info.plist` but documentation around that topic is difficult to find. We also are not using Cognito User Pools for authentication, but only have the library included as it was mentioned it was required to use the Analytics library. 

Here is how we are configuring Amplify in `didFinishLaunchingWithOptions`:

```
do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSPinpointAnalyticsPlugin())
            try Amplify.configure()
            print("Amplify configured with Auth and Analytics plugins")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }
```

Despite being in a try-catch block, we are unable to prevent the exception from crashing the entire app. 

Here is what our `amplifyconfiguration.json` file looks like:

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "xxx",
                    "region": "us-east-1"
                },
                "pinpointTargeting": {
                    "region": "us-east-1"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "xxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId": "xxx",
                        "Region": "us-east-1"
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region": "us-east-1"
                    }
                }
            }
        }
    }
}
```

### Steps To Reproduce

```swift
We are unable to reproduce the crash on the simulator and on most devices. We were able to determine that Amplify was the issue by having a user experiencing the crashes to download a TestFlight build and report the crash log to us which showed the above exception being thrown.
```

### Expected behavior

Amplify to configure and not crash 

### Amplify Framework Version

1.26.0

### Amplify Categories

Analytics, Auth

### Dependency manager

Cocoapods

### Swift version

5.5.2

### CLI version

Not Installed

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone 13 Pro

### iOS Version

15.5

### Specific to simulators

No

**Comment by ameter** [comment]
Thanks for bringing this to our attention.  It appears user pools are somehow being invoked even though they are not in use and therefore not configured, leading to the crash.  Are you able to provide a stack trace or any additional logs to help us diagnose this issue?

**Comment by tjcarrel** [comment]
Hey Chris, thanks for the quick reply. I've attached a screenshot of the backtrace - was really that only thing I saw that might be useful. Let me know if there is anything else I can provide
<img width="611" alt="Screen Shot 2022-08-16 at 4 28 22 PM" src="https://user-images.githubusercontent.com/10950089/184979091-923b8080-fe1a-4259-a90f-d0f78f283aca.png">

**Comment by phantumcode** [comment]
@tjcarrel Can you provide additional details on what type of authentication is configured? Is it using federated signin with a particular third-party (Apple, Google, Facebook)?

**Comment by phantumcode** [comment]
@tjcarrel I'm not able to reproduce this issue with a test app configured with Analytics and Auth (federated sign in with Facebook).  Can you provide any additional details that can help reproduce the issue?

**Comment by tjcarrel** [comment]
Hi @phantumcode - we aren't using any kind of authentication for our users (we use an in-house auth service). The only reason we have the Auth plugin configured was cause the documentation stated we needed it in order to send analytics to Pinpoint. Does this answer your question?

**Comment by phantumcode** [comment]
@tjcarrel Did you use the `amplifycli` to add or configure the Auth category then? If so what was it configured to? Can you share what is configured in the `awsconfiguration.json` or `amplifyconfiguration.json` for Auth? Please remove or de-identify any private details in the configuration file prior to sharing/uploading.

**Comment by tjcarrel** [comment]
@phantumcode I'm not completely sure if we used the CLI. We might have used the CLI to get an example configuration file and then plugged in values for resources that were already created. You can see my `amplifyconfiguration.json` that we were using in my initial post above.

**Comment by phantumcode** [comment]
@tjcarrel Ok,I think it would be helpful to correctly configure the auth category using the CLI then.  You can run `amplify status` to determine the status of Auth category and then run `amplify auth update` to reconfigure it otherwise `amplify auth add` to add it it wasn't configured.

**Comment by tjcarrel** [comment]
@phantumcode We have moved away from using the package and are now using our own custom implementation so will not be trying to reconfigure it. However, I don't see how the CLI or our existing resources would have anything to do with the crash. We were not utilizing User Pools and the package was crashing due to an invalid User Pool configuration.

**Comment by phantumcode** [comment]
It looks like the issue is bad data migration as a result of removal of Amplify Auth and migrating to your own custom implementation.  The user authentication state didn't get cleared out; when configuring Analytics at app startup, the user session is getting fetched because Amplify thinks that the current user state is still signed in.  The app crashes during session fetch because there's a configuration block missing from `amplifyconfiguration.json`.  There are couple solutions:

1. Upgrade to the latest Amplify release as there is logic to cleanup old user/session states that would prevent sessions from being fetched in the first place: https://github.com/aws-amplify/amplify-ios/releases/tag/v1.28.1
2. Add the missing `CognitoUserPool` configuration to `amplifyconfiguration.json`
```
               "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:xxxxxxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1xxxxxxx",
                        "AppClientId": "xxxxxxxxxxxxxxxx",
                        "Region": "us-east-1"
                    }
                },
```

**Comment by phantumcode** [comment]
@tjcarrel Were you able to resolve your issue?

**Comment by tjcarrel** [comment]
@phantumcode as mentioned previously, we have moved away from Amplify so I won't be able to say whether your suggestion will work. You might be on to something though as the users experiencing the issue did use the app back when we were using User Pools. Appreciate the help - feel free to close this.
