### ISSUE TITLE
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred

### ISSUE THREAD

**Issue by gitton** [aws-amplify/amplify-ios#2273]
### Describe the bug

Trying to integrate AWS Cognito for iOS app. After login getting following error 
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=0 "(null)" UserInfo={error=invalid_client}

Please find below for amplifyconfiguration.json
```
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:poolid",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "user_pool_id",
                        "AppClientId": "app_client_id",
                        "AppClientSecret": "client_secret",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "OAuth": {
                            "WebDomain": "domain.us-east-1.amazoncognito.com",
                            "AppClientId": "app_client_id",
                            "SignInRedirectURI":
                            "myapp://signin",
                            "SignOutRedirectURI": "myapp://signout",
                            "Scopes": [
                                                         "phone",
                                                         "email",
                                                         "openid",
                                                         "profile",
                                                         "aws.cognito.signin.user.admin"
                                                     ]
                        },
                    }
                }
            }
        }
    }
}

```

### Steps To Reproduce

```swift
Amplify.Auth.signInWithWebUI(presentationAnchor: vc.view.window!){ result in
            switch result {
                case .success:
                print("\(self.TAG) Sign in succeeded")
                case .failure(let error):
                print("\(self.TAG) Sign in failed \(error)")
                }
        }
```

### Expected behavior

Login response

### Amplify Framework Version

1.28.0

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

manual

### Xcode version

13.4.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 80
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=0 "(null)" UserInfo={error=invalid_client}

```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone 13 Pro

### iOS Version

ios 15.5

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by gitton** [comment]
any help

**Comment by gitton** [comment]
Still Waiting

**Comment by harsh62** [comment]
In order to further investigate, could you share how did you setup the application and what steps did you follow?

From the error I see that you are getting an `invalid_client` which usually is Client authentication failed. For example, when the client includes client_id and client_secret in the authorization header, but there's no such client with that client_id and client_secret.

**Comment by gitton** [comment]
Hi

Thank you for your response. I was following this documentation for the setup https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios/. I did not see other fields other than AppClientId for amplifyconfiguration.json

`{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "[COGNITO IDENTITY POOL ID]",
                            "Region": "[REGION]"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "[COGNITO USER POOL ID]",
                        "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
                        "Region": "[REGION]"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "OAuth": {
                            "WebDomain": "[YOUR COGNITO DOMAIN ]",
                            "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
                            "SignInRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN IN, e.g. myapp://]",
                            "SignOutRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN OUT, e.g. myapp://]",
                            "Scopes": [ 
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                    }
                }
            }
        }
    }
}`

**Comment by harsh62** [comment]
If you compare your configuration with the one that is there in amplify docs, you see that your configuration has `"AppClientSecret": "client_secret",`, which could be why you are seeing an issue.

**Comment by gitton** [comment]
Hi @harsh62 
Thank you it worked
