### ISSUE TITLE
Failing pod install when using plugin

### ISSUE THREAD

**Issue by frankiesimon** [aws-amplify/amplify-ios#2297]
I'm getting this message when running `pod install --repo-update`
```
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In snapshot (Podfile.lock):
    AWSCore (= 2.12.3)

  In Podfile:
    AmplifyPlugins/AWSCognitoAuthPlugin was resolved to 1.0.0, which depends on
      AWSPluginsCore (= 1.0.0) was resolved to 1.0.0, which depends on
        AWSCore (~> 2.13.4)

    MyExtraProject/Analytics (from `submodules/MyExtraProject/MyExtraProject.podspec`) was resolved to 0.0.4, which depends on
      AWSCore

    MyExtraProject/Analytics (from `submodules/MyExtraProject/MyExtraProject.podspec`) was resolved to 0.0.4, which depends on
      AWSMobileAnalytics was resolved to 2.12.3, which depends on
        AWSCore (= 2.12.3)


You have either:
 * changed the constraints of dependency `AWSCore` inside your development pod `MyExtraProject/Analytics`.
   You should run `pod update AWSCore` to apply changes you've made.
CocoaPods could not find compatible versions for pod "AmplifyPlugins/AWSCognitoAuthPlugin":
  In Podfile:
    AmplifyPlugins/AWSCognitoAuthPlugin

There are only pre-release versions available satisfying the following requirements:

	'AmplifyPlugins/AWSCognitoAuthPlugin', '>= 0'

You should explicitly specify the version in order to install a pre-release version
```

In my Podfile I added:
```
pod 'Amplify'
    pod 'AmplifyPlugins/AWSPinpointAnalyticsPlugin'
    pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
```
The project is in Xcode 13.4.1 and the Podfile targets iOS 11 and above (which if I understand the Podspec of the plugins should be fine...)

My Podfile.lock has these:
```
PODS:
  - Amplify (1.28.0):
    - Amplify/Default (= 1.28.0)
  - Amplify/Default (1.28.0)
  - AWSCore (2.12.3)
  - AWSMobileAnalytics (2.12.3):
    - AWSCore (= 2.12.3)
  - AWSPinpoint (2.12.3):
    - AWSCore (= 2.12.3)
  - AWSS3 (2.12.3):
    - AWSCore (= 2.12.3)
```

What am I missing?

**Comment by atierian** [comment]
It appears that there's a version conflict for `AWSCore` that `AWSCognitoAuthPlugin` depends on and the `AWSCore` version that your `MyExtraProject/Analytics` depends on. 

Amplify 1.28.0 depends on `AWSCore` 2.27.9 and it looks like your `MyExtraProject/Analytics` depends on the the exact `AWSCore` version 2.12.3.

If `MyExtraProject/Analytics` is something separate from Amplify, you can try updating that dependency to 2.27.9. If that's a development pod that uses Amplify, you can try `pod cache clean` for your `MyExtraProject/Analytics` pod, or delete the Podfile.lock and run `pod install` (omit the `--repo-update`) again. 

Let us know if you're still experiencing this issue afterwards. Thanks!

**Comment by frankiesimon** [comment]
I got rid of the dependency inside `MyExtraProject/Analytics` to eliminate the conflict. However I'm now facing the issue I described here: https://github.com/aws-amplify/amplify-ios/issues/2298. Will update with the latest Podfile there.

**Comment by atierian** [comment]
Closing for reason mentioned in https://github.com/aws-amplify/amplify-ios/issues/2298.
