### ISSUE TITLE
Amplify.API.mutate(request: .delete - NOT DELETING in DynamoDB 

### ISSUE THREAD

**Issue by DanielZanchi** [aws-amplify/amplify-ios#2314]
### Describe the bug

I am trying to delete an item in a table in DynamoDB but this is not doing anything:
```
Amplify.API.mutate(request: .delete(pack)) { result in
    switch result {
    case .failure(let error):
        print("errror: ", error)
    case .success:
        print("packname: \(pack.packName) - packID: \(packId) - deleted")
    }
} 
```
Where pack is of type _PackDynamo_

prints out **_success_**:

> packname: Squid - packID: 4C9F702B-28B1-4D89-B0A1-5A5EEFD00FD4 - deleted

But if a fetch the list it's still there:
`Amplify.API.query(request: .list(PackDynamo.self))`

And going into Amplify console -> DynamoDB I still see the pack there in the table.

### Steps To Reproduce

```swift
Run a delete on an item in a table
Amplify.API.mutate(request: .delete(pack))
```

### Expected behavior

The item should not be there after deletion.

### Amplify Framework Version

1.28.1

### Amplify Categories

API

### Dependency manager

Cocoapods

### Swift version

5.5

### CLI version

10.0.0

### Xcode version

14.0

### Is this a regression?

No

### Device

iphone 13 pro

### iOS Version

ios 15.6

**Comment by DanielZanchi** [comment]
I solved the issue by running "amplify update api" and Answering "NO" to the question => "enable conflict detection". And then pushing the edit.
Now i cannot access to Amplify Studio and see the data from there but its working good from DynamoDB.

**Comment by atierian** [comment]
Thanks for letting us know.
