### ISSUE TITLE
compile : datastore init sample code fails

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-ios#242]
```swift 
func initAmplify() {
        print("initialising Amplify....")
        do {
            try Amplify.add(plugin: AWSDataStorePlugin(modelRegistration: AmplifyModels()))
            // add after all other plugins
            try Amplify.configure()
        } catch {
            print("An error occurred setting up Amplify: \(error)")
        }
        print("done")
    }
```

This fails to compile because `AmplifyModels()` and other generated code is not added to the project.  The generated classes are visible in the `amplify/generated` directory but they are not added to the project.

Manually adding these files to the project allows to compile.

`amplify codegen models` should add the files to the XCode project

**Comment by rodrigoelp** [comment]
The step d indicates in the [documentation](https://aws-amplify.github.io/docs/ios/start):

> d. Drag the models directory over to your project, click on each file, and on the right panel, under Target Membership, check your app target to add it.

`amplify-tools` won't include these automatically to the target you are working on.

**Comment by sebsto** [comment]
OK, I was a bit too fast reading the doc and I missed this step :-)
