### ISSUE TITLE
Build failure upon first build. Having to remove derive data after the first configuration.

### ISSUE THREAD

**Issue by rodrigoelp** [aws-amplify/amplify-ios#245]
Hello, following the documentation specified [here](https://aws-amplify.github.io/docs/ios/start) I get a random compilation error once I have included my pod dependencies, closed and restarted xcode.

# Steps to reproduce

1. Create a new project (iOS13.2, SwiftUI). Check the device you have selected. By default it should pick your connected device or a simulator (such as iPhone 11).
2. Create a podfile (`pod init`) at the project's root folder.
3. Include the dependencies for     `amplify-tools`, `Amplify`, `AWSPluginsCore`, `AmplifyPlugins/AWSAPIPlugin` as instructed.
4. Call `pod install --repo-update` as instructed.
5. Open the workspace associated with your project `xed .`
6. Try to build (cmd+b). This step fails with the following error:
![image](https://user-images.githubusercontent.com/301434/70491362-3a269a80-1b55-11ea-9a69-7f5085607ff1.png)
7. Switch to a different device/sdk and compile again. This fixes the issue.

# Expected behaviour

The build process works when the workspace is opened on its default architecture.

# Actual behaviour

The build process fails for the selected by default architecture and the solution is to switch to a different architecture/device or remove derive data (closing xcode and reopening).

## Additional info

Once derive data has been dropped and recreated, it seems to be working fine.

**Comment by rodrigoelp** [comment]
By the way, to recover the device you need to delete your derived data folder. This is incredibly annoying.

**Comment by drochetti** [comment]
@rodrigoelp I believe this is no longer an issue in [Amplify v1.0.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.0). Feel free to re-open if you're still experiencing problems.
