### ISSUE TITLE
Amplify Tools: Project files misconfigured with absolute paths (amplifyxc.config, amplifyconfiguration.json and amplify)

### ISSUE THREAD

**Issue by rodrigoelp** [aws-amplify/amplify-ios#247]
This should be consider a failure/error of `amplify-tools` (or some other script)? as the generation of the configuration for the `project.pbxproj` will include `amplifyxc.config`, `amplifyconfiguration.json` and `amplify` using absolute paths as opposed to relative paths. This means the project has to be manually fixed if the project is shared via source control with several team members or configured to build in a CI environment (as it is extremely likely these paths won't match).

# Steps to reproduce

1. Create a new iOS project.
2. Create a podfile `pod init`
3. Include the dependencies as stated in [get started](https://aws-amplify.github.io/docs/ios/start) (basically, add amplify tools, amplify and the plugins)
4. Run `pod install --repo-update`

# Expected behaviour
These files are added with relative paths (given everything has been configured and generated in the project). The build/project should continue to work even when shared via source control to other team members or CI.

# Actual behaviour
These files fail to be included as part of the build process and are reported as missing by xcode.

**Comment by nikhname** [comment]
Hi @rodrigoelp, could you provide the build errors when xcode is reporting the files as missing?

**Comment by rodrigoelp** [comment]
Sure thing, I will do something better... here is the build log we get on a different computer to mine. But, the gist of the matter is:

```
CpResource /Users/rod/dev/ios/aws/awsTest3/amplifyconfiguration.json /Users/macusr/Library/Developer/Xcode/DerivedData/awsTest3-bhayghpakreigefetglrbnbamwmc/Build/Products/Debug-iphonesimulator/awsTest3.app/amplifyconfiguration.json (in target 'awsTest3' from project 'awsTest3')
    cd /Users/macusr/Downloads/awsTest3
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/rod/dev/ios/aws/awsTest3/amplifyconfiguration.json /Users/macusr/Library/Developer/Xcode/DerivedData/awsTest3-bhayghpakreigefetglrbnbamwmc/Build/Products/Debug-iphonesimulator/awsTest3.app

error: /Users/rod/dev/ios/aws/awsTest3/amplifyconfiguration.json: No such file or directory (in target 'awsTest3' from project 'awsTest3')

CpResource /Users/rod/dev/ios/aws/awsTest3/awsconfiguration.json /Users/macusr/Library/Developer/Xcode/DerivedData/awsTest3-bhayghpakreigefetglrbnbamwmc/Build/Products/Debug-iphonesimulator/awsTest3.app/awsconfiguration.json (in target 'awsTest3' from project 'awsTest3')
    cd /Users/macusr/Downloads/awsTest3
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/rod/dev/ios/aws/awsTest3/awsconfiguration.json /Users/macusr/Library/Developer/Xcode/DerivedData/awsTest3-bhayghpakreigefetglrbnbamwmc/Build/Products/Debug-iphonesimulator/awsTest3.app

error: /Users/rod/dev/ios/aws/awsTest3/awsconfiguration.json: No such file or directory (in target 'awsTest3' from project 'awsTest3')
```

[Uploading Build awsTest3_2019-12-13T10-22-32.txt.zip…]()

**Comment by nikhname** [comment]
@rodrigoelp great thanks. As you mentioned, previously the absolute paths of the helper files were added to project.pbxproj. The above fix should solve this problem.

**Comment by rodrigoelp** [comment]
Yup, I looked at your comment and it looks good. Hopefully that will be merged in and release soon 👍

**Comment by mahuser20** [comment]
same problem here. Cannot find 'amplifyxc.config'. 
Where can I find that file?

**Comment by nikhname** [comment]
@mahuser20 are you seeing this problem: https://github.com/aws-amplify/amplify-ios/issues/310 ? 
Could you try running ```npm install -g amplify-app``` and trying again
