### ISSUE TITLE
Are many-to-many connections supported?

### ISSUE THREAD

**Issue by rodrigoelp** [aws-amplify/amplify-ios#254]
I have been unable to create a many-to-many relationship with the current api.

I started with the following model:

```graphql
type Person @model {
  id: ID!
  fullName: String!
  nationality: [Nationality] @connection(keyName: "byCountry", fields: ["id"])
}

type Nationality
  @model(queries: null)
  @key(name: "byCountry", fields: ["personID", "countryID"])
  @key(name: "byCitizen", fields: ["countryID", "personID"]) {
  id: ID!
  personID: ID!
  countryID: ID!
  person: Person! @connection(fields: ["personID"])
  country: Country! @connection(fields: ["countryID"])
}

type Country @model {
  id: ID!
  name: String!
  citizens: [Nationality] @connection(keyName: "byCitizen", fields: ["id"])
}
```

The model generation will create an instance:

```swift
public struct Nationality: Model {
  public let id: String
  public var person: Person
  public var country: Country
  
  public init(id: String = UUID().uuidString,
      person: Person,
      country: Country) {
      self.id = id
      self.person = person
      self.country = country
  }
}
```
Which seems perfectly fine until you call the mutation and get the following error:

```
[Amplify.GraphQLError(message: "Variable \'input\' has coerced Null value for NonNull type \'CountryInput!\'", locations: Optional([Amplify.GraphQLError.Location(line: 1, column: 41)]), path: nil, extensions: nil)]
```

Trying out the endpoint directly in console/AppSync/Query I can see the mutation requires me to provide more than just the ids, it requires the the instances of person and country as well and it seems the generated code isn't doing it for me.

Is this a bug of the generator, a more fundamental issue or am I doing something wrong here?

**Comment by rodrigoelp** [comment]
Providing a bit more information on this ticket, I checked the [documentation](https://aws-amplify.github.io/docs/cli-toolchain/graphql#connection) trying to understand why this is an issue.

In this particular scenario I have modelled the `many to many` relationship as two `one to many` relationships as specified by `Nationality`, yet the attempt to insert data in that connection seems completely broken.

**Comment by drochetti** [comment]
Right now the only way to achieve many-to-many is like you did, define a model so you connect two other models via one-to-many. Automatic (or implicit) many-to-many mapping is something that we intend to support in the future but no concrete plans as of now.

Regarding the error you're seeing, can you share the code you're using to execute the mutation?

**Comment by rodrigoelp** [comment]
If you are talking about the swift code to execute the mutation, here it is:

```swift
let person: Person // This was fetched from the api.
let country: Country // this was also fetched from the api.

let nationality = Nationality()
nationality.person = person
nationality.country = country

Amplify.API.mutate(of: nationality, type: .create) { event in
    switch event {
        case .completed(let result):
            print(String(describing: result))
        case .failed(let error):
            print("Why it does NOT WORK?")
            print(String(describing: error))
            print(String(describing: event))
        default:
            print("Ignoring this scenario for now.")
    }
}
```

Both the instance of persona and country where created just before inserting the nationality, chained as part of the callback for each of its mutate methods.

As I mentioned before, this definition is using the `belongsTo` documentation. I explained in #277 that this functionality seems to be broken as I have not been able to use this definition at all.

**Comment by palpatim** [comment]
@rodrigoelp Is this still an issue with the latest released version of Amplify?

**Comment by rodrigoelp** [comment]
Hi @palpatim, I haven't checked to be honest. We moved away from amplify and now I don't have access to an environment I could use to test this.

**Comment by palpatim** [comment]
Thanks for the update. We've successfully tested many-many connections in the GA version of Amplify and haven't seen issues like you described, so I'm closing this issue.
