### ISSUE TITLE
ios DataStore doc - missing steps 

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-ios#255]
The doc at https://aws-amplify.github.io/docs/ios/datastore#using-cocoapods
is missing a couple of steps.

1.
After adding Pods and opening the project, we need to build the project to have the amplify configuration file and amplify directory created. (build is mentioned but this should be more prominent)

2.
Also, the location of the schema is incorrect.
The doc says 
`amplify/backend/api/schema.graphql`
correct path is 
`amplify/backend/api/amplifyDatasource/schema.graphql`

3.
Developers must set `modelgen=true` in `amplifyxc.config` in order to generate code.  The doc assumes this is set by default, which is not the case.

4. 
the doc does not make it clear we need to manually add amplify's generated model file to the XCode project 

5.
DataStore initialization code is incorrect, an explicit call to `APIPlugin` is required. This requires to update podfile and `pod install` again

**Comment by nikhname** [comment]
@sebsto with #4 which generated model file are you referring to? The models should be in amplify/generated/models. Is the amplify folder not added to your project?

**Comment by sebsto** [comment]
@nikname yes the amplify folder is added to the project, but the `*.swift` file generated are not added to the list of files to compile.

In the initialization code provided by the documentation : 

```swift 
...
    try Amplify.add(plugin: AWSDataStorePlugin(modelRegistration: AmplifyModels()))
...
```

`AmplifyModels()` is unknown and causes a compilation error until I manually add the generated code to the project.

**Comment by nikhname** [comment]
Hi @sebsto, in the section of the docs tied to modelgen with amplify-tools (https://aws-amplify.github.io/docs/ios/start#step-2-generate-your-model-files) step d explains that models should be added to the target manually. We do not automatically copy the models over in case a developer already has a model directory.

**Comment by sebsto** [comment]
Great it is more clear now.  The updated doc has all the steps I enumerated before.  I am closing this issue.
https://aws-amplify.github.io/docs/ios/start#step-2-generate-your-model-files
