### ISSUE TITLE
Datastore + API

### ISSUE THREAD

**Issue by Soek22** [aws-amplify/amplify-ios#262]
Hello, reading this https://github.com/aws-amplify/amplify-ios/issues/239#issue-534310745 and this https://github.com/aws-amplify/amplify-ios/pull/249#discussion_r356254432 I get some doubts. Does this means that by using datastore we are forced to stop using API category?

I have read the docs plus seen published videos about the new Datastore feature and I haven't noticed any comment about being 'incompatible' with API.

**Comment by drochetti** [comment]
> Does this means that by using datastore we are forced to stop using API category?

Technically no. API and DataStore can be used independently. DataStore depends on the API category behind the scenes but it doesn't mean you cannot use API directly alongside with DataStore.

That said, we do have some limitations and bugs in the current preview version we. So if you stumble upon a specific behavior you were not expecting, let us know by filing an issue describing your scenario with some code snippets.

**Comment by Soek22** [comment]
Thank you @drochetti . I will open a new issue in such case.
