### ISSUE TITLE
Attach amplify app's analytics to existing pinpoint project.

### ISSUE THREAD

**Issue by toka756** [aws-amplify/amplify-ios#270]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

First Created a pinpoint project in pinpoint console. 
Then I want to add analytics features.
So I create an amplify app by CLI like follows:
```
amplify init
amplify add analytics
amplify push

```
The amplify app's analytics will create and link to a new pinpoint project.
Is there a way that could link amplify app's analytics to existing pinpoint project?

**Is your feature request related to a problem? Please describe.**
My partner created a pin point project first and already did lots of setting tests on the project.
So we want to import analytics to the existing pinpoint project.

**Describe the solution you'd like**
1.Command like:
`amplify add analytics --projectId <your-pinpoint-project-id>`

2.Just configure awsconfiguration.json and run
```
 amplify update analytics
 amplify push
```
```

 "PinpointAnalytics": {
        "Default": {
            "AppId": "your-pinpoint-project-id",
            "Region": "us-xxxx-x" 
        }
},
```

3.Just configure the analytics in amplify console.

**Describe alternatives you've considered**

**Additional context**

**Comment by lawmicha** [comment]
thanks for reporting this issue @toka756 . events are flushed on an interval at every 60 seconds and is configurable by setting `autoFlushEventsInterval` in the `amplifyconfiguration.json` file like this: https://aws-amplify.github.io/docs/ios/analytics#flush-events 

can you confirm that you are still not seeing any events after waiting for a minute for the events to be submitted to pinpoint? You can also immediately submit those events to pinpoint by calling `Amplify.Analytics.flushEvents()`.

**Comment by toka756** [comment]
@lawmicha Thanks for your reply. Although I set the autoFlushEventsInterval to 20s, I do flush event every time for testing.  None event appears in my console after about 10mins.

```
    Amplify.Analytics.record(event: event)
    // Plugin will automatically flush events.
    // You do not have to do this in the app code.
    Amplify.Analytics.flushEvents()
```

Then I turn the logging on and find **PutEvents Error** ocurrs when posting event request to my existing pin point project.  I also attach the entire log file when I call record function.

[put_event_error.txt](https://github.com/aws-amplify/amplify-ios/files/4025662/put_event_error.txt)

Some parts of log: 

```
2020-01-06 17:18:57:764 SampleProject[337:45062] Response body:
{"Message":"User: arn:aws:sts:: <# My amplify app id >:
assumed-role/amplify-SampleProjectios-dev-184359-unauthRole/CognitoIdentityCredentials is not authorized to perform: 
mobiletargeting:PutEvents on resource: arn:aws:mobiletargeting:us-west-2:
<# My amplify app id>:apps/<# My existing pin project id>/events"}

2020-01-06 17:18:57:766 SampleProject[337:45062] PutEvents Error: 
[Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain
 Code=0 "AccessDeniedException"
 UserInfo={responseStatusCode=403, responseHeaders=<CFBasicHash 0xxxxxxxx[0xFxxxxxxxxx]>
{type = immutable dict, count = 10, entries =>
```

**Comment by lawmicha** [comment]
sorry for the delay, thanks for getting back to us. I can see that from enabling more verbose logging, that your previous pinpoint configuration does not have access to write events to pinpoint endpoints. There was a migration that occured on the pinpoint service side that caused a breaking change for clients in older SDKs and since Amplify.Analytics plugin takes a dependency on the new pinpoint service endpoints then migrating to Amplify Analytics plugin is essentially doing that pinpoint migration. 

To fix the problem, i believe you have to update the iAM policy to allow putEvents write access. Please be aware of migration pains as we cannot account for all the different scenarios that the customer has provisioned their aws servies. I would advise to the route for trying out the Analytics plugin with new backend provisioned with Amplify CLI instead of migrating existing resources as Amplify is currently in preview.

**Comment by toka756** [comment]
I tried the same thing with pinpoint iOS SDK before but not ok so I tried amplify SDK... As starting a new backend with amplify CLI actually works well with pinpoint SDK or amplify SDK, it is ok now. Thanks for your replay.

**Comment by fbarraganef** [comment]
I had the implementation of Amplify SDK only with awsconfiguration.json file, but now I seeing that any event is submitted to the dashboard of Analytics. 

In the debugger it seems to submitted fine, but the dashboard not display nothing. 

I'm implementing the iOS SDK.  

I'm pointing the project id of pinpoint in the awsconfiguration file, but even I receiving the error that the region could not be readed from the file. 

So I don't what exactly changes.
