### ISSUE TITLE
Centralize versions

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#276]
Currently we have versions for Amplify core and AWS plugins strewn somewhat haphazardly throughout code, in configuration, code, and dependency management. We need to centralize this into a single source of truth that other modules can either tap into as needed, or use to generate code (with appropriate "DO NOT MODIFY" comments) that acts as that module's single source of version truth.

Off the top of my head, I know of version being used in these contexts, but there may be others

- (All) Info.plist
- (AWS Plugin) User agent string (which really should be derived from the module's Info.plist)
- (All) Podfile
- (All) Podspec

**Comment by jamesonwilliams** [comment]
We should align our strategies on iOS and Android. I recently changed the behavior of the Android versioning, so that all modules "move together." That is, if we bump to 0.9.1 of a plugin artifact, we would potentially need to release 0.9.1 of all modules, even if the other ones hadn't changed. This single version is also now used in our `User-Agent` headers.

**Comment by palpatim** [comment]
> We should align our strategies on iOS and Android. I recently changed the behavior of the Android versioning, so that all modules "move together." That is, if we bump to 0.9.1 of a plugin artifact, we would potentially need to release 0.9.1 of all modules, even if the other ones hadn't changed. This single version is also now used in our `User-Agent` headers.

In that, at least, we are aligned--iOS also maintains Amplify Core and all of the plugins with the same version, which same version is propagated to the user agent

**Comment by lawmicha** [comment]
this is where currently the versions are used and updated via scripts: https://github.com/aws-amplify/amplify-ios/commit/0cfde3335e0b89bee3e927accb42238200c0d9c2

**Comment by palpatim** [comment]
We have an update script that bumps versions across the various usages. The effort to migrate all of these usages to literally use a single file is going to be more than the benefit of having that file. Closing as wontfix.
