### ISSUE TITLE
AWSDate cannot be used.

### ISSUE THREAD

**Issue by rodrigoelp** [aws-amplify/amplify-ios#278]
The following model fails when an instance is created.

```graphql
type Sample @model {
  id: ID!
  whatever: AWSDate!
}
```

The generated code creates:

```swift
public struct Sample: Model {
  public let id: String
  public var whatever: Date
  
  public init(id: String = UUID().uuidString,
      whatever: Date]) {
      self.id = id
      self.whatever = whatever
  }
}
```
The definition is fine, the serialisation is wrong as pushing this mutation up returns:
```
GraphQLResponseError<Sample>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Variable \'dateOfBirth\' has an invalid value. Unable to parse `2019-12-24T04:15:57.798Z` as a valid date.", locations: Optional([Amplify.GraphQLError.Location(line: 1, column: 26)]), path: nil, extensions: nil)]
```

I think it is either not using an encoder for AWSDate or it is not using the right encoder.

The [documentation](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) indicates the format should be:

> `1970-01-01Z`, `1970-01-01-07:00` and `1970-01-01+05:30` as valid dates. The time zone offset must either be Z (representing the UTC time zone) or be in the format ±hh:mm:ss. The seconds field in the timezone offset will be considered valid even though it is not part of the ISO 8601 standard.

In any case, checking the `AWSPluginCore` I can see we are using the `iso 8601` string encoding for date and date time ([here](https://github.com/aws-amplify/amplify-ios/blob/master/AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift#L28) but I am not quite sure what changes should I make here. I tried providing a date format similar to `1970-01-01Z` but it only crashes somewhere else with a `APIError: valueNotFound`

Changing the schema to the one below seems to fix the serialisation problem... but this needs a better fix.
 
```graphql
type Sample @model {
  id: ID!
  whatever: AWSDateTime! # changed from AWSDate to AWSDateTime
}
```

**Comment by drochetti** [comment]
Thanks for reporting this bug, I'll review our JSON decoding logic for date types.

**Comment by jamesonwilliams** [comment]
Related: https://github.com/aws-amplify/amplify-android/issues/221, https://github.com/aws-amplify/amplify-ios/issues/286
