### ISSUE TITLE
Feature request: clear/flush DataStore

### ISSUE THREAD

**Issue by lazy-var** [aws-amplify/amplify-ios#288]
**Describe the question**
Prevoiusly, when using AppSync client with API category (sdk) we had the option to flush caches with: `.clearCaches(options: clearCacheOptions)`.

Is there something similar to force clear/flush DataStore on client? i.e. I need it when user signs out, etc..

**Comment by drochetti** [comment]
@lazy-var `Amplify.DataStore.clear()` is available as of `1.0.0`. Closing this.

**Comment by lazy-var** [comment]
Thank you very much @drochetti 
I confirm it is working
