### ISSUE TITLE
Mutation event not published when observing for changes to datastore

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-ios#297]
**Describe the bug**

i try to observe for changes using the DataStore.publisher. New items are created via appsync console but the events are not published.

**To Reproduce**
1. i'm using the snippet from the amplify ios docs
```swift
let postSubscription = Amplify
    .DataStore
    .publisher(for: Post.self)
    .sink(receiveCompletion: { completion in
        if case .failure(let err) = completion {
            print("Subscription received error - \(err.localizedDescription)")
        }
    }) {
        print("Subscription received mutation: \($0)")
}
```
2. i create a new Post from the appsync console. 
3. i'm monitoring the datastore sqlite table and can see my new post in the table. 
4. the receiveValue closure is never called

**Expected behavior**
receiveValue closure should be triggered for every mutation

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 0.10.0]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 5.0]

**Device Information (please complete the following information):**
 - Device: iphone 11 prox max simulator
 - iOS Version: ios 13.1

**Comment by wooj2** [comment]
Thank you for reporting this and taking a look at Amplify while we are still in preview mode.  I've submitted a PR and pushed the following PR, which should address this:
https://github.com/aws-amplify/amplify-ios/pull/308

I will be closing this issue, but feel free to re-open if you have any further issues with this.

**Comment by wooj2** [comment]
By the way, if your variable `postSubscription` goes out of context, the callbacks for both `receiveCompletion:` and `receive:` will not get called.  So you may want to have some code that looks something like this:
```
class ViewController {
    var postSubscription: AnyCancellable?
    ...
    func setupSubscription {
        postSubscription = Amplify
            .DataStore
            .publisher(for: Post.self)
            .sink(....)
        .......
    }
}
```
