### ISSUE TITLE
Amazon Transcribe (Streaming Speech To Text) Status?

### ISSUE THREAD

**Issue by prmacias** [aws-amplify/amplify-ios#302]
**Which AWS Services is the feature request for?**
Amazon Transcribe

**Is your feature request related to a problem? Please describe.**
No. I'm looking for the feature for Amazon Transcribe to have the transcript to be streamed from swift to aws. It seems there are web socket, and streaming functionalities in this library. Is it completed?

**Describe the solution you'd like**
Hopefully there is a solution for me to pass the audio and get the text back in real time. 

**Describe alternatives you've considered**
If not, then I'll look in Google Speech to Text

**Additional context**

**Comment by prmacias** [comment]
perfect! I see this url and documentation. Thanks!

`https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSTranscribeStreaming/Classes/AWSTranscribeStreaming.html`

**Comment by prmacias** [comment]
@kneekey23 the sample code will be nice to have. Thanks again!

**Comment by kneekey23** [comment]
hi @prmacias here is how you would call it in Amplify after using the cli to add the resource in aws:
```
    func transcribe() {
        let options = PredictionsSpeechToTextRequest.Options()
        _ = Amplify.Predictions.convert(speechToText: audioFilename, options: options, listener: { (event) in
            
            switch event {
            case .completed(let result):

                print(result.transcription)

            default:
                print("")
                
                
            }
        })
    }
```

**Comment by kneekey23** [comment]
hi @prmacias can we close this one?

**Comment by prmacias** [comment]
@kneekey23 

Yes, I haven't gotten at that point but we can close it. I am still having pods issue (it seems it's not related to amplify. 

Thanks
