### ISSUE TITLE
IOS Deployment Target

### ISSUE THREAD

**Issue by prmacias** [aws-amplify/amplify-ios#306]
**Describe the bug**
I'm following the tutorial to install the Predictions. I installed the auth - default configuration then installed the predications. I scrolled down to the backend section (Connect to Your Backend) - I'm at and installed pod then got the error message - see below. My deployment target version is 11.2. I looked at the requirements but couldn't find the minimum deployment target for the plug in.

Add the dependencies to the Podfile:

```
target :'YOUR-APP-NAME' do
	use_frameworks!
	pod 'AWSPredictionsPlugin'
	pod 'AWSMobileClient', '~> 2.12.0'
end
Run pod install --repo-update before you continue.
```

The error message is 

```
[!] CocoaPods could not find compatible versions for pod "AWSPredictionsPlugin":
  In Podfile:
    AWSPredictionsPlugin

Specs satisfying the `AWSPredictionsPlugin` dependency were found, but they required a higher minimum deployment target.
```

**To Reproduce**

**Which AWS service(s) are affected?**
AWSPredictions?

**Expected behavior**
I expect the installation for backend to be installed.

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 4.13.1
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**

**Comment by prmacias** [comment]
@kneekey23 

I changed the deployment target to 13.1 in Pods. I'm still having some errors - I tried changing 2.10.3 and added 0.10.0 for Predictions Plug in but still having errors.

```
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In snapshot (Podfile.lock):
    AWSCore (= 2.10.3, ~> 2.10.2)

  In Podfile:
    AWSAppSync (~> 2.14.2) was resolved to 2.14.2, which depends on
      AWSCore (~> 2.10.2)

    AWSCore

    AWSPredictionsPlugin was resolved to 0.10.0, which depends on
      AWSTranslate (~> 2.12.2) was resolved to 2.12.2, which depends on
        AWSCore (= 2.12.2)
```

Here are the list of AWS pods -

```
  pod 'AWSCore', '~> 2.10.2'
  pod 'AWSAppSync', '~> 2.14.2'
  pod 'AWSPredictionsPlugin'
  pod 'AWSMobileClient', '~> 2.12.0'
```

**Comment by lazy-var** [comment]
Hi @prmacias, try with running:
`pod update`

That solves this kind of dependency errors when I get them.

**Comment by prmacias** [comment]
@lazy-var 

I fixed by adding the dependencies (in other page) -

https://aws-amplify.github.io/docs/ios/start

IMO, i think the guide should be rewritten to get amplify working first like print something concrete that amplify is successful then pick category whatever we want. At first, I thought the introduction was for to install GraphQL so I skipped it but I need the core files in order to get the Predictions. 

```
  pod 'amplify-tools'

  pod 'Amplify'
  pod 'AWSPluginsCore'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  
  pod 'AWSPredictionsPlugin'
  pod 'AWSMobileClient', '~> 2.12.0'
```

**Comment by kneekey23** [comment]
hi @prmacias I will fix the documentation because you are absolutely right. However you do not need to add the AWSAPIPlugin for predictions unless you are additionally using that category just to clean up your podfile in case you are not.
