### ISSUE TITLE
Generating wrong helper files for iOS platform

### ISSUE THREAD

**Issue by AradaRF** [aws-amplify/amplify-ios#310]
**Describe the bug**
This should be consider a failure/error of amplify-tools (or some other script)? upon generation of the configuration for the project.pbxproj should include amplifyxc.config, amplifyconfiguration.json and amplify, but in my case is not including amplifyxc.config. Generates the Android helper file.

**To Reproduce**
1. Create a new iOS project.
2. Create a podfile pod init
3. Include the dependencies as stated in get started (basically, add amplify tools, amplify and the plugins)
4. Run pod install --repo-update

**Expected behavior**
These files are added with relative paths (given everything has been configured and generated in the project). The build/project should continue to work and generate the helper files for the respective platform

**Actual behavior**
 When we build the project it fails when running the script that makes the push to amplify backend. The file that I get in my directory is the amplify-gradle-config.json that's for Android.
Error: path_to_directory/amplifyxc.config : no such file or directory, line 18

**Comment by nikhname** [comment]
@AradaRF This should be fixed by https://github.com/aws-amplify/amplify-cli/pull/3312. Could you try """npm install -g amplify-app@latest""" and try again.

**Comment by nikhname** [comment]
Also, please remove the amplify folder and amplify-gradle-config.json file before retrying
