### ISSUE TITLE
Add DataStore/API integration test for a model with all supported types

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#314]
This would be a follow up task after @drochetti's work Date/Enum/Primitive support, We should add an integration test which contains a model with all of the supported types

**Comment by lawmicha** [comment]
we should also make sure mutating and querying for AppSync Floats with values that are at the upper limit is working or if there are some limitations, document what is the maximum value possible

**Comment by lawmicha** [comment]
we could take https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyTestCommon/Models/QPredGen.swift and use the schema
```
/*
 Generated from:
 type QPredGen @model {
   id: ID!
   name: String!
   myBool: Boolean
   myDouble: Float
   myInt: Int
   myString: String
   myDate: AWSDate
   myDateTime: AWSDateTime
   myTime: AWSTime
 }
 */
```
in both of the integration tests in DataStore and API

**Comment by kjones** [comment]
Other possible scalars to test: https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html
Are all these supported?

Other scenarios could include all combinations of nullable fields. 
```graphql
type TestModel @model {
  id: ID!
  testInt: Int!
  nullableInt: Int
  intList: [Int!]!
  intNullableList: [Int!]
  nullableIntList: [Int]!
  nullableIntNullableList: [Int]
}
```
Enums and nested types have also been problematic in the past so having tests for them might be useful.
```graphql
type EnumTestModel @model {
  enumVal: TestEnum!
  nullableEnumVal: TestEnum
  enumList: [TestEnum!]!
  enumNullableList: [TestEnum!]
  nullableEnumList: [TestEnum]!
  nullableEnumNullableList: [TestEnum]
}

enum TestEnum {
  VALUE_ONE
  VALUE_TWO
}

type NestedTypeTestModel @model {
  nestedVal: Nested!
  nullableNestedVal: Nested
  nestedList: [Nested!]!
  nestedNullableList: [Nested!]
  nullableNestedList: [Nested]!
  nullableNestedNullableList: [Nested]
}

type Nested {
  valueOne: Int
  valueTwo: String
}
```

**Comment by lawmicha** [comment]
Thanks @kjones, those are great examples. I've used them almost exactly in this PR: https://github.com/aws-amplify/amplify-ios/pull/1135
