### ISSUE TITLE
Add converter class for model into SQLite and GraphQL components

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#318]
Synced with Daniel on this, opening issue to refactor some of this conversion logic into some converter class to be used to take model field types and values into SQLite and GraphQL components

_Originally posted by @lawmicha in https://github.com/aws-amplify/amplify-ios/pull/317_

**Comment by drochetti** [comment]
This was mostly done by the PR #334. I'll close this one for now and we can track future improvements of the serialization code in a new ticket.
