### ISSUE TITLE
Remove AWSDataStoreCategoryPlugin.Cancellable in favor of Amplify.Cancellable

### ISSUE THREAD

**Issue by wooj2** [aws-amplify/amplify-ios#328]
This PR:
https://github.com/aws-amplify/amplify-ios/pull/323/files

Introduces a new Cancellable Protocol.  We should dig into why we are unable to use Amplify.Cancellable in the DataStore Category.

**Comment by wooj2** [comment]
Namespacing Cancellable is not possible due to current limitations in Swift, so accessing Amplify.Cancellable does not work.

@drochetti figured out that we could create a new file and stick the following inside:
```
import Amplify

public typealias AmplifyCancellable = Cancellable
```
This is certainly one way to work around the language limitation, but in that case, why not just change the original protocol's name to AmplifyCancellable?

I will work with other teammates to come to a decision on which path to move forward on.

**Option 1:**
Use the typealias workaround each time this comes up

**Option 2:**
Rename the original Cancellable to something like AmplifyCancellable.

**Option 3:**
Rename `Cancellable` to something like `Killable`
- Note: the original name Protocol name I was working with was Killable.  During this phase, I was working towards a design that when you called kill(), it would immediately destroy the item you called kill on, however, after digging into the code, I realized this isn't really possible to do in an efficient manner given the asynchronous nature of our system, so `cancel()/Cancellable` seems more appropriate.

**Option 4:**
Something else?

**Comment by drochetti** [comment]
Is this still a valid issue?

If so I vote for Option 1, as name clashes are a common problem in large Swift applications with many dependencies and typealias is often used to solve them. Also, I believe using the fully qualified name works: `Amplify.Cancellable`.
