### ISSUE TITLE
Implement AmplifyTools pod in amplify-ios repo

### ISSUE THREAD

**Issue by nikhname** [aws-amplify/amplify-ios#342]
**Is your feature request related to a problem? Please describe.**
The amplify-tools podspec is currently sourced here: https://github.com/nikhname/amplify-tools-spec/blob/master/amplify-tools/0.2.0/amplify-tools.podspec
And published on the trunk here: https://github.com/CocoaPods/Specs/tree/master/Specs/7/4/b/amplify-tools

**Describe the solution you'd like**
Add an AmplifyTools podspec to the amplify-ios repo with the same build_phase script.

**Describe alternatives you've considered**
Add the bash script under script_phases to an existing pod in this repo (e.g. datastore)

**Additional context**
CLI installation, boilerplate project creation and xcode logic will still be in CLI repo as a part of amplify-app package: https://github.com/aws-amplify/amplify-cli/tree/master/packages/amplify-app

**Comment by lawmicha** [comment]
does this mean Amplify-Tools will be versioned with Amplify releases? why not keep it in a separate repo? ie. move https://github.com/nikhname/amplify-tools-spec/ to githubcom/aws-amplify/amplify-tools
