### ISSUE TITLE
New iOS project with DataStore fails to run

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-ios#348]
**Describe the bug**
When building and running a fresh new iOS project with DataStore and following the steps in the documentation at https://aws-amplify.github.io/docs/ios/datastore#datastore, the project fails at runtime with 
```
Fatal error: API category is not configured. Call Amplify.configure() before using any methods on the category.: file /Users/stormacq/Documents/amazon/code/amplify/Datastore/Pods/Amplify/Amplify/Categories/API/AmplifyAPICategory.swift, line 18
2020-03-09 15:17:30.836018+0100 Datastore[22390:150576] Fatal error: API category is not configured. Call Amplify.configure() before using any methods on the category.: file /Users/stormacq/Documents/amazon/code/amplify/Datastore/Pods/Amplify/Amplify/Categories/API/AmplifyAPICategory.swift, line 18
```

**To Reproduce**
1. create a new iOS project
2. `pod init`
3. Add pod as described at https://aws-amplify.github.io/docs/ios/datastore#using-cocoapods
4. Add initialization code as described at https://aws-amplify.github.io/docs/ios/datastore#setup
5. Build and Run

**Expected behavior**
The application should run without errors

**Screenshots**

**Environment(please complete the following information):**
  - Amplify (0.10.0)
  - amplify-tools (0.2.0)
  - AmplifyPlugins/AWSDataStorePlugin (0.10.0):
CocoaPod
Swift 5.x

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 13
 - Specific to simulators:

**Additional context**
1.

I noticed that `amplifyxc.config` has the following values: 
```
push=false
modelgen=false
profile=default
envName=amplify
```
So, instructions in the doc to just build from XCode do not work.  We need to manually generate code using these instructions https://aws-amplify.github.io/docs/ios/datastore#manual-model-generation.

2. 
It looks like nothing initializes the amplify project : neither an `amplify codegen models`, nor the amplify plugin.

```
% amplify push
An error occured during the push operation: Current environment cannot be determined
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```

When strictly following instructions in the doc, these two files are empty `{}` : `awsconfiguration.json` and `amplifyconfiguration.json`

**Workaround**

The workaround is to manually initialize amplify with : 

```
% amplify init
```

Be sure to chose `amplify` as environement name, as this is the env hard coded in `amplifyxc.config`

**Proposed Solution** 

Two possible solutions : 
Either update the doc to make it clear `amplify init` must be called manually before any other instruction is attempted.

Either improve `AmplifyPlugins/AWSDataStorePlugin` to transparently do the `amplify init` at first run

**Comment by sebsto** [comment]
I made more tests around this and found that the order of `amplify init` and the first build is important

**Exemple 1 : **

1. `amplify init`
2. `pod init` and `pod install`
3. open workspace and build 

Result : 
- First build fails (no error), second build works
- local API category is not created

**Exemple 2:**

1. `pod init` and `pod install`
2. open workspace and build 
3. `amplify init`

Result : 
- build succeded
- local API category is created

**Comment by drochetti** [comment]
@sebsto I believe this is no longer an issue in [v1.0.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.0). Feel free to re-open otherwise.
