### ISSUE TITLE
Upgrade across all SDK dependency to `~> 2.13.0` 

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#356]
this PR is outdated now and we can update to take `~> 2.13.0` to get all patch versions of 2.13. a minor version will last a few months

_Originally posted by @lawmicha in https://github.com/aws-amplify/amplify-ios/pull/315#issuecomment-598793987_

**Comment by kneekey23** [comment]
Closing issue as PR was merged
