### ISSUE TITLE
Enable TransferAcceleration

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#36]
**Investigate:** 
JS experience, how it is currently enabled by the developer. Can transferAcceleration be configured on per request basis? ie. only enable for downloads and not uploads, for some reason. Native experience, how is it enabled on transferUtility now?

**CLI changes**
- Ask to enable transferAcceleration
- If Yes:
1. apply some settings on the bucket to allow transfer acceleration
2 add transferAcceleration: true into amplifyconfiguration.json

**Library changes**
Extract `TransferAcceleration` and propagate into setting up dependencies (transferUtility/s3)

**Comment by jamesonwilliams** [comment]
Should we move this to `amplify-cli` project?

**Comment by lawmicha** [comment]
moved this over to pivotal. i think once someone picks this up, we can then open a new issue with CLI for the feature request
