### ISSUE TITLE
Amplify pod does not support new CLI release with customType and EnumPersistable

### ISSUE THREAD

**Issue by AnruStander** [aws-amplify/amplify-ios#366]
**Describe the bug**
I have updated my Amplify CLI after the new release to solve previous issues with [String] and enum types. But now when I run the codegen, xcode complains about undeclared type EnumPersistable as well as ModelFieldType has no member customType. It seems like the Encodable, Decodable issue is also not fixed yet.

**Environment:**
 - Amplify Framework Version: [e.g. 0.10.0]
 - Dependency Manager: [Cocoapods]
 - Swift Version : [5.0]

**Comment by drochetti** [comment]
Hi @AnruStander, we're working towards a new release of Amplify, in the meantime, could you try pointing your pods to the master branch of this repo and give it a try?

```
  pod 'Amplify', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'
  pod 'AWSPluginsCore', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'
  pod 'AmplifyPlugins/AWSAPIPlugin', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'
  pod 'AmplifyPlugins/AWSDataStorePlugin', :git => 'https://github.com/aws-amplify/amplify-ios.git', :branch => 'master'

```

**Comment by AnruStander** [comment]
Thanks, it was quite urgent at the time, so we had to use something else. But will try it again soon. Thank you.

**Comment by drochetti** [comment]
@AnruStander since version `1.0.0` with enum support has been out for a few weeks I'll close this one. Let me know if you still have issues with enums.
