### ISSUE TITLE
Linker Error when using SPM dependency as a dynamic library

### ISSUE THREAD

**Issue by iThink32** [aws-amplify/amplify-ios#3722]
### Describe the bug

I have a package that uses amplify swift as shown below.

```
let package = Package(
    name: "UIComponents",
    platforms: [.iOS(.v16)],
    products: [
        .library(
            name: "UIComponents",
            //type: .dynamic,
            targets: ["UIComponents", "Networking"]),
    ],
    dependencies: [.package(url: "https://github.com/ReactiveX/RxSwift.git",
                            .upToNextMajor(from: Version("6.0.0"))),
                   .package(//name: "Amplify",
                            url: "https://github.com/aws-amplify/amplify-ios", .upToNextMajor(from: Version("2.0.0"))),
                   .package(url: "https://github.com/RxSwiftCommunity/RxDataSources.git", from: "5.0.0")],
    targets: [
        .target(
            name: "UIComponents",dependencies: ["RxSwift", .product(name: "RxCocoa", package: "RxSwift")],
            path: "Submodules/Sources/UIComponents"),
        .target(name: "Networking", dependencies: [.product(name: "Amplify", package: "amplify-ios"),
                                                   .product(name: "AWSPluginsCore", package: "amplify-ios"),
                                                   .product(name: "AWSCognitoAuthPlugin", package: "amplify-ios"),
                                                   .product(name: "RxDataSources", package: "RxDataSources")],
                                                   path: "Submodules/Sources/Networking"),
    ]
)
```

Now when I integrate the above package into an App just like the above, it gets added as a static library and it works fine.
If I uncomment the 

```
//type: .dynamic,
```
above and integrate it. It fails with linker errors as shown below.

<img width="807" alt="Screenshot 2024-05-27 at 11 13 38 PM" src="https://github.com/aws-amplify/amplify-swift/assets/34152717/3b4fc83f-a09f-48dd-b799-d8b170e02c67">

Any way to fix this as I do not intend to use static libraries in my application.

### Steps To Reproduce

```swift
Same as given above.
```

### Expected behavior

The client should be able to decide whether static or dynamic libraries are to be used. It cannot be a limitation on Amplify.

### Amplify Framework Version

2.34.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.10.0

### Xcode version

15.4

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

17

### Device

Iphone 15 Simulator

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by 5d** [comment]
Hi, I was able to build a dynamic library using Swift 5.9 and the latest amplify-swift version as a dependency. Could you share an example project to help reproduce the error?

**Comment by iThink32** [comment]
@5d can you please provide your package.swift file so that I can replicate that and create a sample project?

**Comment by iThink32** [comment]
Also please mention if the version you are using in your package.swift file is stable for a production roll out?

**Comment by 5d** [comment]
I am using Apple's example SPM repo [example-package-dealer](https://github.com/apple/example-package-dealer). I was following your `Package.swift` config.

```
// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

/*
 This source file is part of the Swift.org open source project

 Copyright 2015 – 2021 Apple Inc. and the Swift project authors
 Licensed under Apache License v2.0 with Runtime Library Exception

 See http://swift.org/LICENSE.txt for license information
 See http://swift.org/CONTRIBUTORS.txt for Swift project authors
*/

import PackageDescription

let package = Package(
    name: "dealer",
    platforms: [
        .macOS(.v11),
        .iOS(.v16)
    ],
    products: [
        .executable(name: "dealer", targets: ["dealer"]),
        .library(name: "HelloLib", type: .dynamic, targets: ["Hello"])
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/apple/example-package-deckofplayingcards.git",
                 from: "3.0.0"),
        .package(url: "https://github.com/apple/swift-argument-parser.git",
                 from: "0.4.4"),
        .package(url: "https://github.com/aws-amplify/amplify-swift", from: "2.0.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .executableTarget(
            name: "dealer",
            dependencies: [
                .product(name: "DeckOfPlayingCards",
                         package: "example-package-deckofplayingcards"),
                .product(name: "ArgumentParser",
                         package: "swift-argument-parser")
            ]),
        .testTarget(
            name: "DealerTests",
            dependencies: [
                .byName(name: "dealer")
            ]),
        .target(
            name: "Hello",
            dependencies: [
                .product(name: "Amplify", package: "amplify-swift"),
                .product(name: "AWSPluginsCore", package: "amplify-swift"),
                .product(name: "AWSCognitoAuthPlugin", package: "amplify-swift")
            ],
            path: "Sources/TestLib"
        )
    ]
)
```

**Comment by iThink32** [comment]
ok ill use this and let you know.

**Comment by iThink32** [comment]
@5d why is it that I'm using 
```
.package(//name: "Amplify",
                            url: "https://github.com/aws-amplify/amplify-ios", .upToNextMajor(from: Version("2.0.0"))),
```
and you are using 

```
.package(url: "https://github.com/aws-amplify/amplify-swift", from: "2.0.0")
```

What's the difference here?

**Comment by lawmicha** [comment]
If the question is about the two inputs, 

`https://github.com/aws-amplify/amplify-ios` was renamed to `https://github.com/aws-amplify/amplify-swift` so using either is the same

the second input represents the dependency resolution https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#package-dependency-requirement 
```
/// The following example allows the Swift Package Manager to select a version
/// like a  `1.2.3`, `1.2.4`, or `1.3.0`, but not `2.0.0`.
///
///    .package(url: "https://example.com/example-package.git", from: "1.2.3"),
```

**Comment by iThink32** [comment]
HI @lawmicha, @5d  tried on a sample project and it seems to work fine. Any idea on why this might be happening on the main project? Any leads would help

**Comment by lawmicha** [comment]
Can you expand on what you mean by the sample project working and main project not, with some code snippets or steps to reproduce?

**Comment by iThink32** [comment]
@lawmicha Well the main project and the sample project has the following architecture:

Project A -> Package B -> Package C (having amplify as a dependency)

This means a Project A has a package B as a dependency which intern has Package C has a dependency which finally has Amplify as its dependency.

Now Project A when used as is faces linker issues with the dynamic library of Amplify
But when I created Project B and added the same dependencies, it worked fine.

From my initial observation, 
1. Project A initially had cocoa pods but now it has been completely migrated to SPM.
2. Project A has other SPM dependencies as well.

Whereas 
1. Project B has been created from scratch so it only has traces of SPM
2. No other dependencies

I hope this is sufficient to explain. Im yet to dig deeper and compare the build settings of both to determine what is causing this.

**Comment by thisisabhash** [comment]
Are you still facing problems when you re-create 
```
Project A -> Package B -> Package C
```
from scratch?

**Comment by iThink32** [comment]
No.

**Comment by iThink32** [comment]
@harsh62 I guess yes but any pointers on how to solve this issue would help me.
