### ISSUE TITLE
Where we declare Mutation, Query and Subscription

### ISSUE THREAD

**Issue by vishaldroisys** [aws-amplify/amplify-ios#411]
Hello,

As we have configure and initialise Amplify for iOS Project. Amplify folder is generated with Default graphql file. how to generate model, Query,mutation and Subscription through Schema.json or schema.graphql(generated from AWS portal)

Thanks In advanced

<img width="1238" alt="Screenshot 2020-04-30 at 6 36 14 PM" src="https://user-images.githubusercontent.com/49299967/80714003-f5a29800-8b11-11ea-91bd-5e3cd3929d38.png">

**Comment by lawmicha** [comment]
Hi @vishaldroisys are you trying to generate the Model classes used in DataStore/API? you can run `amplify codegen models` to generate them.

**Comment by lawmicha** [comment]
Please take a look at https://docs.amplify.aws/lib/q/platform/ios for more documentation. closing this now, let us know if you have any other questions
