### ISSUE TITLE
AuthProvider naming conflict

### ISSUE THREAD

**Issue by royjit** [aws-amplify/amplify-ios#426]
We use the term `AuthProvider` in different context

1. DataStore AuthRule [Ref](https://github.com/aws-amplify/amplify-ios/blob/724a29839396665b1496944bdfbe8ca373862e99/Amplify/Categories/DataStore/Model/Schema/AuthRule.swift#L15)
```
public enum AuthProvider {
    case apiKey
    case iam
    case oidc
    case userPools
}
```
2. AWSPluginsCore [Ref](https://github.com/aws-amplify/amplify-ios/blob/master/AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AuthProvider.swift)
```
public enum AuthProvider {
    case apiKey(APIKeyProvider)
    case tokenProvider(AuthTokenProvider)
    case iamCredentialsProvider(IAMCredentialsProvider)
}
```
3. Authentication provider in Auth category [Ref](https://github.com/aws-amplify/amplify-ios/blob/AuthCategory/Amplify/Categories/Auth/Models/AuthSocialProvider.swift#L10)
```
public enum AuthProvider {

    case amazon

    case apple

    case facebook

    case google

    case oidc

    case saml

    case custom(String)
}
```

We need distinguish between these different enum

**Comment by lawmicha** [comment]
the first one can be `AuthRuleProvider`or will it work if it defined within the AuthRule? like AuthRule.Provider

**Comment by royjit** [comment]
Yes, sounds good. Second one is AuthZProvider and third AuthNProviders. Wondering whether we should name like that?

**Comment by royjit** [comment]
How about this:
1. In DataStore - `AuthorizationType`
2. In AWSPluginsCore - `AuthorizationProvider`
3. In Auth category - `AuthProvider`

**Comment by palpatim** [comment]
We call the GraphQL auth types (IAM, API Key, etc) ["Authorization Modes"](https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#authorization-modes). However, as AWS-specific types, these should not be housed in the top-level Amplify project.

**Comment by lawmicha** [comment]
> We call the GraphQL auth types (IAM, API Key, etc) ["Authorization Modes"](https://docs.amplify.aws/sdk/api/graphql/q/platform/ios#authorization-modes). However, as AWS-specific types, these should not be housed in the top-level Amplify project.

removing the first one here https://github.com/aws-amplify/amplify-ios/pull/458

**Comment by lawmicha** [comment]
> How about this:
> 
> 1. In DataStore - `AuthorizationType`
> 2. In AWSPluginsCore - `AuthorizationProvider`
> 3. In Auth category - `AuthProvider`

for 2, AuthorizationProvider, looks good

**Comment by royjit** [comment]
Removing 2 since it is not used anywhere.
PR to rename 3 - https://github.com/aws-amplify/amplify-ios/pull/467
