### ISSUE TITLE
PredictionsPluginConfiguration - Configuration - Fails with Default Region

### ISSUE THREAD

**Issue by christoff-1992** [aws-amplify/amplify-ios#431]
**Describe the bug**
Using a default region as part of the awsPredictionsPlugin fails as an error is thrown.

```Swift
if let configuration = try values.decodeIfPresent(ConvertConfiguration.self, forKey: .convert)
```

<details>
  <summary>PredictionsPluginConfiguration</summary>
  
```Swift
extension PredictionsPluginConfiguration: Decodable {

    enum CodingKeys: String, CodingKey {
        case identify
        case interpret
        case convert
        case defaultRegion
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        let regionString = try values.decode(String.self, forKey: .defaultRegion) as NSString
        self.defaultRegion = regionString.aws_regionTypeValue()

        if let configuration = try values.decodeIfPresent(IdentifyConfiguration.self, forKey: .identify) {
            self.identify = configuration
        } else {
            self.identify = IdentifyConfiguration(defaultRegion)
        }

        if let configuration = try values.decodeIfPresent(InterpretConfiguration.self, forKey: .interpret) {
            self.interpret = configuration
        } else {
            self.interpret = InterpretConfiguration(defaultRegion)
        }

        if let configuration = try values.decodeIfPresent(ConvertConfiguration.self, forKey: .convert) {
            self.convert = configuration
        } else {
            self.convert = ConvertConfiguration(defaultRegion)
        }
    }
}
```
</details>

If a default region is not specified the following error is thrown and then re-thrown up the call hierarchy.

```Swift
 throw PluginError.pluginConfigurationError(PluginErrorMessage.missingRegion.errorDescription,
                                                       PluginErrorMessage.missingRegion.recoverySuggestion)
```

<details>
  <summary>ConvertConfiguration</summary>
  
```Swift
public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        var awsRegion: AWSRegionType?

        if let configuration = try values.decodeIfPresent(TranslateTextConfiguration.self,
                                                          forKey: .translateText) {
            self.translateText = configuration
            let nestedContainer = try values.nestedContainer(keyedBy: SubRegion.self,
                                                             forKey: .translateText)
            awsRegion = awsRegion ?? ConvertConfiguration.getRegionIfPresent(nestedContainer)
        } else {
            self.translateText = nil
        }

        if let configuration = try values.decodeIfPresent(SpeechGeneratorConfiguration.self,
                                                          forKey: .speechGenerator) {
            self.speechGenerator = configuration
            let nestedContainer = try values.nestedContainer(keyedBy: SubRegion.self,
                                                             forKey: .speechGenerator)
            awsRegion = awsRegion ?? ConvertConfiguration.getRegionIfPresent(nestedContainer)
        } else {
            self.speechGenerator = nil
        }
        guard  let region = awsRegion else {
            throw PluginError.pluginConfigurationError(PluginErrorMessage.missingRegion.errorDescription,
                                                       PluginErrorMessage.missingRegion.recoverySuggestion)
        }
        self.region = region
    }
```
</details>

**To Reproduce**

1. Create a awsPredictionsPlugin configuration with a default region.
2. Add the AWSPredictionsPlugin to Amplify
3. Configure Amplify
4. Error will be thrown

**Expected behavior**
Expect the configuration to be created using the default values

**Environment(please complete the following information):**
 - Amplify Framework Version: Issue Present in Master
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Other Comments**
I expect this issue could occur for other default values due to way this has been written.

This could also be due to the fact that it appears that 'transcription' is not currently part of the prediction plugins configuration. I may have misunderstood the documentation for the usage of transcribe. (Audio to Text)

In this scenario is the following required in the setup for Amplify or can you directly use the methods to convert speech to text as described on https://docs.amplify.aws/lib/predictions/transcribe/q/platform/ios?

```Swift
try Amplify.add(plugin: predictionsPlugin)
try Amplify.configure()
```

**Comment by lawmicha** [comment]
hi @christoff-1992 we'll have to try to reproduce this to better understand the issue you are seeing regarding regions. Could you provide us more context on how you are provisioning the backend? are you running `amplify add predictions` and which steps did u choose? what does your configuration file look like (please obfuscate the values) or are you configuring it programatically?

**Comment by christoff-1992** [comment]
Thanks @lawmicha, after looking into this in further detail I have realised that the latest version hadn't been cloned locally. I can see in 0.11.0 that transcription has been added as part of the configuration within the ConvertConfiguration. (TranscriptionConfiguration) This resolves the original issue I was having however it still feels a bit strange that the default region wont be used by default due to the method throwing a plugin error instead of a nil region.

**Comment by lawmicha** [comment]
Hi @christoff-1992 , thanks for looking again. I missed the code snippet in your description earlier. I think the region is required since the service calls will not know which region your AWS resources is provisioned in. "defaultRegion" is a required in your configuration (whether that is programmatic or through `amplifyconfiguration.json`) since the plugin does not make any assumptions to the region that you are in. Perhaps the name of the key is misleading since it's called "defaultRegion" instead of just "region". Glad to hear the original issue with the transcription was resolved. Feel free to open another issue if you are having troubles
