### ISSUE TITLE
The App does not run as expected with multiple sign in and sign out.

### ISSUE THREAD

**Issue by DongQuanRui** [aws-amplify/amplify-ios#456]
**Describe the bug**
One user is signed in in two iOS simulators. and when signing out from one of the two simulators, the other one cannot perform sign in or sign out as expected (The App is somehow crashed, need to go to "Device" -> "Erase all content and settings", and reinstall this app then it become normal).

**To Reproduce**
1. Start two simulators (call 1st simulator and 2nd simulator respectively) with the same iOS project (I think with signIn(), signOut() and signUp() are enough to reproduce this issue). 
2. Should have a signed up user (this user I would call "test" here) in Cognito user pool.
3. Log in "test" user in 1st simulator, and then log in this "test" user in the 2nd simulator. Now this "test" user is signed in in both simulators.
4. Since both simulators are signed in with the same user, now sign out from 2nd simulator (it doesn't matter sign out from which simulator).
5. It shows error when trying to sign out from 1st simulator. The error can be seen in the screenshot I attach below.

**Expected behavior**
I think no matter how many devices one user signs in with, this user should be able to sign out from all of them one by one using "Amplify.Auth.signOut()".

**Screenshots**
<img width="1202" alt="Screen Shot 2020-05-18 at 09 52 11" src="https://user-images.githubusercontent.com/48600426/82256438-302a7400-990b-11ea-984e-df0c98f6121e.png">

**Environment(please complete the following information):**
 - Xcode Version: 11.4.1 
 - Amplify Framework Version: The latest one in aws-amplify/amplify-ios, clone it locally and use local pods.
 - Dependency Manager: Cocoapods
 - Swift Version : [e.g. 5.0]

**Device Information (please complete the following information):**
 - Device: iPhone SE (2nd generation) simulator, iPhone 11 simulator
 - iOS Version: iOS 13.4.1

**Comment by royjit** [comment]
Fix is merged in to master. Please verify

**Comment by DongQuanRui** [comment]
The sign out works very well now, closing this issue
