### ISSUE TITLE
Support custom file name of amplifyconfiguration.json to support different targets and schemes

### ISSUE THREAD

**Issue by Ankish** [aws-amplify/amplify-ios#460]
**Is your feature request related to a problem? Please describe.**

This is the current amplifyconfiguration.json, I want to have multiple files that I can use for different targets, schema. Currently, it fetched directly from amplifyconfiguration.json. No easy way to support custom file name.
```
{
    "UserAgent": "",
    "Version": "=",

    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "XX": {
                    "endpointType": "REST",
                    "endpoint": "XX",
                    "region": "us-west-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket" : "XX",
                "region" : "us-west-2"
            }
        }
    },
}
```

**Describe the solution you'd like**
Currently we can configure awsconfiguration.json with a dictionay :
 AWSInfo.configureDefaultAWSInfo(configurationDict)

Something similar would be great.

**Describe alternatives you've considered**

I have considered using guard ((try? Amplify.configure(AmplifyConfiguration.init(analytics: nil, api: APICategoryConfiguration.init(plugins: amplifyDict[""] as! [String : JSONValue]), dataStore: nil, hub: nil, logging: nil, predictions: nil, storage: StorageCategoryConfiguration()))) != nil) else {
            return
        }
But it has JSONValue and no clear way how to configure 

**Additional context**
There seems to be internal functions with bundle , but they are not pubic yet

**Comment by palpatim** [comment]
@Ankish 

You can currently construct the configuration in-memory via the (admittedly verbose) `AmplifyConfiguration.init(analytics:api:auth:dataStore:hub:logging:predictions:storage:)` constructor.

As you pointed out, there exists an internal method that reads from a JSON file by passing a file path to `AmplifyConfiguration.init(configurationFile:)`. We'll investigate this as a feature request to see if we want to expose this as a public API.

**Comment by Ankish** [comment]
@palpatim : I couldnt find any examples of using that function. 
It would be of great help, Can you post the code , how I could use the above file to construct function with ? Did not see any examples in the code as well.

AmplifyConfiguration.init(analytics:api:auth:dataStore:hub:logging:predictions:storage:)

**Comment by palpatim** [comment]
@Ankish Sure thing--the tests primarily use that constructor, as in https://github.com/aws-amplify/amplify-ios/blob/master/AmplifyTests/CategoryTests/API/APICategoryClientGraphQLTests.swift#L21-L25

To generalize this: each Amplify category has a few options that apply to the entire category, plus a "plugins" object that holds the configuration for the specific plugin--in this case, the AWSAPIPlugin. The configuration values for the AWS plugins is simply a dictionary with values that mirror those in `amplifyconfiguration.json`. For example, an `amplifyconfiguration.json` that has been configured with the API category might have a stanza that looks like:

```json
"api": {
    "plugins": {
        "awsAPIPlugin": {
            "myendpointname": {
                "endpointType": "GraphQL",
                "endpoint": "REPLACE",
                "region": "REPLACE",
                "authorizationType": "AMAZON_COGNITO_USER_POOLS"
            }
        }
    }
}
```

Which we could mimic with this code:

```swift
let apiConfig = APICategoryConfiguration(
    plugins: ["awsAPIPlugin":
        [
            "myendpointname": [
                "endpointType": "GraphQL",
                "endpoint": "REPLACE",
                "region": "REPLACE",
                "authorizationType": "AMAZON_COGNITO_USER_POOLS"
            ]
        ]
    ]
)
```

Which we'd then use to configure Amplify:

```swift
let config = AmplifyConfiguration(api: apiConfig)
Amplify.configure(config)
```

Those are mostly useful for creating one or two easy-to-configure categories, but that should give you a pointer on how to proceed until we take a decision on whether to expose the file-based configuration as a public API.

**Comment by palpatim** [comment]
Need to hoist https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Core/Configuration/Internal/AmplifyConfigurationInitialization.swift#L31-L33 to `public` accessibility.

Call pattern would then be:

```swift
guard let file = Bundle.main.url(forResource: "myDifferentConfigFileName", withExtension: ".json") else {
    return
}
let configuration = AmplifyConfiguration(configurationFile: file)
try Amplify.configure(configuration)
```

**Comment by palpatim** [comment]
Released on https://github.com/aws-amplify/amplify-ios/releases/tag/v1.1.0

**Comment by Darkangel956** [comment]
Can You please reopen
