### ISSUE TITLE
Q: When is GA release?

### ISSUE THREAD

**Issue by skryshi** [aws-amplify/amplify-ios#468]
We are deciding whether to go with AWS Amplify or some other solution for our iOS production app. I understand that Amplify for iOS is in preview release now.

Can you please give some guidance on when you expect to have a general release for iOS Amplify? We don't need precise dates, but ballpark what are we talking about? Q3'20? Q1'21?

**Comment by mlabieniec** [comment]
Hi @skryshi we are still on track and close to completion of GA for this Q3 this year.
https://github.com/aws-amplify/amplify-ios/issues/335#issuecomment-593408357

**Comment by skryshi** [comment]
@mlabieniec Thank you!
