### ISSUE TITLE
Owner-based auth based on IdentityClaim

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#485]
Currently, a developer using Auth directive can set their own `identityClaim` which determines which value to use as the owner. DataStore uses `Auth.getCurrentUser` and uses the `username` as owner. This feature is to support different `identityClaims` like cognito sub or something else. 

The impact of not doing this is no support for custom identityClaims.

**Comment by palpatim** [comment]
Code snippet for reference https://github.com/aws-amplify/amplify-ios/blob/4cb4423a6eb3d46dc0caf4bf55392384b0e4acc8/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/SubscriptionSync/IncomingAsyncSubscriptionEventPublisher.swift#L159-L165

**Comment by lawmicha** [comment]
https://github.com/aws-amplify/amplify-ios/pull/794#discussion_r499046705

**Comment by wooj2** [comment]
This PR should resolve this issue:
https://github.com/aws-amplify/amplify-ios/pull/813
