### ISSUE TITLE
Amplify Plugins dependency on AWSCore - First time build fails

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#489]
**Describe the bug**
When i create a new Xcode project, and install Amplify plugin pod dependencies, the first build usually fails, i have to then run clean all (Shfit+CMD+K) and (CMD+B) and is then successful

**To Reproduce**
1. a pod file with Amplify dependencies, most likely one of the plugins that depend on AWSCore
2. pod install 
3. open workspace
4. CMD+B, see a build issue

**Expected behavior**
First build shouldn't fail

**Screenshots**
![image](https://user-images.githubusercontent.com/1365977/82958165-a7928000-9f69-11ea-9563-c0f0596b0389.png)

**Comment by palpatim** [comment]
I've also confirmed that disabling parallelized builds does not fix the issue.

**Comment by palpatim** [comment]
I've confirmed that using the legacy build system does not fix the issue.

**Comment by palpatim** [comment]
Note: When this is resolved, remove the build error callouts I introduced in https://github.com/aws-amplify/docs/pull/1894. (Don't just revert the change, as it also includes some minor formatting cleanup that is useful to keep)

**Comment by palpatim** [comment]
Easier repro: perform these same steps in one of the plugin projects target, so you don't have to manage a completely separate Pod project. E.g.

- AWSPinpointAnalyticsPlugin
- Let indexing complete
- Run unit test, or build for testing

**Comment by palpatim** [comment]
Reopening until we release

**Comment by drochetti** [comment]
[1.0.1](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.1) is out and contains the fix. Closing.
