### ISSUE TITLE
iOS DataStore Sync receives WebSocket notification but Publisher code is not called.

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-ios#496]
**Describe the bug**
In a iOS App, I am creating a DataStore subscriber to receive notifications when data are modified on the backend.
When I trigger a mutation in the console, on the device, I see logs from DataStore web socket protocol receiving the notification, but my subscriber code is never called.
The DataStore offline store is updated.  When I `query()` the data after observing the web socket log message, the data set returned contains the change I made in the app sync console.

**To Reproduce**
1. Create a Hello World project as per the doc at 
https://docs.amplify.aws/start/getting-started/native_setup/q/integration/ios
Create the backend (`amplify push`) 
Generate the model (`amplify codegen models`)

2. Initialize Amplify plugins

```swift
            try Amplify.add(plugin: AWSAPIPlugin())
            try Amplify.add(plugin: AWSDataStorePlugin(modelRegistration: AmplifyModels()))
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            
            try Amplify.configure()
```
3. Register a listener 

```swift
            let postSubscription = Amplify.DataStore
                .publisher(for: Note.self)
                .sink(receiveCompletion: { completion in
                    print("== SUB == \(completion)")
                    if case .failure(let error) = completion {
                        print("== SUB ==  error - \(error.localizedDescription)")
                    }
                })
                { changes in
                    // handle incoming changes
                    print("== SUB == received mutation: \(changes)")
                }
```

4. Build & Start the app

5. Open App Sync Console and execute the following mutation 

```graphql
mutation CreateNote {
     createNote(
         input: {
         content: "-- 08:48 -- Added through AppSync Console"
         }
     ) {
         id,
         content,
         _version,
  		   _deleted,
         _lastChangedAt
     }
 }
```

6. on the device console (in XCode), observe the message is correctly received

```text
2020-05-27 08:49:06.879378+0200 amplify-lib-ios-demo[72748:10029860] WebsocketDidReceiveMessage - {"id":"94C9A9F2-EA1F-4EDC-A2E1-A1A4D8E2B679","type":"data","payload":{"data":{"onCreateNote":{"id":"25fb6f27-b55f-4f86-bc0e-98144b3eaf5d","content":"-- 08:48 -- Added through AppSync Console","__typename":"Note","_version":1,"_deleted":null,"_lastChangedAt":1590562146545}}}}
```

Observe that no line starting with `== SUB ==`  is printed in the console.  This indicates the subscription code is not triggered.

**Expected behavior**
The line starting with `== SUB == received mutation:` should be printed in the console

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.0.0
 - Dependency Manager: [Cocoapods
 - Swift Version : 5.x

**Device Information (please complete the following information):**
 - Device: simulator
 - iOS Version: 13.5
 - Specific to simulators:

**Additional context**
The exact same mutation triggered from AppSync console causes the Android subscription code to trigger.

Full source code is available here https://github.com/sebsto/amplify-mobile-news-blog/tree/master/amplify-lib-ios-demo

Subscription-related code is here https://github.com/sebsto/amplify-mobile-news-blog/blob/master/amplify-lib-ios-demo/amplify-lib-ios-demo/AppDelegate.swift#L105

**Comment by palpatim** [comment]
@sebsto Combine subscriptions are only weakly retained by the publishers, so it's up to you to hold onto the returned `cancellable`. Instead of a local variable that passes immediately out of scope, try holding onto the publisher subscription in an instance variable of the view controller. 

E.g.,

```swift
            self.postSubscription = Amplify.DataStore
                .publisher(for: Note.self)
                 // ...
```

**Comment by sebsto** [comment]
Thank you @palpatim very good catch.  We should make this explicit in the doc at
https://next-docs.amplify.aws/lib/datastore/real-time/q/platform/ios

I will open an issue against the doc. 

For the record, the way to declare the publisher is 

```swift 
    var publisher : AnyPublisher<MutationEvent, DataStoreError>?
    var cancellabeSubscription : AnyCancellable?
```

**Comment by sebsto** [comment]
To track the change in the doc https://github.com/aws-amplify/docs/issues/1865
