### ISSUE TITLE
 Amplify Tool fails if I have multiple AWS profile and default is not valid

### ISSUE THREAD

**Issue by royjit** [aws-amplify/amplify-ios#500]
**Describe the bug**
I am getting a build failure when I followed the getting started guide for iOS, particularly the last step "Connect to the cloud".

**To Reproduce**
1. Have multiple AWS profile in your CLI, make the default profile fill with invalid credentials
2. Follow the getting started guide
3. When you reach connect to the cloud step build fails

**Additional context**

**Comment by drochetti** [comment]
This also fails if `default` doesn't exist. The `amplify-app` flow (i.e. headless CLI) uses `default` and I believe there's no way to change it... not sure how to address this.

It might end up being a *wontfix* until we come up with a replacement for the current implementation of Amplify Tools.

**Comment by lawmicha** [comment]
To fix this right now, I think the developer will have to use the CLI to rectify the situation. Let me know if you took other steps to fix your profiles.

1. if `default` does not exist, run `amplify configure` and follow the steps to set up the default profile. 
2. If your `default` profile has invalid credentials, you can also run `amplify configure` and copy existing profile values to reuse the credentials
3. First change to `~/.aws` directory
4. modify the `config` file with the editor of your choice, for example:
```
[default]
region=us-west-2

[profile default2]
region=us-west-2
```
5. do the same for the `credentials`
```
[default]
aws_access_key_id = [ACCESS_KEY_ID]
aws_secret_access_key = [SECRET_ACCESS_KEY]

[default2]
aws_access_key_id= [ACCESS_KEY_ID]
aws_secret_access_key=[SECRET_ACCESS_KEY]
```


More information about profiles can be found here https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
