### ISSUE TITLE
Documentation: Using Amplify Library/Plugins without Amplify Backend/CLI

### ISSUE THREAD

**Issue by cerupcat** [aws-amplify/amplify-ios#501]
**Is your feature request related to a problem? Please describe.**

If it's possible to use the library without using Amplify/CLI, it would be nice to have example documentation for how to configure manually.

I'm currently using `aws-sdk-ios` and `AWSMobileClient` to connect to AWS services (not Amplify). `amplify-iOS plugins` include useful utilities/helper-methods for connecting to AWS services. If would be great to have some documentation on using the library without the requirement of using Amplify/CLI.

**Describe the solution you'd like**

Documentation for manually configuring amplify library to connect to manually created AWS backend services.

**Comment by joyacv2** [comment]
Hi,

I have the same problem. I want to use the amplify iOS library but I can't use my existing API. The documentation for manual configuration is only available for Javascript. Is necessary to document the same scenario for iOS. Right now you can have a backend team separately if you want to use amplify for iOS. The first page of the documentation indicates that you can use your existing backend resources, but is not explained for iOS.

**Comment by drochetti** [comment]
> The documentation for manual configuration is only available for Javascript

@joyacv2 can you share the URL of the documentation you're referring to so we can make sure we address this correctly?

**Comment by joyacv2** [comment]
Hi @drochetti,

The url for manual configuration for JS is:
https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js#manual-setup-import-existing-rest-api

**Comment by joyacv2** [comment]
Hi @drochetti , 

Also for iOS you can see this, thanks to @lawmicha : 
https://github.com/aws-amplify/docs/blob/ddfee66f0c5e9e511faf186f0a9d2b0751edec44/docs/lib/restapi/fragments/ios/authz.md and
https://github.com/aws-amplify/docs/blob/ddfee66f0c5e9e511faf186f0a9d2b0751edec44/docs/lib/graphqlapi/fragments/native_common/authz/common.md

**Comment by lawmicha** [comment]
Hi @joyacv2 , the documentation you are looking for is now live at https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios Feel free to let us know if you have any troubles with configuring the plugin to use your own endpoint.

**Comment by drochetti** [comment]
Closing this due inactivity. Feel free to re-open if you're still experiencing the same issue.
