### ISSUE TITLE
Amplify-app stopping xcode build with amplify-tools (following getting-started tutorial)

### ISSUE THREAD

**Issue by mickeysox** [aws-amplify/amplify-ios#502]
**Describe the bug**

Following the tutorial [https://docs.amplify.aws/start/getting-started/native_setup/q/integration/ios#adding-amplify-tools](url) xcode can sometimes fail to build if you have ever installed amplify-app.  This is because in the root of the xcode directory, the amplify-app would have created amplifyxc.config but the run script now uses amplifytools.xcconfig.  

**Screenshots**
<img width="895" alt="Screenshot 2020-05-31 at 08 39 54" src="https://user-images.githubusercontent.com/5666707/83347513-614c7080-a31d-11ea-92c7-b6d03371b912.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 4.21.0
 - Dependency Manager: npm

**Device Information (please complete the following information):**
 - Device: iPhone 11 Pro Simulator 
 - iOS Version: 13.5
-  xcode 11.5

**Additional context**

Thanks to @daniel_rox for his help and for the solution:

Uninstall  amplify-app ````npm uninstall -g amplify-app```` remove all references to amplify (amplify folder, amplifyxc.config, amplifyconfiguration.json, awsconfiguration.json) in the root of the xcode folder and rebuild the project.

**Comment by wooj2** [comment]
Pending PR:
https://github.com/aws-amplify/amplify-ios/pull/511

**Comment by wooj2** [comment]
Pushed PR #511 to master.  I will be optimistically closing this ticket.  Thanks again for reporting!
