### ISSUE TITLE
GraphQL query for model with list attribute gives error: "Sub selection required" 

### ISSUE THREAD

**Issue by andriworld** [aws-amplify/amplify-ios#529]
**Describe the bug**
Our model includes a field which is a list of elements of another type. The children are stored inline as an array of objects, not in a separate DynamoDB table. This is breaking in iOS (Swift). See repro steps below

**Amplify CLI Version**
4.21.0    (ios)

**To Reproduce**
Add an api with the following schema:
```
type Todo @model {
  id: ID!
  name: String!
  description: String
  categories: [Category]
}

type Category {
  name: ID!
  color: String!
}
```

Fetch a Todo using the generated model:

`
Amplify.API.query(request: .get(Todo.self, byId: "........"))
`

**Observed Behavior**
The following error is returned:

`[Amplify.GraphQLError(message: "Validation error of type SubSelectionRequired: Sub selection required for type null of field categories @ \'getTodo/categories\'"
`

**Additional context**
We have an Amplify environment running in production with such a schema and it is working well with a Javascript client.  I am trying to add an iOS client and am running into this and other issues.

Things I've tried:
- I added @model and @connection directives hoping it will fix the query. The operation returned successfully but the field was nil, as it was not being included in the document's SelectionSet
- I forced the field to be included in the SelectionSet by hard-coding it in SelectionSet.swift.  The query was correct and the server returned the list values, but the decoding failed as it was expecting non-existent fields Category.todoCategoriesId and Category.id

What can I do to work around this problem?  Is there a way to run a custom query against AppSync and parse my own results, either with Amplify or another client?   If not, is there another way to get an object from DyamoDB? 
Thank you

**Comment by andriworld** [comment]
@sebsto yes you are seeing the same issue as I am. Note that after I hacked SelectionSet.swift so that the correct query went through, there were other issues decoding the results, as it's expecting a model.  It seems the design doesn't account for non-model associations. In the meantime, I'm using AWSAppSyncClient for the API category.

**Comment by sebsto** [comment]
Can you share your `SelectionSet` hack ? I am following the same path and try to modify `SelectionSet` but this is hardcoded for my Model, not a generic solution. (see this [gist](https://gist.github.com/sebsto/a81db362d06f5d7b3afc65b4c19048a3)) 
My hack unblocked me for `queries` I did not try mutation or anything fancy.

I reached the same conclusion as you, there is no support for non-model associations as of today. Not sure if this is by design or a miss.

I asked @lawmicha to take a look as he worked on that part of the code recently (https://github.com/aws-amplify/amplify-ios/pull/509)

**Comment by andriworld** [comment]
@sebsto My hack was even more specific. Something like `if field.isAssociationOwner || field.name == "categories"`.    Good that you are unblocked. Even with the correct query, the decoding failed for me.

Actually your case has a single item of the nested type, whereas I have an array of items of the nested type.

**Comment by sebsto** [comment]
just for reference https://github.com/aws-amplify/amplify-ios/pull/539

**Comment by sebsto** [comment]
Test with libs 1.0.2 and CLI 4.22.0
Works for me.
@andriworld can you confirm this version fixes your problem too ?

**Comment by andriworld** [comment]
It works!

Versions: `@aws-amplify/cli@4.22.0`,  `AmplifyPlugins/AWSAPIPlugin (1.0.3)`
Steps: re-ran `amplify codegen models` and reimported into Xcode. Cleaned build folder
Schema: same as my original post, i.e. with nested array of non-model type
Output: `Successfully retrieved todo: Todo(id: "E5F117FB-194F-4D82-87FE-CCF007222BA8", name: "my first todo", description: Optional("todo description"), categories: Optional([AmplifySandboxIOS.Category(name: "urgent", color: "red"), AmplifySandboxIOS.Category(name: "info", color: "green")]))
`

Thanks @lawmicha and @sebsto !
