### ISSUE TITLE
AmplifyConfig folder is not generated again after deleting it

### ISSUE THREAD

**Issue by ruiguoamz** [aws-amplify/amplify-ios#533]
**Describe the bug**
Use amplify-tools to generate `AmplifyConfig` folder, delete the folder and try to generate it again with `Cmd+B`, the folder is not generated again.

**To Reproduce**
1. Create a new Xcode project
2. Add a Build Phase to your app target.
3. Click on the project in the project workspace, then click the app target, and then click on `Build Phases`.
4. Tap the `+` button to add another phase, and select `New Run Script Phase`
5. Drag the new Run Script phase to move the phase so that it runs prior to the `Compile Sources` phase
6. Update the Run Script build phase title to `Run Amplify Tools`, and then update the shell script to have a single line with: `${PODS_ROOT}/AmplifyTools/amplify-tools.sh`
7. Now that Amplify tools is added to the build process, it will run when you build you project. Build your project in Xcode `Cmd+B`
8. After step 7 is done, delete the `AmplifyConfig` by "Moving to trash" and try `Cmd+B` again.

**Expected behavior**
The `AmplifyConfig` folder and the containing four files should be generated again.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.0.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.1

**Device Information (please complete the following information):**
 - Device: Simulators
 - iOS Version: iOS 13.5

**Comment by drochetti** [comment]
This is still a relevant issue and needs to be triaged and prioritized.

**Comment by ruiguoamz** [comment]
Seems like we don't want to support `Amplify Tools` anymore
