### ISSUE TITLE
Support for not passing in value for Optional Embedded Collection of Strings

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#541]
**Describe the bug**
API request is failing when not specifying a value for an optional embedded collection of strings

**To Reproduce**
1. schema
```
type Todo @model {
  id: ID!
  stickies: [String]
}
```
2. Create a Todo without any stickies, it will default to empty array `[]`.
3. Make API call, it will create the query variables
```
{
  "input" : {
    "stickies" : [

    ],
    "id" : "65883374-7B84-4457-81CD-FE1314173F44"
  }
}
```
3. See error
```
{
  "data": {
    "createTodo": null
  },
  "errors": [
    {
      "path": [
        "createTodo"
      ],
      "data": null,
      "errorType": "DynamoDB:DynamoDbException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Supplied AttributeValue is empty, must contain exactly one of the supported datatypes (Service: DynamoDb, Status Code: 400, Request ID: HQVD25FPEVRHJQMBCCSTO6TFFVVV4KQNSO5AEMVJF66Q9ASUAAJG)"
    }
  ]
}
```
**Expected behavior**
When there is an empty array, we should just remove it from the variables. this may be a regression for this change? https://github.com/aws-amplify/amplify-ios/pull/519

**Comment by lawmicha** [comment]
codegen changes were released in 4.21.4 but deprecated, to reproduce for now, use 
` npm install -g @aws-amplify/cli@iosCodegenWorkshop`
or use latest master branch of CLI

**Comment by DongQuanRui** [comment]
API works correctly with this schema, closing it

**Comment by DongQuanRui** [comment]
Using Schema in this link: https://github.com/aws-amplify/amplify-ios/blob/15a23697452ee8ec89b7bf49412ee2092a82d919/AmplifyTestCommon/Models/NonModel/Todo.swift

**Comment by DongQuanRui** [comment]
Using 
- embedded type
- CLI (4.21.4)
the issue doesn't occur anymore.

This is how todo object (without stickies) got created based on the schema from above link
`
let todo = Todo(id: "1234",
                            name: "name",
                            description: "description",
                            categories: [Category(name: "Category",
                                                  color: Color(name: "red",
                                                                        red: 255,
                                                                        green: 0,
                                                                        blue: 0))],
                            section: Section(name: "section", number: 1.0))
`

**Comment by lawmicha** [comment]
this was reproduced here https://github.com/aws-amplify/amplify-ios/issues/595
