### ISSUE TITLE
Model not updating optional string

### ISSUE THREAD

**Issue by jaivia** [aws-amplify/amplify-ios#546]
**Describe the bug**
An optional string on a model is not being updated using the mutation function on API. When backend table is looked at the version number increases but property remains the same 

**To Reproduce**
Create a model with optional string property
Change model's property and then update

- Value remains the same on the model that is returned

**Expected behavior**
Models returned from update should reflect what was passed during update

**Environment(please complete the following information):**
 - Amplify Framework Version: 4.21.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 11
 - Specific to simulators:

**Comment by drochetti** [comment]
@jaivia can you confirm if you're using Amplify 1.0.1?

That was a known bug in 1.0.0 and it was fixed in 1.0.1: https://github.com/aws-amplify/amplify-ios/pull/519

**Comment by drochetti** [comment]
Closing as current version of Amplify is 1.0.3 and should contain a fix to the issue.
Re-open if you still experience the same issue.
