### ISSUE TITLE
Amplify.Auth.signInWithWebUI and Amplify.Auth.fetchAuthSession crashing app

### ISSUE THREAD

**Issue by mobee-bill** [aws-amplify/amplify-ios#550]
**Describe the bug**
I have gone through the setup guide a few times.  I have the following intialization:
```
Amplify.Logging.logLevel = .verbose
 do {
       try Amplify.add(plugin: AWSCognitoAuthPlugin())
       try Amplify.configure()
       print("Amplify configured with auth plugin")
  } catch {
       print("Failed to initialize Amplify with \(error)")
  }
```

In the console:
```
Adding plugin: AmplifyPlugins.AWSCognitoAuthPlugin)
  [Amplify] Configuring
  [Amplify] Configuration: nil
```

Everything going according to the docs so far...
Calling the following:
```
_ = Amplify.Auth.signInWithWebUI(for: .apple, presentationAnchor: self.view.window!) { result in
            switch result {
            case .success(_):
                print("Sign in succeeded")
            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }
```
or even...
```
_ = Amplify.Auth.fetchAuthSession { result in
            switch result {
            case .success(let session):
                print("Is user signed in - \(session.isSignedIn)")
            case .failure(let error):
                print("Fetch session failed with error \(error)")
            }
        }
```
Both crash with `Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`

**To Reproduce**
Initialize Amplify, then try calling `fetchAuthSession` or `signInWIthWebUI`

**Observed Behavior**
App crashes

**Expected Behavior**
Sign in UI is shown, or fetchAuthSession shows a signed out status, or an error if there is an error

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
Amplify Auth + Sign in with Apple for iOS

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: AmplifyPlugins (1.0.1) Amplify (1.0.1)
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0
 - Xcode Version: 11.5

**Device Information (please complete the following information):**
 - Device: iPhone 8
 - iOS Version: ios 13.4.1

**Comment by mobee-bill** [comment]
@wooj2 Thanks for checking it out, I guess my issue is that I had an existing user pool + identity pool that we are currently utilizing for uploads to S3.  Is there no way to utilize these in some sort of manual setup like the older AWSMobileClient API provides?  I have been able to integrate a full sign in with Apple using that but I wanted to check if the newer Amplify SDK provided a somewhat more user friendly experience. (Like showing the apple login UI but avoiding popping up a browser in the background or avoid prompting the user to use "amazoncognito.com" to sign in). Ideally I want to just show the apple UI but it seems that Apple currently being limited to hosted ui is not making that possible?

**Comment by palpatim** [comment]
@mobee-bill The Amplify Auth category does support directly logging into a given auth provider's Web UI with the [`signInWithWebUI(for:presentationAnchor:options:listener:)` method](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios#launch-social-web-ui-sign-in). By passing the specified `AuthProvider`, Amplify will launch directly into that provider's auth flow, which *might* skip the UI depending on that provider's configuration and the current authentication state for the user. Behind the scenes, it still uses a webview, which means that if the user isn't currently logged in, it will present a webview over your `presentationAnchor` window, but in some cases, it can bypass UI altogether. I think in the SIWA case, it will prompt you for one of your Apple-provided config values rather than "amazoncognito.com", but you'd have to double check.

Hope this helps.

**Comment by mobee-bill** [comment]
Thanks for the info @palpatim. I will keep this in mind!

**Comment by yarivadam** [comment]
I have this exact same issue when trying to use the hosted web sign-in UI with an existing identity pool and user pool. I manually configured the amplifyconfiguration.json file, and I can't get it to work, always the same crash. Is there a tutorial out there for setting up a hosted auth flow using existing cognito resources (without using the Amplify CLI)? Thanks!

**Comment by psredzinski** [comment]
Same issue here, Amplify crashes

**Comment by meavydev** [comment]
Amplify.Auth.signInWithWebUI is crashing with the same EXC_BAD_INSTRUCTION on the iPhone 14.4 simulator, but Amplify.Auth.signIn with a username and password works.
This suggests that it's not a problem with the amplifyconfiguration.json, but possibly something to do with the presentationAnchor parameter to signInWithWebUI.
I haven't tried on a real iPhone yet, just the sim.

**Comment by jacobsapps** [comment]
Why is this issue closed? It's preventing me from implementing SIWA or any social auth provider at all
