### ISSUE TITLE
Fatal error: Storage category is not configured. 

### ISSUE THREAD

**Issue by Nicolaidam** [aws-amplify/amplify-ios#552]
I have set up Auth, Storage and a graphql api with the new Amplify guide. (16. june 2020) However I get this message even efter configuring Storage: Fatal error: Storage category is not configured. Call Amplify.configure() before using any methods on the category.: file

This is how i configure in AppDelegate.

         let apiPlugin = AWSAPIPlugin(modelRegistration: AmplifyModels())
        let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels())
        
        do {
            
            // AmplifyModels is generated in the previous step
            try Amplify.add(plugin: dataStorePlugin)
            try Amplify.add(plugin: apiPlugin)
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSS3StoragePlugin())
            
            
            try Amplify.configure()
            print("Amplify configured with DataStore plugin")
        } catch {
            print("Failed to initialize Amplify with \(error)")
            return false
        }

The API and Auth works fine but Storage is bugging.

**Comment by Wilsonilo** [comment]
I'm having the same issue, i see you closed this issue, just wondering what happened.

**Comment by nahttoter** [comment]
Same here,

```
Failed to initialize Amplify with AuthError: No plugin has been added for 'storage'.
Recovery suggestion: Either add a plugin for 'storage', or use one of the known keys: awsCognitoAuthPlugin

```
any suggestions?
```
do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSDataStorePlugin(modelRegistration: AmplifyModels()))
            try Amplify.add(plugin: AWSAPIPlugin(modelRegistration: AmplifyModels()))
            try Amplify.add(plugin: AWSS3StoragePlugin())

            try Amplify.configure()
            print("Amplify configured")
        } catch {
            print("Failed to initialize Amplify with \(error)")
 }
```
