### ISSUE TITLE
signInWithWebUI doesn't work inside UINavigationController

### ISSUE THREAD

**Issue by mTRx0** [aws-amplify/amplify-ios#569]
**Describe the bug**
I have a TabBarController which, as soon as a Tab is clicked, instantiates a new UINavigationController with a SignInViewController (UIViewController) as root. When using 

`Amplify.Auth.signInWithWebUI(for: .apple, presentationAnchor: self.view.window!)`

inside this SignInViewController nothing happens and the Debugger gives me this warning:

`Warning: Attempt to present <UINavigationController: 0x7f8ba6872e00>  on <myApp.TabBarController: 0x7f8ba600fa00> which is already presenting <UINavigationController: 0x7f8ba783d600>`

**To Reproduce**
1. Create a UITabBarController
2. Present a UINavigationController with a UIViewController as root modally on top of the UITabBarController 
3. Call `Amplify.Auth.signInWithWebUI(for: .apple, presentationAnchor: self.view.window!)`
4. See error/warning

**Expected behavior**
The Amplify SignIn UI should be displayed on top of the SignInViewController and allow the user to sign in.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.0.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 11, Simulator
 - iOS Version: iOS 13.5
 - Specific to simulators: /

**Comment by palpatim** [comment]
@mTRx0 Thanks for reporting this. We'll investigate & see what we can find.

**Comment by nigel545** [comment]
@palpatim  Any updates on this, i am having this issue as well and is blocking my current project. Thanks

**Comment by royjit** [comment]
Amplify.Auth.signInWithWebUI was trying to present on the windows root view controller and it fails if there is already a view presenting. The PR #635 should fix the issue.
