### ISSUE TITLE
DataStore SyncEngine completely fails when at least one subscription fails.

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#576]
**Describe the bug**
Using auth directive with different groups such as `allow: owner` and `allow:groups` for each model. Sync Engine creates subscriptions for each model. A user that is signed-In may not be enrolled in group. When this happens, the subscription will fail with unauthorized for the model with `groups` authorization, causing entire sync engine to fail.

**To Reproduce**
https://github.com/aws-amplify/amplify-ios/issues/561#issuecomment-648405023

**Expected behavior**
SyncEngine successfully creates subscriptions for models with owner authorization when the user is signed in, so that data is reconciled with the local store.

**Comment by lawmicha** [comment]
subscriptions in sync engine should gracefully fail. Also subscriptions should start failing if permissions are de-escalated (user is removed from a group). this is pending prioitization

**Comment by lawmicha** [comment]
unassigning myself- I believe @diegocstn is working on this

**Comment by diegocstn** [comment]
@lawmicha yesterday we merged https://github.com/aws-amplify/amplify-ios/pull/815, sync engine shouldn't stop anymore if one or more model subscriptions fail

**Comment by drochetti** [comment]
> @lawmicha yesterday we merged #815, sync engine shouldn't stop anymore if one or more model subscriptions fail

Awesome! I labeled as _pending release_ then 🚀

**Comment by drochetti** [comment]
Amplify [1.4.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.4.0) was released and contains the fix to this issue.
