### ISSUE TITLE
Can not install Pods from github master branch anymore

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-ios#582]
**Describe the bug**
When pulling out Amplify iOS Libs from Github's master branch, cocoapod fails with 

```
Analyzing dependencies
Pre-downloading: `AWSPluginsCore` from `https://github.com/aws-amplify/amplify-ios`, branch `master`

[!] Error installing AWSPluginsCore
[!] Failed to download 'AWSPluginsCore': [!] /usr/bin/git clone https://github.com/aws-amplify/amplify-ios /var/folders/_t/dhwbrc3n1lzb50zf28_w_nbdb9p3jg/T/d20200625-15344-wzk53i --template= --single-branch --depth 1 --branch master

Cloning into '/var/folders/_t/dhwbrc3n1lzb50zf28_w_nbdb9p3jg/T/d20200625-15344-wzk53i'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```

**To Reproduce**
1. Clean your pod environment 

```bash
rm -rf ~/.cocoapods
rm Podfile.lock
rm -rf Pods/
```

2. Use this `Podfile`

```
platform :ios, '13.0'

$LOCAL_REPO = '~/Downloads/amplify-ios-workshop/amplify-ios'
target 'Landmarks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Landmarks
  pod 'Amplify', :git => 'https://github.com/aws-amplify/amplify-ios', :branch => 'master'
  pod 'Amplify/Tools', :git => 'https://github.com/aws-amplify/amplify-ios', :branch => 'master'
  pod 'AWSPluginsCore', :git => 'https://github.com/aws-amplify/amplify-ios', :branch => 'master'

  pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :git => 'https://github.com/aws-amplify/amplify-ios', :branch => 'master'
  pod 'AmplifyPlugins/AWSAPIPlugin', :git => 'https://github.com/aws-amplify/amplify-ios', :branch => 'master'
  pod 'AmplifyPlugins/AWSS3StoragePlugin', :git => 'https://github.com/aws-amplify/amplify-ios', :branch => 'master'

end
```

3. Run `pod install`

```
Analyzing dependencies
Pre-downloading: `AWSPluginsCore` from `https://github.com/aws-amplify/amplify-ios`, branch `master`

[!] Error installing AWSPluginsCore
[!] Failed to download 'AWSPluginsCore': [!] /usr/bin/git clone https://github.com/aws-amplify/amplify-ios /var/folders/_t/dhwbrc3n1lzb50zf28_w_nbdb9p3jg/T/d20200625-15344-wzk53i --template= --single-branch --depth 1 --branch master

Cloning into '/var/folders/_t/dhwbrc3n1lzb50zf28_w_nbdb9p3jg/T/d20200625-15344-wzk53i'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```

**Expected behavior**
Pods should be installed from master branch

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: master branch
 - Dependency Manager: [e.g. Cocoapods, Carthage] cocoapods 1.9.3
 - Swift Version : [e.g. 5.0] n/a

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator] n/a
 - iOS Version: [e.g. iOS 11] n/a
 - Specific to simulators: n/a

**Additional context**
Used to work two days ago

**Comment by palpatim** [comment]
@sebsto We changed the name of the default branch from `master` to `main` as part of the 1.0.2 release.

**Comment by sebsto** [comment]
Thanks. All sorted now.

**Comment by RakshilDudhat** [comment]
[!] Error installing VolumePayComponent
[!] /usr/bin/git clone https://github.com/getvolume/volume-sdk-ios-cocoapods.git /var/folders/b8/dg3xl_r50f341ny4_bg9298w0000gn/T/d20240904-13754-4wothj --template= --single-branch --depth 1 --branch 2.1.0

Cloning into '/var/folders/b8/dg3xl_r50f341ny4_bg9298w0000gn/T/d20240904-13754-4wothj'...
remote: Repository not found.
fatal: repository 'https://github.com/getvolume/volume-sdk-ios-cocoapods.git/' not found



i got this error when install pod. But main issue is this is not got on my mac. it's got from another user mac. @sebsto

**Comment by ruisebas** [comment]
@RakshilDudhat We don't own that **VolumePayComponent** product.

That repo doesn't seem to exist either, but based on that URL it seems it was published by the https://github.com/getvolume/ org.
You might want to reach out to them.
