### ISSUE TITLE
Unstable DataStore integration tests

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#587]
**Describe the bug**

The `AWSDataStoreCategoryPluginIntegrationTests` target runs multiple integration and end-to-end tests of the AWSDataStoreCategoryPlugin. However, running these tests fails in unexpected ways when invoking them in a batch, even though they pass individually. This makes it hard to troubleshoot errors and makes it unsuitable for using in a CI pipeline, and reduces confidence in the DataStorePlugin's stability.

**To Reproduce**
1. Set up the integ test environment per the [`README.md` instructions](https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/README.md)
2. Launch Xcode with the `DataStoreCategoryPlugin.xcworkspace` project
3. Switch the active scheme to *AWSDataStoreCategoryPluginIntegrationTests*
4. Run all tests with **Product > Test** (Cmd-U)

**Expected behavior**
Tests pass consistently

**Actual behavior**
Tests fail intermittently:
- testCreateMutateDelete
- testCreateThenMutateWithCondition
- testSubscribeReceivesCreateMutateDelete

**Environment(please complete the following information):**
- Amplify Framework Version: 1.0.2
- Dependency Manager: CocoaPods
- Swift Version: 5.2
- Xcode Version: 11.5
- Amplify CLI version: 4.22.0

**Device Information (please complete the following information):**
- Device: Simulator
- iOS Version: iOS 13.5

**Comment by DongQuanRui** [comment]
When the tests are running individually, they don't affect each other. But when trying to run the tests all at the same time, the hub listener of a specific test may get a response which is not related to this test. 
Take `testCreateMutateDelete()` as example, `createReceived`, `updateReceived` and `deleteReceived` should be `fulfill()` in order. But the hub listener receives a payload which contains an mutationEvent(say this is a delete event) of another test, `deleteReceived` could be `fulfill()` more than once in `testCreateMutateDelete()`.
Solution so far is: after `mutationEvent.decodeModel() as? Post`, need to check whether this is the post we want for this particular test by checking `if post.id == newPost.id`

**Comment by palpatim** [comment]
That sounds like a good way to build resiliency into the test, thanks for the suggestion.

**Comment by lawmicha** [comment]
https://github.com/aws-amplify/amplify-ios/pull/596
