### ISSUE TITLE
Monetization events? 

### ISSUE THREAD

**Issue by fbarraganef** [aws-amplify/amplify-ios#601]
I watching the documentation from the new Amplify SDK but when I'm migration to this version there is any Monetization Events is there only BasicAnalyticsEvent object. 

How can register in pinpoint the revenue using this new SDK?

**Comment by drochetti** [comment]
Hey @fbarraganef. Right now `Amplify.Analytics` doesn't provide monetization events out-of-the-box. However, you can achieve that by calling the `AWSPinpoint` client directly by using `getEscapeHatch()` as documented here: https://docs.amplify.aws/lib/analytics/record/q/platform/ios#escape-hatch

Supporting more event types in `Amplify.Analytics` is something that we will evaluate as demands like yours become more popular.

Let me know if my suggestion helped you.

**Comment by fbarraganef** [comment]
Thanks @drochetti for example I have my whole implementation using AWSPinpoint, events and I have my own implementation of federated login, I changed the pods to the current version of Amplify and my current implementation works well, I only have 2 .json files instead of just 1, do I have to be careful with something?

In this case I don't need to use the getEscapeHatch because I'm using the instance directly, right?

**Comment by drochetti** [comment]
@fbarraganef reg. your questions:

> I changed the pods to the current version of Amplify and my current implementation works well, I only have 2 .json files instead of just 1, do I have to be careful with something?

It's OK to have both configurations. Amplify plugins use the SDKs under the hood, so it's ok to have both and that's why Amplify also provide the `getEscapeHatch` API to bridge calls to the underlying SDK.

> In this case I don't need to use the getEscapeHatch because I'm using the instance directly, right?

If you're managing the Pinpoint instance yourself, then no. The `getEscapeHatch` is useful when you're using `Amplify.Analytics` and then wants to call a Pinpoint-specific feature that is not available through the Amplify provided methods.

**Comment by fbarraganef** [comment]
@drochetti thanks, so the getEscapeHatch is just in case to use the Analytics instance and extend its functionality using the PinPoint instance too. But in my case how I'm not using Analytics instance, I don't need it.

Thank you.

**Comment by drochetti** [comment]
No problem, glad to help!
