### ISSUE TITLE
Multiple Active Sessions

### ISSUE THREAD

**Issue by prettyClouds** [aws-amplify/amplify-ios#605]
I am trying to build an app that allows the user to simultaneously have multiple active sessions. Imagine a product like SLACK, where you can be signed into multiple workspaces. Can I achieve this with amplify? I think it stores the session in a singleton, but I am curious if there is a way to have multiple "profiles".

If it's not possible, do I have any options I can fall back onto in the amplify SDK?

**Comment by wooj2** [comment]
Hi @prettyClouds -

1.  Multiple active "sessions"/"profiles" is not something that is supported in Amplify.

2.  Similarly, I don't think there is anything that will help you achieve this in our high level clients that we offer as part of the AWS iOS SDK either.  For example, with AWSMobileClient we do not support switching configurations on the fly - https://github.com/aws-amplify/aws-sdk-ios/issues/2405

3.  I'm not exactly what your requirements are, so it's a bit difficult to comment here, but... I suspect you would be required to work directly with the low level, automatically generated SDKs, that are a part of the AWS iOS SDK.

Best of luck!

**Comment by drochetti** [comment]
Closing this due inactivity. Feel free to re-open if you're experiencing the same issue or believe this was closed by mistaked.
