### ISSUE TITLE
"Sign In With Apple" - AWSCognitoAuthErrorDomain Code=-3000

### ISSUE THREAD

**Issue by matt-harding** [aws-amplify/amplify-ios#613]
**Describe the bug**
I followed the instruction on integrating "Sign In With Apple" into my SwiftUI app (https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios#update-infoplist) however upon completing sign in via the Apple WebUI that pops up I get the following error

```
Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/matt/Desktop/*MYAPPNAME*/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-3000 "(null)" UserInfo={error=invalid_request: SignInWithApple Error - 400 invalid_client}
```

**To Reproduce**
Steps to reproduce the behaviour:

Calling signInWithWebUI throws above error on result
```
_ = Amplify.Auth.signInWithWebUI(for: .apple, presentationAnchor: UIApplication.shared.windows.first!) { result in
            switch result {
            case .success(_):
                print("Sign in succeeded")
            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }
```

If I try signing in from the Web UI via the "Launch Hosted UI" in the "App Client Settings" panel of the User Pool I get a 200 from Apple with the auth response date but also the following error from my user pool domains oauth2/idresponse endpoint

![Screenshot 2020-07-02 at 16 19 09](https://user-images.githubusercontent.com/3025116/86377212-efe74100-bc7f-11ea-8d40-34ebc1f5afcd.png)

```
Request URL: *MYAPPNAME*://?error_description=SignInWithApple+Error+-+400+invalid_client&error=invalid_request
error_description: SignInWithApple Error - 400 invalid_client
error: invalid_request
```

![Screenshot 2020-07-02 at 16 16 37](https://user-images.githubusercontent.com/3025116/86376953-a72f8800-bc7f-11ea-9a3d-ec5f6886f5ec.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 4.22.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5 - SwifUI

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: 13.4

**Comment by lawmicha** [comment]
Hi @matt-harding since you mentioned that going to the web ui and getting the same result, it is most likely a service set up issue. can you double check to make sure you have followed this? https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios#configure-auth-category
Steps under "You need to now inform your auth provider of this URL:", Sign In with Apple tab.

**Comment by matt-harding** [comment]
This was the point in the documentation that caused some confusion for me. I took the Amazon Cognito domain from the App Integration tab of the User Pool but wasn't sure if that was the correct thing to use as the documentation references using the Hosted UI domain?

![Screenshot 2020-07-13 at 19 11 25](https://user-images.githubusercontent.com/3025116/87338338-ec37a200-c53c-11ea-8fda-a615457e0204.png)

![Screenshot 2020-07-13 at 19 16 42](https://user-images.githubusercontent.com/3025116/87338787-9c0d0f80-c53d-11ea-9bc3-6df30bbb731b.png)

**Comment by royjit** [comment]
Hi @matt-harding 

Under the Domains and Subdomains section of apple you should provide the domain of your hostedUI, something like this:

`applxx-344e4-xx.auth.us-east-1.amazoncognito.com`

And under the Return URLs please provide something like this:

`https://applxx-344e4-xx.auth.us-east-1.amazoncognito.com/oauth2/idpresponse`

**Comment by drochetti** [comment]
Closing this issue due inactivity. If you're still facing this problem and think this was closed by mistake, feel free to re-open it and provide us more information of the current state.
