### ISSUE TITLE
Example from Amplify.Predictions fails to compile

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#614]
**Describe the bug**
The following code snippet, taken from [here](https://docs.amplify.aws/lib/predictions/identify-text/q/platform/ios#identify-text-from-image)

    func detectText(_ image: URL) {
    _ = Amplify.Predictions.identify(type: .detectText(.form), image: image, options: PredictionsIdentifyRequest.Options(), listener: { (event) in
            switch event {
            case .completed(let result):
                let data = result as! IdentifyDocumentTextResult
                print(data)
            case .failed(let error):
                print(error)
            default:
                print("")
            }
        })
    }

fails to compile with:

Cannot infer contextual base in reference to member 'completed'

Pattern cannot match values of type 'AmplifyOperation<PredictionsIdentifyRequest, IdentifyResult, PredictionsError>.OperationResult' (aka 'Result<IdentifyResult, PredictionsError>')

**To Reproduce**
Attempt to compile the code snippet from the documentation.

**Expected behavior**
I'd like for the code to compile.

**Screenshots**
![Screenshot 2020-07-03 at 00 29 05](https://user-images.githubusercontent.com/67764399/86414565-8ccbcd80-bcc4-11ea-8d1d-96555b3dd993.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 
    CHECKOUT OPTIONS:
    Amplify:
    :commit: 3f784105b5c36eaa2d2b34900d752c46fd7d4a0c
    :git: https://github.com/aws-amplify/amplify-ios.git
    AmplifyPlugins:
    :commit: 3f784105b5c36eaa2d2b34900d752c46fd7d4a0c
    :git: https://github.com/aws-amplify/amplify-ios.git
    AWSPluginsCore:
    :commit: 3f784105b5c36eaa2d2b34900d752c46fd7d4a0c
    :git: https://github.com/aws-amplify/amplify-ios.git
    AWSPredictionsPlugin:
    :commit: 3f784105b5c36eaa2d2b34900d752c46fd7d4a0c
    :git: https://github.com/aws-amplify/amplify-ios.git

 - Dependency Manager: Cocoapods
 - Swift Version : 5.0
 - Xcode Version 11.5 (11E608c)

**Additional context**
Interestingly enough, this used to work in a previous version (from mid May)
    CHECKOUT OPTIONS:
    Amplify:
    :commit: d6b9349171d097782565d8e74842ec86e4c1d40c
    :git: https://github.com/aws-amplify/amplify-ios.git
    AmplifyPlugins:
    :commit: 22e8732ecb4b6c080860d2e09707eff8e5f20e48
    :git: https://github.com/aws-amplify/amplify-ios.git
    AWSPluginsCore:
    :commit: d6b9349171d097782565d8e74842ec86e4c1d40c
    :git: https://github.com/aws-amplify/amplify-ios.git
    AWSPredictionsPlugin:
    :commit: d6b9349171d097782565d8e74842ec86e4c1d40c
    :git: https://github.com/aws-amplify/amplify-ios.git

**Comment by drochetti** [comment]
hey @anatomybook, thanks for reporting this issue.

Before the 1.0.0 release there were a few API changes and the documentation you referred is outdated. I'll update it right away.

In the meantime, here's the fixed code snippet for your case:

```swift
_ = Amplify.Predictions.identify(type: .detectText(.form), image: image) { (event) in
    switch event {
    case .success(let result):
        let data = result as! IdentifyDocumentTextResult
        print(data)
    case .failure(let error):
        print(error)
    }
}
```

**Comment by drochetti** [comment]
@anatomybook Documentation updated. Feel free to re-open if you're still facing the same issue.
