### ISSUE TITLE
Questions about old vs new amplify approach

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-ios#616]
Hello,

After reading this I have some questions:
https://aws.amazon.com/about-aws/whats-new/2020/05/announcing-general-availability-amplify-ios-android-authentication-data-ai-ml-support/

Should I use the new Amplify version if I think it is not necessary in my case? My iOS app works perfectly and I don't feel anything from the new approach.
Are you going to deprecate "AWS Mobile SDKs for iOS" or maintain both approaches?

My app uses Cognito (passwordless login, that is, I modified the cloud formation template to add 4 lambda functions and specific configuration), AppSync (without offline support or caching and custom cloud formation templates to support pipelines), S3, Aurora Serverless (no predicates using eq, ne, le, equals...). I don't see any advantage using the new Amplify libraries for iOS in my case.
What is your opinion about this? Should I use the newest approach sooner or later.

Thanks a lot for suggestions.

BTW, here:
https://github.com/aws-amplify/amplify-ios
I see: 
_"All services and features not listed above are supported via the **iOS SDK** or if supported by a category can be accessed via the Escape Hatch like below"_
That link opens the new version of the documentation, so I guess it is wrong. It should open the old one.

**Comment by drochetti** [comment]
Hi @Ricardo1980,

> Should I use the new Amplify version if I think it is not necessary in my case?

It is really up to you. If you have an app in production and feel like Amplify won't help you, then you don't need to feel the urge nor obligated to migrate.

> Are you going to deprecate "AWS Mobile SDKs for iOS" or maintain both approaches?

Eventually we will, but we will announce it in advance and provide a migration plan. Right now both will be maintained. However, new features will only be added to Amplify.

> What is your opinion about this? Should I use the newest approach sooner or later.

It's hard to tell without knowing more details about your use case and the reality of your app in terms of stability, number of users, etc. But from what you have seen so far, if you believe Amplify won't help your existing app then trust your knowledge about your app to define the best strategy.

If I may recommend something, I would say you could try Amplify in a new app, for testing purposes if you're curious about the differences between the new approach and the existing SDK. That could give you a better idea for future endeavors.

Let me know if my answers helped you.

---

> That link opens the new version of the documentation, so I guess it is wrong. It should open the old one.

You're right, that link is broken. Thanks for reporting!

**Comment by drochetti** [comment]
> That link opens the new version of the documentation, so I guess it is wrong. It should open the old one.

You're right, that link is broken. Thanks for reporting!

**Comment by Ricardo1980** [comment]
Thanks a lot!
