### ISSUE TITLE
DataStore sync failing for connected Model without auth directive 

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#622]
Hi, I am also facing same issue while using graphql api with amazon cognito as default authentication. It continuously tries to connect to the api but always failing. I have taken care of everything as mentioned by @lawmicha for @auth directive. My ios App is unable to sync the data with the cloud. I have checked the recieptmodel app by @lawmicha and has done everything same like it but still I'm not able fulfill my purpose. I am attaching my schema with it and even though I have signed in still the app is unable to connect with the api.
![Screenshot 2020-07-05 at 3 27 13 AM](https://user-images.githubusercontent.com/59662149/86521523-9180b500-be6f-11ea-8e78-06adf6e91cb6.png)
![Screenshot 2020-07-05 at 3 27 27 AM](https://user-images.githubusercontent.com/59662149/86521527-96456900-be6f-11ea-92c5-88192cd25337.png)

![Screenshot 2020-07-05 at 3 25 39 AM](https://user-images.githubusercontent.com/59662149/86521504-3fd82a80-be6f-11ea-823b-877a823aad3f.png)

_Originally posted by @Aken27 in https://github.com/aws-amplify/amplify-ios/issues/561#issuecomment-653816929_

**Comment by lawmicha** [comment]
hi @Aken27, It appears the provisioned backend requires owner authorization on Items when there is a connection from Categories when Categories require owner auth. The library is not aware of this requirement since it is not explicitly added on the Items type. We can take this as a bug and make sure the library can account for this case.

A workaround here is to specify `allow: owner` on the `Items`
```
type Category @model @auth(rules: [ {allow: owner}]) {
    id: ID!
    name: String!
    color: String!
    items: [Item] @connection
}

type Item @model @auth(rules: [ {allow: owner}]){
    id: ID!
    title: String!
    done: Boolean!
    categoryID: ID!
}
```

**Comment by drochetti** [comment]
@wooj2 and @diegocstn this seems related to the work you have been doing. Can you double check if this issue is still relevant?

**Comment by diegocstn** [comment]
Hi @Aken27,
with https://github.com/aws-amplify/amplify-ios/pull/815 a failing model subscription shouldn't halt the DataStore sync engine anymore.

There's also a separate issue with the usage of `@connection` without arguments in a _has-many_ relationship that will cause the subscription to fail with an error similar to what as been reported in https://github.com/aws-amplify/amplify-ios/issues/828.

I'd suggest as a workaround to update the schema 
```

type Category @model @auth(rules: [ {allow: owner} ]) {
    id: ID!
    name: String!
    color: String!
    items: [Item] @connection(keyName: "byCategory", fields: ["id"])
}

type Item @model @auth(rules: [ {allow: owner} ]) @key(name: "byCategory", fields: ["categoryID"]) {
    id: ID!
    title: String!
    done: Boolean!
    categoryID: ID!
}
```
