### ISSUE TITLE
DataStore to support auth directive with `allow: private`

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#625]
**Is your feature request related to a problem? Please describe.**
The library currently does not construct correct API requests when using DataStore/model based API requests for backends provisioned with auth directive using `allow: private`.

**Describe the solution you'd like**
Support for auth directive with `allow: private` with different providers, and operations combinations.

**Comment by brightfuture** [comment]
I encountered the same issue, my current solution is to give all owner-crud-public-read models public-crud access
hopefully this can be solved soon
please let me know best practice to upgrade to owner-crud-public-read once this issue get solved :)

**Comment by diegocstn** [comment]
Released https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/ios#private-authorization
