### ISSUE TITLE
Crash when attempting to get User Attributes after federatedSignIn with Facebook.

### ISSUE THREAD

**Issue by garrettfritz** [aws-amplify/amplify-ios#627]
**Describe the bug**
We have been using the Amplify.Auth.signInWithWebUI function to login with facebook which has been working fine except for the fact that the web ui has the drawback of requiring the user to login to facebook through the interface even though they are already logged in to the facebook app.

To get around this, we have implemented the login with facebook directly through the facebook SDK which works fine and we get the access token.  We are even able to pass this access token string into the 

` AWSMobileClient.default().federatedSignIn(providerName: IdentityProvider.facebook.rawValue, token: token.tokenString)`

method and that results in seemingly a success with correct credentials and userState of signedIn.

But, after all that, we get a crash the moment we try to get the userAttributes through Amplify.Auth.fetchUserAttributes().  

The crash is on this line: 725 of AWSMobileClientExtensions.swift: 
` self.credentialsFetchLock.leave()`

*To Reproduce**
1) Login with facebook SDK
2) Pass resulting token to awsmobileclient federated signin
3) attempt to retrieve user attributes
**Expected behavior**
To get the user attributes and not crash

**Screenshots**

**Environment(please complete the following information):**
 - Amplify (1.0.4):
    - Amplify/Default (= 1.0.4)
  - Amplify/Default (1.0.4)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.0.4):
    - AWSAuthCore (~> 2.14.0)
    - AWSCore (~> 2.14.0)
    - AWSMobileClient (~> 2.14.0)
    - AWSPluginsCore (= 1.0.4)
  - AmplifyPlugins/AWSS3StoragePlugin (1.0.4):
    - AWSAuthCore (~> 2.14.0)
    - AWSCore (~> 2.14.0)
    - AWSPluginsCore (= 1.0.4)
    - AWSS3 (~> 2.14.0)
  - AWSAuthCore (2.14.0):
    - AWSCore (= 2.14.0)
  - AWSCognitoIdentityProvider (2.14.0):
    - AWSCognitoIdentityProviderASF (= 1.0.1)
    - AWSCore (= 2.14.0)
  - AWSCognitoIdentityProviderASF (1.0.1)
  - AWSCore (2.14.0)
  - AWSMobileClient (2.14.0):
    - AWSAuthCore (= 2.14.0)
    - AWSCognitoIdentityProvider (= 2.14.0)
  - AWSPluginsCore (1.0.4):
    - Amplify (= 1.0.4)
    - AWSCore (~> 2.14.0)
    - AWSMobileClient (~> 2.14.0)
  - AWSS3 (2.14.0):
    - AWSCore (= 2.14.0)

**Device Information (please complete the following information):**
 - emulator iphone 11 pro, device: iphone 10

**Comment by garrettfritz** [comment]
Has anyone had a chance to look at this?

In short, we just need a way to do a native facebook sign in on iOS using federated sign in that doesnt crash, so that we don't need to open the webview that requires users to re-login to FB in the webview.

**Comment by royjit** [comment]
Hi @garrettfritz 

SignIn through the `AWSMobileClient.default().federatedSignIn` does not create a user in the AWS Cognito User Pool, so you wont get any user attributes when you call `Amplify.Auth.fetchUserAttributes()`. If you require user management, you have to use the hostedUI provided by Amazon Cognito User Pool which you tried first `Amplify.Auth.signInWithWebUI`.

`AWSMobileClient.default().federatedSignIn` only federates you to Amazon Cognito Identity Pool and vends AWS Credentials for you.

But in either scenario, the crash should not occur. In this case `Amplify.Auth.fetchUserAttributes()` should return an error saying that user attributes are not available when federated to Identity Pool.

**Comment by garrettfritz** [comment]
Thanks @royjit  for the response.

I don't need the user to be created in the user pool, just need the AWS credentials.  So as long as the crash is resolved this would work well for us!

**Comment by royjit** [comment]
Made a fix in the underlying `AWSMobileClient` to return an appropriate error. This should be available when the SDK is released https://github.com/aws-amplify/aws-sdk-ios/pull/2866

**Comment by royjit** [comment]
The fix has been released, please try with the latest SDK. Feel free to reach us if you have any concerns.
