### ISSUE TITLE
Methods that return an enqueued operation could be marked with `@discardableResult`

### ISSUE THREAD

**Issue by jtbergman** [aws-amplify/amplify-ios#628]
**Problem**
The [documentation](https://docs.amplify.aws/lib/auth/signin/q/platform/ios) (specifically for auth, but maybe others) often shows using `_ = ` to suppress compiler warnings that the result of the function call is unused. These functions return a reference to an `Operation` that has already been added to the `OperationQueue`. Since the returned `Operation` has already been enqueued, it is unnecessary to retain it unless you want to cancel it in the future. It would be nice to not have to use `_ =` to suppress compiler warnings. 

Example usage from documentation: 
```swift
func fetchCurrentAuthSession() {
    _ = Amplify.Auth.fetchAuthSession { result in
        switch result {
        case .success(let session):
            print("Is user signed in - \(session.isSignedIn)")
        case .failure(let error):
            print("Fetch session failed with error \(error)")
        }
    }
}
```

**Describe the solution you'd like**
Methods that return an enqueued `Operation`, such as all the methods [here](https://github.com/aws-amplify/amplify-ios/blob/eb5b7ff98ae9ac090dc8c71e374b8f3bcb0ee472/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin%2BClientBehavior.swift), should be marked with `@discardableResult` allowing them to be used without using `_ =` to suppress warnings. 

Example
```swift
// Change 
@discardableResult
public func signUp(...) -> AuthSignUpOperation 

// Usage 
Amplify.Auth.signUp(username: ..., password: ..., options: nil) { result in 
    print(result)
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by palpatim** [comment]
@jtbergman This has bugged me for a while, so thanks for the push to get it resolved :)

We intentionally did not mark `API.subscribe(request:valueListener:completionListener:)` ignorable, since without the handle to the operation, there is no way to cancel the subscription to the GraphQL backend.

We've got this flagged for the Amplify 1.1 release, but we don't have an ETA on that just yet.

**Comment by palpatim** [comment]
Released on https://github.com/aws-amplify/amplify-ios/releases/tag/v1.1.0
