### ISSUE TITLE
Custom Attribute is not returned in Amplify.Auth.fetchUserAttributes()

### ISSUE THREAD

**Issue by Vivek205** [aws-amplify/amplify-ios#629]
**Describe the bug**

**To Reproduce**
1. Create Custom Attribute in the Userpool ( browser )
2. Provide read and write access to the respective AppClients
3. Call the `Amplify.Auth.fetchUserAttributes()` method in the iOS application.
4. In the response, you won't see the custom attributes.

**Expected behavior**
fetchUserAttributes() should  return the custom attributes that are created in the UserPool

**Environment(please complete the following information):**
 - Amplify Framework Version: (1.0.0):
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device:  Simulator - iPhone 11
 - iOS Version: 13.5
 - Specific to simulators: No

**Comment by lawmicha** [comment]
Hi @Vivek205, just creating the custom attribute in user pool will not add any attributes to a user. Can you verify that you are adding attributes to the user? Please take a look at https://docs.amplify.aws/lib/auth/user-attributes/q/platform/ios if you are still having troubles, could you provide us with expanded code snippets and logging output (values redacted)?

**Comment by Vivek205** [comment]
@lawmicha 

It started working when I added value for the custom attribute using Cognito.
So basically when the user signs up the custom attribute is not there, so I'm setting a default value at that time.
Later, when the user signs in, the custom attribute is appearing.

I suggest you to provide more clarity in the documentation.

**Comment by lawmicha** [comment]
Hi @Vivek205, glad to hear it is working for you. Thanks for the suggestion, we can link to the [Cognito docs here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes) and mention that custom attributes cannot be required, then show how to save and retrieve custom attributes.

**Comment by royjit** [comment]
I do not think this need to be added in the documentation. It is the same behavior for other attributes as well, when you call fetchAttribute only the added attributes are returned by the api. Closing this issue as the expected behavior.
