### ISSUE TITLE
Amplify.Auth.signOut() not returning a result after webview redirects, user still signed in

### ISSUE THREAD

**Issue by nigel545** [aws-amplify/amplify-ios#630]
**Describe the bug**
Amplify.Auth.signOut() not returning a result after webview redirects back to the app. And user is still signed into the app. Same config setup works on our Android app.

**Observed Behavior**
- Call Amplify.Auth.signOut()
- Web view opens
- Web view does signout through the url set
- Web view closes and returns to page where web view was opened
- Amplify.Auth.signOut() completion is never triggered with a success or fail result

**Expected Behavior**
- Call Amplify.Auth.signOut()
- Web view opens
- Web view does signout through the url set
- Web view closes and returns to page where web view was opened
- Amplify.Auth.signOut() completion is triggered with success or fail

**Code Snippet**

```
            _ = Amplify.Auth.signOut() { (result) in
                switch result {
                    case .success:
                        print("Successfully signed out")
                    }
                    case .failure(let error):
                        print("Sign out failed with error \(error)")
                }
            }
```
**POD**
Amplify 1.0.4

**Other Info** 
when calling Amplify.Auth.fetchAuthSession i get result:
<img width="588" alt="Screen Shot 2020-07-09 at 3 16 34 PM" src="https://user-images.githubusercontent.com/67649266/87156868-bf149680-c293-11ea-8eff-e1b00d8b09f1.png">

**Comment by royjit** [comment]
Hi,

Looks like the redirection if not reaching the underlying SDK. I would like to verify that the redirect uri is configured at the right places. Can you please check if the following places are configured correctly (assuming your redirect uri is `myapp://signout`) :

1. Info.plist of your app should have `myapp` as one of the url scheme
```
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>myapp</string>
		</array>
	</dict>
</array>
```
2. `amplifyconfiguration.json` should contain the signout redirect uri as shown below
```

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxx",
                        "AppClientId": "xxx",
                        "AppClientSecret": "xxx",
                        "Region": "xx"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxx",
                            "AppClientId": "xxx",
                            "AppClientSecret": "xxx",
                            "SignInRedirectURI": "xxx",
                            "SignOutRedirectURI": "myapp://signout",
                            "Scopes": [
                                ...
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```
3. The app client that you are using should have the signout redirect uri in the Cognito aws console.

![Screen Shot 2020-07-10 at 3 57 41 PM](https://user-images.githubusercontent.com/51138777/87209314-42e77680-c2c6-11ea-912b-03bfe2b749e4.png)

**Comment by nigel545** [comment]
@royjit  i seemed to have fixed the issue by defining "SignOutURI" as well in aws config file, does this make sense and seem like it is a solid fix to it?

**Comment by royjit** [comment]
@nigel545 Glad to hear that it got fixed. "SignOutRedirectURI" needs to be added in `amplifyconfiguration.json` file, it is the right fix. Closing this issue, feel free to reach out if you have any concerns.
