### ISSUE TITLE
Support long-running background operations

### ISSUE THREAD

**Issue by nick3389** [aws-amplify/amplify-ios#638]
Hello,

I want to migrate the old aws-ios-sdk to the Amplify SDK, as the former has been declared as legacy code despite the updates and bug fixes. Therefore, I would like to ask if static credentials are supported in this sdk to upload files to S3. in my current implementation I use static credentials along with Transfer utility as follows:

`let staticCredentialsProvider = AWSStaticCredentialsProvider(accessKey: accessKey, secretKey: secretKey)
  let s3Utility = AWSS3TransferUtilityConfiguration()
  s3Utility.timeoutIntervalForResource = 50 * 60 * 24 * 7
                
  let wifiTU = AWSS3TransferUtility.s3TransferUtility(forKey: "custom_key")
  let wifiConfiguration = AWSServiceConfiguration(region: region, credentialsProvider: staticCredentialsProvider)
  wifiConfiguration?.allowsCellularAccess = false

  AWSS3TransferUtility.register(with: wifiConfiguration!, transferUtilityConfiguration: s3Utility, forKey: "custom_key")`

Will I be able to have a similar setup with Amplify?

Thanks.

**Comment by wooj2** [comment]
Using AWSStaticCredentialsProvider w/ passing in an access key and secret key in your application is not recommended.  These credentials can easily be extracted from your application by extracting the binary and running a simple `strings` command against the compiled binary.  I believe it was only added for test purposes, so just to be super clear: we highly recommend you avoid using this for production use cases.

Could you tell us a little bit more about your use case?  We may be able to recommend an approach with using the Amplify Libraries?

**Comment by nick3389** [comment]
@wooj2 Actually the case is that regularly we upload files to S3. The example that I gave you in my initial post is the actual implementation I use, so there is nothing more to say here. Please free to suggest any different approach

**Comment by wooj2** [comment]
HI @nick3389,

Unfortunately, a static credentials provider is not available for Amplify storage. But as you've noted, what's important is that we will need to add support for long standing uploads that happen while the app is in the background.

Thanks for calling this out, and I will be marking this as a feature request/enhancement.

**Comment by nick3389** [comment]
@wooj2 Are static credentials going to be supported in future releases of amplify?

**Comment by wooj2** [comment]
Hi @nick3389 

I can not promise anything, but I believe that supporting long standing uploads that happen while the app is in the background is an important use case for our customers.,  Unfortunately, I'm unable to comment whether or not we would be using static credentials to support that. That being said, I would imagine that if there was another way to support long standing uploads while the app is in the background without static credentials, we would try going down that route, but I'm not aware of anyone on the team who has done this investigation.

**Comment by nick3389** [comment]
@wooj2 I think setting up a `AWSServiceConfiguration` with a credentials provider that conforms to `AWSCredentialsProvider` as `AWSStaticCredentialsProvider` does in the [aws-ios-sdk](https://github.com/aws-amplify/aws-sdk-ios) is irrelevant of whether a service like `AWSS3TransferUtility` supports uploads/downloads in the background. I am sorry if my question was misinterpreted, but I wanted to ask whether static credentials will be another way to setup a service configuration object or generally use them as a setup to be able to upload files to S3...

**Comment by palpatim** [comment]
I'm changing the title of this issue so it more accurately reflects the use case we're trying to support with the feature request, and hopefully avoids an XY problem. Static credentials *may* be the only way to accomplish this, but what we really want to support is long-running background transfers.

**Comment by rromanchuk** [comment]
> I want to migrate the old aws-ios-sdk to the Amplify SDK, as the former has been declared as legacy code despite the updates and bug fixes. 

@nick3389 can you share with me where you read that? Or do you just mean it "feels" that way?

**Comment by nick3389** [comment]
@rromanchuk Sorry for the delay. You can read it [here](https://docs.amplify.aws/sdk/q/platform/ios) at the bottom.

**Comment by brennanMKE** [comment]
@nick3389 Would you like to file a feature request so we can collect the necessary details and close this issue?

**Comment by nick3389** [comment]
@brennanMKE Just submitted #1559

**Comment by brennanMKE** [comment]
@nick3389 Thanks, I will raise the feature request with the team.
