### ISSUE TITLE
Return Error Status when attempting Datastore mutation,  CognitoUserPools logged out state

### ISSUE THREAD

**Issue by wooj2** [aws-amplify/amplify-ios#645]
**Is your feature request related to a problem? Please describe.**
Originally reported here https://github.com/aws-amplify/amplify-ios/issues/395
There is a case if you configure an iOS app with the following:
1.  Authentication: cognito user pools
2.  Datastore w/ syncing capability via API
3.  A basic schema without @auth, for example, the one we have in our documentation:
```
type Post @model {
  id: ID!
  title: String!
  status: PostStatus!
  rating: Int
  content: String
}
enum PostStatus {
  DRAFT
  PUBLISHED
}
```
Given that when calling `Amplify.Auth.fetchAuthSession` returns false, attempt to make a mutation via `Amplify.DataStore.save()`, data is saved locally but fails to be synchronized to the backend.

**Describe the solution you'd like**
At a high level,  the customer would like to know if something failed in the sync engine process, and perhaps if the mutation can never make it to the backend, then the mutation should not be stored locally, and an error should be presented to the user.  This can be implemented in a variety of ways, but we have not done the work to come up with a design.  Potential approaches to explore:
* callback
* hub notification
* event on the publisher

**Additional context**
* We will need to make sure that the behavior on iOS is also consistent on Android and JS.

**Comment by drochetti** [comment]
> At a high level, the customer would like to know if something failed in the sync engine process, and perhaps if the mutation can never make it to the backend

That expectation is correct and the DataStore configuration has an `errorHandler` that should be triggered in that scenario.

**Comment by wooj2** [comment]
@drochetti Great call out.

I tested a custom errorHandler and the errorHandler does get called, but the locally stored item doesn't seem to get sync'ed to the backend (even when you go back into an authenticated state and restart the sync engine).  Looks like we'll need to dig into this.

**Comment by drochetti** [comment]
@wooj2 @diegocstn is this one possibly related to the sync engine start/stop/restart logic being currently reviewed?

**Comment by diegocstn** [comment]
I believe with the current state of DataStore, when the sync engine is restarted (either via `start` or any other operation) the locally stored item should get sent to the backend.
Also per https://github.com/aws-amplify/amplify-ios/pull/815 and https://github.com/aws-amplify/amplify-ios/pull/1299 the sync engine should not halt in case of authentication errors.
