### ISSUE TITLE
[DataStore] missing "paginationInput" to call

### ISSUE THREAD

**Issue by DongQuanRui** [aws-amplify/amplify-ios#646]
**Describe the bug**
Missing a parameter to call `paginationInput` in file "StorageEngineAdapter+SQLite.swift"

Going to create a PR to add `paginationInput` in it.

**Comment by DongQuanRui** [comment]
The fixing is on the way. https://github.com/aws-amplify/amplify-ios/pull/647

**Comment by drochetti** [comment]
1.0.5 is out and this should be fixed.
