### ISSUE TITLE
fetchAuthSession error: No valid cognito identity pool configured

### ISSUE THREAD

**Issue by cerupcat** [aws-amplify/amplify-ios#651]
**Describe the bug**

I'm currently using the AuthPlugin with manual configuration. After a successful login, I am attempting to get the Cognito token via `fetchAuthSession`, but it returns an error `There is no valid cognito identity pool configured in awsconfiguration.json`. I'm not using an `awsconfiguration.json` configuration file since Amplify is manually configured.

**To Reproduce**

1. Configure Auth Plugin with manual configuration:

```
let plugin = AWSCognitoAuthPlugin()
try Amplify.add(plugin: plugin)

 let categoryConfig = AuthCategoryConfiguration(plugins: [
            "awsCognitoAuthPlugin": [
                "CognitoUserPool": ["Default": [
                    "PoolId": "xx",
                    "Region": "us-east-1",
                    "AppClientId": "xx",
                    "AppClientSecret": "xx"]]
            ]
        ])
        let amplifyConfig = AmplifyConfiguration(auth: categoryConfig)
        do {
            try Amplify.configure(amplifyConfig)
        } catch {
            // error
        }
```
2. Call `Amplify.Auth.SignIn` (with valid credentials)
3. Call `Amplify.Auth.fetchAuthSession` and notice that none of the userSubResults are returned. They all have error relating to `no valid Cognito identity pool configured`.

**Expected behavior**
UserSubResults to be returned since there is a valid pool configured.

If I step through the code, the `toAWSCognitoUserPoolTokens` do exist, but since `internalCredentialsProvider == nil` in `getAWSCredentials` they never get returned in `fetchAuthSession`

**Comment by cerupcat** [comment]
closed since a duplicate of merged solution

**Comment by davidstendardi** [comment]
May i ask you how you solved this issue ?

**Comment by cerupcat** [comment]
@davidstendardi yes. I'm using the version from that commit right now.
