### ISSUE TITLE
Able to reset and reconfigure the Amplify config after it has been set from app start

### ISSUE THREAD

**Issue by nigel545** [aws-amplify/amplify-ios#656]
**Is your feature request related to a problem? Please describe.**
In my app there is an environment switch that requires diffrent AWS configurations after run time so i need to be able to reset the config then rebuild it after the appDelegate has set up the initial config.

**Describe the solution you'd like**
Be able to reset and then rebuild the Amplify.Config() after build time

**Comment by DongQuanRui** [comment]
Hi, @nigel545. Unfortunately, `reset` and `reconfigure` during runtime are not supported by Amplify Library at this time. 

But thanks for reaching out. We will treat your issue as a feature request.

**Comment by DongQuanRui** [comment]
Related to https://github.com/aws-amplify/amplify-ios/issues/527

**Comment by DongQuanRui** [comment]
Hi, @nigel545. We are interested to know what's your use case so that we can get an idea of this feature request. Thanks.

**Comment by nigel545** [comment]
@DongQuanRui  Our use case is we have an environment switch that allows our testers to point to diffrent environments. We support different AWS configs so ideally we would like to be able to change the AWS config on the button press so our hosted UI would be pointing to the correct environment based on the new config used.

**Comment by drochetti** [comment]
> @DongQuanRui Our use case is we have an environment switch that allows our testers to point to diffrent environments. We support different AWS configs so ideally we would like to be able to change the AWS config on the button press so our hosted UI would be pointing to the correct environment based on the new config used.

Hey @nigel545 for such scenarios it's really hard to make sure the application state will be consistent if you change the AWS resources being used on the fly.

One possible solution would be to restart the app once the button that changes the environment is pressed (e.g. you change a preference in the `UserDefaults` and next time the app starts it will initialize the chosen environment).

There are more details in the aforementioned issue #527. We do intend to add better support for multiple environment configuration, but support for switching environment on the fly is not something we intend to support given the risks.

**Comment by nigel545** [comment]
Thanks we have implemented a restart after env change so we will use this as our solution for the time being. Thanks!

**Comment by drochetti** [comment]
@nigel545 no problem! I'll close this one, feel free to follow #527 for updates on better environment configuration support.
