### ISSUE TITLE
Cognito social login authentication fails on version 1.0.4

### ISSUE THREAD

**Issue by joao-jesus** [aws-amplify/amplify-ios#665]
**Describe the bug**
The new version of the amplify SDK fails to authenticate when using the social login (e.g. Facebook login).
ERROR: "AuthError: There is no valid cognito identity pool configured in `awsconfiguration.json`.\nRecovery suggestion: Make sure that the amplify configuration passed to Auth plugin is valid"

Also, on further logins this appears to be misconfigured:
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-23 at 12 14 43](https://user-images.githubusercontent.com/15733910/88280674-21cb5080-ccde-11ea-9f52-cfec0082ca76.png)

Note: I don't require an identity pool configured since I only use the cognito as a way to authenticate. No other aws services.

Using the following json as config:
`{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-west-1_XXXXXXXXX",
                        "AppClientId": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
                        "Region": "eu-west-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "XXXXXXXXXX.eu-west-1.amazoncognito.com",
                            "AppClientId": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
                            "SignInRedirectURI": "XXXXX://XXXXXXXXX",
                            "SignOutRedirectURI": "XXXXX://XXXXXXXXX",
                            "Scopes": [
                                "email",
                                "openid"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}`

**To Reproduce**
1. Authenticate by calling the `Amplify.Auth.signInWithWebUI(for: .facebook, presentationAnchor: window)`
2. Provide a valid facebook credentials
3. Press login
4. See error: 'AuthError: There is no valid cognito identity pool configured in `awsconfiguration.json`'

**Expected behavior**
Expect to social login to work.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.0.4
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: OS 13.5 

**Additional context**
A workaround to fix this issue was to clone the repo from this commit:
`chore(release): Prep 1.0.1 release (#528)	a41065b5	Jithin Roy <51138777+royjit@users.noreply.github.com>	6 Jun 2020 at 01:05`
And apply the following fix: [#632 ](https://github.com/aws-amplify/amplify-ios/pull/632)
And it works fine without change any configuration.

Also with this version (v1.0.4), appear also a new behaviour:
If you succeed to login (by using the solution above) and update the sdk, the following calls to sdk api:
`Amplify.Auth.fetchAuthSession` or `Amplify.Auth.signOut` 
may cause a web ui popup to appear to signIn with social login.

**Comment by joao-jesus** [comment]
To further clarify the issue:
v1.0.5-unstable.9 fix the issue (AuthError: There is no valid cognito identity pool configured), but the remain behaviour continues:
- web ui popup to appear to signIn with social login when calling `Amplify.Auth.fetchAuthSession` or `Amplify.Auth.signOut`
- And after a successful login and logout then further login's get the wrong configuration: "Required String parameter 'redirect_uri' is not present"

From my testing this behaviour started around when the AWS_SDK_VERSION > 2.13.6.

**Comment by DongQuanRui** [comment]
Hi, @joao-jesus. Thanks for reaching out.
I followed your reproducing steps and also removed the `CredentialProvider` block in `amplifyconfiguration.json`. I could perform `Amplify.Auth.signInWithWebUI` as expected without seeing the error you saw.
I'm not sure what happened to your App. But could you check you followed every steps correctly?
https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/ios#amazon-cognito-user-pool-setup
Make sure several things:
- Do the setup correctly in `developers.facebook.com`
- Do `amplify add auth` correctly
- `Info.plist` is correctly updated
- Drag `amplifyconfiguration.json` into your App workspace and check `yourApp` as the `Target Membership`
See if you can still seeing the error.

**Comment by joao-jesus** [comment]
Hi @DongQuanRui ,

I check and did all the steps.

The error "AuthError: There is no valid cognito identity pool configured " is fixed in recent versions so you can discard this part of the issue.

My issue is the recent version's of SDK, when I sign-out, it request to sign-in and then stays in misconfigured state.

**Comment by DongQuanRui** [comment]
Hi, @joao-jesus. Glad to hear one error is fixed. 
The expected behavior is: when you call `Amplify.signOut()`, it actually pops out `Sign In` window and click `continue` to `Sign Out`
Could you please clarify what is the `misconfigured state` you mentioned here?

**Comment by joao-jesus** [comment]
Hi @DongQuanRui ,
We discover the problem, the "SignOutRedirectURI" in server configuration was missing but the local iOS configuration was present. 

This was causing the issue of misconfigured state (when logout it appears a popup to signIn and then an error appear "Required String parameter ''redirect_urin" was not present".

With this fix in our side, when we logout, all is good 👍 

Thank you for your feedback, I'll close the issue
