### ISSUE TITLE
Amplify iOS: Amplify.API.query missing list fields in response 

### ISSUE THREAD

**Issue by salvodicara** [aws-amplify/amplify-ios#666]
**Bug description**
My team and I have a problem with performing a specific Amplify query in iOS. Maximum depth for nested responses has been set to 5 (as declared in the .graphqlconfig.yml). By getting the list of users, response should include the following nested information: 
```
user -> tenant -> name
        |
        -> attributes (primitive types)
        |
        -> memberships -> versionRecord -> file
```
But instead we are getting the following:
```
user -> tenant -> name
        |
        -> attributes (primitive types)
        |
        -> memberships -> nil
```
For each user, only some attributes (all primitive types) are set. All the other fields, including the Amplify.List objects we were expecting to receive, are nil. See our debug log ([screenshot 1](https://user-images.githubusercontent.com/34038011/88287246-f189af00-cce9-11ea-87b5-aad6449b7a8d.png)) and [schema.graphql](https://github.com/salvodicara/TestAWS/blob/master/amplify/backend/api/amplifyDatasource/schema.graphql) for more details.
These properties, though are all visible through the AWS console (see [screenshot 2](https://user-images.githubusercontent.com/34038011/88287444-344b8700-ccea-11ea-8f9e-3a0a3bafb321.png)). 

**To Reproduce**
1. Create a new iOS project. 
2. Initialize Amplify into the project folder by following the getting started [tutorial](https://docs.amplify.aws/start/q/integration/ios) for iOS.
**Note** that we are not using Datastore but just the API (GraphQL) plugin.
3. Use this specific [GraphQL schema](https://github.com/salvodicara/TestAWS/blob/master/amplify/backend/api/amplifyDatasource/schema.graphql).
4. Perform the following mutations, in order to fill DynamoDB with some dummy data:
```
mutation createTenant {
  createTenant(input: {name: "TENANT_NAME", city:"CITY", address1: "ADDRESS_1", postcode: "POSTCODE"}) {
    id
  }
}
#You will then receive a TENANT_ID for the newly generated tenant.

mutation createUser {
  createUser(input: {tenantID: "TENANT_ID", name: "USER_NAME", email:"USER_EMAIL"}) {
    id
  }
}
#Similarly you will receive a USER_ID for the newly generated user.

mutation createSolution {
  createSolution(input: {tenantID: "TENANT_ID", ownerUser: "USER_NAME", name: "SOLUTION_NAME"}) {
    id
  }
}
#You will receive the SOLUTON_ID.

mutation createFile {
  createS3ObjectFile(input: {key: "YOUR_KEY", region: "YOUR_REGION", bucket: "YOUR_BUCKET"}) {
    id
  }
}
#You will receive the FILE_ID.

mutation createVersion {
  createVersion(input: {solutionID: "SOLUTION_ID", ownerUser: "USER_NAME", name: "VERSION_NAME", fileID: "FILE_ID"}) {
    id
  }
}
#You will receive the VERSION_ID.

mutation createrUserVersion {
  createUserVersion(input: {versionID: "VERSION_ID", userID: "USER_ID"}) {
    id
  }
}
```
5. Make sure the data are added correctly and then perform a query on the AWS console, in order to list the user you just created (see [screenshot 2](https://user-images.githubusercontent.com/34038011/88287444-344b8700-ccea-11ea-8f9e-3a0a3bafb321.png)). 
6. Perform the same query from the iOS app code, by using the Amplify.API.query function (like we did in [SceneDelegate.swift](https://github.com/salvodicara/TestAWS/blob/master/TestAWS/SceneDelegate.swift))

**Expected behavior**
In the iOS client, by running the query, we should be able to get all the information we just added, just like in the AWS console.

**Screenshots**
Screenshot 1
<img width="570" alt="Screenshot 2020-07-23 at 12 11 12" src="https://user-images.githubusercontent.com/34038011/88287246-f189af00-cce9-11ea-87b5-aad6449b7a8d.png">

Screenshot 2
<img width="1209" alt="Screenshot 2020-07-23 at 12 16 26" src="https://user-images.githubusercontent.com/34038011/88287444-344b8700-ccea-11ea-8f9e-3a0a3bafb321.png">

**Environment**

 - Amplify iOS Framework Version: 1.0.4
- Amplify CLI version: 4.24.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information**
 - Device: iPhone SE (2nd generation) Simulator
 - iOS Version: iOS 13.6

**Comment by DongQuanRui** [comment]
Hi, @salvodicara. Thanks for reaching out. Currently, `APIPlugin` do not support nested response and only support one level. I believe your `.graphqlconfig.yml` is generated by Amplify CLI when you are asked if you want `API.swfit`. But that is unrelated to `APIPlugin` since you are using model type API.
You need to construct your own custom GraphQL request so that service side returns nested response. 
something like:
`
let document = """
        query ListUsers {
          listUsers {
            items {
              name
              email
              tenant {
                name
                address1
                city
                postcode
              }
              memberships {
                items {
                  userID
                  versionID
                  versionRecord {
                    name
                    file {
                      key
                    }
                    solution {
                      name
                    }
                  }
                }
              }
            }
          }
        }
        """
        let request = GraphQLRequest(document: document, responseType: JSONValue.self, decodePath: "listUsers")
        _ = Amplify.API.query(request: request) { res in
            switch res {
            case .success(let success):
                switch success {
                case .success(let data):
                    print(data)
                case .failure(let error):
                    print(error)
                }
        }
`
And you can further deserialize data
Here is the link to a similar issue. https://github.com/aws-amplify/amplify-ios/issues/599

**Comment by drochetti** [comment]
This issue will be closed in favor of the feature request we're tracking in #599. Please, follow up there for workarounds and announcements.
