### ISSUE TITLE
Unable to sign out properly with web-based ODIC provider

### ISSUE THREAD

**Issue by janejjshen** [aws-amplify/amplify-ios#672]
**Describe the bug**

Our iOS app is unable to log out properly with a Cognito -> OIDC set up. 

Cognito is set up to be a RP for an OIDC provider (SAP Gigya). We use the Cognito hosted UI to launch the Gigya sign in screen, which uses a JavaScript based SDK to sign in and keeps its sessions in browser cookies. 

In order to sign out, we configured the `logout_uri` to be a custom HTML page because the JavaScript code on that page needs to clear the Gigya session and cookies via the Gigya SDK. Then this HTML page would manually redirect to `myapp://signout`.  This does not work for the iOS app since in the SDK there's a line that explicitly checks if the configured `logout_uri` matches the url the app is being redirected back to (`myapp://signout`). 

Line in SDK: 
```
if( [urlLowerCaseString hasPrefix:signOutRedirectLowerCaseString]){
```
where `urlLowerCaseString` is `myapp://signout` and `signOutRedirectLowerCaseString` is the configured HTML URL. 

I understand this is not a traditional approach since the sign out process is broken into 2 steps, but we needed to sign out of Cognito AND Gigya, and couldn't figure out another way. 

Is there any reason this explicit check exists? Is there a way to remediate it? This approach works for JavaScript.

**To Reproduce**
1. Sign in through the federated provider screen
2. Sign out using `Amplify.signOut`
3. User is redirected back to the app, but still signed in.

**Expected behavior**
User is signed out in Cognito and Gigya, and app is redirected back to the right page.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.0.4
 - Swift Version : [e.g. 5.0]

**Device Information (please complete the following information):**
 - Device:  iPhone, Simulator
 - iOS Version: iOS 13

**Additional context**

**Comment by janejjshen** [comment]
Figured out... The amplifyconfig value block is a bit complicated (overwriting some values) but could work at the end. 

```
"OAuth": {
                          "WebDomain": "<cognito domain>",
                          "AppClientId": "<appclientid>",
                          "SignInRedirectURI": "myapp://callback",
                          "TokenURI": "<cognito domain>/oauth2/token",
                          "SignInURI" : "<cognito domain>/oauth2/authorize",
                          "SignOutURI": "<cognito domain>/logout",
                          "SignOutRedirectURI": "myapp://signout",
                          "SignOutURIQueryParameters": {
                              "client_id" : "<appclientid>",
                              "logout_uri" : "<Gigya log out URL>"
                          },
                          "Scopes": ["openid", "email", "profile"]
                        }
                    } 
```

**Comment by gabimo** [comment]
>        "SignInURI" : "<cognito domain>/oauth2/authorize",
>        "SignOutURI": "<cognito domain>/logout",

@janejjshen 

How did you get to this? Did you find some documentation for the json config?
