### ISSUE TITLE
signIn method crashes

### ISSUE THREAD

**Issue by SzymonWojcik** [aws-amplify/amplify-ios#674]
**Describe the bug**
Method **signIn(username:, password:, options: nil)** crashes on each call with **Terminating app due to uncaught exception 'NSRangeException', reason: ' -[__NSCFString substringFromIndex:]: Index 9223372036854775808 out of bounds; string length 46'.** Tested agains real device and simulator.

**To Reproduce**
1. Try to call signIn method with valid credentials
2. `*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSCFString substringFromIndex:]: Index 9223372036854775808 out of bounds; string length 46'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001137dcf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x000000010fe759b2 objc_exception_throw + 48
	2   Foundation                          0x000000010f606074 -[NSString substringToIndex:] + 0
	3   AWSCognitoIdentityProvider          0x000000010e25d7f3 -[AWSCognitoIdentityUserPool strippedPoolId] + 195
	4   AWSCognitoIdentityProvider          0x000000010e24e3a1 -[AWSCognitoIdentityUser srpAuthInternalStep2:srpHelper:] + 193
	5   AWSCognitoIdentityProvider          0x000000010e24e28f __105-[AWSCognitoIdentityUser srpAuthInternal:password:validationData:lastChallenge:isInitialCustomChallenge:]_block_invoke_3 + 335
	6   AWSCore                             0x000000010e580b5b __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 155
	7   AWSCore                             0x000000010e58024d __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 109
	8   AWSCore                             0x000000010e522fa6 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 182
	9   AWSCore                             0x000000010e523817 -[AWSExecutor execute:] + 87
	10  AWSCore                             0x000000010e5800f4 -[AWSTask continueWithExecutor:block:cancellationToken:] + 868
	11  AWSCore                             0x000000010e580a50 -[AWSTask continueWithExecutor:successBlock:cancellationToken:] + 320
	12  AWSCore                             0x000000010e580c14 -[AWSTask continueWithSuccessBlock:] + 132
	13  AWSCognitoIdentityProvider          0x000000010e24dff5 __105-[AWSCognitoIdentityUser srpAuthInternal:password:validationData:lastChallenge:isInitialCustomChallenge:]_block_invoke.533 + 613
	14  AWSCore                             0x000000010e58024d __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 109
	15  AWSCore                             0x000000010e522fa6 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 182
	16  AWSCore                             0x000000010e523817 -[AWSExecutor execute:] + 87
	17  AWSCore                             0x000000010e58069b __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke.103 + 43
	18  AWSCore                             0x000000010e57fb68 -[AWSTask runContinuations] + 776
	19  AWSCore                             0x000000010e57f361 -[AWSTask trySetResult:] + 241
	20  AWSCore                             0x000000010e58165b -[AWSTaskCompletionSource setResult:] + 91
	21  AWSCore                             0x000000010e5aef48 __61-[AWSURLSessionManager URLSession:task:didCompleteWithError:]_block_invoke + 10056
	22  AWSCore                             0x000000010e580b5b __63-[AWSTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 155
	23  AWSCore                             0x000000010e58024d __56-[AWSTask continueWithExecutor:block:cancellationToken:]_block_invoke + 109
	24  AWSCore                             0x000000010e522fa6 __30+[AWSExecutor defaultExecutor]_block_invoke_2 + 182
	25  AWSCore                             0x000000010e523817 -[AWSExecutor execute:] + 87
	26  AWSCore                             0x000000010e5800f4 -[AWSTask continueWithExecutor:block:cancellationToken:] + 868
	27  AWSCore                             0x000000010e580a50 -[AWSTask continueWithExecutor:successBlock:cancellationToken:] + 320
	28  AWSCore                             0x000000010e580c14 -[AWSTask continueWithSuccessBlock:] + 132
	29  AWSCore                             0x000000010e5ac692 -[AWSURLSessionManager URLSession:task:didCompleteWithError:] + 738
	30  CFNetwork                           0x0000000114231003 _CFNetworkHTTPConnectionCacheSetLimit + 207379
	31  Foundation                          0x000000010f5e028c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	32  Foundation                          0x000000010f5e01ad -[NSBlockOperation main] + 80
	33  Foundation                          0x000000010f5e30dc __NSOPERATION_IS_INVOKING_MAIN__ + 17
	34  Foundation                          0x000000010f5df3ee -[NSOperation start] + 731
	35  Foundation                          0x000000010f5e3a20 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
	36  Foundation                          0x000000010f5e3540 __NSOQSchedule_f + 182
	37  libdispatch.dylib                   0x000000011312c4dc _dispatch_block_async_invoke2 + 83
	38  libdispatch.dylib                   0x000000011311de8e _dispatch_client_callout + 8
	39  libdispatch.dylib                   0x00000001131207a3 _dispatch_continuation_pop + 552
	40  libdispatch.dylib                   0x000000011311fbbb _dispatch_async_redirect_invoke + 771
	41  libdispatch.dylib                   0x000000011312f399 _dispatch_root_queue_drain + 351
	42  libdispatch.dylib                   0x000000011312fca6 _dispatch_worker_thread2 + 135
	43  libsystem_pthread.dylib             0x000000011368b9f7 _pthread_wqthread + 220
	44  libsystem_pthread.dylib             0x000000011368ab77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.0.5
 - Dependency Manager: Cocoapods
 - Swift Version : 5.3

**Device Information (please complete the following information):**
 - Device: iPhone 11, Simulator
 - iOS Version: iOS 13

I'll appreciate any help regarding this issue, feel free to ask for more information.

**Comment by SzymonWojcik** [comment]
Seems it was caused by incorrect **PoolId**. Still, it should not crash the whole app.

**Comment by DongQuanRui** [comment]
Hi, @SzymonWojcik. Thanks for reaching out.
I did two things:
1, Call `signIn(username:, password:, options: nil)` with valid credential, no error returns and got signed in successfully.
2, Call `signIn(username:, password:, options: nil)` with invalid credential, sign in error returns and the app didn't crash.
Sorry but your description seems unclear under what condition the crash happen. Could you give me more details? I would appreciate it and better help you out

**Comment by SzymonWojcik** [comment]
@DongQuanRui  As I mentioned in the above comment, the crash is caused by invalid **PoolId** in configuration. Everything works fine with correct **PoolId**. Despite this, instead of crash SDK should throw proper error about incorrect id setting.
So to reproduce this try to set invalid **PoolId** (e.g. eu-west-2:12xc1234-123b-1m23-a9bc-n123ko123456) and try to sign in.

**Comment by DongQuanRui** [comment]
Sorry for the mistake I made. 
Bullet 2 I commented should be: Call signIn(username:, password:, options: nil) with invalid PoolId, I could see error returns but didn't see the App crashed.

**Comment by SzymonWojcik** [comment]
Here's a example invalid config which crashes for me:
`{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "CognitoUserPool": {
                    "Default": {
                        "Region": "eu-west-2",
                        "PoolId": "eu-west-2:12xc1234-123b-1m23-a9bc-n123ko123456",
                        "AppClientId": "XXX",
                        "AppClientSecret": "XXX"
                    }
                },
                "CredentialsProvider": {
                  "CognitoIdentity": {
                    "Default": {
                      "PoolId": "eu-west-2:10bb8092-939a-4a00-a9cf-a698ab840891",
                      "Region": "ew-west-2"
                    }
                  }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_PASSWORD_AUTH"
                    }
                }
            }
        }
    }
}`

**Comment by DongQuanRui** [comment]
Hi, I noticed something different in your config from mine. the PoolId looks something like `eu-west-2_ab3deF7hI` instead of `eu-west-2:followed by uuid`. 
Can you go to Cognito console to check if you are using the correct poolId in your `amplifyconfiguration.json`? My app did crash when using a poolId formatted like the one you are using.

**Comment by SzymonWojcik** [comment]
As I said, I'm aware that **PoolId** is wrong. Moreover, I'm aware that's the cause of the crash. What I'm trying to say is that I don't think that SDK should terminate the app in a case of wrong **PoolId**. If you guys think that's expected behavior you can close the issue. I just feel it's the wrong way of handling the incorrect id error.

**Comment by palpatim** [comment]
@SzymonWojcik Thanks for the report. This sounds like the same issue reported on https://github.com/aws-amplify/aws-sdk-ios/issues/2272, and we're treating it as a "won't fix" for the reasons discussed on that bug.

If this is resulting from an automatically-generated pool ID (as opposed to a typo in a manual configuration), then please re-open this bug and provide some more info describing what process is generating the invalid configuration--that would be where we'd want to focus our efforts.
