### ISSUE TITLE
Subscriptions disconnect after 10 minutes of the app being in background, requiring the app to be restarted

### ISSUE THREAD

**Issue by benrosen78** [aws-amplify/amplify-ios#677]
This issue, present in one of the libraries behind Amplify for iOS, is also present in Amplify for iOS. 

This issue has been reported in other locations, but I wanted to make a ticket in this repo so that it can get fixed promptly.
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/403
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/396
https://github.com/aws-amplify/aws-appsync-realtime-client-ios/issues/24

This issue is highly replicable. After 10 minutes of an iOS app being in the background, AppSync subscriptions fail to connect.

This issue is making AppSync unreliable to use in a production app.

Let me know if more information is needed, but there should be ample information in the issues I linked above. Thank you.

**Comment by palpatim** [comment]
Tracking on https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/396

**Comment by palpatim** [comment]
Released this on [v1.0.6](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.0.6)
