### ISSUE TITLE
AWS amplify ios (awsTextract Unable to get data in table form)

### ISSUE THREAD

**Issue by Saurabh9520** [aws-amplify/amplify-ios#679]
![Webp net-compress-image](https://user-images.githubusercontent.com/53576807/88933727-6be3a180-d29d-11ea-90dc-6722b19db123.jpg)

Im using AWS amplify to get data in table in ios app in image data is in table
used Aws services required but i,m getting data in string format under the list 
how can i get data in table form
thanks in advance

**Comment by drochetti** [comment]
Hi @Saurabh9520 this is a known issue and it's been tracked here: #641 

I'll close this one as a duplicate, but feel free to follow the main issue for updates. A fix is on the way.
