### ISSUE TITLE
[Predictions] Missing `rowIndex` and `columnIndex` in `Cell` struct

### ISSUE THREAD

**Issue by DongQuanRui** [aws-amplify/amplify-ios#694]
**Describe the bug**
Each table has many cells and each cell should have `rowIndex` and `columnIndex` to tell the its relative location. The raw response from `AWS Textract` contains these two value type but `struct cell` is missing these two values and `IdentifyTextractTransformer` is not correctly processing them.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.0.6 and before

**Comment by lawmicha** [comment]
https://docs.aws.amazon.com/textract/latest/dg/API_Block.html#Textract-Type-Block-RowSpan
