### ISSUE TITLE
Add Auth Integration tests for Custom Auth and MFA flows

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#709]
This set of integration tests can act as secondary documentation to enabling custom auth for sign up and MFA for sign in (requiring confirm sign in after sign in). Add metadata to the requests where possible to verify the configured lambda triggers receive the data as `clientMetadata`. 

- custom auth triggered lambda can hardcode required code for sign up so test can automatically align with that value and confirm sign up of the user using the same code
- resend confirmation code can be done as part of the test, after sign up and before confirm sign up.
- MFA sign-in would be harder to automate in a test since the destination is email or phone number after sign in is executed

See https://github.com/aws-amplify/amplify-ios/pull/700 for initial Auth work to propagate metadata downstream

**Comment by palpatim** [comment]
Released in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.1.0
