### ISSUE TITLE
Protocol-defined APIs marked with `@discardableResult` don't propagate to implementations

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#713]
Thanks for adding this ! After I updated my project to 1.1.0, removing derived data and cleaning the build, I still receive the 'unsused' warning.  What do I miss ?

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/401798/90102281-8e1afc00-dd40-11ea-8805-0e0a06df1035.png">

I am sure I have the correct version :

```swift
    @discardableResult
    func signIn(username: String?,
                password: String?,
                options: AuthSignInOperation.Request.Options?,
                listener: AuthSignInOperation.ResultListener?) -> AuthSignInOperation

```

_Originally posted by @sebsto in https://github.com/aws-amplify/amplify-ios/pull/633#issuecomment-673293165_

**Comment by palpatim** [comment]
As noted in https://bugs.swift.org/browse/SR-7186, this is actually expected behavior in Swift, which I neglected to validate down the call chain. :( Will fix.

**Comment by palpatim** [comment]
Released in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.1.1

**Comment by sebsto** [comment]
Thanks for addressing this. 
Looks like `Amplify.Hub.listen`did not wen through 
https://github.com/aws-amplify/amplify-ios/blob/main/Amplify/Categories/Hub/HubCategoryBehavior.swift#L26 and related implementations

**Comment by palpatim** [comment]
That's intentional--Hub APIs don't return an AmplifyOperation, they return a cancellation token, similar to what `Publisher.sink()` does. The Combine flavor of Hub is `Hub.publisher(for:)`, but as with other Combine flavored APIs, the result of accessing the publisher is not discardable.

**Comment by sebsto** [comment]
Thanks Tim for the explanation.
