### ISSUE TITLE
Support or deprecate List.limit(_:)

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#727]
`List` currently exposes a `limit(_:)` API that has no meaningful implementation

https://github.com/aws-amplify/amplify-ios/blob/461c3cfd8923fbbb6eb10b60495b0f4594879cf4/Amplify/Categories/DataStore/Model/Collection/List+Model.swift#L94-L99

We need to either implement or deprecate this API.

**Comment by lawmicha** [comment]
Pending release of https://github.com/aws-amplify/amplify-ios/pull/1000 which addresses this

**Comment by palpatim** [comment]
Released in [v1.6.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0)
