### ISSUE TITLE
Move model name resolution to Amplify core

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#728]
As noted in this code snippet

https://github.com/aws-amplify/amplify-ios/blob/4cb4423a6eb3d46dc0caf4bf55392384b0e4acc8/Amplify/Categories/DataStore/Model/Collection/List+LazyLoad.swift#L40-L46

model name resolution is currently relegated to individual plugins. We should evaluate whether this is something we want to bring into Amplify core for consistency between plugin implementations.

**Comment by lawmicha** [comment]
this was addressed in https://github.com/aws-amplify/amplify-ios/pull/1009/files#diff-67755fffc75706a5336f5f05454d47dbdec5fdf6e5bd6a2e3450746d65685359R74

the code was migrated to DataStore plugin DataStoreListProvider, and creates the predicate with just the model name. When the name to SQL column name translation happens within the DataStore.Query call, it will do the translation to the "[modelName+associatedFieldName+Id]"
