### ISSUE TITLE
Support DataStore.delete with predicate

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#730]
As noted in the TODO in this snippet

https://github.com/aws-amplify/amplify-ios/blob/4cb4423a6eb3d46dc0caf4bf55392384b0e4acc8/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin+DataStoreBaseBehavior.swift#L102-L110

We don't currently support predicates for DataStore deletes. We need to.

**Comment by ruiguoamz** [comment]
Seems related to this PR: https://github.com/aws-amplify/amplify-ios/pull/1030

**Comment by palpatim** [comment]
Released in [v1.6.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0)
