### ISSUE TITLE
sessionExpired Hub Event does not appear to fire

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-ios#735]
**Describe the bug**
I have setup a Hub listener to listen for signIn, signOut and sessionExpired events. My understanding is that when a request is made which requires an active session, the sessionExpired event should be triggered.  However, when I attempt a signOut on an expired session, this does not happen (I've tried other methods, such as the storage plugin's upload method).  Additionally, when I attempt to request the session, the signedIn flag is set to `true`, and sessionExpired errors are included in the rest of the response (not sure if that's an issue or not).

```
_ = Amplify.Hub.listen(to: .auth) { payload in
          switch payload.eventName {
            case HubPayload.EventName.Auth.signedIn:
              let hubEvent: Dictionary<String, Any> = ["eventName" : "SIGNED_IN"]
              events(hubEvent)
            case HubPayload.EventName.Auth.sessionExpired:
              let hubEvent: Dictionary<String, Any> = ["eventName" : "SESSION_EXPIRED"]
              events(hubEvent)
            case HubPayload.EventName.Auth.signedOut:
              let hubEvent: Dictionary<String, Any> = ["eventName" : "SIGNED_OUT"]
              events(hubEvent)
            default:
              break
            }
          }
```

**To Reproduce**
1. Allow a session to expire
2. Attempt signout or other such event
3. Note that sessionExpired event does not appear to fire.

**Expected behavior**
I would expect the sessionExpired event to be triggered when an expired session is detected, or to otherwise have a documented path to handle this scenario.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.1.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 8 Simulator (13.3)
 - iOS Version: 11

**Additional context**
This is the Swift portion of a flutter plugin.

**Comment by palpatim** [comment]
We will take this on in an upcoming sprint. @drochetti to follow up.

**Comment by zhouhao27** [comment]
Is this fixed? I still have the same issue. Our version for Amplify is 1.5.

**Comment by royjit** [comment]
I have just tested this with the latest Amplify iOS library and I was able to get the right hub event. Explained here - https://github.com/aws-amplify/amplify-ios/issues/1028#issuecomment-776121181 regarding different tokens and when the hub event is called.
