### ISSUE TITLE
App gets stuck in a error state on logout

### ISSUE THREAD

**Issue by nigel545** [aws-amplify/amplify-ios#741]
**Describe the bug**
I was having an issue with logout on my old config, i switched to a new config that would fix the logout issue and then i got an error screen every time i would prompt a logout "an error was encountered ....". I tried clearing the browser info, deleting the app etc no luck. I then cleared all content and settings from the whole phone and then the app works for logout. So the only way to get it out of this error sate was to clear all settings from the phone. Obviously this is not ideal since it effects the whole phone. It would seem to me something from previous configs must be saved in keychain and doesn't not get overwritten with the new config info (that would be the only thing that persists deleting the app that i can think of).

**To Reproduce**
1.  Initialized app with a config
2. switched to a diffrent config and ran the app again
3. app keeps getting error screen when logging out
4. clear all content and setting from the whole phone
5. download app again and run it, logout works as intended

**Expected behavior**
Logout should work after changing amplify configuration without having to reset whole phone

**Screenshots**
<img width="387" alt="Screen Shot 2020-08-25 at 4 40 03 PM" src="https://user-images.githubusercontent.com/67649266/91347656-12499680-e7b9-11ea-8c5e-c11f4764110a.png">

**Environment(please complete the following information):**
 - pod: Amplify 1.1.1
 - Swift Version : 3.0

**Device Information (please complete the following information):**
 - Device: simulator/physical device
 - iOS Version: iOS 13

**Additional context**
This same issue was reported by another colleague getting stuck in same state, their only fix was to clear all content and settings as well.

**Comment by nigel545** [comment]
@palpatim  just wondering if this has been looked into at all?

**Comment by palpatim** [comment]
Hi @nigel545, this is on our backlog, but we haven't made any progress on the investigation yet. We'll update when we have more info.

**Comment by ruiguoamz** [comment]
Hi, @nigel545 

Can you be more specific on which authentication method you are using? Like [normal sign in](https://docs.amplify.aws/lib/auth/signin/q/platform/ios)? [sign in with Web UI](https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/ios)? cuz I couldn't have this reproduced with normal sign in, thanks.
