### ISSUE TITLE
Add ability to avoid iOS sign in Permission Warning Alert by using new ASWebAuthenticationSession instead of SFAuthenticationSession

### ISSUE THREAD

**Issue by muhaye** [aws-amplify/amplify-ios#745]
This feature is related to the fallowing Permission Warning Alert `{AppName}" Wants to Use "{idp link}" to Sign In. This allows the app and website to share information about you.`

<img width="413" alt="Screen Shot 2020-08-27 at 3 49 54 PM" src="https://user-images.githubusercontent.com/723702/91489924-a1b97d00-e87f-11ea-82a1-04a8c9023e9c.png">

The user get this Warning Msg before each {Login, Logout}.

If the implementation of Amplify.Auth.signInWithWebUI use new ASWebAuthenticationSession instead of the old SFAuthenticationSession, we could Potentially get rid of the Permission Warning Alert.

In order for this to be possible we'll need to pass a parameter `setPrefersEphemeralWebBrowserSession` value.

**Comment by muhaye** [comment]
The issue has been moved to https://github.com/aws-amplify/amplify-ios/issues/745

**Comment by palpatim** [comment]
Thanks for noting this. ASWebAuthenticationSession will require a platform support of iOS 12 or higher, and our current platform support goes back to iOS 11. It would be technically possible to use different underlying mechanisms for hosted UI, but in a module as complex as Auth already is, I'm not inclined to add more branching. We'll leave this feature request open to consider when we migrate platform support to iOS 12+.

**Comment by joao-jesus** [comment]
Hi, is there an alternative to bypass this popup on logout?
Is very confusing to appear a message "{AppName}" Wants to Use "{idp link}" to Sign In" on logout.

Is it acceptable, security wise, to bypass the Amplify.Auth.signOut callback and just clear locally the data?

Or is it possible to use a SafariController to skip this popup? 

Bellow from amplify (AWSCognitoAuth.m). 
How to trigger the self.useSFAuthenticationSession to false and configure proper the sdk to continue working. 
What configuration is needed to be changed? 
```objc
    if (self.useSFAuthenticationSession) {
        if (@available(iOS 11.0, *)) {
            self.sfAuthenticationSessionAvailable = YES;
            self.sfAuthSession = [[SFAuthenticationSession alloc] initWithURL:[NSURL URLWithString:url] callbackURLScheme:[self urlEncode:self.authConfiguration.signOutRedirectUri] completionHandler:^(NSURL * _Nullable url, NSError * _Nullable error) {
                if (url) {
                    [self processURL:url forRedirection:NO];
                } else {
                    [self signOutLocallyAndClearLastKnownUser];
                    [self dismissSafariViewControllerAndCompleteSignOut:error];
                }
            }];
            [self.sfAuthSession start];
        } else {
            [self signOutSFSafariVC:vc
                                url:url];
        }
    } else {
        [self signOutSFSafariVC:vc
                            url:url];
    }
```

**Comment by fotiDim** [comment]
I think this can be closed now. AWS SDK 2.22 adds support for ASWebAuthenticationSession

**Comment by royjit** [comment]
Hi,

Thank you for the patience while we were working on this. We have upgraded hostedUI to use ASWebAuthenticationSession and the changes are released in - https://github.com/aws-amplify/amplify-ios/releases/tag/v1.6.0.

signInWithWebUI will use `ASWebAuthenticationSession`  internally for iOS 13.0+ and for older iOS versions it will fallback to `SFWebAuthenticationSession`. Also for iOS 13.0+ you can enable the private browsing session by setting the value of `preferPrivateSession` in `AWSAuthWebUISignInOptions`.

```swift
// Sign in With private session
let pluginOption = AWSAuthWebUISignInOptions(preferPrivateSession: true)
let webUISignInoptions = AuthWebUISignInRequest.Options(pluginOptions: pluginOption)
Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!, 
                             options: webUISignInoptions) { ... }

// Using the static builder options to signin with private session
Amplify.Auth.signInWithWebUI(presentationAnchor: self.view.window!, 
                             options: .preferPrivateSession()) { ... }

```

If private session was enabled during signIn, when you signout Amplify.Auth will do a local only signOut and the `ASWebAuthenticationSession` popup will not be shown.
