### ISSUE TITLE
Querying items with hash and sort key

### ISSUE THREAD

**Issue by leungy2** [aws-amplify/amplify-ios#753]
I am building an iOS app that uses Amplify, DataStore and API (GraphQL) to populate items in a DynamoDB table. I created a schema with the @key method:
type Item @model @key(fields: ["id", "email"]) {
  id: ID!
  email: String!
}
This DynamoDB table generates as expected, with a hash key "id" and sort key "email". However, to query for items with a hash and sort key, I tried Amplify.API.query(request: .get(Item.self, byId: "firstItem"))", and it returns the error:
"GraphQLResponseError<Optional<Item>>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Validation error of type MissingFieldArgument: Missing field argument email @ \'getItem\'", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: nil, extensions: nil)]".

So it seems that I am unable to query by just id. However, there is also no way of adding the "email" field to query with both the hash and sort key. As a result, it is impossible to query anything from the table.

There really should be some way to query by primary key "id" or query with both primary key and sort key. Any help would be appreciated!

**Comment by drochetti** [comment]
hey @leungy2, can you confirm if you're using `Amplify.DataStore` or `Amplify.API`?

In `DataStore` you don't need `@key` to introduce sorting. You could remove it and use the query API like this:

```swift
Amplify.DataStore.query(Item.self,
                        sorting: .ascending(Item.keys.email)) {
    // handle result
}
```

Docs: https://docs.amplify.aws/lib/datastore/data-access/q/platform/ios#sort

---

In case you are using `Amplify.API`, then the answer above is not valid. In that case I would need to investigate a solution. When the default queries don't work, you can potentially [create your own `GraphQLRequest` with a valid query](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios).
