### ISSUE TITLE
isSignUpComplete flag set to false

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-ios#760]
**Describe the bug**
Upon creating a userpool record using the .signUp method, the result contains an 'isSignUpComplete' flag which is set to false.  As indicated by the discussion [in this amplify-android issue](https://github.com/aws-amplify/amplify-android/issues/686#issuecomment-674927461), the expectation is that this flag should be set to true (even if confirmation is still needed).

**To Reproduce**
1. Call 'signUp' on a userpool which requires confirmation.
2. Receive a response indicating that the next step is CONFIRM_SIGN_UP_STEP
3. Note that 'isSignUpComplete' is 'false.

**Expected behavior**
As indicated [here](https://github.com/aws-amplify/amplify-android/issues/686#issuecomment-674927461), isSignUpComplete should be true.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.1.2
 - Dependency Manager: Cocoapods
 - Swift Version : 11.0

**Device Information (please complete the following information):**
 - Device: iPhone 11 Simulator
 - iOS Version:  11 (13.7)

**Comment by palpatim** [comment]
Please see discussion on https://github.com/aws-amplify/amplify-android/issues/686 -- my recollection of that decision differs from @TrekSoft's.

**Comment by enteleca** [comment]
Create a lambda function to automatically flag it to true when a user signs up. You can set the trigger in `amplify auth console`

**Comment by palpatim** [comment]
The existing behaviors across platforms are incompatible, and cannot be resolved without breaking one platform or another.

Next steps:
- Document the behavior of the flag in each platform, with a warning or alert that the behavior differs across platforms
- When the time comes to look at Auth 2.0, consider what the desired behavior is and write tests across platforms to assert that desired behavior

I am flagging this as a "documentation" bug now. Once we resolve the documentation part of this, we can re-characterize it as a feature request.

**Comment by royjit** [comment]
Closing this issue since we are changing this in Android - https://github.com/aws-amplify/amplify-android/issues/686
