### ISSUE TITLE
OpenID Connect auth with external token provider

### ISSUE THREAD

**Issue by damienpontifex** [aws-amplify/amplify-ios#761]
**Is your feature request related to a problem? Please describe.**
Our iPad devices are enrolled with Intune and we would like to use the MSAL authentication libraries to simplify auth here for our app and so are looking to use the OpenID Connect authentication option for AppSync. In here:

https://github.com/aws-amplify/amplify-ios/blob/64fcd539ecb3578220b86e8062c619035e515fbf/AmplifyPlugins/API/AWSAPICategoryPlugin/SubscriptionFactory/AWSSubscriptionConnectionFactory.swift#L59-L62

it mentions "OIDC Token Provider from somewhere else that the developer added"

This would be great if we can use the MSAL libraries as the provider for the token and implement an implementation of `OIDCAuthProvider` to provide this token.

So the request here is the appropriate hook points that we could implement this protocol and hook it into the configuration for the library to use

**Describe the solution you'd like**
Appropriate hook points so we can register an OpenID connect token provider

**Describe alternatives you've considered**
Looked at an AuthPlugin, but complexity is quite high it seems when most of the logic we need is external to the libraries concerns here

n.b. I'd be happy to make a PR, but some guidance on how this should work would be much appreciated

**Comment by damienpontifex** [comment]
I found a section for adding a 3rd party OIDC provider here https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios#oidc

Following the docs exactly, I hit this line with `preconditionFailure`

https://github.com/aws-amplify/amplify-ios/blob/64fcd539ecb3578220b86e8062c619035e515fbf/Amplify/Categories/Auth/AuthCategory.swift#L26-L28

This seems a bit odd as It's using a bunch of token and auth providers while the docs say just add an interceptor and mutate the request

**Comment by lawmicha** [comment]
Hi @damienpontifex, thanks for the details- we are investigating this and will provide an update

**Comment by damienpontifex** [comment]
@lawmicha looking at [Release 1.4.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.4.0) it reads that this is now possible?

**Comment by lawmicha** [comment]
> @lawmicha looking at [Release 1.4.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.4.0) it reads that this is now possible?
> Reading the PR details - maybe this just covers the API side? Does it also cover the realtime websocket updates?

Hi @damienpontifex, yes this covers subscriptions as well! the PR https://github.com/aws-amplify/amplify-ios/pull/842 describes how to use the ODIC provider, and we'll be working on updating the documentation. Please let us know if you have any questions

**Comment by damienpontifex** [comment]
@lawmicha I tried with the sample code from #842 and when configuring amplify get `preconditionFailure("No plugins added to \(categoryType.displayName) category.")`

My configuration is:
```swift
let apiAuthProviderFactory = MsalOidcProviderFactory()
try Amplify.add(plugin: AWSDataStorePlugin(modelRegistration: AmplifyModels()))
try Amplify.add(plugin: AWSAPIPlugin(apiAuthProviderFactory: apiAuthProviderFactory))
try Amplify.configure()
```

**Comment by lawmicha** [comment]
Hi @damienpontifex, what does the stack trace look like? if the auth plugin key is in your `amplifyconfiguration.json` then you may see that failure when you call `Amplify.configure()` without adding AWSCognitoAuthPlugin.

**Comment by damienpontifex** [comment]
@lawmicha I tried to create a minimal reproduction but ran into so many issues setting up with amplify again I just gave up. I won't pursue this any further here and we will just live with what we've got
