### ISSUE TITLE
Handling Users' Potentially Bad Network Connections and Implementing Asynchronous Saves to Models

### ISSUE THREAD

**Issue by enteleca** [aws-amplify/amplify-ios#762]
Hi, I'm creating my application with Amplify and it has been great so far.

I have a general question on how a particular save functionality would work.

In my app, I have a Post schema that has views like this (there are more fields, but I simplified it for easy reading):

```
type Post @model {
  id: ID!
  views: Int!
}
```

Basically, when a user clicks on my post, I run a function that takes the current post that the user is viewing, save it off as a variable, add 1 to the view, and then save it again. This could be demonstrated as follows:

```
var newPost = post
newPost.views += 1

Amplify.DataStore.save(newPost) {
             switch $0 {
             case .success:
                     print("saved post with adding 1 new view")
                                            
             case .failure(let error):
                     print("an error has occurred")
             }
}
```

I'm not sure if my worries should be warranted or if Amplify handles this, but with this setup, I am worried that users with bad internet connection could hold up the newPost save. I'll give an example:

> There is a post with 10 views.
> Joe has bad internet connection. He logs onto the app and views the post, prompting the above code. As Amplify is trying to save the new post so that it has 11 views, many other users view the post and save the post before Joe.
> 
> Jared, Bob, and Jill all view the post and save it one by one in order. The post in the cloud now has 13 views and Joe is still trying to save his post with his new view added.
> 
> Finally, Joe's internet connection comes through and his post is saved. Only now, since Joe's App's newPost field only had 11 views, the post is now saved with 11 views. 
> 
>The post went from 10 views -> 13 views -> 11 views.
>
> The post is supposed to now have 14 views, but it only displays 11 views.

Is this something that could happen? I understand that my method of saving these posts is sort of "hackish" but I only started coding with Amplify about a month ago, so it would be great if someone could lend me a hand and point me in the right direction with possibly a better way to do this.

Thank you so much! Please let me know if you'd like me to clarify anything.

**Comment by enteleca** [comment]
Wasn't really using my mind here. This could easily be solved by a subscription to the Model, if anyone else is thinking about this issue!

**Comment by drochetti** [comment]
Hi @enteleca, I'm glad you're enjoying your experience so far.

Like you said, the fact that data is distributed across devices and updates can happen asynchronously, it's really up to you, the developer, to take care of the consistency of your dataset. In your case, the subscription is definitely one way of handling it.

Also, note that the DataStore backend, AppSync, has an auto-merge algorithm that tries to resolve data conflicts when multiple updates happen when offline in different devices and need to be reconciled later. You can customize that behavior if needed. You can read more about that here: https://docs.amplify.aws/lib/datastore/conflict/q/platform/ios

Let me know if that's helpful. Good luck in your project!
