### ISSUE TITLE
Crash - Fatal error: No plugins added to Authentication category.

### ISSUE THREAD

**Issue by mayckonx** [aws-amplify/amplify-ios#764]
**Describe the bug**
I have created a new project and did the standard process to pull an existing amplify app into my ios app. 
But once I run the application I get the crash on the amplify initialization. 

**To Reproduce**

1. On the root of the project called `amplify pull` with the id of the application  and the environment
2. Generated the model through Cmd+B
3. Run the  application

**Expected behavior**
I expect the app runs normally, without any crash since I pulled the environment already. 

**Screenshots**

My config: 

<img width="718" alt="Screenshot 2020-09-11 at 09 02 07" src="https://user-images.githubusercontent.com/8951261/92879690-89b03480-f40d-11ea-97c6-95bb0a1c87d1.png">

awsconfiguration.json: 
`
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "AppSync": {
        "Default": {
            "ApiUrl": "https://cecmiuovbbblplcoar6ta2ncfy.appsync-api.us-east-1.amazonaws.com/graphql",
            "Region": "us-east-1",
            "AuthMode": "AWS_IAM",
            "ClientDatabasePrefix": "dashboard_AWS_IAM"
        }
    }
}
`

amplifyconfiguration.json: 
`
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "dashboard": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://cecmiuovbbblplcoar6ta2ncfy.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "AWS_IAM"
                }
            }
        }
    }
}
`

Crash screenshot: 

<img width="1327" alt="Screenshot 2020-09-11 at 08 59 27" src="https://user-images.githubusercontent.com/8951261/92879191-1c9c9f00-f40d-11ea-91fd-016880db975d.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 4.27.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - iOS Simulator(any device)
 - XCode 11.6 and also reproducible on Xcode 12.0 Beta

**Additional context**
I tried to create a project to make sure it wasn't being caused by something I might mess up on my local environment, but I can confirm, it's happening whenever I pull the project and run the app. 

I don't have authentication in my application. Why is amplify asking me for that Plugin?

**Comment by palpatim** [comment]
Your amplifyconfiguration.json shows that your API backend is set up to use `AWS_IAM`, but you haven't configured the auth category in `amplifyconfiguration.json`, nor added the AWSCognitoAuth plugin.

1. Update your Podfile to add a dependency on the plugin:

    ```ruby
    pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
    ```

2. Add the plugin in your Amplify configuration code:

    ```swift
    try Amplify.add(plugin: AWSCognitoAuthPlugin())
    ```

3. The final piece is to  update your `amplifyconfiguration.json` file with your Auth configuration. The right way to do this will depend on how you configured your API to use the `AWS_IAM` auth mode. Did you perhaps change the auth mode via the AWS AppSync console rather than the Amplify CLI? If so, you'll need to follow the ["Use existing resources" docs](https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios) to manually update your `amplifyconfiguration.json` file with the auth config.

    If on the other hand you used the Amplify CLI to add Auth and update your GraphQL API's auth mode to `AWS_IAM`, then there may be a bug in the `amplify pull` flow. Please provide more detail around how you generated your backend to help troubleshoot. We'll especially need to know which version(s) of the Amplify CLI you used and the cli commands you used to generate, update, and pull.

**Comment by mayckonx** [comment]
Hi @palpaatim, thanks for your input. I have changed the auth mode from `AWS_IAM` to `API_KEY` but know I'm getting the following error: 

<img width="1063" alt="Screenshot 2020-09-12 at 06 53 24" src="https://user-images.githubusercontent.com/8951261/92987638-a8bdcd80-f4c4-11ea-82dd-5ad8ed8f0396.png">

It seems it can't decoded the response.

**Comment by mayckonx** [comment]
I had removed the AuthMode from the amplifyconfiguration file and added the API_KEY as well and it worked. Thank you! :D
