### ISSUE TITLE
How i can set sharedContainerIdentifier for Amplify iOS

### ISSUE THREAD

**Issue by mdawais92** [aws-amplify/amplify-ios#767]
I am using Amplify for iOS share extension. How i can set sharedContainerIdentifier for Amplify. I wanna use Amplify for uploading media in share extension.

**Comment by wooj2** [comment]
Hi @mdawais92 ,

We currently do not support building Amplify into an extension.  In any case, would you be able to provide some code samples as well as expected behavior of how you are expecting Amplify to operate?

**Comment by mdawais92** [comment]
Yes, I wanted to upload media (image or videos) from my share extension.

If you need any further info, let me know.

**Comment by wooj2** [comment]
Hi mdawais92@,

As pointed out in your [previous post](https://github.com/aws-amplify/aws-sdk-ios/issues/3013), running the AWS SDK for iOS is currently only supported for iOS apps, and not extensions at the moment.

Given that this has already been reported, I will be closing this issue.
