### ISSUE TITLE
Cannot find any cancel call in Amplify module in iOS

### ISSUE THREAD

**Issue by saravr** [aws-amplify/amplify-ios#772]
**Is your feature request related to a problem? Please describe.**
Is there a way to cancel, for example, Amplify.Auth.signIn() ? AWSMobileClient module has something like 'releaseSignInWait' that can be used but I am using Amplify module.

**Describe the solution you'd like**
Is there a function I can call in Amplify or is there some other way?

**Describe alternatives you've considered**

**Additional context**
Using Amplify 1.0.5

**Comment by ruiguoamz** [comment]
Hi, @saravr 
Thanks for reaching out.

When using `AWSMobileClient`, `releaseSignInWait` can be called when `signedOutFederatedTokensInvalid` and `signedOutUserPoolsTokensInvalid` states are returned from the listener, see [here](https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/ios#how-it-works). In Amplify, `releaseSignInWait` is not required.

We am more curious on your use case, and what do you mean by `cancel`. Thanks.

**Comment by saravr** [comment]
@ruiguoamz I just want to cancel any pending login/signup operations (say if it is taking long time, timing out, etc.)

**Comment by ruiguoamz** [comment]
Hi, you can try
```swift
let signInOperation = Amplify.Auth.signIn()
...

signInOperation.cancel()
```

**Comment by saravr** [comment]
Thanks. However, still getting messages like

`Task <D7DB0E1B-3117-49DB-AC3A-7E63BDAE5538>.<4> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x600001b407e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <D7DB0E1B-3117-49DB-AC3A-7E63BDAE5538>.<4>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <D7DB0E1B-3117-49DB-AC3A-7E63BDAE5538>.<4>"`

I simulated bad network during login and backed out from login screen (iOS) which triggered this cancel() call. Not really sure if cancel took effect.

BTW, where are these calls (cancel()) are documented?

**Comment by royjit** [comment]
The cancel operation just cancels the call back. If the request as initiated there is no way to currently stop the network activity.

**Comment by drochetti** [comment]
> BTW, where are these calls (cancel()) are documented?

@saravr I created an issue in the docs repo so we can address the lack of documentation of the cancellable operations: https://github.com/aws-amplify/docs/issues/2540
