### ISSUE TITLE
Sporadic Crashes when datastore is syncing from scratch

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#773]
**Describe the bug**
I'm experiencing sporadic problems when installing/running my app from scratch. This only seems to occur when several thousand DB-entries are involved.
Initially, I became aware of the problem, when
`[ReconcileAndLocalSaveOperation] The operation couldn’t be completed. (Amplify.DataStoreError error 8.)`
starting showing up.
To investigate, I turned all output on. More specifically, the problem is:
`Recovery suggestion: The operation couldn’t be completed. (SQLite.Result error 0.)
Caused by:
FOREIGN KEY constraint failed (code: 19))) -> inError(DataStoreError: The operation couldn’t be completed. (SQLite.Result error 0.)`
What puzzles me is that a comparison between two consecutive runs (each time erasing the app directly prior for a fresh start) shows that the very same item is sometimes written without an issue. Hence, I rule out any data inconsistency.

I have attached two dumps that I've made with `Amplify.Logging.logLevel = .verbose`

Take, for example, item E45A353D-95FC-468C-89C8-7AAFAC0E4DCE
In dump1.txt, in line 12310, the write error seems to occur with that item.
In dump2.txt, the first write error occurs in line 15887. The item E45A... last mentioned in line 13932. So I believe it was written correctly.

[dump1.txt](https://github.com/aws-amplify/amplify-ios/files/5251765/dump1.txt)
[dump2.txt](https://github.com/aws-amplify/amplify-ios/files/5251767/dump2.txt)
[schema.graphql.txt](https://github.com/aws-amplify/amplify-ios/files/5251770/schema.graphql.txt)

Next, I investigated the foreign key (B3881893-781F-4E77-B8D9-0B3D579CEA2C). It seems to me that in dump1.txt, the item is written much later compared to dump2.txt. I guess that would explain why the error occurs in one case, but not the other. However, I've no idea why that is or if I'm reading the output correctly. I've also attached the schema file.

Additionally, sometimes the app comes crashes entirely, always in function `AWSModelReconciliationQueue.enqueue`. I have attached a screenshot. Either it crashes on line 146 or 139, i.e. on insertion or removal. However, I'm not entirely sure whether this is the same issue or not. But it seems close enough, which is why I added it here.
![Screenshot 2020-09-20 at 15 09 38](https://user-images.githubusercontent.com/67764399/93712075-77dc3900-fb53-11ea-8f0e-a87d56ae24fc.png)

**To Reproduce**
This is were it becomes difficult. I cannot tell you how to reproduce, because the errors occur sporadically. :( When I was building my app with play data, there was no problem. Now, that I've included actual data, the problems started to show.

**Expected behavior**
The app syncing cleanly from scratch, even when larger amounts of data are involved.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.2.0
 - Dependency Manager: Cocoapods
 - Swift Version: Xcode Version 12.0

[Podfile.lock.txt](https://github.com/aws-amplify/amplify-ios/files/5251787/Podfile.lock.txt)

**Device Information (please complete the following information):**
 - Device: iPhone 6s, iPhone 6s+, Simulator iPhone 11
 - iOS Version: Actually phones iOS 13.7, Simulator iOS 14
 - Specific to simulators: The crash (see screenshot), occurs much more frequently in the simulator. The foreign key issue occurs on both.

**Additional context**
Thanks for reading until here! If you need any additional information from my side, please let me know.

**Comment by anatomybook** [comment]
I just caught another crash - this time in the remove part.
![Screenshot 2020-09-20 at 18 08 56](https://user-images.githubusercontent.com/67764399/93715873-4754c900-fb6c-11ea-8503-8d21a1c83cc7.png)

**Comment by anatomybook** [comment]
I just found some time to closer inspect the errors again. It seems to be a threading issue. The `reconcileAndLocalSaveOperationSinks` Set is being accessed by two threads at the same time. As a quick fix, I've added a serial queue and re-routed all Set accesses via sync and it seems to work.
Maybe this helps?!

**Comment by jimkqwantegy** [comment]
Seeing the same thing with only a few items. Consistently crashing on the remove operation. Using AmplifyPlugins 1.2.

**Comment by palpatim** [comment]
Thanks for the investigation @anatomybook. I agree this smells a lot like a data race issue. We'll investigate this and update when we have more information.

**Comment by palpatim** [comment]
This is fixed in #790 and merged to `main`. We plan on releasing this today.

**Comment by jimkqwantegy** [comment]
Awesome. Thanks.

**Comment by palpatim** [comment]
We have released this fix on [1.3.1](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.3.1). Please reopen this issue if you continue to have problems.
