### ISSUE TITLE
AmplifyTools overwrites custom configuration

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#774]
**Describe the bug**

Reported by jgj#6252 on [Discord](https://discord.com/channels/705853757799399426/707328996995760179/757615038155587654):

> (jgj) @ undef_obj @ Palpatim Thanks for the help. I think we just got it figured it out. We were bouncing between the 'plugin not found error' and another error that our config file was missing certain values for the auth plugin. It looks like the custom build script was overwriting our manual changes to the "auth" part of the config file because our GraphQL API (created with the CLI) was adding auth behind the scenes...
> 
> (Palpatim) @ jgj When you say "custom build script", do you mean the Build Phase that Amplify Tools adds, a build step that invokes the Amplify CLI, or a custom script specific to your project? The Amplify CLI is designed to not overwrite changes, so if you're seeing a case where your manual configuration changes are being overwritten, I'd want to investigate further.
> 
> (jgj) @ Palpatim  I’m referring to the run script that’s added by amplify tools. We would manually add a “CognitoUserPool” object under auth, but when we built the project it would disappear and the only thing under auth was the “AppSync” object

It's unclear to me whether this is happening because of a bug, or whether it's expected behavior because of some combination of configurations between the backend and frontend. 

---

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 0.10.0]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 5.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11]
 - Specific to simulators:

**Additional context**

**Comment by wooj2** [comment]
This is by design, amplify cli is responsible for managing whether or not to overwrite configurations.
