### ISSUE TITLE
AuthProvider enum should conform to Equatable protocol

### ISSUE THREAD

**Issue by mTRx0** [aws-amplify/amplify-ios#776]
**Is your feature request related to a problem? Please describe.**
I'm having a hard time trying to compare two variables of type `AuthProvider`:

```
var selectedProvider: AuthProvider = .apple

func compareAuthProvider() {
  if self.selectedProvider != AuthProvider.apple { // Comparison is not possible
    XCTFail("Apple is not the selected auth provider")
  }
}
```

**Describe the solution you'd like**
The AuthProvider enum should conform to 'Equatable' protocol

**Comment by drochetti** [comment]
Hey @mTRx0, Swift supports enum matching at the language level using `if case`:

```swift
if case .apple = self.selectedProvider {
    XCTFail("Apple is not the selected auth provider")
}
```

Let me know if that's helpful.

**Comment by mTRx0** [comment]
Great, didn't know that until now. Thanks!
