### ISSUE TITLE
How to use generated code from API.swift for connections/GSI's

### ISSUE THREAD

**Issue by chris-mds** [aws-amplify/amplify-ios#802]
I have the following model

```
type Process @model{
    id: ID!
    ...
    tasks:[Task]! @connection(keyName:"byProcess",fields:["id"])
}

type Task @model
    @key(name:"byProcess",fields:["processID"],queryField:"tasksByProcess"){
    id:ID!
   processID:ID!
   name:String!
    ...
}
```

This will generate inside my API.swift the class` TasksByProcessQuery` The initializers of the class are like expected and I can give it the processID, so I could query it. With the AppSync console this works like a charm and I get my expected results. 
But now I don't know how I can call a method inside my app to get my results.
Is there any wrapper, where I can put my custom GSI-queries generated from codegen in and make the call? Custom queries have the protocol 'GraphQLQuery', but I don't know how to work with that type.

**Comment by royjit** [comment]
Hi @chris-mds 

Can you please provide more details on which library are you using and the version. `@key` works differently for AWSAppSync iOS SDK and Amplify iOS library. Please provide more details to debug further. 

---

**Environment(please complete the following information):**
 - Amplify Framework Version: [e.g. 0.10.0]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 5.0]

**Comment by chris-mds** [comment]
Hi @royjit ,

Amplify Framework Version: [1.2.0]
Dependency Manager: [Cocoapods]
Swift Version : [5.3]

**Comment by royjit** [comment]
Thank you for providing the information. For Amplify library you have to create custom GraphlQLRequest as explained in this [document](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios). For your use case you can convert the `TasksByProcessQuery` to a `GraphQLRequest` as follows:

```swift

extension GraphQLRequest {
    public static func tasksByProcess(query: TasksByProcessQuery) -> GraphQLRequest<List<Task>> {
        let request = GraphQLRequest<List<Task>>(document: TasksByProcessQuery.operationString,
                                                 variables: query.variables,
                                                 responseType: List.self,
                                                 decodePath: "tasksByProcess.items")
        return request
    }
}
```
Now you can use this request to query the items:

```swift

Amplify.API.query(request: .tasksByProcess(query: query)) { (event) in
    
    do {
        let result = try event.get()
        let graphQLResult = try result.get()
        
    } catch {
        print(error)
    }
}
```

**Comment by chris-mds** [comment]
Hi @royjit,

thank you for your response.

I updated your code as follows, because it gives me a warning and wrong results

```
extension GraphQLRequest {
    public static func tasksByProcess(query: TasksByProcessQuery) -> GraphQLRequest<List<Task>> {
        let request = GraphQLRequest<List<Task>>(document: TasksByProcessQuery.operationString,
                                                     variables: query.variables?.jsonObject, //I added .jsonObject 
                                                 responseType: List.self,
                                                 decodePath: "tasksByProcess.items")
        return request
    }
}
```

Now this works, but only for Types with no model depth. I recognized that Codegen doesn't generate the right operationString to query data with nested structure. I changed maxDepth in Codegen to 4, but this didn't made any changes. Do I have to do additional configurations, so Codegen can generate the right operationString? I can manually change it, but every time I will run Codegen it would override my changes.

**Comment by chris-mds** [comment]
Turns out I mixed old AppSync API with AmplifyPlugins/APIPlugin
Thanks!
