### ISSUE TITLE
Question: Deny resetPassword on device

### ISSUE THREAD

**Issue by Troush** [aws-amplify/amplify-ios#808]
Hello!

Is it possible to somehow deny the ability to call resetPassword from the device from Cognito configuration?
I want to impliment security questions before we will allow user to change password. But I want to prevent users to bypass security questions screens and call resetPassword directly. Is it possible with backend policy?

**Comment by royjit** [comment]
Hi @Troush 

`Amplify.Auth` do not have any logic of preventing a resetPassword. It is upto the customers business logic to call `resetPassword` or not. You can make the app logic in such a way that `Amplify.Auth.resetPassword` is called only after a set of security questions are answered.
