### ISSUE TITLE
ShowSignInWebView calls completion before the SafariViewController is dismissed

### ISSUE THREAD

**Issue by ovidiuadorian-yonder** [aws-amplify/amplify-ios#809]
**Describe the bug**
When you call showSignInWebView, the completion is called before the safari view controller finished dismiss

**To Reproduce**
private func showSignInWebView(window: UIWindow,
                                   request: AuthWebUISignInRequest,
                                   completionHandler: @escaping (Result<AuthSignInResult, AuthError>) -> Void)

Completion on this method is called before the safari view controller finished the dismiss.

**Expected behavior**
The completion should be called only after the call to navController.dismiss(animated: false) is completed.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.1.2
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Device: NA
 - iOS Version: iOS 12,13,14
 - Specific to simulators:

**Comment by royjit** [comment]
PR - https://github.com/aws-amplify/amplify-ios/pull/820 should fix the issue

**Comment by drochetti** [comment]
Hey @ovidiuadorian-yonder, [1.4.0](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.4.0) was released and contains the fix to this issue.

**Comment by gevartosky** [comment]
Hi, 

Does this applies to `Amplify.Auth.signOut` too? I'm trying to navigate to another tab right after I signout but any operation on the presenting view controller is still targeting the Safare web view.

**Comment by ovidiuadorian-yonder** [comment]
SignOut seemed to work fine for me. The problem was only at sign-in

**Comment by gevartosky** [comment]
Yeah I'm still noticing this on 1.4.1

Right after the completion for `Amplify.Auth.signOut` is called, the top view controller is still safari
![image](https://user-images.githubusercontent.com/5980943/101778207-52b3f280-3ad2-11eb-95df-c1d35fd377e1.png)
