### ISSUE TITLE
Fetch user attributes not working with Google Federated signin

### ISSUE THREAD

**Issue by Vivek205** [aws-amplify/amplify-ios#811]
**Page**: [`/lib/auth/user-attributes/q/platform/ios`](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/ios)

I'm using semaphores to wait for the `Amplify.API.post` response. It is working fine when I signin using username/password in my application. 
But when I signin using Google, the app is getting frozen in the API call.

```
 let semaphore = DispatchSemaphore(value: 0)
....
 _ = Amplify.API.post(request: request, listener: { (result) in
....
switch result {
 case .success(let data):
semaphore.signal()
 case .failure(let apiError):
semaphore.signal()
}})
....
 _ = semaphore.wait(timeout: .distantFuture)
    print("api completed")
```

**Comment by royjit** [comment]
Hi @Vivek205 

How are you signIn in using Google? Can you please provide some code sample. If you are federating to Cognito Identity Pool, you will not be able to get user attributes from social providers. On the other hand if you are using hostedUI by calling `Amplify.Auth.signInWithWebUI()` you will be able to fetch the user attributes.

**Comment by Vivek205** [comment]
Hi @royjit , 

I'm using HostedUI to handle Google Signin. PFB my code snipet. 

```
        _ = Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: self.view.window!) { result in
            switch result {
            case .success(let session):
                onSuccess()
            case .failure(let error):
                onFailure(error: error)
            }
        }
```

**Comment by royjit** [comment]
Thank you for the information. Please verify that you have mapping in place for Google attributes in Cognito UserPool console as shown in the screenshot below:
![Screen Shot 2020-10-08 at 1 46 05 PM](https://user-images.githubusercontent.com/51138777/95511699-ad16c280-096c-11eb-80d0-c93a8ed2d5d4.png)

Also, can you share the error coming from `Amplify.Auth.fetchUserAttributes` ?


```
func fetchAttributes() {
    Amplify.Auth.fetchUserAttributes() { result in
        switch result {
        case .success(let attributes):
            print("User attributes - \(attributes)")
        case .failure(let error):
            print("Fetching user attributes failed with error \(error)")
        }
    }
}
```

**Comment by drochetti** [comment]
> I'm using semaphores to wait for the Amplify.API.post response. It is working fine when I signin using username/password in my application.

Hey @Vivek205 Is there's a particular reason for using semaphores and not making the code asynchronous?

**Comment by Vivek205** [comment]
@drochetti, 
Yeah, we are using the research-kit for a survey.
In the survey, some of the questions are dynamic, i.e. the next question will be determined based on the current question's answer. 
There we are obliged to wait for the API response synchronously.

**Comment by Vivek205** [comment]
@royjit , 
> Please verify that you have mapping in place for Google attributes in Cognito UserPool

Yh I have the proper mapping in cognito console
<img width="911" alt="image" src="https://user-images.githubusercontent.com/26110173/96087215-253b3600-0ee1-11eb-86a0-a7ffdef88666.png">

> Also, can you share the error coming from Amplify.Auth.fetchUserAttributes ?

There is no error in fetchAttributes method. It just hangs. not responding

**Comment by Vivek205** [comment]
@drochetti @royjit , any update on this issue?

**Comment by drochetti** [comment]
> @drochetti @royjit , any update on this issue?

No updates yet, I have not had a chance to reproduce it.

**Comment by royjit** [comment]
I created a sample app with Google signIn for hostedUI. And I was able to successfully get the user attributes:

SignIn code

```swift
        Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: self.view.window!) { (result) in
            switch result {
            case .success(let result):
                print(result)
            case .failure(let error):
                print(error)
            }
        }
```

Fetch attributes:

```swift
        Amplify.Auth.fetchUserAttributes { (result) in
            switch result {
            case .success(let result):
                print(result)
            case .failure(let error):
                print(error)
            }
        }
```

Result

```terminal
[Amplify.AuthUserAttribute(key: Amplify.AuthUserAttributeKey.unknown("sub"), value: "xxx"), Amplify.AuthUserAttribute(key: Amplify.AuthUserAttributeKey.email, value: "xx@gmail.com"), Amplify.AuthUserAttribute(key: Amplify.AuthUserAttributeKey.unknown("identities"), value: "[{\"userId\":\"xx\",\"providerName\":\"Google\",\"providerType\":\"Google\",\"issuer\":null,\"primary\":true,\"dateCreated\":xx}]"), Amplify.AuthUserAttribute(key: Amplify.AuthUserAttributeKey.unknown("email_verified"), value: "false")]
```

**Comment by royjit** [comment]
We cannot debug further without more information on how to reproduce this or with error logs. You can enable more verbose logging by adding the following when the app starts:

```swift
import AWSCore

AWSDDLog.sharedInstance.logLevel = .verbose
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

If the fetch user attributes call is made, you could see logs similar to this:

```terminal

Request headers:
{
    "Content-Type" = "application/x-amz-json-1.1";
    Host = "cognito-idp.us-east-1.amazonaws.com";
    "User-Agent" = "amplify-iOS/(Function) iOS/14.0 en_US";
    "X-Amz-Date" = xx;
    "X-Amz-Target" = "AWSCognitoIdentityProviderService.GetUser";
}

Request body:
{"AccessToken":"xxx"}

Response headers:
{
    "Content-Length" = 405;
    "Content-Type" = "application/x-amz-json-1.1";
    Date = "xx";
    "x-amzn-requestid" = "xx";
}
2020-11-12 14:12:25:255 CognitoUserPool[42979:4105099] Response body:
{"UserAttributes":[{"Name":"sub","Value ...)]

```

**Comment by bluepixeltech** [comment]
Were you able to figure out the problem? I have the same problem. Amplify.Auth.fetchUserAttributes sometimes (not always) hangs and doesn't return anything! Not even an error.
