### ISSUE TITLE
AWSAuthCognitoSession - There is no user signed in to retreive user sub

### ISSUE THREAD

**Issue by mrkslrssn** [aws-amplify/amplify-ios#818]
**Describe the bug**
Tokens not found when upgrading from using `AWSCognitoIdentityProvider` to Amplify Auth:  

When using `AWSCognitoIdentityUserPool.default().currentUser()?.getSession().continueWith` and `AWSCognitoIdentityUserSession` to fetch idToken, acessToken and refreshToken the tokens are available. (Works with Amplify 1.3.0) 

But when calling `Amplify.Auth.fetchAuthSession` it fails, `AWSAuthCognitoSession` does not contain the user sub or tokens. So users needs to re-sign in. 

Or do you need to configure it differently in this kind of scenario? 

Re-sign in with Amplify and then fetch auth session works as expected.

When using Amplify and amplifyconfiguration:

````
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "[COGNITO IDENTITY POOL ID]",
                            "Region": "[REGION]"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "[COGNITO USER POOL ID]",
                        "AppClientId": "[COGNITO USER POOL APP CLIENT ID]",
                        "Region": "[REGION]"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
````

````
try Amplify.add(plugin: AWSCognitoAuthPlugin())
try Amplify.configure()
````

````
Amplify.Auth.fetchAuthSession : result

userSubResult: There is no user signed in to retreive user sub
identityIdResult: success : "us-east-1..."
awsCredentialsResult: success: AuthAWSCognitoCredentials
cognitoTokensResult: failure: There is no user signed in to retreive cognito tokens
````

**Expected behavior**
The session is maintained when upgrading to `Amplify` ` AWSCognitoAuthPlugin` for the current user identity from using `AWSCognitoIdentityProvider`. Expected to get  cognito tokens when calling fetchAuthSession with a config structure similar to above. 

**Environment(please complete the following information):**
 - Amplify Framework Version: Amplify (1.3.0)
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 14

**Comment by royjit** [comment]
`AWSCognitoIdentityProvider` is not upgradable to `Amplify.Auth`, user's has to signIn again. Internally `Amplify.Auth` uses `AWSMobileClient`, and migrating from `AWSMobileClient` to `Amplify.Auth` should work without any issue. This is because `Amplify.Auth` depend on the keychain information inside [AWSMobileClient](https://github.com/aws-amplify/aws-sdk-ios/blob/0f3087c24b9346a6f1da5710c91301520f0ac3dc/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift#L236-L238) to determine the current user state, this doesnot happen if you are migrating from `AWSCognitoIdentityProvider `.
