### ISSUE TITLE
create object error

### ISSUE THREAD

**Issue by springlo** [aws-amplify/amplify-ios#826]
I want to create Post:
```
let uid = Amplify.Auth.getCurrentUser()!.username
let post = Post(title: title, content: content, link: link, tags: tags, isPublic: isPublic, userID: uid)
let build = GraphQLRequest<Post>.create(post)
```
then I print ```po build.variables``` , I lost the userID.  and This situation sometimes occurs.

```
Optional<Dictionary<String, Any>>
  ▿ some : 1 element
    ▿ 0 : 2 elements
      - key : "input"
      ▿ value : 15 elements
        ▿ 0 : 2 elements
          - key : "keywords"
          ▿ value : Optional<Any>
            - some : 0 elements
        ▿ 1 : 2 elements
          - key : "shippingFrom"
          ▿ value : Optional<Any>
            - some : "sadly "
        ▿ 2 : 2 elements
          - key : "title"
          ▿ value : Optional<Any>
            - some : "Xo1"
        ▿ 3 : 2 elements
          - key : "isPublic"
          ▿ value : Optional<Any>
            - some : true
        ▿ 4 : 2 elements
          - key : "tags"
          ▿ value : Optional<Any>
            - some : 0 elements { ... }
        ▿ 5 : 2 elements
          - key : "id"
          ▿ value : Optional<Any>
            - some : "3957E404-A2DE-4534-9F54-CB247D9B61C7"
        ▿ 6 : 2 elements
          - key : "markCount"
          - value : nil
        ▿ 7 : 2 elements
          - key : "rate"
          - value : nil
        ▿ 8 : 2 elements
          - key : "storeID"
          ▿ value : Optional<Any>
            - some : "1"
        ▿ 9 : 2 elements
          - key : "instruction"
          ▿ value : Optional<Any>
            - some : "Sdlfjslsjl"
        ▿ 10 : 2 elements
          - key : "createdAt"
          - value : nil
        ▿ 11 : 2 elements
          - key : "content"
          ▿ value : Optional<Any>
            - some : "Sdlfjslsjl"
        ▿ 12 : 2 elements
          - key : "price"
          ▿ value : Optional<Any>
            - some : 11.0
        ▿ 13 : 2 elements
          - key : "orderCount"
          - value : nil
        ▿ 14 : 2 elements
          - key : "likeCount"
          - value : nil
```
But run ```po post.userID ```  in console , It can print userID。

finally I got the error:
`
[Amplify.GraphQLError(message: "Variable \'input\' has coerced Null value for NonNull type \'ID!\'", locations: Optional([Amplify.GraphQLError.Location(line: 1, column: 24)]), path: nil, extensions: nil)]
`

***Post.swift***
```
public struct Post: Model {
  public let id: String
  public var title: String
  public var images: List<Image>?
  public var content: String
  public var link: String?
  public var tags: [String]?
  public var keywords: [String]?
  public var isPublic: Bool
  public var userInfo: UserInfo?
  public var comments: List<Comment>?
  public var likes: List<Like>?
  public var marks: List<Mark>?
  public var likeCount: Int?
  public var markCount: Int?
  public var commentCount: Int?
  public var createdAt: Temporal.DateTime?
  public var userID: String
}
```

**Comment by drochetti** [comment]
@springlo is `userID` part of your `schema.graphql` and also has a field definition in `Post+Schema.swift` (the generated file)? I'm asking because the `GraphQLRequest<Post>` is created based on the metadata in the `Post+Schema.swift` file, if you add it manually to your model ten it won't be there.

**Comment by springlo** [comment]
```
extension Post {
  // MARK: - CodingKeys 
   public enum CodingKeys: String, ModelKey {
    case id
    case title
    case images
    case content
    case link
    case tags
    case keywords
    case isPublic
    case userInfo
    case comments
    case likes
    case marks
    case likeCount
    case markCount
    case commentCount
    case createdAt
    case userID
  }
  
  public static let keys = CodingKeys.self
  //  MARK: - ModelSchema 
  
  public static let schema = defineSchema { model in
    let post = Post.keys
    
    model.authRules = [
      rule(allow: .owner, ownerField: "userID", identityClaim: "cognito:username", operations: [.create, .update, .delete, .read])
    ]
    
    model.pluralName = "Posts"
    
    model.fields(
      .id(),
      .field(post.title, is: .required, ofType: .string),
      .hasMany(post.images, is: .optional, ofType: Image.self, associatedWith: Image.keys.connectID),
      .field(post.content, is: .required, ofType: .string),
      .field(post.link, is: .optional, ofType: .string),
      .field(post.tags, is: .optional, ofType: .embeddedCollection(of: String.self)),
      .field(post.keywords, is: .optional, ofType: .embeddedCollection(of: String.self)),
      .field(post.isPublic, is: .required, ofType: .bool),
      .belongsTo(post.userInfo, is: .optional, ofType: UserInfo.self, targetName: "userID"),
      .hasMany(post.comments, is: .optional, ofType: Comment.self, associatedWith: Comment.keys.postID),
      .hasMany(post.likes, is: .optional, ofType: Like.self, associatedWith: Like.keys.postID),
      .hasMany(post.marks, is: .optional, ofType: Mark.self, associatedWith: Mark.keys.postID),
      .field(post.likeCount, is: .optional, ofType: .int),
      .field(post.markCount, is: .optional, ofType: .int),
      .field(post.commentCount, is: .optional, ofType: .int),
      .field(post.createdAt, is: .optional, ofType: .dateTime),
      .field(post.userID, is: .required, ofType: .string)
    )
    }
}
```

This is my `Post+Schema.swift`

**Comment by springlo** [comment]
I'm not sure if it was manually added by the back-end developer, I have to ask.

**Comment by drochetti** [comment]
> I'm not sure if it was manually added by the back-end developer, I have to ask.
> Wouldn’t it work if it was added manually?

@springlo the officially supported way is to rely on `schema.graphql` as the source of truth and update the models with `amplify codegen models`. Updating manually would work in case you do it correctly (i.e. update both `Post.swift` and `Post+Schema.swift` to reflect your backend) but they will always get overwritten once codegen kicks in.

That said, by looking at your `Post+Schema.swift` the `userID` is there but in the `build.variables` you shared I see a few properties that are not in your model, such as `shippingFrom`, `instruction`, `content` and a few others. I suspect something is out of sync there... have you tried cleaning the Xcode project and building again?

**Comment by springlo** [comment]
@drochetti , Sorry about that, that is the printed result of another object, the error is consistent.
You mean it should be fine if two files are added manually at the same time, right?

**Comment by drochetti** [comment]
@springlo

> Sorry about that, that is the printed result of another object, the error is consistent.

That's ok, can you update the issue with the correct output?

> You mean it should be fine if two files are added manually at the same time, right?

Like I said, it depends. You should really rely on `amplify codegen models` for generating the models based on your `schema.graphql`

**Comment by chenrui** [comment]
@drochetti 
This is our schema
`type Product @model @auth(rules: [{ allow: owner, ownerField: "userID", operations: [create, update, delete] }])
@key(name: "byStore", fields: ["storeID", "createdAt"])
@key(name: "byUser", fields: ["userID", "createdAt"])
{
  id: ID!
  userID: ID!
  storeID: ID!
  title: String!
  images: [Image] @connection(keyName: "byConnectID", fields: ["id"])
  content: String!
  instruction: String!
  price: Float!
  shippingFrom: String!
  tags: [String]!
  keywords: [String]
  isPublic: Boolean!

  userInfo: UserInfo @connection(fields: ["userID"])
  store: Store @connection(fields: ["storeID"])

  order: [OrderProduct] @connection(keyName: "byProduct", fields: ["id"]) 
  likes: [Like] @connection(keyName: "byPost", fields: ["id"])
  marks: [Mark] @connection(keyName: "byPost", fields: ["id"])

  likeCount: Int
  markCount: Int
  orderCount: Int

  rate: Float
  createdAt: AWSDateTime
}`

After `amplify codegen models`, why some fileds missed like storeID?

Product.swift
`// swiftlint:disable all
import Amplify
import Foundation

public struct Product: Model {
  public let id: String
  public var title: String
  public var images: List<Image>?
  public var content: String
  public var instruction: String
  public var price: Double
  public var shippingFrom: String
  public var tags: [String]?
  public var keywords: [String]?
  public var isPublic: Bool
  public var userInfo: UserInfo?
  public var store: Store?
  public var order: List<OrderProduct>?
  public var likes: List<Like>?
  public var marks: List<Mark>?
  public var likeCount: Int?
  public var markCount: Int?
  public var orderCount: Int?
  public var rate: Double?
  public var createdAt: Temporal.DateTime?
  public var userID: String?
  
  public init(id: String = UUID().uuidString,
      title: String,
      images: List<Image>? = [],
      content: String,
      instruction: String,
      price: Double,
      shippingFrom: String,
      tags: [String]? = [],
      keywords: [String]? = [],
      isPublic: Bool,
      userInfo: UserInfo? = nil,
      store: Store? = nil,
      order: List<OrderProduct>? = [],
      likes: List<Like>? = [],
      marks: List<Mark>? = [],
      likeCount: Int? = nil,
      markCount: Int? = nil,
      orderCount: Int? = nil,
      rate: Double? = nil,
      createdAt: Temporal.DateTime? = nil,
      userID: String? = nil) {
      self.id = id
      self.title = title
      self.images = images
      self.content = content
      self.instruction = instruction
      self.price = price
      self.shippingFrom = shippingFrom
      self.tags = tags
      self.keywords = keywords
      self.isPublic = isPublic
      self.userInfo = userInfo
      self.store = store
      self.order = order
      self.likes = likes
      self.marks = marks
      self.likeCount = likeCount
      self.markCount = markCount
      self.orderCount = orderCount
      self.rate = rate
      self.createdAt = createdAt
      self.userID = userID
  }
}`

Product+Schema.swift
`// swiftlint:disable all
import Amplify
import Foundation

extension Product {
  // MARK: - CodingKeys 
   public enum CodingKeys: String, ModelKey {
    case id
    case title
    case images
    case content
    case instruction
    case price
    case shippingFrom
    case tags
    case keywords
    case isPublic
    case userInfo
    case store
    case order
    case likes
    case marks
    case likeCount
    case markCount
    case orderCount
    case rate
    case createdAt
    case userID
  }
  
  public static let keys = CodingKeys.self
  //  MARK: - ModelSchema 
  
  public static let schema = defineSchema { model in
    let product = Product.keys
    
    model.authRules = [
      rule(allow: .owner, ownerField: "userID", identityClaim: "cognito:username", operations: [.create, .update, .delete])
    ]
    
    model.pluralName = "Products"
    
    model.fields(
      .id(),
      .field(product.title, is: .required, ofType: .string),
      .hasMany(product.images, is: .optional, ofType: Image.self, associatedWith: Image.keys.connectID),
      .field(product.content, is: .required, ofType: .string),
      .field(product.instruction, is: .required, ofType: .string),
      .field(product.price, is: .required, ofType: .double),
      .field(product.shippingFrom, is: .required, ofType: .string),
      .field(product.tags, is: .optional, ofType: .embeddedCollection(of: String.self)),
      .field(product.keywords, is: .optional, ofType: .embeddedCollection(of: String.self)),
      .field(product.isPublic, is: .required, ofType: .bool),
      .belongsTo(product.userInfo, is: .optional, ofType: UserInfo.self, targetName: "userID"),
      .belongsTo(product.store, is: .optional, ofType: Store.self, targetName: "storeID"),
      .hasMany(product.order, is: .optional, ofType: OrderProduct.self, associatedWith: OrderProduct.keys.product),
      .hasMany(product.likes, is: .optional, ofType: Like.self, associatedWith: Like.keys.postID),
      .hasMany(product.marks, is: .optional, ofType: Mark.self, associatedWith: Mark.keys.postID),
      .field(product.likeCount, is: .optional, ofType: .int),
      .field(product.markCount, is: .optional, ofType: .int),
      .field(product.orderCount, is: .optional, ofType: .int),
      .field(product.rate, is: .optional, ofType: .double),
      .field(product.createdAt, is: .optional, ofType: .dateTime),
      .field(product.userID, is: .optional, ofType: .string)
    )
    }
}`

**Comment by springlo** [comment]
Thank you for your prompt reply. I also passed `userInfo` into Model, and now it can be created successfully. If only `userID` is passed in, an error will be reported.
And I don't know why.
```
type Post @model
@auth(rules: [
  { allow: owner, ownerField: "userID" },
  { allow: private, operations: [read] },
  { allow: public, operations: [read] }
])
@key(name: "byUser", fields: ["userID", "createdAt"])
{
  id: ID!
  userID: ID!
  title: String!
  images: [Image] @connection(keyName: "byConnectID", fields: ["id"])
  content: String!
  link: String
  tags: [String]!
  keywords: [String]
  isPublic: Boolean!
  userInfo: UserInfo @connection(fields: ["userID"])
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
  likes: [Like] @connection(keyName: "byPost", fields: ["id"])
  marks: [Mark] @connection(keyName: "byPost", fields: ["id"])

  likeCount: Int
  markCount: Int
  commentCount: Int

  createdAt: AWSDateTime
}
```

**Comment by drochetti** [comment]
@springlo 

> After amplify codegen models, why some filed was missed like storeID?

When creating models, the redundant fields are omitted. The `storeID` field you declared explicitly is the key used to connect `Product` to `Store`. Therefore, `product.storeID` is `product.store.id`.

What I don't understand is why in the case of `User`, it created both `userInfo` and `userID`. I would expect `userID` not to be there, so you rely on connecting the models `User` and `Product` instead of managing the keys yourself.

This might be a bug in the codegen and we'll need to investigate.

**Comment by brennanMKE** [comment]
@springlo I've been looking into this issue. Can you tell me if this is still happening. You said this "sometime occurs" which makes me think it could be a sporadic problem and that could be caused by async work and a weak reference which is losing the values needed to do this work. Without seeing more of the code it is hard to know for sure.

Could you let me know if this is still happening and if you have updated to the latest Amplify versions? Thanks!

Also, I expect as I send this message is out your workday is starting in China. I will check this issue later for your reply. And maybe we can chat on our Discord server to work this out.
