### ISSUE TITLE
Pinpoint Analytics - Custom Event does not display/register under the Events Filter

### ISSUE THREAD

**Issue by tony-attia** [aws-amplify/amplify-ios#841]
**Describe the bug**

Following the [Amplify Analytics Docs](https://docs.amplify.aws/lib/analytics/record/q/platform/ios), the record event call executes but does not reflect in the Pinpoint dashboard; i.e. the custom event does not appear under the Event Filters, as if there was no record call at all. I tried attaching the `AmazonMobileAnalyticsFullAccess` policy to the IAM user, as well as adding Analytics to the Cognito User Pool, but to no avail.

**To Reproduce**

1. Set up the Analytics backend [as per the documentation](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/ios#set-up-analytics-backend).
2. Call `Amplify.Analytics.record()` with a `BasicAnalyticsEvent` var.

**Expected behavior**

The new custom event should be displayed under the Event Filters after calling `Amplify.Analytics.record()`.

**Environment:**
 - Amplify Framework Version: [e.g. 0.10.0]
 - Dependency Manager: Cocoapods
 - Swift Version  Unspecified

**Device Information:**
 - Device: Simulator; iPhone 11 Pro Max
 - iOS Version: iOS 13.1

**Comment by diegocstn** [comment]
Hi @tony-attia,
thanks for reaching out.

To clarify, are you seeing any change in Pinpoint dashboard "Event count" value?
If one or more events have been successfully recorded and sent, the "Event count" value should reflect that almost immediately but you might experience some delay in seeing that change in the "Event filter".

Also to verify that events are being captured and sent to Pinpoint as expected you can temporarily update the log level to `.debug` and initialize logging to your Xcode console using the following code in your main entry point file (_AppDelegate.swift_ or _App.swift_ in case of a SwiftUI app):
```
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
AWSDDLog.sharedInstance.logLevel = .debug
```
After generating some events and leaving the app in background for 5 seconds you should be able to see in Xcode console something along the lines of

`Successfully put events to server--response code: 202. accepted: XX; retryable: 0; dirty: 0`

where _XX_ is the number of events sent.

Can you also review the [Pinpoint Quotas](https://docs.aws.amazon.com/pinpoint/latest/developerguide/quotas.html) to see if any of these may be preventing your events from being recorded?

**Comment by tony-attia** [comment]
Thanks for getting back to me @diegocstn!

> To clarify, are you seeing any change in Pinpoint dashboard "Event count" value?

Not with the custom event, though it appears there is an issue with the event call.

> Also to verify that events are being captured and sent to Pinpoint as expected you can temporarily update the log level to .debug 

Thanks, that helped clear things up:
```
2020-10-26 16:07:51:155 QeepemDev[55596:1077218] Response body:
{"message":"User: arn:aws:sts::577636870619:assumed-role/us-east-1_HXRGEmd6Q-appuserGroupRole/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:PutEvents on resource: arn:aws:mobiletargeting:us-east-1:577636870619:apps/a173d26da14140238f36623b351029f8/events"}
2020-10-26 16:07:51:156 QeepemDev[55596:1077218] PutEvents Error: [Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain Code=0 "AccessDeniedException" UserInfo={responseStatusCode=403, message=User: arn:aws:sts::577636870619:assumed-role/us-east-1_HXRGEmd6Q-appuserGroupRole/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:PutEvents on resource: arn:aws:mobiletargeting:us-east-1:577636870619:apps/a173d26da14140238f36623b351029f8/events, responseHeaders=<CFBasicHash 0x600000f2d2c0 [0x7fff8062d750]>{type = immutable dict, count = 12,
entries =>
	0 : Content-Type = <CFString 0x6000014f40f0 [0x7fff8062d750]>{contents = "application/json"}
	1 : Access-Control-Allow-Origin = *
	2 : X-Amz-Cf-Id = <CFString 0x600003971d60 [0x7fff8062d750]>{contents = "my0v0G_NoQZ-SgIk7cxaVx2G1-T7OZIVsPf-gNCBkMcse_HRBFs7MA=="}
	3 : x-amzn-ErrorType = <CFString 0x6000014ec5a0 [0x7fff8062d750]>{contents = "AccessDeniedException"}
	5 : Via = <CFString 0x600003e60420 [0x7fff8062d750]>{contents = "1.1 69e952c7b08727f752b5559b0b6d2109.cloudfront.net (CloudFront)"}
	7 : X-Amz-Cf-Pop = IAD66-C1
	12 : x-amz-apigw-id = <CFString 0x6000014a3c90 [0x7fff8062d750]>{contents = "VCPnoEPLoAMF_Hg="}
	13 : Date = <CFString 0x6000014f8ae0 [0x7fff8062d750]>{contents = "Mon, 26 Oct 2020 20:07:51 GMT"}
	15 : Content-Length = 283
	17 : Connection = <CFString 0x600001a396a0 [0x7fff8062d750]>{contents = "keep-alive"}
	19 : x-amzn-RequestId = <CFString 0x600000f56880 [0x7fff8062d750]>{contents = "7c25a2bb-ba5f-4356-b009-c0f56c86692d"}
	22 : X-Cache = <CFString 0x6000014b74e0 [0x7fff8062d750]>{contents = "Error from cloudfront"}
}
, responseDataSize=283, NSLocalizedFailureReason=AccessDeniedException}]
2020-10-26 16:07:51:164 QeepemDev[55596:1077218] Unable to successfully deliver events to server. Events will be retried. Error Message:Error Domain=com.amazonaws.AWSPinpointTargetingErrorDomain Code=0 "AccessDeniedException" UserInfo={responseStatusCode=403, message=User: arn:aws:sts::577636870619:assumed-role/us-east-1_HXRGEmd6Q-appuserGroupRole/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:PutEvents on resource: arn:aws:mobiletargeting:us-east-1:577636870619:apps/a173d26da14140238f36623b351029f8/events, responseHeaders=<CFBasicHash 0x600000f2d2c0 [0x7fff8062d750]>{type = immutable dict, count = 12,
entries =>
	0 : Content-Type = <CFString 0x6000014f40f0 [0x7fff8062d750]>{contents = "application/json"}
	1 : Access-Control-Allow-Origin = *
	2 : X-Amz-Cf-Id = <CFString 0x600003971d60 [0x7fff8062d750]>{contents = "my0v0G_NoQZ-SgIk7cxaVx2G1-T7OZIVsPf-gNCBkMcse_HRBFs7MA=="}
	3 : x-amzn-ErrorType = <CFString 0x6000014ec5a0 [0x7fff8062d750]>{contents = "AccessDeniedException"}
	5 : Via = <CFString 0x600003e60420 [0x7fff8062d750]>{contents = "1.1 69e952c7b08727f752b5559b0b6d2109.cloudfront.net (CloudFront)"}
	7 : X-Amz-Cf-Pop = IAD66-C1
	12 : x-amz-apigw-id = <CFString 0x6000014a3c90 [0x7fff8062d750]>{contents = "VCPnoEPLoAMF_Hg="}
	13 : Date = <CFString 0x6000014f8ae0 [0x7fff8062d750]>{contents = "Mon, 26 Oct 2020 20:07:51 GMT"}
	15 : Content-Length = 283
	17 : Connection = <CFString 0x600001a396a0 [0x7fff8062d750]>{contents = "keep-alive"}
	19 : x-amzn-RequestId = <CFString 0x600000f56880 [0x7fff8062d750]>{contents = "7c25a2bb-ba5f-4356-b009-c0f56c86692d"}
	22 : X-Cache = <CFString 0x6000014b74e0 [0x7fff8062d750]>{contents = "Error from cloudfront"}
}
, responseDataSize=283, NSLocalizedFailureReason=AccessDeniedException}
```

I checked the respective Pinpoint Cognito role (the same one as the lambda function's `LambdaExecutionRole`) and it contains Full Access to Mobile Analytics and Pinpoint, so I'm not sure why it's getting Access Denied.

> Can you also review the Pinpoint Quotas to see if any of these may be preventing your events from being recorded?

The quotas are at the default value so I believe it's the aforementioned Cognito permission issue at play here.

**Comment by drochetti** [comment]
> I checked the respective Pinpoint Cognito role (the same one as the lambda application's LambdaExecutionRole) and it contains Full Access to Mobile Analytics and Pinpoint, so I'm not sure why it's getting Access Denied.

@tony-attia can you confirm whether you created your backend using `amplify add analytics` or not? I want to check if the backend was provisioned through Amplify or manually. Also, do you have both the Analytics and the Auth plugins setup? The [Amplify setup docs](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/ios#set-up-analytics-backend) have more details about it.

**Comment by tony-attia** [comment]
> @tony-attia can you confirm whether you created your backend using amplify add analytics or not? I want to check if the backend was provisioned through Amplify or manually. Also, do you have both the Analytics and the Auth plugins setup? The Amplify setup docs have more details about it.

Yes, I followed the documentation and set it up accordingly, so the backend was created using `amplify add analytics` and both the Analytics and Auth plugins are set up.

**Comment by diegocstn** [comment]
@tony-attia can you please verify that both `CognitoUnauthPolicy` and `CognitoAuthPolicy` policies are correctly listed and both grant access to `mobiletargeting:PutEvents` in  `amplify/backend/analytics/[YOUR_APP_NAME]/pinpoint-cloudformation.json`?

**Comment by tony-attia** [comment]
@diegocstn They are indeed listed and grant access to `mobiletargeting:PutEvents`, as well as `mobiletargeting:UpdateEndpoint` and `mobiletargeting:GetUserEndpoints`.

**Comment by diegocstn** [comment]
@tony-attia thanks for double-checking. Do you mind sharing both your `awsconfiguration.json` and  `amplifyconfiguration.json` redacted of any sensitive information (i.e. appId, cognito poolId)?

**Comment by tony-attia** [comment]
@diegocstn Sure thing - 

`awsconfiguration.json`:
```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "REDACTED",
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "REDACTED",
            "AppClientId": "REDACTED",
            "AppClientSecret": "REDACTED",
            "Region": "us-east-1"
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    },
    "S3TransferUtility": {
        "Default": {
            "Bucket": "REDACTED",
            "Region": "us-east-1"
        }
    },
    "AppSync": {
        "Default": {
            "ApiUrl": "REDACTED",
            "Region": "us-east-1",
            "AuthMode": "AMAZON_COGNITO_USER_POOLS",
            "ClientDatabasePrefix": "REDACTED_AMAZON_COGNITO_USER_POOLS"
        }
    },
    "PinpointAnalytics": {
        "Default": {
            "AppId": "REDACTED",
            "Region": "us-east-1"
        }
    },
    "PinpointTargeting": {
        "Default": {
            "Region": "us-east-1"
        }
    }
}
```

`amplifyconfiguration.json`:
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "spendleeenveapi": {
                    "endpointType": "GraphQL",
                    "endpoint": "REDACTED",
                    "region": "us-east-1",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "REDACTED",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "REDACTED",
                        "AppClientId": "REDACTED",
                        "AppClientSecret": "REDACTED",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "REDACTED",
                        "Region": "us-east-1"
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "REDACTED",
                        "Region": "us-east-1",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "REDACTED_AMAZON_COGNITO_USER_POOLS"
                    }
                },
                "PinpointAnalytics": {
                    "Default": {
                        "AppId": "REDACTED",
                        "Region": "us-east-1"
                    }
                },
                "PinpointTargeting": {
                    "Default": {
                        "Region": "us-east-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "REDACTED",
                "region": "us-east-1",
                "defaultAccessLevel": "guest"
            }
        }
    },
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "REDACTED",
                    "region": "us-east-1"
                },
                "pinpointTargeting": {
                    "region": "us-east-1"
                }
            }
        }
    }
}
```

**Comment by diegocstn** [comment]
@tony-attia do you mind verify a few things on the AWS console?
1. Please check that two IAM roles "_-unauthRole_" and "_-authrole_" have been created and both have a pinpoint policy attached like the following
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint",
                "mobiletargeting:GetUserEndpoints"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:*:XXX:apps/YYY*"
            ],
            "Effect": "Allow"
        }
    ]
}
```
where _YYY_ is the Pinpoint project ID (visible under _Pinpoint > All projects > _YOURAPP_ > Settings > General settings_)

2. the Cognito identity pool have the "Enable access to unauthenticated identities" flag on (_Cognito > _YOURIDPOOL_ > Edit identity pool > Unauthenticated identities_)
