### ISSUE TITLE
Not possible to call Api Gateway REST-API as guest

### ISSUE THREAD

**Issue by chris-mds** [aws-amplify/amplify-ios#870]
**Describe the bug**
I want to call a REST-API from API-Gateway, before I am logged in. So I updated the auth category and added guest access. 
Now I want to call my REST-API but I get an error:

`APIError: Failed to retrieve Cognito UserPool token.
Caused by:
AuthError: There is no user signed in to retreive cognito tokens
Recovery suggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession`

Of course I am not logged in, because I am still in guest state.
How can I call my REST-API?

**To Reproduce**
1. Create REST-API in API Gateway
2. Enable guest mode in Auth
3. Try to call the API

**Expected behavior**
Call API's in guest mode

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.3.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 14

**Comment by lawmicha** [comment]
Hi @chris-mds, based on your `amplifyconfiguration.json`, the auth type configured will assign different types of interceptors for the request. If you have set the user pool auth type then it will attempt to retrieve the token and throw the AuthError if no user is signed in. If you set it to IAM then it will sign the request for unauth access. Let us know if this is applicable in your case. To further debug, could you provide us 
- steps you took to create the REST-API in API Gateway, did you hand roll the amplifyconfiguration.json or was it generated by amplify CLI? 
- How did you enable guest mode in Auth?
- what does your amplifyconfiguration.json look like? please redact any sensitive information like actual endpoint or auth keys

**Comment by chris-mds** [comment]
Oh boy, yes I changed from UserPools to IAM and forgot to set it in my amplifyconfiguration.json . Now it works!
Thank you!
