### ISSUE TITLE
AWS Predictions (AWSPredictionsService) Index out of Range due to Emojis

### ISSUE THREAD

**Issue by enteleca** [aws-amplify/amplify-ios#873]
**Describe the bug**

AWS Predictions (text comprehend) crashes when passing in a string of text that contains specific emojis. I am pretty sure this is because some of these emojis count for 1 character but when getting the endIndex swift will return 1 more than the count.

The particular emoji I am referring to is one:👇🏽. This increases the string character count `theString.count` by 1 but when taking `theString.endIndex`, it will return 2. I am sure there are many other emojis with the same issue as well. It may have to do with the different colors that are selectable with the emojis, but I am uncertain.

The crash happens around line 140 in the file "AWSPredictionsService+Comprehend.swift" when we try to define the endIndex `let endIndex = text.index(text.startIndex, offsetBy: endOffset)`.

I have implemented a temporary guard bandaid to skip the syntax if the endIndex is out of range, but whenever there is time to fix this, the issue is there. I have a feeling that putting the emoji in the middle of a longer string may also mess up the indexes of the words that are interpreted and return inaccurate strings of the key phrases of the string, but I have not tested this.

**To Reproduce**
1. Create a string with 👇🏽 at the end of the string.
2. Pass into Amplify.Predictions.interpret()
3. Crash occurs.

**Expected behavior**
No crash and accurate interpretation of string returned.

**Screenshots**
Unnecessary.

Thank you for the great platform otherwise!

**Comment by wooj2** [comment]
PR was approved, pending push into the main branch, and also pending release.

**Comment by palpatim** [comment]
Released in [1.5.1](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.5.1)
