### ISSUE TITLE
Amplify Auth Subscriptions Clarification

### ISSUE THREAD

**Issue by obrian33** [aws-amplify/amplify-ios#879]
Reading through the documentation found at this link: https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/ios

I call a subscription like so: subscription = Amplify.API.subscribe(request: **.subscription(of: Todo.self, type: .onCreate)**)

However, having the @auth directive results in a "Not Authorized Exception". So I switched over to using this other function
subscription = Amplify.API.subscribe(request: **.subscription(to: Todo.self, subscriptionType: .onCreate, ownerId: "ownerID")**) where I can provide the ownerID. But then I get an error saying "Validation error of type FieldUndefined" for fields:  _version, _lastChangedAt, _deleted. 

My schema is as so:

type Todo @model
  @auth(rules: [
    {
        allow: owner,
        operations: [create, update, delete, read]
    }
])
  {
  id: ID!
  content: String
}

Is the second function the correct one to use? If so how do I add the missing fields that are being asked for? 

Environment:

Amplify Framework Version: 1.1.1

Dependency Manager: Cocoapods

Swift Version : 5.0

Device Information:

Device: iPhone 11 Pro Simulator (13.3)

**Comment by drochetti** [comment]
Hey @obrian33, the message your shared:

> But then I get an error saying "Validation error of type FieldUndefined" for fields: _version, _lastChangedAt, _deleted.

Indicates me you have a DataStore-enabled backend, but you're trying to interact directly with the backend. In that case you will need to manage the metadata fields AppSync use for distributed data sync. Take a look at this and let me know if it's helpful: https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/ios#writing-data-from-the-appsync-console

**Comment by obrian33** [comment]
@drochetti That was helpful but I don't think I'm using the DataStore because the functions I'm using are in Amplify.API vs. Amplify.DataStore. I might have a misunderstanding on my approach but what I was trying to accomplish was that a user has a collection of Todos and if a new Todo is added for that user by someone else the subscription would push it to the user and they would see it. In order to accomplish this would I need the DataStore?

**Comment by drochetti** [comment]
> @drochetti That was helpful but I don't think I'm using the DataStore because the functions I'm using are in Amplify.API vs. Amplify.DataStore. I might have a misunderstanding on my approach but what I was trying to accomplish was that a user has a collection of Todos and if a new Todo is added for that user by someone else the subscription would push it to the user and they would see it. In order to accomplish this would I need the DataStore?

The fact that your error message contains `_version`, `_lastChangedAt` and `_deleted` tells me your backend has **conflict resolution enabled**, which is something DataStore uses to control the distributed data. If that was intentional, then you need to refer to that link and make sure you include those fields in your GraphQL operations, otherwise you can use the CLI to update you backend: `amplify update api` and then `Disable DataStore for entire API`.

**Comment by obrian33** [comment]
@drochetti Gotcha! I do remember enabling that. I tried to disable it but it didn't work so then I tried your first approach and added what is needed for the DataStore (_version, _lastChangedAt, _deleted). After a few missteps on my part, I finally managed to get it working! Thank you so so much :)
