### ISSUE TITLE
Update operations doesn't sync to cloud anymore after enabling auth

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-ios#887]
**Describe the bug**
Everything worked great. Then I enabled auth by adding
`@auth(rules: [{ allow: owner }])`
to every type is my schema and updating the api (see below). Now, after properly logging in, everything seems to work again, except update operations. They succeed locally, but I cannot see them in the cloud. Create, read and delete sync as expected.
Again, before switching to auth with Cognito User Pool, I was using API Key and everything worked fine.

**To Reproduce**
Set up a project with api like so:

$ amplify update api
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Walkthrough all configurations
? Choose the default authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project.
? Do you want to configure advanced settings for the GraphQL API Yes, I want to make some additional changes.
? Configure additional auth types? No
? Configure conflict detection? Yes
? Select the default resolution strategy Auto Merge
? Do you want to override default per model settings? No

Finally:
$ amplify push

The datatype looks like so:
type SomeType @model @auth(rules: [{ allow: owner }])
{
  id: ID!
  remarks: String
 .
 .
 .
}

Now insert some items and observe that they're also being created in the cloud. Now pick an item and update, say, the `remarks` field. The changes will succeed locally, however, in cloud the old version remains.

**Expected behavior**
Update operations, that succeed locally, should be synced to the cloud.

**Environment(please complete the following information):**
 - Amplify Framework Version: Amplify (1.4.0)
 - Dependency Manager: Cocoapods
 - Swift Version : Xcode 12.1.

CHECKOUT OPTIONS:
  Amplify:
    :commit: 732f7e72afbd3b4451ddd0a1c5ea426c40de6572
    :git: https://github.com/aws-amplify/amplify-ios.git
  AmplifyPlugins:
    :commit: 732f7e72afbd3b4451ddd0a1c5ea426c40de6572
    :git: https://github.com/aws-amplify/amplify-ios.git
  AWSPluginsCore:
    :commit: 732f7e72afbd3b4451ddd0a1c5ea426c40de6572
    :git: https://github.com/aws-amplify/amplify-ios.git

**Device Information (please complete the following information):**
 - Device: iPhone6S+, Simulator
 - iOS Version: iOS 14

**Comment by wooj2** [comment]
Hi @anatomybook ,

Sorry to hear you are having trouble issuing updates on your model.

Are you attempting to update a record that was created when you were using API Key (which will not have an owner field), or, are you attempting to update a record that was created by the user that was signed in?

**Comment by anatomybook** [comment]
Hello @wooj2 ,

thanks for your quick reply.

The record I'm trying to update has an owner field. I've created this record with the new auth in place and I can confirm that the right owner field is present. Additionally, I've removed the App and reinstalled it. After authenticating, it did read all the data from the cloud as it's supposed to. I can also delete items. Just updating doesn't work.

**Comment by wooj2** [comment]
Hi @anatomybook

I tried very hard to reproduce the setup you have, but was unable to reproduce what you're seeing.  In each of my cases, I was able to update mutations and see updates in the associated dynamo table.

Here is my thought process:
A.  The instructions you posted with regards to enabling conflict resolution look good.
B.  Setting up "Amazon Cognito User Pools" as the default authorization type also look good.
C.  Your schema also looks very similar to mine as well:
```
type ScenarioATest1Post @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  title: String!
}
```
D.  The code I'm using to add an instance of `ScenarioATest1Post` looks like:
```
var counter = 0
@objc func didTapMakeMutation(_ sender: UIButton) {
    counter += 1
    let post = ScenarioATest1Post(title: "post\(counter)")
    Amplify.DataStore.save(post) {
        switch $0 {
        case .success:
            print("saved post:\(post)")
        case .failure(let error):
            print("error on save:\(error)")
        }
    }
}
```
E.  In my example, updating the first queryable instance of this ScenarioATest1Post, looks like this:
```
@objc func didTapUpdateMutation(_ sender: UIButton) {
    Amplify.DataStore.query(ScenarioATest1Post.self) {
        switch $0 {
        case .success(let result):
            var foundPost: ScenarioATest1Post? = nil
            for post in result {
                if !post.title.contains("updated") {
                    foundPost = post
                    break;
                }
            }
            guard var postToUpdate = foundPost else {
                print("unable to find a post that was not updated")
                return
            }
            let lastTitle = postToUpdate.title
            postToUpdate.title = "\(lastTitle) was updated!"

            Amplify.DataStore.save(postToUpdate, completion: {result in
                switch(result) {
                case .success:
                    print("Success in Updating")
                case .failure(let error):
                    print("failed with error: \(error)")

                }
            })

        case .failure(let error):
            print("Error on query() for type Post - \(error.localizedDescription)")
        }
    }
}
```

A couple questions:
1.  Does the code for adding an instance look similar to your code?
2.  Does the code for updating an instance look similar to your code?
3.  What version of the Amplify CLI are you using?  To find this out, you can issue the command `amplify --version`
4.  Are you calling `clear()`, and then `query()` after a user logs in?  Currently there is no coordination between the Amplify's Auth category and Amplify's DataStore category.  In the future, we will be provide functions like start()/stop() to control starting and stopping of the sync engine.  Until then (if your use case allows for it) it is advised to call `clear()`, and then `query()` after a user logs in, in order to restart the sync engine.  More details can be found in this comment: https://github.com/aws-amplify/amplify-ios/issues/886#issuecomment-726431121
5.  Finally, you may be running into an instability/regression we found with our 1.4.0 release, which makes the sync engine unstable when a subscription fails.  This can easily happen when a user starts the application and the user is not signed in.  This issue was fixed in 1.4.3 -- perhaps you can try to upgrade to this version and see if this resolves your issue?

**Comment by anatomybook** [comment]
Hello @wooj2 ,

thanks for your response.

As far as I can tell, my code looks similar. I did extract the smallest possible app to reproduce the failures. You can find it here: [https://github.com/anatomybook/reproduce_failure_to_update](url)
But first things first: Here are the answers to your questions:
1. I believe so.
2. I believe so.
3. 4.30.0
4. Yes, I did call clear() as well as query(). Please see below, I'll provide the sequence to reproduce the failures to update
5. I just ran to update and the problem still persists:
CHECKOUT OPTIONS:
  Amplify:
    :commit: 732f7e72afbd3b4451ddd0a1c5ea426c40de6572
    :git: https://github.com/aws-amplify/amplify-ios.git
  AmplifyPlugins:
    :commit: 732f7e72afbd3b4451ddd0a1c5ea426c40de6572
    :git: https://github.com/aws-amplify/amplify-ios.git
  AWSPluginsCore:
    :commit: 732f7e72afbd3b4451ddd0a1c5ea426c40de6572
    :git: https://github.com/aws-amplify/amplify-ios.git

### Here is the command line that I used to set everything up from scratch:

```
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project AwsTester
? Enter a name for the environment debugone
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building ios
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
```

```
$ amplify add auth
Using service: Cognito, provided by: awscloudformation
 
 The current configured provider is Amazon Cognito. 
 
 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections. 
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
Successfully added auth resource awstester_xyz locally
```

```
$ amplify add api
Scanning for plugins...
Plugin scan successful
? Please select from one of the below mentioned services: GraphQL
? Provide API name: debugupdate
? Choose the default authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project.
? Do you want to configure advanced settings for the GraphQL API Yes, I want to make some additional changes.
? Configure additional auth types? No
? Configure conflict detection? Yes
? Select the default resolution strategy Auto Merge

```

The schema is in the repository.

```
$ amplify push
   │   Update available {currentVersion} → {latestVersion}    │
   │              Run {updateCommand} to update               │

✔ Successfully pulled backend environment debugone from the cloud.

Current Environment: debugone

| Category | Resource name     | Operation | Provider plugin   |
| -------- | ----------------- | --------- | ----------------- |
| Auth     | awstester_xyz | Create    | awscloudformation |
| Api      | debugupdate       | Create    | awscloudformation |

? Are you sure you want to continue? Yes

GraphQL schema compiled successfully.

Edit your schema at /Users/ben/Documents/20201114_AwsTester/AwsTester/amplify/backend/api/debugupdate/schema.graphql or place .graphql files in a directory at /Users/ben/Documents/20201114_AwsTester/AwsTester/amplify/backend/api/debugupdate/schema
? Do you want to generate code for your newly created GraphQL API Yes
? Enter the file name pattern of graphql queries, mutations and subscriptions graphql/**/*.graphql
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code API.swift
 Updating resources in the cloud. This may take a few minutes...
```

Side note: The update message still contains the variable names `{currentVersion}, {latestVersion}, {updateCommand}` not the contents.

### Steps to reproduce with the app in the repository, I linked above:
1. Make create a user and log in
2. Either erase app and reinstall or use clear button - I tried both - makes no difference
3. Create a Buyer object (3rd button from top in section "BUYER STUFF"). This will:
    a) create an object
    b) put it in the database
    c) set it as main object for GUI to read from
4. Update the buyer (4th button from the top in section "BUYER STUFF"). This will:
    a) do the update as expected
    b) so far, so good
5. Click refresh buyer (last button). This will:
   a) Merely re-read the previously created object via query() by ID
   b) set it as main object for GUI to read from
6. Go to step 4) - _the update will fail, i.e. not be visible in the database_
   a) **that's what throws me off. I have no idea why this is**

7. There's another update routine, more closely related to your suggestion. That's button "update buyer remarks". This will also fail
8. You may restart the app. In this case, choose the top-most button "load buyer..." to load buyer objects and take the first for the GUI. Whatever I tried from this point, as soon as the GUI object gets replaced from the original that was put directly after buyer creation, no more updating.
9. Deletion works
10. Start over as needed...

Summary: As soon as the central buyer object is reloaded after being created, updates stop working. Only when the central buyer object is set directly after creation, updates work.

Please let me know, if this makes sense and/or whether you need any more information. I've been braining about this for a while and I don't get it. On the other hand I'm new to Swift and App programming. Maybe I'm missing the obvious. Any hints are highly appreciated.

Thank you!

**Comment by wooj2** [comment]
Hi @anatomybook

Thank you so much for taking the time to give us a sample example!  I compiled the code in the repository you provided into a new amplify project, but unfortunately was unable to reproduce the issue you are seeing.

Each time I clicked the "update buyer" button, I was able to see the update being persisted in the remote dynamo table.  To verify that the record was being updated, I observed that the `version` field of the record was incrementing each time I clicked the "update buyer" button.  Similarly, the same behavior existed with "update buyer remarks".

As far as what might be wrong:
1.  It could be the version of the Amplify CLI you are running.  I believe we made a number of changes to support owner based @auth in the CLI, so I highly recommend you use the latest version.  I am running version 4.32.1.  To update to the latest version, you should be able to run the following command:
```
npm install -g @aws-amplify/cli@latest
```
After updating the CLI, you'll want to regenerate the graph ql schema (`amplify api gql-compile`) and update the generated code (`amplify codegen models`), and push your changes to the backend (`amplify push`).

2.  With regards to the version of the amplify-iOS library, can you verify that you are running, at least version 1.4.3?  The SHA1 commits you sent reference 1.4.0, which is known to have instabilities with the sync engine.

Best of luck!

**Comment by anatomybook** [comment]
Hello @wooj2,

thanks you very much for your advice. 
My problem seems to be fixed. I'm now running with amplify:
CHECKOUT OPTIONS:
  Amplify:
    :commit: 70970d27040b99fedf1b1458fcc27ce242572dd4
    :git: https://github.com/aws-amplify/amplify-ios.git
  AmplifyPlugins:
    :commit: 70970d27040b99fedf1b1458fcc27ce242572dd4
    :git: https://github.com/aws-amplify/amplify-ios.git
  AWSPluginsCore:
    :commit: 70970d27040b99fedf1b1458fcc27ce242572dd4
    :git: https://github.com/aws-amplify/amplify-ios.git

and the latest CLI 4.32.1.

I don't know which of the two fixed it, but it's works. Thanks again.
