### ISSUE TITLE
Amplify Hosted WEB-UI SignIn/SignUp call throws error randomly

### ISSUE THREAD

**Issue by mashhoodqazi93** [aws-amplify/amplify-ios#893]
I am using Amplify library for social SignIn/SignUp with *Cognito Hosted WEB-UI* in  iOS and Android applications. We are using *Swift UI* for development.

**Describe the bug**
Some times, when a new user tries to signin using Facebook or apple, he receives an error, when user tries again (second time), the flow works fine. The issue is happening on iOS and Android both platforms randomly. 

**AWS FUNCTION USED TO SIGNIN/SIGNUP:**

*SWIFT (iOS):*
``` swift
_ = Amplify.Auth.signInWithWebUI(for: type, presentationAnchor: window!) { result in
                DispatchQueue.main.async {
                    switch result {
                    case .success:
                        self.userID = userId
                        completion(true)
                        
                    case .failure(let error):
                        NotificationBanner.show(error.errorDescription)
                        completion(false)
                    }
                }
            } 
```		
*KOTLIN (Android):*
 ``` kotlin
 Amplify.Auth.signInWithSocialWebUI(
            provider,
            activity,
            {
                callback.onSignInSuccess(result = it, loginType = loginType)
            },
            {
                callback.onAuthError(exception = it)
            }
        )
```

**Error from Amplify**
```
AuthError: Unexpected error occurred with message: An unknown error occurred

Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:

file: /Users/syed.zain/Desktop/parcelx-ios/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift

function: recoverySuggestion

line: 79

Caused by:

Error Domain=com.apple.SafariServices.Authentication Code=1 "(null)"
```

**To Reproduce**
This error shows up randomly but frequently (QA team faced it 3 to 4 times in a day) and we are unable to find the exact pattern of occurrence.

**Environment(please complete the following information):**
 - Amplify (1.3.2):
 - Amplify/Default (= 1.3.2)
 - Amplify/Default (1.3.2)
 - AmplifyPlugins/AWSCognitoAuthPlugin (1.3.2):
 - AWSAuthCore (~> 2.17.0)
 - AWSCognitoIdentityProvider (~> 2.17.0)
 - AWSCognitoIdentityProviderASF (~> 2.17.0)
 - AWSCore (~> 2.17.0)
 - AWSMobileClient (~> 2.17.0)
 - AWSPluginsCore (= 1.3.2)
 - Dependency Manager:  Cocoapods, Swift Package Manager
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: Tested on iPhone 6S, iPhone 11 
 - iOS Version: Tested on 13.6, 14.0, 14.2

**Comment by royjit** [comment]
Hi @mashhoodqazi93 

"Error Domain=com.apple.SafariServices.Authentication Code=1 "(null)" is thrown when you cancel the the webUI. - https://developer.apple.com/documentation/safariservices/sfauthenticationerror/sfauthenticationerror/canceledlogin

If you like to take action based on the error, you can do the following:

```swift
                if case AuthError.unknown(_, let underlyingError) = error,
                   case .canceledLogin = (underlyingError as? SFAuthenticationError)?.code {
                   print("Take action")
                }
```
