### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ios#90]
We need to support Swift Package Manager as a distribution mechanism for Amplify and bundled plugins.

**Comment by rodrigoelp** [comment]
Given Apple is moving towards a swift world and swift package manager is the way to go, I think this support is more than necessary.

**Comment by nikhil-dabhade** [comment]
@palpatim @rodrigoelp I agree with the input here. Have added this to the product roadmap. Will update this thread when we have it prioritized.

**Comment by AugustDev** [comment]
Any progress on this?

**Comment by farshadtx** [comment]
Is this new feature going to simplify the release?
Distributing Binary Frameworks as Swift Packages

**Comment by rodrigoelp** [comment]
It should as binary components can be included and distributed with your package.

**Comment by jfahrenkrug** [comment]
I'd love to see this implemented as well. I'd be happy to help. Are there specific issues that have been a roadblock to it in the past?

**Comment by rodrigoelp** [comment]
> I'd love to see this implemented as well. I'd be happy to help. Are there specific issues that have been a roadblock to it in the past?

The one most likely to be the issue is the fact that implify was implemented on node, making it hard to migrate over by just including a few files and what not. Ideally, implify spm should be a self-contained package, just like GraphQL Apollo's client (Ellen put an amazing work to migrate and rewrite quite a lot of their CLI in pure swift to maintain a SPM totally clean... ish).

Step one to achieve this would be to write some of these in bash or some sort of shell/swift script. That means the code generators, connectors to AWS and what not. An alternative is to not link everything with implify... Effectively turn the client into a pure client you need to provide the endpoint and credentials to suck down the schema and generate the classes/structs/types of it.

**Comment by drochetti** [comment]
We are currently investigating Swift Package Manager support. Amplify uses some of the AWS SDKs so there's quite a bit of surface area to cover.

Although I have no ETA, we're actively working on this and I'll keep this issue updated with the status.

**Comment by CarbnJacob** [comment]
+1

**Comment by jodafm** [comment]
+1

**Comment by mregnauld** [comment]
So, any update on this?
I personally need need the support for:

- API Gateway
- Cognito
- S3

**Comment by toftof** [comment]
Any ETA?

**Comment by jacobsapps** [comment]
Hey, do you have an approx. timeline for this? Next week, next month, next quarter, 2021, 2022+? 

I'm using the main services given by Amplify:

- Amplify
- AWSCognitoAuthPlugin
- AWSAPIPlugin
- AWSDataStorePlugin
- AWSS3StoragePlugin

**Comment by AugustDev** [comment]
Need this asap.

**Comment by lemonbitsapp** [comment]
hello, when will this be available?

**Comment by palpatim** [comment]
Hi folks, thanks for your interest in this. We're actively working on supporting Swift Package Manager, but don't have an ETA to report just yet. We'll update this ticket as soon as we have information.

**Comment by codeslubber** [comment]
Wow this sucks, this whole platform is shooting itself in the face, showing all the signs of low competition lardass syndrome.

**Comment by gevartosky** [comment]
Any ETA on having some sort of beta so we can start testing with SPM on our side?
Firebase started and stopped but at least there are some beta branches to test.
Dropping Carthage means we are stuck with awful cocoapods 🤦🏻‍♂️

**Comment by toftof** [comment]
Hello looks like the entire cosmos is waiting for this. Any update? when can we have SPM support.

**Comment by lemonbitsapp** [comment]
can support carthage at least? cocoapods is dated. we can live with carthage while waiting for apm support

**Comment by faisalalt** [comment]
Will this be supported soon? Any updates?

**Comment by atomichades** [comment]
We could really use this - looking at a use case at the moment that this would be perfect for!

**Comment by gevartosky** [comment]
+1

**Comment by Ignelios** [comment]
+1

**Comment by tedgonzalez** [comment]
+1

**Comment by cbscd** [comment]
We have chosen another service due to the lack of support for this, because we are against cocoa cocoapods.

**Comment by mregnauld** [comment]
@cbscd Which service did you choose? Just curious.

**Comment by El-Fitz** [comment]
There appears to be a recent PR here https://github.com/aws-amplify/amplify-ios/pull/1123#issue-598385261
Haven't tested it though

**Comment by cbscd** [comment]
> @cbscd Which service did you choose? Just curious.

@El-Fitz, we chose Firebase but I’m not very happy with it.

**Comment by palpatim** [comment]
Amplify iOS (except for the predictions category) can now be installed via Swift Package Manager. See the [README](https://github.com/aws-amplify/amplify-ios/blob/main/README.md) for full details. (#1146)

**Comment by brightfuture** [comment]
thanks for the hard work 👏🏻

**Comment by El-Fitz** [comment]
Awesome, thank you!

**Comment by lemonbitsapp** [comment]
i would like to thank the team here. worth the wait. 👌

**Comment by gevartosky** [comment]
❤️❤️❤️❤️

**Comment by 3m** [comment]
Thanks so much much for the hard work to make this happen

**Comment by palpatim** [comment]
Since we haven't heard any technical errors related to this, I'm going to close out this issue now. If you encounter any problems using SPM that aren't covered in the [README](https://github.com/aws-amplify/amplify-ios/blob/main/README.md), please file a new issue and refer to this issue for context.
