### ISSUE TITLE
How to handle custom errors from API Gateway / Lambda - REST

### ISSUE THREAD

**Issue by chris-mds** [aws-amplify/amplify-ios#900]
**Is your feature request related to a problem? Please describe.**
Use Case: We are using Lambda functions for creating PDF documents on runtime and by request. For example the user selects in our app start and end date, and our Lambda fetches all data which was created between this timestamps and creates the PDF with the data.
Now there is the possibility, that the timeframe between the two timestamps the user has selected, doesn't contain any dataset, so we want to throw a custom error with e.g. "No dataset found, please change start or and date".

We tried different things, but doesn't get it working.

On our lambda:

Attempt 1
`return {
            'headers': { "Content-Type": "application/json" },
            'statusCode': 550,
            'body': json.dumps('No entries found')}`

Attempt 2
`return {
            "errorMessage" : "No Entries found",
            "httpStatus" : 550
        }`

Attempt 3

`raise Exception("[NoEntry] No dataset found, please change start or and date")`

For our selected status code, we also changed the response headers in API Gateway.

No the problem in our iOS-App is, that we cant catch this custom error.

`
//make the request with start and end date in the body
Amplify.API.post(request: request) { event in
            switch event{
            case.failure(let error): print(error); completion(.failure(.failedLoadingPDF))
            case .success(let data):
                //Cast and convert the data to a pdf document
                guard let response = try? JSONSerialization.jsonObject(with: data, options: []),
                      let jsonResponse = response as? [String:Any],
                      let body = jsonResponse["body"] as? String,
                      let pdfData = Data(base64Encoded: body,options: .ignoreUnknownCharacters),
                      let pdfDocument = PDFDocument(data: pdfData)
                else { completion(.failure(. failedLoadingPDF));return }
                completion(.success(pdfDocument))
            }
        }
`

When we set the errors like Attempt 1 & 2 (with returns), we got a successful response from Lambda, even with status code 500
When we set the errors like Attempt 3, we cant get the error message from the response error type.

Is there any approach / documentation, how to handle this?

**Comment by lawmicha** [comment]
Hi @chris-mds,

formatting the code block (triple backticks)
```swift
//make the request with start and end date in the body
Amplify.API.post(request: request) { event in
    switch event{
    case.failure(let error):
        print(error);
        completion(.failure(.failedLoadingPDF))
    case .success(let data):
    //Cast and convert the data to a pdf document
        guard let response = try? JSONSerialization.jsonObject(with: data, options: []),
              let jsonResponse = response as? [String:Any],
              let body = jsonResponse["body"] as? String,
              let pdfData = Data(base64Encoded: body,options: .ignoreUnknownCharacters),
              let pdfDocument = PDFDocument(data: pdfData) else {
            completion(.failure(. failedLoadingPDF));
            return
        }
        completion(.success(pdfDocument))
    }
}
```

I'm not too familiar with how the lambdas lifecycle work, however for Attempt 3, could you clarify if the Amplify.API call is getting a `event` back at all? or is APIGateway not returning a response payload at all? If APIGateway is not returning when you raise the Exception then there's not much the client can do, if there is a response, then we can narrow down how the cient is handling it.

I would suggest turning it into a `return` like Attempt 1 and 2 as a 400 "Bad Request" status code for your "No dataset found, please change start or and date" error

**Comment by chris-mds** [comment]
Hi @lawmicha ,

We finally get it to throw an error, here for example with StatusCode 550.
Now the problem is, that we can't access the message, which is contained in the error response. The APIError class contains an public enum case named "httpStatusError". We need to access this, but don't know how.
<img width="659" alt="amplifyError" src="https://user-images.githubusercontent.com/71610076/100587428-d6125e80-32f0-11eb-8727-40a7b1933b18.png">

Our config is now the following:

Lambda:
![lambda](https://user-images.githubusercontent.com/71610076/100587070-64d2ab80-32f0-11eb-86d1-99e24c221473.png)

API Gateway
![apiGateway_1](https://user-images.githubusercontent.com/71610076/100587448-dc083f80-32f0-11eb-92b5-2dbd5573040a.png)
![apiGateway_2](https://user-images.githubusercontent.com/71610076/100587449-dca0d600-32f0-11eb-89cd-567699391d1c.png)

We tested it with Postman and got successfully an error with its message.
![postman](https://user-images.githubusercontent.com/71610076/100587565-04903980-32f1-11eb-9fb7-f89ce619476d.png)


I am very sure that we can access this message also, when we know how to get into this httpStatusError from your APIError class. But how?

**Comment by royjit** [comment]
Hi @chris-mds 

Does this work for you?

```swift
Amplify.API.get(request: request) { event in
            switch event {
            case .success(let data):
                  // Success
            case .failure(let error):
                guard case let .httpStatusError(statusCode, _) = error else {
                    // Got error
                    return
                }
            }
        }
```

**Comment by chris-mds** [comment]
Hi @royjit ,

Yes this does the trick. Now we can access our own http error codes!

Thank you

**Comment by iThink32** [comment]
@royjit @chris-mds i understood the status code part but how do we get the error description? I get the correct status code the message is always 
```
APIError: The HTTP response status code is [400].
Recovery suggestion: The metadata associated with the response is contained in the HTTPURLResponse.
For more information on HTTP status codes, take a look at
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
0 elements
```
