### ISSUE TITLE
Field missing from model when used in a @connection

### ISSUE THREAD

**Issue by EdwardFinegan** [aws-amplify/amplify-ios#923]
We are using the following schema, but when we generate the models the groupID is not being created in the generated code for the Member model? Our understanding is this should be the field that is used to reference the Group in the connection. Whats going on here, and why is the groupID missing? Is this a bug?

```
type Member @model
@key(
    name: "getMemberGroupID"
    fields: ["groupID"]
    queryField: "getMemberByGroupID"
)
{
  id: ID!
  groupID: ID!
  group: Group @connection (fields: ["groupID"])
}

type Group @model
{
    id: ID!
    members: [Member] @connection(keyName: "getMemberGroupID", fields: ["id"])
}
```

Member.swift:

```
// swiftlint:disable all
import Amplify
import Foundation

public struct Member: Model {
  public let id: String
  public var group: Group?
  
  public init(id: String = UUID().uuidString,
      group: Group? = nil) {
      self.id = id
      self.group = group
  }
}
```

Member+Schema.swift:

```
// swiftlint:disable all
import Amplify
import Foundation

extension Member {
  // MARK: - CodingKeys 
   public enum CodingKeys: String, ModelKey {
    case id
    case group
  }
  
  public static let keys = CodingKeys.self
  //  MARK: - ModelSchema 
  
  public static let schema = defineSchema { model in
    let member = Member.keys
    
    model.pluralName = "Members"
    
    model.fields(
      .id(),
      .belongsTo(member.group, is: .optional, ofType: Group.self, targetName: "groupID")
    )
    }
}
```

Group.swift:

```
// swiftlint:disable all
import Amplify
import Foundation

public struct Group: Model {
  public let id: String
  public var members: List<Member>?
  
  public init(id: String = UUID().uuidString,
      members: List<Member>? = []) {
      self.id = id
      self.members = members
  }
}
```

Group+Schema.swift:

```
// swiftlint:disable all
import Amplify
import Foundation

extension Group {
  // MARK: - CodingKeys 
   public enum CodingKeys: String, ModelKey {
    case id
    case members
  }
  
  public static let keys = CodingKeys.self
  //  MARK: - ModelSchema 
  
  public static let schema = defineSchema { model in
    let group = Group.keys
    
    model.pluralName = "Groups"
    
    model.fields(
      .id(),
      .hasMany(group.members, is: .optional, ofType: Member.self, associatedWith: Member.keys.group)
    )
    }
}

```

  - Amplify (1.4.4):
    - Amplify/Default (= 1.4.4)
  - Amplify/Default (1.4.4)
  - AmplifyPlugins/AWSAPIPlugin (1.4.4):
    - AppSyncRealTimeClient (~> 1.4.0)
    - AWSCore (~> 2.19.0)
    - AWSPluginsCore (= 1.4.4)
    - ReachabilitySwift (~> 5.0.0)
  - AppSyncRealTimeClient (1.4.2):
    - Starscream (~> 3.1.0)
  - AWSAuthCore (2.19.1):
    - AWSCore (= 2.19.1)
  - AWSCognitoIdentityProvider (2.19.1):
    - AWSCognitoIdentityProviderASF (= 2.19.1)
    - AWSCore (= 2.19.1)
  - AWSCognitoIdentityProviderASF (2.19.1)
  - AWSCore (2.19.1)
  - AWSMobileClient (2.19.1):
    - AWSAuthCore (= 2.19.1)
    - AWSCognitoIdentityProvider (= 2.19.1)
    - AWSCognitoIdentityProviderASF (= 2.19.1)
    - AWSCore (= 2.19.1)
  - AWSPluginsCore (1.4.4):
    - Amplify (= 1.4.4)
    - AWSCore (~> 2.19.0)
    - AWSMobileClient (~> 2.19.0)
  - ReachabilitySwift (5.0.0)
  - Starscream (3.1.1)

**Comment by lawmicha** [comment]
Hi @EdwardFinegan, the `groupID` field is omitted from the swift Member Model and is managed for you at runtime using the group object passed into the Member object. For example
```swift
let group = Group()
Amplify.API.mutate(request: .create(group)) // Persist the group first
// on mutation complete, create the member with the group
let member = Member(group: group)
Amplify.API.mutate(request: .create(member))
```
Internally, `Amplify.API.mutate(request: .create(member))` will use the targetName "groupID" in the schema swift class to generate the correct GraphQL Input as
```
{
"groupID": "groupI123" // group.id
}
```

I recall there's a [PR in progress](https://github.com/aws-amplify/amplify-ios/pull/885) that fixes your scenario when querying a list of Members by `groupID`:
```swift
// This will fail
let predicate = Member.keys.group.eq("memberId123")
Amplify.API.query(request: .list(Member.self, where: predicate))
```

Feel free to let us know if you have more questions

**Comment by EdwardFinegan** [comment]
Thanks for the clarification. When the connection is defined as:
`group: Group @connection (fields: ["groupID"])
`
Can the 'fields: ["groupID"]' parameter be omitted? The documentation seems to suggest it can be but what ramifications does this have on your above example?

**Comment by lawmicha** [comment]
From what I can tell, it's better to keep the explicit field like `groupID` on the Member Model and referencing it on the `@connection` as `fields: ["groupID"]` so that you can perform a list operation for members by groupID. 

Under "Alternative definition" https://docs.amplify.aws/cli/graphql-transformer/connection#many-to-many-connections
```
The above definition is the recommended way to create relationships between model types in your API. This involves defining index structures using @key and connection resolvers using @connection. There is an older parameterization of @connection that creates indices and connection resolvers that is still functional for backwards compatibility reasons. It is recommended to use @key and the new @connection via the fields argument.
```

If you remove the `fields` from `@connection` directive, i actually think you'll be using the older usage of the directive. If you consider this AppSync API
```
listMembers(filter: {groupID: {eq: "groupID123"}})
```

Without the explicit field, you would not be able filter on groupID
