### ISSUE TITLE
Deleting a parent in datastore doesn't delete the children from remote, only locally

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-ios#933]
**Describe the bug**

In DataStore category, if you have a connected model such as `Blog` and `Post` where a `Post` belongs to a `Blog` and a `Blog` has several `Post`s if a `Blog` instance is deleted, all the children `Post` instances are deleted in the local datastore, however these children remove Mutations are not sent to appsync. 

Since appsync itself doesn’t reinforce foreign key constraints, the orphaned items (Posts) will stay in the server and when a new device tries to sync it will result in a `Foreign Key Constraint error` while saving these orphaned `Post`s since their `BlogId` doesn't exist in the `Blog` table. 

This cannot be resolved until the customer delete such orphans from the server, no workaround that I am aware of.

**To Reproduce**
1. Create model schema for `Post` and a `Blog` where a post belongs to a Blog.
2. Save a new blog and several posts for that blog.
3. Delete the new blog and see that all the posts are deleted from the local datastore.
4. **Issue** -> The delete mutations for `Post` are not sent to appsync and so posts are never removed from the remote server. `publisher` doesn't send any notifications for post deletions either.
5. Sync this schema to a new device and turn on `verbose` logging. Observe the foreign key constraint errors in the logs.

**Expected behavior**
Expect publisher to send events for children who are getting cascade deleted and send mutations for them to appsync

**Additional context**
Android issue for the same bug https://github.com/aws-amplify/amplify-android/issues/1013

**Comment by Amplifiyer** [comment]
Still an issue. Leaving a comment to avoid auto-close

**Comment by wooj2** [comment]
Code has been merged to main branch.  Setting to pending release.  This fix should be released in our next version of amplify-ios.

**Comment by ruiguoamz** [comment]
Code has been release as part of Amplify 1.5.4. Closing this issue
