### ISSUE TITLE
Sign in with Web UI locks up app when user taps outside safari modal (iOS)

### ISSUE THREAD

**Issue by petermauger** [aws-amplify/amplify-ios#936]
**Describe the bug**
Our app uses signInWithWebUI to authenticate our users in Amplify iOS. On the iPad the web UI is presented as a modal dialog with the app becoming shaded in the background. If the user taps the Cancel button on the top-left of the dialog all functions as normal. If the user taps OUTSIDE the dialog window instead (ie on the shaded area of the app) then the dialog is dismissed however all user interaction with the app is blocked.

**To Reproduce**
1. Initialise Amplify iOS project with Auth
2. Trigger signInWithWebUI to display the safari based login process
3. Tap outside of the safari login dialog window (it should dismiss)
4. Attempt to interact with any part of the app UI (you can't)

**Expected behavior**
After being dismissed by tapping outside the sign in dialog the user should be able to continue to interact with the app without force quitting it 

**Screenshots**
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-12-04 at 07 35 58](https://user-images.githubusercontent.com/32285042/101101933-c1410e00-3603-11eb-9870-8d7c8be8f98c.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.4.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Device: iPad Simulators and Devices
 - iOS Version: iOS 14
 - Specific to simulators: No

**Additional context**
The problem is caused by an additional UIView that is pushed onto the navstack prior to the signIn Web UI dialog being displayed. This is dismissed in the completion handler for awsMobileClient.showSignIn however that completion isn't triggered when the user taps outside the dialog to dismiss it. That view (which is transparent and has no controls) has isUserInteractionEnabled = true and it therefore intercepts all taps (and does nothing). Either set the 'empty' view isUserInteractionEnabled = false (what we're doing as a workaround at the moment) or ensure it is properly dismissed, or maybe find a way not to add that seemingly unnecessary view in the first place?

Pods/AmplifyPlugins/AWSCognitoAuthPlugin/AuthenticationProviderAdapter+SignIn.swift lines 136-155:

        // Create a navigation controller with an empty UIViewController.        <- why is this needed???
        let navController = UINavigationController(rootViewController: UIViewController())
        navController.isNavigationBarHidden = true
        navController.modalPresentationStyle = .overCurrentContext

        // Get top most view controller to present a navController
        var parentViewController = window.rootViewController
        while (parentViewController?.presentedViewController) != nil {
            parentViewController = parentViewController?.presentedViewController
        }

        parentViewController?.present(navController, animated: false, completion: {

            self.awsMobileClient.showSignIn(navigationController: navController,
                                            signInUIOptions: SignInUIOptions(),
                                            hostedUIOptions: hostedUIOptions) { [weak self] state, error in

                DispatchQueue.main.async {
                    navController.dismiss(animated: false) {.     // <- this is not called when the user taps outside the dialog

**Comment by ruiguoamz** [comment]
The PR was merged in and is pending release!

**Comment by royjit** [comment]
The fix is released in 1.5.2, please take a look https://github.com/aws-amplify/amplify-ios/releases/tag/1.5.2
