### ISSUE TITLE
Amplify.Auth.signInWithWebUI : Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred

### ISSUE THREAD

**Issue by ravikanhasoft** [aws-amplify/amplify-ios#943]
**Describe the bug**
Using `Amplify.Auth.signInWithWebUI` i am trying to sign in with google and apple but i am facing an issue with this output.
I am using manual configure json file with the help of this link **[Use existing AWS resources](https://docs.amplify.aws/lib/auth/existing-resources/q/platform/ios)** . 

Here I am providing information about google sign in, unfortunately, sign in with apple having the same issue. 

Here is my `amplifyconfiguration.json`
![amplifyconfiguration](https://user-images.githubusercontent.com/29453207/101234435-36d0db00-36e5-11eb-9343-934658ca4b02.png)

**To Reproduce**
1. execute below code

```
 Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: self.view.window!) { result in
               switch result {
               case .success:
                   print("Sign in succeeded")
               case .failure(let error):
                   print("Sign in failed \(error)")
               }
           }
```

2. it will open prompt in iOS app for login with google sign in UI. After put email and password it automatically close the popup and goes into failer block.
             ```
                   case .failure(let error):
                   print("Sign in failed \(error)")
               ```

3. And this error will print into logs. See error

> _Sign in failed AuthError: Unexpected error occurred with message: An unknown error occurred
> Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
> file: /Users/ravi/Documents/AWSCognito/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
> function: recoverySuggestion
> line: 79
> Caused by:
> Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=0 "(null)" UserInfo={error=invalid_client}_
> 

**Expected behavior**
it should sign in successfully and goes into success block.

**Screenshots**
![screen1](https://user-images.githubusercontent.com/29453207/101234323-413ea500-36e4-11eb-8820-78045c4762fe.png)
![screen2](https://user-images.githubusercontent.com/29453207/101234321-3e43b480-36e4-11eb-8a11-49bcef9b5749.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 8 Plus simulator, iPhone 7plus real device
 - iOS Version: 14
 - Specific to simulators:

**Comment by ruiguoamz** [comment]
Hi, @ravikanhasoft.

Thanks for reaching out.

I guess this is caused by an CLI issue that just got fixed. From the screenshot of `amplifyconfiguration.json` you provided, I noticed the `AppClientSecret` is missing. The correct info should look like:

```json
"CognitoUserPool": {
    "Default": {
        "PoolId": "us-west-2_***",
        "AppClientId": "***",
        "AppClientSecret": "***",
        "Region": "us-west-2"
    }
},
```
You can add it back in your `amplifyconfiguration.json` file, the AppClientSecret can be found in your AWS Cognito User Pool console.

Also, remember to run `npm install -g @aws-amplify/cli@latest` to get the latest CLI version to download the fix.

If this doesn't fix your issue, please reach out again. Thanks!

**Comment by ravikanhasoft** [comment]
It seems like there was an issue with `Scopes`. As I change my `Scopes` in `amplifyconfiguration.json` with only single `email`. And then i have tried with goolge and apple sign in and both platform working fine. 
It looks like this 

```
                 "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "*********************.us-east-1.amazoncognito.com",
                            "AppClientId": "**********************",
                            "SignInRedirectURI": "appname://",
                            "SignOutRedirectURI": "appname://",
                            "Scopes": [
                                "email"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
```
So I am closing this issue now.

**Comment by smithton7330** [comment]
I have a same probelm with you.
could you share your code?
