### ISSUE TITLE
Auth + API + DataStore - AWSClient.getTokens() deadlock

### ISSUE THREAD

**Issue by petermauger** [aws-amplify/amplify-ios#948]
**Describe the bug**
On app launch we need to determine the user's authentication state so we utilise fetchAuthSession. Randomly (with about 1/5 - 1/10 frequency) this check doesn't call the completion block. This leaves our app (which requires the user to be authenticated) with an infinite spinning loading screen that requires them to force-quit and relaunch the app.

**To Reproduce**
We cannot reliably reproduce this fault as it appears to be a race condition between our call to fetchAuthSession and the RemoteSyncEngine calling the same function (to initialise subscriptions). These two calls (when the bug occurs) result in two threads in our iOS app both blocked in the AWSMobileClient.getTokens(...) on self.tokenFetchLock.wait() (line 788 in AWSMobileClient/AWSMobileClientExtensions.swift).

**Expected behavior**
Semaphore deadlocks in AWSMobileClient.getTokens(...) don't occur.

**Screenshots**
This screenshot is our Xcode debugging session when the problem occurs. Unfortunately it doesn't capture the second (separate) thread that is also locked on self.tokenFetchLock.wait() however you can see the two threads that have called AWSClient.getTokens() and their call stacks. Thread 7 is from RemoteSyncEngine and I believe Thread 9 is how our call to fetchAuthSession() is handled asynchronously.
![Screen Shot 2020-12-04 at 12 41 16 pm](https://user-images.githubusercontent.com/32285042/101331640-3dab4980-38af-11eb-8d5b-00d6731c4fc6.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.4.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Device: iPad simulators and devices
 - iOS Version: iOS 13 and iOS 14
 - Specific to simulators: No

**Additional context**
There is no obvious means of triggering the race condition. It happens on app launch and completely at random. The only way for our users to resolve this issue is to force-quit and restart our app (because we require them to have an auth session to use the app)

**Comment by petermauger** [comment]
Should note that we're using Cognito User Pools for authentication that are using OpenIDConnector to an Azure AD instance.

**Comment by petermauger** [comment]
I believe it only occurs when the user has already got a valid token (ie is signed into the app and has their token cached in keychain)

**Comment by spenceps** [comment]
I'm getting something similar. I'm just using email/password auth with Cognito. It's a little hard to reproduce too but it does freeze the app. What I've done that is mostly successful to mitigate the problem is throttle my requests so that only 20 or so are happening at the same time. 

<img width="799" alt="FeezeCS" src="https://user-images.githubusercontent.com/5713863/102253908-31ce1180-3ec5-11eb-9837-4bb111ee424e.png">

![FreezeSS](https://user-images.githubusercontent.com/5713863/102253928-372b5c00-3ec5-11eb-8d29-71acea84cbe2.jpg)

**Comment by ruiguoamz** [comment]
Hi @petermauger and @spenceps 
I was not able to have it reproduced

Are there further details you remember to help me? Like which two methods you call at the same time that might cause the issue?

**Comment by petermauger** [comment]
The occurrence is completely random. I can have a run of many times starting the app with no problems and then 1 or more deadlocks. We can't predict it or reproduce it ourselves. We are only triggering the call to Amplify.Auth.fetchAuthSession once. The other call that is causing the deadlock appears to be coming from DataStore's attempts to sync. When those two calls 'line up' we get the deadlock

**Comment by petermauger** [comment]
I've discussed with the Amplify.iOS team that we need to be able to control when the sync starts (ie after we've authenticated our users so we don't get this deadlock). If that could be prioritised it would give us at least a workaround...

**Comment by ruiguoamz** [comment]
Ya, you can try the suggested workaround see if you can avoid the deadlock.

See [1.5.0 release note](https://github.com/aws-amplify/amplify-ios/releases?after=v1.5.1-unstable.6), the `start` and `stop` were released recently and [usage ](https://docs.amplify.aws/lib/datastore/other-methods/q/platform/ios#clear)
