### ISSUE TITLE
Fetch user attributes not working with Sign In With Apple

### ISSUE THREAD

**Issue by eax32** [aws-amplify/amplify-ios#953]
**Describe the bug**
Amplify returns something like: 
failure(AuthError: Access Token does not have required scopes
Recovery suggestion: Check whether the given values are correct and the user is authorized to perform the operation.)

**To Reproduce**
```
        let options = AuthWebUISignInRequest.Options(scopes: ["openid", "email", "profile"])

        Amplify.Auth.signInWithWebUI(for: .apple, presentationAnchor: UIApplication.shared.windows.last!, options: options) { result in
            switch result {
            case .success:
                print("Sign in succeeded")
                Amplify.Auth.fetchUserAttributes { (result) in
                    print(result)
                }
                break

            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }
```

We can get user info by calling AWSMobileClient.default().getTokens and parse token, but it's not cool.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: All Devices
 - iOS Version: 13.5, 14.2

**Comment by royjit** [comment]
Hi,

You need to provide the scope `aws.cognito.signin.user.admin` when you signIn to fetch the user attributes.
