### ISSUE TITLE
Can I force all my data to sync using AWS Amplify?

### ISSUE THREAD

**Issue by KatsuShooter** [aws-amplify/amplify-ios#955]
Hi! I have an app where I can import some data from other sources, so I need to sync this data to the cloud and handle it in real-time on other devices. But the amount of this data can reach 1000 records, so it syncs one-by-one and it's quite long.

Can I push all this data to the cloud immediately and listen to changes in real-time on other devices? Maybe there is a way to force a sync?

**Comment by palpatim** [comment]
Are you asking for both the mutation (updating data into the backend) and the subscription (delivering data from the backend) to have batch payloads? Also, are you talking about Amplify API, or DataStore?

**Comment by KatsuShooter** [comment]
Yes, DataStore

**Comment by ruiguoamz** [comment]
Hi, @KatsuShooter 

Are you asking something like a batch sync (call a method once to sync everything instead of calling a method 1000 times)?

**Comment by KatsuShooter** [comment]
Yes

**Comment by ruiguoamz** [comment]
Hi, Sorry for the late reply. We don't have an api to do that, even if we have a `DataStore.batchSave()` it would just be calling `DataStore.save()` many times internally. Just wondering, in your app, is calling `DataStore.save()` multiple time not a good experience?
