### ISSUE TITLE
Auth signOut after webUI signIn does not clear browser previous user id

### ISSUE THREAD

**Issue by shikhilnuwal** [aws-amplify/amplify-ios#958]
**Describe the bug**
 Amplify.Auth.signOut() does not clear the previously used id. This will not allow the user to sign in again with another user.

**To Reproduce**
1. SignIn using Amplify.Auth.signInWithWebUI
2. After successful signIn, signout the user by Amplify.Auth.signOut
3. Now try to signIn again using Amplify.Auth.signInWithWebUI.
4. The user is not presented a signIn screen, Amplify automatically sign in the user with the previous user's account.

**Expected behavior**
 After signOut Amplify.Auth.signInWithWebUI should work as a fresh start.

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Comment by palpatim** [comment]
See https://github.com/aws-amplify/amplify-ios/issues/964 for additional detail

**Comment by ravikanhasoft** [comment]
@palpatim  @shikhilnuwal  Is there any solution you find on this?

**Comment by shikhilnuwal** [comment]
> @palpatim @shikhilnuwal Is there any solution you found on this?

No. Waiting for Amplify team to respond.

**Comment by royjit** [comment]
Hi @shikhilnuwal 

Are you using a social provider to signIn in HostedUI? We do not have control on the session if you are signing through other social providers like Apple, Google, FB etc.

**Comment by petermauger** [comment]
If you go into General Settings app -> Safari you can clear the cache. This will clear the sign in
