### ISSUE TITLE
Auth signOut calls completion before the SafariViewController is completely dismissed

### ISSUE THREAD

**Issue by gevartosky** [aws-amplify/amplify-ios#959]
**Describe the bug**
Right after the completion for `Amplify.Auth.signOut` is called, the top view controller is still SFAuthenticationViewController

**To Reproduce**
1. Put a breakpoint on the `Amplify.Auth.signOut` completion
2. Check for presenting view controller
3. See that its still SF View controller

**Expected behavior**
Execute the `Amplify.Auth.signOut` completion after SFAuthenticationViewController is completely dismissed

**Screenshots**
![image](https://user-images.githubusercontent.com/5980943/101778207-52b3f280-3ad2-11eb-95df-c1d35fd377e1.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.4.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 12+

**Comment by royjit** [comment]
Hi,

This seems like the behavior of SFAuthenticationSession, the callback of `SFAuthenticationSession` is called before dismissing the authentication controller. We will see if we can work around it and delay the Amplify callback.

**Comment by markfraserr** [comment]
Hey @royjit , 
I'm working on the same project as Greg on the Android side and we are experiencing the same problem. onSuccess is being triggered immediately after signOut is called - wiping the users data on the app but leaving a valid session if they cancel.

Is there a way we could relay this same enhancement to the Android team for investigation? Thanks.

**Comment by royjit** [comment]
Hi @markfraserr 

Can you please raise the issue in the Android repo, the issue there might be different - https://github.com/aws-amplify/amplify-android

@gevartosky  Can you please give us the use case or any issue that arise due to the signOut callback getting called before the SFAuthenticationSession is completely dismissed? If we know the issue we might be able to help better.

**Comment by gevartosky** [comment]
Hi @royjit 

We try to redirect the user to another screen after logout. Some times the redirecting does not work because the presenting view controller is still the Safari view controller instead of the app view hierarchy.

**Comment by didia** [comment]
We had the same issue. What we ended up doing on our side was adding a 1 sec delay before executing our callback. Is there a way for the library to check if the SFAuthenticationSession is completely dismissed before calling the callback ? Or maybe the delay could be handled by the library.

**Comment by palpatim** [comment]
Unfortunately this is not something we'll be able to address for iOS 12 and below--the completion APIs are invoked before the view controller is actually dismissed, and so your delay workaround (or one similar to it) are the only option we can see.

We are investigating to see whether ASWebAuthenticationSession has the same behavior, and will update this ticket when we have more info.

**Comment by royjit** [comment]
I tested this out with `ASWebAuthenticationSession` as well using the following code and the same issue exists :

```
AWSMobileClient.default().showSignIn(presentationAnchor: self.navigationController!.view.window!,
                                        hostedUIOptions: hostedUIOptions!) { (userState, error) in
                                        }
```


```
AWSMobileClient.default().signOut(presentationAnchor: self.view.window!) {(error) in
   
}

//
po self.topMostController()
▿ Optional<UIViewController>
  - some : <SFAuthenticationViewController: 0x7f837b01f800>

```

**Comment by royjit** [comment]
Fixing this inside the library by adding a delay would require a lot of assumptions about the host app's current UI setup. Also we cannot guarantee that it would work in the future iterations of ASWebAuthenticationSession. To be on the safer side and to support wider range of UI scenarios, we are marking this as `wont fix` and would recommend customers to add a delay if they want to do any UI related task in the callback.
