### ISSUE TITLE
Hitting "Cancel" on the system prompt puts the app on an intermediate state

### ISSUE THREAD

**Issue by gevartosky** [aws-amplify/amplify-ios#966]
**Describe the bug**
After calling `Amplify.Auth.signOut { result in` and having the system prompt presented, if the user hit Cancel, the app gets in a state where if you call `Amplify.Auth.signInWithWebUI` you get an error message saying you are already signed in, but if you call `Amplify.Auth.getCurrentUser()` you get `nil`. This makes the app present screens that it's not supposed to or prevent's the user to access places it should have access since he logged in.

**To Reproduce**
1. SignIn
2. Call SignOut but hit Cancel instead
3. Navigate out of a restricted area
4. Try to return to a restricted are
5. The app won't allow it because `Amplify.Auth.getCurrentUser()` returns nil
6. The app will automatically call `Amplify.Auth.signInWithWebUI` but it will fail with an error saying the user is already logged in

**Screenshots**
![image](https://user-images.githubusercontent.com/5980943/101926625-312a3800-3bb2-11eb-857e-1b4ee455775e.png)

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.4.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.2

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 12+

**Comment by palpatim** [comment]
I could have sworn we had an open issue on this, but I can't find one.

**Comment by royjit** [comment]
Hi @gevartosky 

We fixed this in the underlying SDK, please refer this issue https://github.com/aws-amplify/aws-sdk-ios/issues/2886 . Are you seeing this issue in the latest library of Amplify?

**Comment by gevartosky** [comment]
oh thank you @royjit  🙏🏻 Updating the SDK seems to have fixed the issue
