### ISSUE TITLE
Amplify.Auth.signInWithWebUI - Remove Confirmation PopUp While Sign in With Google/FaceBook 

### ISSUE THREAD

**Issue by shikhilnuwal** [aws-amplify/amplify-ios#969]
**Describe the bug**
Is there any way to get rid of these popup and sent user silently to login page of Google/Facebook ?

**To Reproduce**
1. Call the method `Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: self.view.window!) `
2. A popup is presented to "App want to use amazoncognito to Sign in" before opening google sign in UI

**Expected behavior**
Should directly open the google sign in UI

**Screenshots**
<img width="470" alt="Untitled" src="https://user-images.githubusercontent.com/13962237/102105426-6a360700-3e55-11eb-9174-ecc69e3772b3.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Comment by ruiguoamz** [comment]
Hi, @shikhilnuwal 
Thanks for reaching out. 

So, the `signInWithWebUI` calls `SFAuthenticationSession` at some point (see [here](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCognitoAuth/AWSCognitoAuth.m#L266)), the behavior is designed by Apple. 

See this [StackOverflow link](https://stackoverflow.com/questions/47536258/why-does-sfauthenticationsession-prompt-for-consent-every-time) and [Apple link](https://developer.apple.com/documentation/safariservices/sfauthenticationsession)

We don't actually have control over the asking of PopUp. Hope this answers your question

**Comment by shikhilnuwal** [comment]
> Hi, @shikhilnuwal
> Thanks for reaching out.
> 
> So, the `signInWithWebUI` calls `SFAuthenticationSession` at some point (see [here](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCognitoAuth/AWSCognitoAuth.m#L266)), the behavior is designed by Apple.
> 
> See this [StackOverflow link](https://stackoverflow.com/questions/47536258/why-does-sfauthenticationsession-prompt-for-consent-every-time) and [Apple link](https://developer.apple.com/documentation/safariservices/sfauthenticationsession)
> 
> We don't actually have control over the asking of PopUp. Hope this answers your question

Thanks @ruiguoamz .
