### ISSUE TITLE
API request signature is generated prior to URL encoding

### ISSUE THREAD

**Issue by edwinveger** [aws-amplify/amplify-ios#977]
**Describe the bug**
It appears request signing takes place prior to URL encoding. This fails the request if there are query parameters contains characters that need to be encoded, e.g. `@`.

**To Reproduce**
We have a GET endpoint that require a query parameter (`/my/endpoint/path/:id?email=my@email.address.com`).
We create a RESTRequest like so:
```swift
let request = RESTRequest(
    path: "/my/endpoint/path/\(id)",
    queryParameters: ["email": "my@email.address.com"]
)

Amplify.API.get(request: request) { 
    // etc.
}
```

This request fails with a signing error.
Status code: 403
Body:
```json
{
  "error": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/my/endpoint/path/:id\nemail=my%40email.address.com\ncontent-type:application/json\nhost:REDACTED\nuser-agent:amplify-iOS/(Function) iOS/14.3 en\nx-amz-date:20201217T105627Z\nx-amz-security-token:REDACTED\n\ncontent-type;host;user-agent;x-amz-date;x-amz-security-token\REDACTED'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\REDACTED\n20201217/us-east-1/execute-api/aws4_request\REDACTED'\n"
}
```

**Expected behavior**
A successful request (i.e. not receiving a signing error).

**Environment:**
 - Amplify Framework Version: 1.4.3 (also reproducible on 1.5.1)
 - Dependency Manager: Cocoapods
 - Swift Version : 5.3.2

**Device Information:**
 - Device: Simulator
 - iOS Version: iOS 14.3

**Comment by edwinveger** [comment]
Although we thought up a workaround for above particular case, this issue has surfaced in another URL request. In this case we pass a timestamp (e.g. `2021-06-18T09:00:00Z`) in which the `:` characters are encoded (as `%3A0`).

This is actively blocking our development. It seems like a very common use case, and I must say I am quite confused that this issue has not been reported/addressed earlier.

If there is a simple workaround that I have missed so far, please provide directions.

**Comment by diegocstn** [comment]
PR in review: https://github.com/aws-amplify/amplify-ios/pull/1068

**Comment by palpatim** [comment]
Removed "closing soon" label pending PR approval & release.
