### ISSUE TITLE
Hub related documentation

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-ios#98]
we may have to link "via the Hub" to the `Hub` category or even to a guide. Not something that needs to be addressed right now but maybe we could create a task to track it? We will need to do it not only here, but it just occurred to me, that we should assume that some devs might now know what "via the Hub" means, or how to do it, when they are reading the docs of other categories.

_Originally posted by @drochetti in https://github.com/aws-amplify/amplify-ios/pull/93_

**Comment by drochetti** [comment]
This is still a relevant issue and needs to be triaged and prioritized.

**Comment by lawmicha** [comment]
JS has hub docs: https://docs.amplify.aws/lib/utilities/hub/q/platform/js#listening-for-messages

**Comment by lawmicha** [comment]
this comment was from the category API doc comment at https://github.com/aws-amplify/amplify-ios/pull/93/files/4745ae542f4fc3caa241aaef0bc8a0bd1b88fc05#diff-a6e16f7d518ba3f3535817d6749ba4e746e922ca12c821d40372eb2223dd3600 
```
/// Perform a GraphQL subscribe operation against a previously configured API. This operation
    /// will be asychronous, with the callback accessible both locally and via the Hub.
```
As mentioned in the comment thread, discuss a "How it works" in the API documentation and point to Hub documentation, similarly use JS has a reference for a Hub documentation structure
