### ISSUE TITLE
SignIn with Apple fails.

### ISSUE THREAD

**Issue by Nookaraju** [aws-amplify/amplify-ios#983]
**Describe the bug**
I have pool configured with Apple signing. everything work fine, it prompt to enter apple account details and grant and then closes the authentication UI and throws below error:

/Amplify/Amplify/Categories/Auth/Error/AuthError.swift
function: recoverySuggestion
line: 79
Caused by:
Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-3000 "(null)" UserInfo={error=invalid_request: Invalid user attributes: name: The attribute is required
 }

 let options = AuthWebUISignInRequest.Options(scopes: ["openid", "email", "profile"])
        _ = Amplify.Auth.signInWithWebUI(for: .apple, presentationAnchor: self.view.window!,options: options) { result in
            switch result {
            case .success(_):
                print("Sign in succeeded")
            case .failure(let error):
                print("Sign in failed \(error)")
            }
        }

**To Reproduce**
SignIn with apple.

email and name are required fields in user attributes.

configured the required fields in attribute mapping. Google signing works but Apple sign fails.

**Expected behavior**
It should allow user to Signin with Apple.

**Screenshots**

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.1
 - Dependency Manager: . Cocoapods
 - Swift Version : 5.3

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: .iOS 14
 - Specific to simulators:

**Additional context**

**Comment by royjit** [comment]
Hi @Nookaraju 

Does it work if you remove `name` as the required field from user attributes?

**Comment by Nookaraju** [comment]
@royjit  I cannot remove name as the required attribute because it won't allow me to do. If I create a new Pool, I will lose all the users in existing pool.

**Comment by Nookaraju** [comment]
@royjit I created a new pool it works fine. Please go ahead and close.
