### ISSUE TITLE
amplify-tools.sh doesn't recognize Amplify CLI Version

### ISSUE THREAD

**Issue by mTRx0** [aws-amplify/amplify-ios#988]
**Describe the bug**
The amplify-tools.sh script does not recognize the currently installed Amplify CLI version. (I'm not sure if this is the right place for this bug report)

Log output:
`error: Minimum version required of Amplify CLI is not installed.`
`Min required version: (4.22.0)`
`Found Version: ((y/N) [1A[6D[86C[1B)`

**To Reproduce**
1. Install Amplify CLI v4.40.0
2. Add 'Run Script" to "Build phases" with `${PODS_ROOT}/AmplifyTools/amplify-tools.sh` as source
3. Compile Project

**Expected behavior**
The correct Amplify CLI Version should be recognized.

**Screenshots**
Build Log
<img width="385" alt="Bildschirmfoto 2020-12-21 um 19 06 26" src="https://user-images.githubusercontent.com/39348200/102807845-b508cf00-43bf-11eb-8f86-545c1fda8377.png">

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.1
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0

**Device Information (please complete the following information):**
 - Device: iPhone XS Max
 - iOS Version: iOS 14.2

**Comment by royjit** [comment]
Hi @mTRx0 

Thank you for reaching out, the use of amplify-tools has been changed and we have updated the steps here - https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios#setup-local-development-environment . Can you please take a look and see if that fixes your issue?

**Comment by mTRx0** [comment]
Hey @royjit 

Thank you for the fast response, I've removed the `amplify-tools.sh` script from build phases and it seems to work as usual again. Not sure if I've overlooked anything while updating the Amplify CLI, but I think there should be some kind of warning regarding the changed usage of amplify-tools.
